### PR TITLE
desktop,ci: Adding AppImage support

### PR DESCRIPTION
**Pull request by kevin-wijnen**
Adding [AppImage](https://appimage.org/) support through the use of [Cargo AppImage](https://github.com/StratusFearMe21/cargo-appimage) in the CI through GitHub Actions.

For more details, see #12401.

Current issues:

- `Cargo.toml` of the desktop package would not be able to used, despite modifications.

### CODE REVIEW

**Comment by n0samu** [comment]
Thank you for your work on this! I'm not a Linux user, but I know it is a goal of the project to offer AppImage builds. Can you tell us what problem you ran into with the Cargo.toml?

**Comment by kevin-wijnen** [comment]
Thank you all for even bringing this project to life!

> Can you tell us what problem you ran into with the Cargo.toml?

During the `cargo appimage` process, it simply gives a generic error of `Cannot load metadata from Cargo.toml`. This seems to happen after building the crate itself. I am currently unsure whether it is a Rust generic issue, or one with Cargo AppImage itself as I did not find any similar open issues at [Cargo AppImage's repository](https://github.com/StratusFearMe21/cargo-appimage).

The only similar issue that has been previously resolved, is [#16, which details it has something to do with actual locating it because of a differing file location.](https://github.com/StratusFearMe21/cargo-appimage/issues/16)

I'm currently running another run with an empty `src` directory, to see if that temporary workaround does work.

**Comment by kevin-wijnen** [comment]
Even with the empty `src` folder workaround, it does not seem to function. The specific issue lies with Cargo AppImage, as it does a `cargo build` before doing its own process to package it. Yet for said own process, it simply cannot find the right `Cargo.toml`, despite using it prior for building the Crate to begin with.

Already issued a report at [#27 at their repository](https://github.com/StratusFearMe21/cargo-appimage/issues/27). I will try to find a different method of producing working AppImages, if Cargo AppImage will continue to fail.

**Comment by kevin-wijnen** [comment]
Sorry for the late response:

I recently took another look at trying to get AppImages to be packed for this project. Yet my (personal) motivation dwindled since recent AppImage versions (personally tested it with the nightly released on Fri Jan 26th 2024) do run on my Steam Deck.

So with the lack of personal motivation and knowledge about Rust, I will close this Pull Request for now, hopefully someone else will continue the work.

@n0samu Any pointers re: AppImage support are found here, #12401 and in #12633.

**Pull request closed without merging**
