### PR TITLE
core,desktop: Update to `winit` `v0.30.5` and latest `egui` from git

### PR DESCRIPTION
**Pull request by torokati44**
Still needs some cleanup and porting and migrating away from deprecated stuff to the new and shiny new trait-based APIs I think.

~~Not latest minor version, because:~~
~~https://github.com/emilk/egui/pull/4849#issuecomment-2258111041~~

~~But soon it probably can be:~~
~~https://github.com/rust-windowing/winit/pull/3849~~

Supersedes https://github.com/ruffle-rs/ruffle/pull/16835.

### CODE REVIEW

**Comment by torokati44** [comment]
Soon we can (hopefully) bump to `0.30.5`: https://github.com/emilk/egui/pull/4939
Also, this may fix the touch interactivity problems on Steam Deck? :eyes:

**Comment by torokati44** [comment]
Right now, this is a mechanical, "just the minimum to get it working" port, with two `#[allow(deprecated)]` lines added.
To get rid of those, a significant refactor to `app.rs` will have to be done.
There's also a minor change in behavior wrt. `max_window_size`, but I don't think it can be problematic really.

**Comment by torokati44** [comment]
After this is merged, update dependencies to include these:
 - To deduplicate `bindgen`:
   - https://github.com/ruffle-rs/jpegxr/pull/2
   - https://github.com/RustAudio/coreaudio-sys/pull/107
 - To deduplicate `wayland-protocols`:
   - https://github.com/PolyMeilex/rfd/pull/212

**Review by sleepycatcoding — APPROVED** [review]

**Comment by torokati44** [comment]
Thank you for the approval, @sleepycatcoding!
I've just now added a `TODO` comment to both of the `allow(deprecated)` attributes, and bumped `egui` to the current latest `master`, which necessitated following an API change: https://github.com/emilk/egui/pull/5025

I hope these don't invalidate your approval. :)

**Pull request merged**
