### PR TITLE
fix: SharedObject data property is not deleteable

### PR DESCRIPTION
**Pull request by midgleyc**
Given a SharedObject `SO`, the command `delete SO.data` should fail.

Fixes saving in Cyber Ortek Flier.

### CODE REVIEW

**Comment by relrelb** [comment]
Maybe the new test should be added to the already existing [one](https://github.com/ruffle-rs/ruffle/tree/master/core/tests/swfs/avm1/shared_object)?

**Comment by midgleyc** [comment]
That'd be a good idea, but I don't know how to compile a bare `.as` file to the format required.

**Comment by relrelb** [comment]
Seems like it lacks a `.fla` file. I guess it should be recreated.

**Comment by midgleyc** [comment]
Other files in `tests` say they're compiled using `mtasc`, so I did the same.

```
mtasc -main -header 200:150:30 test.as -swf test.swf
```

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
