### PR TITLE
avm2: implement coerce_x opcodes

### PR DESCRIPTION
**Pull request by midgleyc**
I created the test for these by taking the original `op_coerce` test and editing it in JPEXS so that the `coerce_x` opcodes were used instead.

I don't know how to create the `.asasm` files that came with the original, so it's just the swf and `output.txt` for now.

### CODE REVIEW

**Comment by kmeisthax** [comment]
asasm files are generated with rabcasm; you first extract the ABC file and then disassemble it to get a proper `test-0` structure. You can then edit the files inside and then reassemble and inject it into the SWF.

**Comment by adrian17** [comment]
To be sure, do we wanna keep the .abc file in the commit?

**Comment by midgleyc** [comment]
I followed the practice of the `op_coerce` test, which did, but I'm happy to leave it out as well.

**Comment by adrian17** [comment]
I don't really know either way :) But if that's the case, I think this can be merged.

**Review by adrian17 — APPROVED** [review]

**Pull request merged**
