### PR TITLE
swf: Write a non-zero 'index' value for true/false/undefined/null default values

### PR DESCRIPTION
**Pull request by Aaron1011**
A zero 'index' does not have a subsequent 'kind' field in the
written SWF. The 'index' field is not actually used for
true/false/undefined/null, so it can be anything as long
as it's non-zero.

### CODE REVIEW

**Comment by Herschel** [comment]
We don't really guarantee byte-for-byte roundtrip on SWF data -- for example, byte-for-byte would require storing the # of bits for any variable-length values, which is basically all shape data --  I've really only been concenred about semantic equivalence when roundtripping data. It makes the API more complex for users too.

So I don't think we should bother storing the index in this case. What index does the Flex compiler typically write out in this case? Seems like it writes out the the `value_kind`, so let's just do that.

**Comment by adrian17** [comment]
> What index does the Flex compiler typically write out? Seems like it writes out the the value_kind twice, so let's just do that.

For undefined (as in: when default is not defined explicitly), I think it may be outputting a single 0 without writing kind.

**Comment by Aaron1011** [comment]
Investigating further - it looks like both JPEXs and asc.jar unconditional read both the index and kind:

https://github.com/jindrapetrik/jpexs-decompiler/blob/dba68c582ca8657376e439d64d0242cb1de40044/libsrc/ffdec_lib/src/com/jpexs/decompiler/flash/abc/ABCInputStream.java#L362-L364

https://github.com/apache/flex-sdk/blob/ba414443032b49c45ff11b61db452c8a8f428bd8/modules/asc/src/java/macromedia/abc/Decoder.java#L289-L293

We still might want to write out a non-zero index, but the bug I was experiencing seems to be due to our our code skipping reading the 'kind' when the index is 0.

**Comment by Aaron1011** [comment]
@Herschel @adrian17 I've updated this PR to just write out a non-zero 'index' for the affect default value kinds.

**Review by adrian17 — APPROVED** [review]
LGTM.
Maybe we should rename the functions, because `write_constant_value`/`write_optional_value` doesn't really tell much about the main context they're in (function default args vs trait defaults).

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
