### PR TITLE
core: Support for custom context menu items on movie root

### PR DESCRIPTION
**Pull request by adrian17**
Note that this only detects context menu set on the movie root (eg `_root.menu`), so it still doesn't support fancier use cases.

Also only works on web, as we haven't figured out context menus on desktop at all yet.

Fixes https://github.com/ruffle-rs/ruffle/issues/4153 (on web), possibly more.

Things to do before un-WIP:

- [ ] finish the core refactor
- [x] support remaining menu item properties:
- - [x] `enabled`
- - [x] `separatorBefore`

Video:

https://user-images.githubusercontent.com/4729533/116623778-0bc27e80-a947-11eb-831f-f6e03ae49738.mp4

### CODE REVIEW

**Comment by rufflue** [comment]
you might want to check if your fix also fixes #4094 since it looks like a similar issue

**Review by Herschel — COMMENTED** [review]
Some thoughts:

 * Since the context menu info will be used by both AVM1 and AVM2, let's move `contextmenu.rs` up to `core` and rename it to `context_menu.rs`.
 * Let's prepare for AVM2 by adding a `ContextMenuCallback` type:
```
enum ContextMenuCallback {
   Avm1 { this: avm1::Object<'gc>, callback: avm1::Object<'gc> },
   Avm2 { this: avm2::Object<'gc>, callback: avm2::Object<'gc> },

   // Built-ins
   Play,
   Quality,
   Rewind,
   // etc.
}
```
 * By adding the built-ins as "special" callbacks, the distinction between builtin and custom items isn't necessary, and they'll be treated the same on the front-end. The info will simply contain `items`. Core will match on the callback type and forward the built-ins to the necessary player methods.
 * Let's go ahead and add `ContextMenuItemInfo::checked` to handle checked built-in items, and this will remove the need for `ContextMenuInfo::is_playing_root_movie`.
 * You could store the callbacks separately from the item info. This avoids the `'gc` plaguing the info type. `ContextMenuState` becomes something like:
```
struct ContextMenuState<'gc> {
    info: ContextMenuInfo,
    callbacks: Vec<ContextMenuCallback<'gc>>,
}
```
Now `ContextMenuItemState` is not needed, as we can pass `info.state` directly across to the frontends as-is.
 * `ContextMenuState::new` is the code that generates the info from the AVM1 object, and this should move to a function in `avm1::globals::context_menu`. This keeps separation between the core-common ContextMenu info, and the AVM-specific code that generates it.
 * With the types simplified a bit, I think we can do these moves+renames:
   * `crate::avm1::ContextMenuInfo -> crate::context_menu::ContextMenu`
   * `crate::avm1::ContextMenuItemInfo -> crate::context_menu::ContextMenuItem`
   * `crate::avm1::ContextMenuState -> crate::context_menu::ContextMenuState`

**Comment by adrian17** [comment]
> you might want to check if your fix also fixes #4094 since it looks like a similar issue

This should already be working, I added "play" a couple days ago. Thanks for reporting.

**Comment by adrian17** [comment]
OK, refactor done.

Things I'm still not happy with:
- having to store the `&'a mut Option<ContextMenuState<'gc>>` in UpdateContext, ideally I'd just pull them from gc_root as I only access this in Player anyway - but not sure if it's even possible,
- `prepare_context_menu` having to `clone()` the items returned to Web because of lifetimes (again, should be safe as long as `instance` lives, but the way everthing runs within GC closures makes it impossible to represent with lifetimes, right?)
- having two similar typed context menu item stuctures in TS - but maybe they can just be left this way

During refactor, I also did some minor improvements to playback options:
- `rewind`/`back` are now disabled if we are on 1st frame (like in FP),
- I fixed most of issues reported in these videos: https://github.com/ruffle-rs/ruffle/pull/4141#issuecomment-826970115 by calling `run_actions` after seeking. This is the only remaining mismatch I found:

https://user-images.githubusercontent.com/4729533/116817269-c4660900-ab65-11eb-8f6e-1a842f75bfac.mp4

**Comment by Herschel** [comment]
Thanks, this looks good!

 * I have a feeling we could replace `ContextMenuItem` with `InternalContextMenuItem`, perhaps adding an optional `onClick?` field to deal with the Fullscreen, About, etc. elements. If it's not set, then you use the player's context menu handler.
 * If we wanted to get rid of the clone, we could have the player store only the callbacks `Vec<ContextMenuCallback>`, as this is all it needs, and then we can safely move the info vec without a clone. But it's not really an issue, this is a clone of a few items done on right click. (If we really cared, we might try returning an Iterator from the `make_context_menu_state` isntead...!)

This is good to merge to me, thank you 👍

**Pull request merged**
