### PR TITLE
Revert "ci: Don't test on Edge as the latest release is missing for Linux"

### PR DESCRIPTION
**Pull request by torokati44**
Reverts ruffle-rs/ruffle#17253
To be merged once https://github.com/MicrosoftEdge/EdgeWebDriver/issues/156 is fixed.

### CODE REVIEW

**Comment by torokati44** [comment]
I wonder whether this is a `wdio` bug - why doesn't it try to use the installed Edge WebDriver 126.0.2592.102 (even though Edge is 126.0.2592.113).
Or maybe it's a GHA hosted Ubuntu image bug, since ideally the installed versions should match exactly?

**Comment by danielhjacobs** [comment]
> Or maybe it's a GHA hosted Ubuntu image bug, since ideally the installed versions should match exactly?

I did open https://github.com/actions/runner-images/issues/10336

**Comment by torokati44** [comment]
Looks like this works now, @danielhjacobs. Let's hope it doesn't reoccur soon...

**Comment by danielhjacobs** [comment]
While it's fixed for now, runner-images will create a PR for a new image within the day. I want to see what Edge version and Edgedriver version it uses and see if that version has a Linux release yet.

**Comment by danielhjacobs** [comment]
Yup: https://github.com/actions/runner-images/blob/bc9dc728e1e3b41ffed3cd950db959f3c2475fd2/images/ubuntu/Ubuntu2204-Readme.md#browsers-and-drivers

**Comment by torokati44** [comment]
There's still a tiny mismatch: 

> Microsoft Edge 127.0.2651.74
> Microsoft Edge WebDriver 127.0.2651.72

**Comment by danielhjacobs** [comment]
Yeah, and that will cause an issue:

https://msedgedriver.azureedge.net/127.0.2651.74/edgedriver_linux64.zip does not exist.

**Comment by danielhjacobs** [comment]
See also: https://github.com/webdriverio/webdriverio/issues/13251

I now have issues open with all the relevant parties, so we'll see if any are willing to fix this.

**Pull request closed without merging**
