### PR TITLE
Updating the verbiage for the AS3 warnings to try and reduce the number of support questions about it.

### PR DESCRIPTION
**Pull request by sombraguerrero**

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]

**Review by relrelb — APPROVED** [review]
Thank you!

**Comment by torokati44** [comment]
I don't think the AS3 support is lacking only in interactivity, so making the message specific in this way could be misleading if a completely non-interactive movie doesn't work either.
(Also a tiny nit: the indentation of the added line in the CSS does not seem to match the preceding lines perfectly.)

**Comment by torokati44** [comment]
Oof, I was 7 minutes late.

**Comment by relrelb** [comment]
@torokati44 Don't worry, feel free to toss another PR :)

**Comment by sombraguerrero** [comment]
> I don't think the AS3 support is lacking only in interactivity, so making the message specific in this way could be misleading if a completely non-interactive movie doesn't work either.
> 
> (Also a tiny nit: the indentation of the added line in the CSS does not seem to match the preceding lines perfectly.)

Understood, and one can feel free to change it again, but Nosamu and I were basing this primarily off of what we field in the Discord, which is by and large the desire for interactive games.

**Pull request merged**
