### PR TITLE
web: Use Symphonia to decode MP3

### PR DESCRIPTION
**Pull request by torokati44**
This contains about half of https://github.com/ruffle-rs/ruffle/pull/4273, plus a minor fix by me in the last commit.

Fixes the following z0r.de loops having no sound in Firefox (SOME ARE NSFW!): 860, 1585, 1896, 4434, 4436, 4832, 5183, 6061, 6315, 6861, 7095, 7230, 7347, 7354, 7636, 7686, 7709, 7737, 7770, 7790, 7811

Some explanation:

Unfortunately, the `decodeAudioData` function currently in use has no way to specify what format the data is in, so it must rely on intact headers or format sniffing heuristics. These differ from browser to browser, which means that some truncated/corrupted MP3 data was not recognized as such by Firefox, but was by Chrome.

With Symphonia, we can use the MP3 decoder explicitly, no format sniffing required.

### CODE REVIEW

**Comment by Herschel** [comment]
Thanks for rebasing this! I am indeed excited to get rid of a lot of the old web audio code. My only concern with using `ScriptProcessorNode` at the moment is whether the audio latency might be somewhat poor. Ideally we use use `AudioWorklet` when available with `ScriptProcessor` as a fallback, but we can always add this later if `ScriptProcessor` works well enough. Could you test this a bit @Toad06?

Another potential improvement is to only start the `ScriptProcessor` when audio actually starts playing, to avoid doing so in case of silent SWFs (I'm thinking of old Flash web sites where there are 8+ SWF buttons on a page not doing much audio; probably not a great idea to spin up a ton of processor nodes).

**Comment by torokati44** [comment]
> Ideally we use use `AudioWorklet` when available with `ScriptProcessor` as a fallback, but we can always add this later if `ScriptProcessor` works well enough.

I know, I left out those (WIP) parts of your branch because I can't really put much more time into this right now... :/

> Another potential improvement is to only start the `ScriptProcessor` when audio actually starts playing, to avoid doing so in case of silent SWFs

Yes, that would be nice, but ... see above.

> probably not a great idea to spin up a ton of processor nodes

I don't know how taxing it is, if it is _really_ trivial, then this might be just a premature optimization, which is, as they say, the root of something?

_PS: I'm not afraid to admit that I really just wanted to make the mentioned z0r.de loops work in Firefox as quickly and easily as possible, judge this PR accordingly._

**Comment by Toad06** [comment]
> My only concern with using `ScriptProcessorNode` at the moment is whether the audio latency might be somewhat poor.

Yes, I noticed that this unfortunately happens quite often in Firefox. :(

For instance in [Ultimate Flash Sonic](https://uploads.ungrounded.net/151000/151706_ultimate_sonic.swf?1077899965), sound effects are played too late - for some reason, if I switch to another tab for 10 seconds and go back to the game, this "fixes" the issue and next sounds will play in synch.

**Comment by torokati44** [comment]
Thanks for the testing again, @Toad06!
Well, I wouldn't want to regress the gaming experience for the sake of some animations, so it can wait...

**Comment by Herschel** [comment]
I'll look into it some tonight. Another possibility is queuing up `AudioBufferSourceNode`s, which is the tack used by [`cpal`](https://github.com/RustAudio/cpal/blob/master/src/host/webaudio/mod.rs#L312) for its web backend. Maybe this is a little better.

Actually we could possibly use `cpal` directly. I think @relrelb suggested this before, I was a little ambivalent about it at the time, but it's worth trying out, especially now that the backends will share most of the code anyway via `AudioMixer`.

**Comment by Herschel** [comment]
Here's a branch playing the audio using `AudioBufferSourceNode`s: https://github.com/Herschel/ruffle/tree/webaudio-audiobuffersource
Could you test this branch out a bit? @Toad06 @torokati44

**Comment by torokati44** [comment]
Overall, the linked works great in both Firefox and Chrome when testing the loops above.
In 7347 however, there is a short glitch every time the music loops.
This was already the case before your last commit (so, with this PR itself), but not on current `master` in Chrome, where there is still a slight hitch, but not as noticeable.

**Comment by Toad06** [comment]
There's a strange bug affecting _Sonic Shorts Volume_ (and likely other files) depending on the size of the canvas:
- [Natural dimensions](https://github.com/ruffle-rs/ruffle/files/9211513/sonic-shorts-volume.zip) (550x400): no issue.
- [Maximized size](https://img-hws.y8.com/cloud/y8-flash-animation/contents/item_versions/flash_animations/1519/original/sonic_shorts_volume_1.swf?1522393336) (when opening the SWF directly): Click the in-game "Play" button quickly: notice the audio will stutter for about 10 seconds. Now reload the SWF and wait about 10 seconds (once the first frame is displayed) before clicking the in-game "Play" button: the audio should play without stuttering.

This happens in Firefox and Chrome on my device. This is strange because I didn't experience any FPS drops when running the file.

**Comment by Herschel** [comment]
Thanks! I think I've fixed that stuttering issue on my branch, caused by the chug during the initial load. Does the latency seem better than ScriptProcessor?

One downside compared to the old web audio is that music will cut out in a similar way if, for example, AS code does a busy loop and hangs for a bit. But I think this is an acceptable tradeoff for now, and hopefully wouldn't be a problem with AudioWorklet.

A quick comparison to master on https://www.newgrounds.com/portal/view/124117 shows a ~60MB memory usage reduction in Firefox on my machine, as the uncompressed audio is no longer stored in memory.

**Comment by Herschel** [comment]
> In 7347 however, there is a short glitch every time the music loops (I think there are two "lines" of the lyrics per loop).

This doesn't occur on desktop with minimp3, so seems like this is a symphonia issue, or maybe an issue with how we are looping using symphonia.

**Comment by Toad06** [comment]
> Thanks! I think I've fixed that stuttering issue on [my branch](https://github.com/Herschel/ruffle/tree/webaudio-audiobuffersource), caused by the chug during the initial load. Does the latency seem better than ScriptProcessor?

I confirm the stuttering issue is also fixed on my end (Firefox and Chrome). 😉 I also haven't experienced any issue related to latency.

This will fix and close https://github.com/ruffle-rs/ruffle/issues/1673#issuecomment-736355688 and #6611.

**Comment by Herschel** [comment]
> > In 7347 however, there is a short glitch every time the music loops (I think there are two "lines" of the lyrics per loop).
> 
> This doesn't occur on desktop with minimp3, so seems like this is a symphonia issue, or maybe an issue with how we are looping using symphonia. (The loop point does seem just slightly different between FP and Ruffle desktop, though).

Should be fixed now, we weren't resetting the symphonia decoder state when doing a seek.

**Comment by Herschel** [comment]
Going to move these changes back over to #4273, thank you!

**Comment by torokati44** [comment]
Awesome! Thank _you_! :partying_face:

**Pull request closed without merging**
