### PR TITLE
chore: Remove unused dependencies

### PR DESCRIPTION
**Pull request by sleepycatcoding**

### CODE REVIEW

**Review by torokati44 — APPROVED** [review]
I can't imagine anything breaking if CI passes.

**Comment by torokati44** [comment]
The lint check failure seems unrelated.

BTW, `cargo-udeps` says:

```
unused dependencies:
`build_playerglobal v0.1.0 (/home/attila/projects/ruffle/core/build_playerglobal)`
└─── dependencies
     ├─── "colored"
     └─── "serde-xml-rs"
`ruffle_render v0.1.0 (/home/attila/projects/ruffle/render)`
└─── dependencies
     └─── "lru"
`ruffle_render_canvas v0.1.0 (/home/attila/projects/ruffle/render/canvas)`
└─── dependencies
     └─── "fnv"
`ruffle_render_webgl v0.1.0 (/home/attila/projects/ruffle/render/webgl)`
└─── dependencies
     └─── "fnv"
`ruffle_web v0.1.0 (/home/attila/projects/ruffle/web)`
└─── dependencies
     └─── "ruffle_render_wgpu"
`ruffle_web_safari v0.1.0 (/home/attila/projects/ruffle/web/packages/extension/safari)`
└─── dependencies
     └─── "objc"
```

**Comment by sleepycatcoding** [comment]
> The lint check failure seems unrelated.
> 
> BTW, `cargo-udeps` says:
> 
> ```
> unused dependencies:
> `build_playerglobal v0.1.0 (/home/attila/projects/ruffle/core/build_playerglobal)`
> └─── dependencies
>      ├─── "colored"
>      └─── "serde-xml-rs"
> `ruffle_render v0.1.0 (/home/attila/projects/ruffle/render)`
> └─── dependencies
>      └─── "lru"
> `ruffle_render_canvas v0.1.0 (/home/attila/projects/ruffle/render/canvas)`
> └─── dependencies
>      └─── "fnv"
> `ruffle_render_webgl v0.1.0 (/home/attila/projects/ruffle/render/webgl)`
> └─── dependencies
>      └─── "fnv"
> `ruffle_web v0.1.0 (/home/attila/projects/ruffle/web)`
> └─── dependencies
>      └─── "ruffle_render_wgpu"
> `ruffle_web_safari v0.1.0 (/home/attila/projects/ruffle/web/packages/extension/safari)`
> └─── dependencies
>      └─── "objc"
> ```

Do I add them to this PR?

**Comment by torokati44** [comment]
> Do I add them to this PR?

However you feel like. I'm fine merging this as is, or with those removals added.

**Comment by torokati44** [comment]
> Actually we cannot remove the objc dependency from ruffle_web_safari since that is actually used, but only when the target is MacOS.

To be fair, the tool also said:
```
Note: These dependencies might be used by other targets.
      To find dependencies that are not used by any target, enable `--all-targets`.
Note: They might be false-positive.
      For example, `cargo-udeps` cannot detect usage of crates that are only used in doc-tests.
      To ignore some dependencies, write `package.metadata.cargo-udeps.ignore` in Cargo.toml.
```
:upside_down_face:

**Review by torokati44 — APPROVED** [review]
Thank you!

**Pull request merged**
