### PR TITLE
tests: Have at most one image per test

### PR DESCRIPTION
**Pull request by relrelb**
Previously image tests had an image per platform (i.e. Linux, Windows).
However, due to containing the LLVM version in their name, which
constantly updates on CI, and the fact that those images are actually
identical, unify them into a single `expected.png` image.

### CODE REVIEW

**Comment by Aaron1011** [comment]
In general, there's no reason to expect these results to be identical, especially when we start to test things like antialiasing. I think we should instead just strip out the LLVM version from the Linux filename suffix.

**Comment by relrelb** [comment]
> In general, there's no reason to expect these results to be identical, especially when we start to test things like antialiasing. I think we should instead just strip out the LLVM version from the Linux filename suffix.

Hmm, did you actually see different results between Linux and Windows? If it really can happen, I'm fine with splitting the images again, once appropriate tests are added. But right now we can let ourselves to have platform-agnostic images.

**Comment by Aaron1011** [comment]
I thought that we would see platform differences in https://github.com/ruffle-rs/ruffle/pull/7254 due to `TextField` rendering, but surprisingly, the images seem to be identical.

However, we're definitely going to see platform differences when we implement device fonts (https://github.com/ruffle-rs/ruffle/issues/1862). I don't think it's a good idea to remove this logic just because it's not needed right now. We'd just be creating more work for ourselves later, when we have to revert this change after adding (image tests for) device fonts.

**Comment by relrelb** [comment]
> I thought that we would see platform differences in #7254 due to `TextField` rendering, but surprisingly, the images seem to be identical.
> 
> However, we're definitely going to see platform differences when we implement device fonts (#1862). I don't think it's a good idea to remove this logic just because it's not needed right now. We'd just be creating more work for ourselves later, when we have to revert this change after adding (image tests for) device fonts.

Good to hear that #7254 produces platform-agnostic graphics. As for #1862, you're most likely right. But given that the logic in question is pretty small and thus can be restored very easily, and I don't expect device fonts to be supported in the foreseeable future, I'd still like to keep things simple for now. The extra work will be very minor, and I worry that discussing it further can be a subject to bikeshedding.

**Pull request merged**
