### PR TITLE
avm2: Don't forget to set the state in `Avm2Button::set_state`

### LINKED ISSUE #14922: TLF regression in MLP game on latest nightly build
### Describe the bug

Text boxes no longer works, last stable nightly for Gotta Catch em All one more time was 2024_01_23

### Expected behavior

Everything should work correctly

### Content Location

[Gotta.Catch.em.All.one.more.time.zip](https://github.com/ruffle-rs/ruffle/files/14031259/Gotta.Catch.em.All.one.more.time.zip)

### Affected platform

Desktop app

### Operating system

Windows 10 x64

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by moulins**
Fixes #14922

### CODE REVIEW

**Comment by torokati44** [comment]
For the record, this regressed in https://github.com/ruffle-rs/ruffle/pull/14820.

Have you also checked the two other lines, that I have commented on, under https://github.com/ruffle-rs/ruffle/commit/e014d7c023db5085e57e0d784dafdd961ef0ea80 ?

**Comment by moulins** [comment]
Done :)

**Review by torokati44 — APPROVED** [review]
Thanks!

**Comment by torokati44** [comment]
Although, actually, the commit name is now not the best, as it is only about one of the two changes it makes... :/

**Comment by torokati44** [comment]
Ah, but the second line was simply redundant, `needs_frame_construction` was already set to `false` a few lines above.

**Comment by torokati44** [comment]
I did a sneaky and simply added a few words to the second line of your commit message. I hope you don't mind. :no_mouth:

**Pull request merged**
