### PR TITLE
avm1: Improve execution order

### LINKED ISSUE #1535: avm1: Unload clip event handlers should cause clips to be destroyed later
In the official Flash Player, movieclips with an `unload` clip event handler seem to "stay alive" for one frame longer than normal when they are removed. In Ruffle, they are destroyed immediately.

Say there is a movieclip named "clip" on frame 1. On frame 2, if you remove the clip and `trace(clip);`, normally this prints the empty string as the clip no longer exists. However, if you add an `unload` event handler to the clip, such as:
```
onClipEvent(unload) {
	trace("unload clipEvent");
}
```
then the `trace(clip)` will work and print `_level0.clip`, even though the clip no longer exists on frame 2. All properties of the clip also remain accessible, even though it's no longer visible. It seems that the clip is kept alive for an extra frame. This also happens if you use `clip.onUnload = function() { .. }`. On frame 3, these all return `undefined` as expected.

This can also cause some confusing behavior. Say that there is an entirely new movieclip named "clip" on frame 2. `clip` would still refer to the previous frame 1 clip, including all of its properties (for example, `trace(clip._x)` would print the previous clip's position). Removing the unload handler causes it to correctly refer to the frame 2 clip.

Example SWF:
[unload.zip](https://github.com/ruffle-rs/ruffle/files/5513020/unload.zip)

### LINKED ISSUE #1626: Ultimate Flash Sonic : Collision Issues
Various collision and physics issues, especially notable in the second act of the first zone, in which the player can collide with and stand on background interior tiles that they should infact incur no collision with. In addition, it seems possible to jump out of S-Tunnels, which does not appear possible when using native flash.

Version:
Ruffle Nightly - 2020-11-18
used on Archive.org

### PR DESCRIPTION
**Pull request by Herschel**
Fixes two things:
 * AVM1 execution order is based on order of instantiation, so all display objects are moved to a global list inside AVM1.
 * Clips with an unload event handler "stay alive" during the frame that they execute their unload handler, so that their properties remain accessible. They are moved to a negative dummy depth and are actually removed at the end of the frame. (This is the one case in AVM1 where it's possible for multiple clips to occupy the same depth).

Other misc changes in support of the above:
 * Remove execution list logic from `ChildContainer`, since this is a global list.
 * `Player::run_frame` has been split into AVM1 and AVM2 sections.
 * ~~`DisplayObject::unload` mostly only runs in AVM1 movies.~~
 * ~~`ActionHaltMode` has been added to specify the particular ways that AVM code can halt execution when the base clip is destroyed. This replaces the `is_unload` parameter of `ActionQueue::queue_actions`.~~

TODO for future:
 * `Avm1::clip_exec_list` could be a list of `MovieClip` instead of `DisplayObject`.
 * Because we have the global list, it's easier to broadcast clip events to all clips now by iterating over the list instead of recursively. This may both be more correct, and reduce the need for the action queue in many places.
 * `ChildContainer` may only need a single list of children objects, instead of keeping the map of depths alongside the list. The fact that unloaded clips may occupy the same depth throws a wrench into the use of a map, and I suspect Flash just does a linear search when searching for a depth.

Fixes #1626, #1986, #4446.
Supersedes #3104.

### CODE REVIEW

**Comment by Herschel** [comment]
@Toad06 could you give this a bit of testing since it's a fairly invasive change?

**Comment by adrian17** [comment]
Could this also affect https://github.com/ruffle-rs/ruffle/issues/1108 ?

**Comment by Herschel** [comment]
> Could this also affect #1108 ?

Don't think so, as that's more related to mouse state than clip unloading.

**Comment by Toad06** [comment]
Done some testings on desktop (Windows) and the web extension (Firefox).


[Zizzo Challenge](http://www.cartoondan.com/games/zizzo_challenge.swf)
✔️ The "Fight" mini-game is now playable (inputs were not registered before).

[Bouncy the Ball](https://uploads.ungrounded.net/204000/204189_Bouncy_The_Ball.swf?1101740597)
❌ Pressing "Enter" on the password screen no longer works (eg. "bounce" is a valid password).

[DTunnel 3D](https://uploads.ungrounded.net/174000/174308_nhsdtunnel3d.swf?1086971709)
❌ For some reason, the music no longer loops (it uses the `Sound.onSoundComplete` listener to restart the music).

[Dr Carter And The Wheels Of Salvation](https://www.miniclip.com/games/wheels-of-salvation/fr/wheelsofsalvation.swf?mc_gamename=Wheels+of+Salvation)
❌ The game is much slower than in the current nightly builds.
❌ The character is often "teleported" to the top of the window, unexpectedly completing the level.

[Steppenwolf 2-1](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/489/original/steppenwolf_chapter_2_episode_1.1?1522273372)
✔️ The game no longer softlocks on the game over screen after a death by dog bite.

[Steppenwolf 3-1](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/493/original/steppenwolf_chapter_3_episode_1.swf?1521281315)
✔️ It's no longer possible to hold the spacebar and the down arrow simultaneously when hiding behind the desk [in this area](https://user-images.githubusercontent.com/14274782/120200867-195c7400-c225-11eb-9d6b-8c4e2b67b010.png) (matching Flash behavior). This was creating... [a huge issue](https://user-images.githubusercontent.com/14274782/107158740-79848d00-698c-11eb-949d-9d80e1e05350.jpg). 😅
❌ The character gets stuck when reaching [this area](https://user-images.githubusercontent.com/14274782/120200947-2d07da80-c225-11eb-99c4-a44a254dcb7c.png) (can be "unlocked" by opening and closing the inventory). To reach this place, press spacebar near the elevator, jump (shift key) to the north, take the ball on the photocopier, go back to the previous area, throw the ball from the elevator (space), jump and finally climb the grid.

[Super Chick Sisters](https://uploads.ungrounded.net/396000/396372_superChickSisters.swf?1187735367)
✔️ Collisions with bonus birds now only happen once (matching Flash behavior).
❌ Most graphic elements are no longer displayed and the background is completely black. To reproduce, start a new game (you can use the code "gopam" to start the game quicker).

[Super Mario 63](https://uploads.ungrounded.net/498000/498969_Super_Mario_63__2009_.swf?1353774292)
❌ When the first level starts, Mario gets stuck in the air, making the game unplayable. This problem did happen in a previous PR and was related to the `_parent` property \([see this comment](https://github.com/ruffle-rs/ruffle/pull/1473#issuecomment-734086428)\); however, at this point, this change fixes #1701.

**Comment by Herschel** [comment]
I think maybe I'll split out the "unload" part of this into a separate PR, as that's the more dangerous part and I think causing most of the above issues.

**Comment by adrian17** [comment]
> The game is much slower than in the current nightly builds.

For the record, I didn't notice a difference visually, but there's a noticeable difference (2-3x more time spent in `tick()`) in the profiler:
image

**Comment by Herschel** [comment]
I yanked out the "unload" changes as I need to investigate this more. Now this PR is only the AVM1 execution order list. I confirmed that all regressions in @Toad06's report are okay now:
 * Zizzo Challenge: Fight mini game works.
 * Bouncy the Ball text input bug fixed. The more accurate execution order caused this bug to appear. keyPress events will take precedence over text input events, but Ruffle was sending the enter press to the text field.
 * DTunnel 3D music loops.
 * Wheel of Salvation bugs and performance issues should no longer occur.
 * The "stuck" regression issue in the Chapter 3 Ep 1 no longer occurs. Steppenwolf death-soft-lock and "huge" issue will still occur (not a regression). 
 * Super Chick Sisters background should work (this was due to bitmaps not being placed on the new execution list).
 * Super Mario 64 no longer gets stuck in midair.

**Comment by Herschel** [comment]
Fixed the bug in Steppenwolf 5-1. This was caused by the "ladder climbing" clip being stuck in memory, which would cause the player to teleport to the bottom of the gutter when they pressed down for a moment.

**Pull request merged**
