### PR TITLE
avm1: Implement onDragOver, onDragOut, and _droptarget

### LINKED ISSUE #795: Incriminati - Click, drag and release of item doesn't trigger expected action.
https://www.newgrounds.com/portal/view/38654

In Incriminati, you drag items onto hiding places and it hides them accordingly. When playing with Ruffle, you can click an drag an object but placing it on the target area doesn't result in it becoming hidden.

### LINKED ISSUE #3191: The drag and drop function  not work
The drag ad drop function of our activities does not work. When trying to drag and drop a tile to its destination, it is not validated and the game crashes. Attached is an example of two activities.

System: windows pC
browser: chrome 88

Video: https://www.ondaeduca.com/videos_ruffle/drag&drop.mp4

**Action scrip:**
[example_ drag&drop.zip](https://github.com/ruffle-rs/ruffle/files/5960608/example_.drag.drop.zip)
!!(the files cannot be opened outside your main app, but I attach them for help see the code)

function dragSetup(clip, targ, finalx, finaly, ficha_ver)
{
   clip.onPress = function()
   {
      _root.nivel = _root.nivel + 1;
      this.swapDepths(_root.nivel);
      _root.nivel = _root.nivel + 1;
      _root.solucion_1.swapDepths(_root.nivel);
      _root.nivel = _root.nivel + 1;
      _root.solucion_2.swapDepths(_root.nivel);
      startDrag(this,0);
   };
   clip.onRollOver = function()
   {
      this.gotoAndPlay("activo");
   };
   clip.onRollOut = function()
   {
      this.gotoAndPlay("activoFin");
   };
   clip.myHomeX = clip._x;
   clip.myHomeY = clip._y;
   clip.myFinalX = finalx;
   clip.myFinalY = finaly;
   clip.onRelease = clip.onReleaseOutside = function()

### PR DESCRIPTION
**Pull request by Herschel**
* Implement the drag button states, triggered by clicking + holding on a button and dragging out and back over the button. (`onDragOver`, `onDragOut`, `onReleaseOutside`).
 * Improve general button state behavior when clicking and dragging.
 * Implement `_droptarget` property to return info about where an object is dragged.

Fixes #795, #1451, #1828, #2515, #2833, #3070, #3139, #3183, #3411, #3690, #3758, probably more.
Possibly fixes #3191?

### CODE REVIEW

**Comment by Toad06** [comment]
#2146 can also be added to the list. :)

I've also noticed a few regressions in the following games.

[Bungee Rescue](https://uploads.ungrounded.net/372000/372306_bungee.swf?1178594120)
When you click "Play game", the mouse input now still lives when the level starts, so the grappling hook instantly goes down.
Steps to reproduce: Click "Play game", "Menu", "Main menu" and "Play game" again.

[Hydrophobia](http://www.ferryhalim.com/orisinal/g2/frog.htm)
In this game, the frog can eat flies by pressing the space bar but the input is now very rarely registered.

[Bubble Bees](http://www.ferryhalim.com/orisinal/g2/bubble.htm)
It seems like it's now more difficult to catch bees inside bubbles.

**Comment by Herschel** [comment]
Fixed the issues:
 * Need to be sure to pump the action queue after handing an event. Fixes Hydrophobia and Bubble Bees.
 * Clip events like `mouseMove` and `mouseDown` need to occur before button events like `rollOver` and `press`. Fixes Bungee Rescue.

**Comment by UnknownOriginal** [comment]
> 
> 
> #2146 can also be added to the list. :)
> 
No, #2146 CAN NOT be added to the "Closed" List!..... BECAUSE IT STILL ISN'T WORKING 6 MONTHS LATER!!!

**Comment by Toad06** [comment]
I've checked again and I haven't noticed any issue with this game in the most recent nightly build (nightly-2021-06-29).

**Comment by UnknownOriginal** [comment]
> 
> 
> I've checked again and I haven't noticed any issue with this game in the most recent nightly build (nightly-2021-06-29).

I tested with (nightly-2021-06-27) and when you release the mouse button, the disc still just falls to the ground.

**Pull request merged**
