### PR TITLE
web: Don't polyfill with self-hosted Ruffle while extension is loading

### PR DESCRIPTION
**Pull request by danielhjacobs**
Finally found a way to make this work.

### CODE REVIEW

**Comment by Herschel** [comment]
Does this fix the various conflicts with self-hosted+extension loading in different orders?

**Comment by danielhjacobs** [comment]
It stops the self-hosted build from loading if the extension is loaded (except in such cases where the plugin polyfill is slower to load than the self-hosted build, which can on rare occasions happen in Chrome). So it should make it predictable, and in conjunction with the extension config PR, it should load the correct configuration settings. If there are still issues, they can be fixed in the PublicAPI negotiate function.

**Comment by Herschel** [comment]
Thanks for explaining!

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you for your continued work!

**Pull request merged**
