### PR TITLE
initial web extension

### PR DESCRIPTION
**Pull request by devsnek**
This extension scans for flash objects and replaces them with ruffle players. It had to be written with an injected script because of https://bugzilla.mozilla.org/show_bug.cgi?id=1536094. This extension should be able to be published for both chrome and firefox, although i've only tested it on firefox.

This still needs a lot of polish, and I don't know that much about flash, so any help is appreciated.

Screenshots:

### CODE REVIEW

**Comment by kmeisthax** [comment]
So I've been working on the exact same thing. It's on https://github.com/kmeisthax/ruffle/tree/extension. It's technically further along (I use a custom element in mine, so that I can eventually emulate some Flash API surfaces) but I'm hitting up against some hard limitations of Webpack that make it completely unsuitable for extension usage.

I was informed by @Herschel about this draft PR and decided to take a look. I saw your "shove the entire script in a tag" thing and realized why that's there: Firefox ships a bunch of Javascript sandboxing (called [Xray vision](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Xray_vision)) that keeps privileged extension code from being interfered with by malicious site code. Webpack doesn't know *anything* about this, and even if I feed it the correct extension URL prefix, it can't see the code it's loading because it's on the wrong side of the sandbox.

So I took your idea and made *another* layer of bootstrapping (called `lv0`) that generates a webpack path and pushes it and the main webpack file outside of the extension sandbox boundary. This technically works: if I load the extension on, say, [homestarrunner.net/sbemail2.html](https://homestarrunner.com/sbemail2.html), I get ruffle playing back some old SB Emails. You can see this in commit 4d43fa4d2e22978a27d0127d0cfa45957dcc1ebb on my branch.

However, this isn't suitable long-term: any site that uses Webpack will break, because we're overriding the *site's* webpack public path so that we can use our webpack there. Furthermore, I also plan to make a non-extension version that webmasters can just slap on their own site, which means we need to either:

1. Find a way to no-conflict Webpack so that this can be embedded on other sites safely
2. Migrate away from Webpack to another build system that can aggregate ES6 modules and invoke wasmpack

I'm going to investigate that next. If you have any suggestions as to what kind of build system to use (I'm thinking *maybe* babel and gulp?) please offer them.

**Comment by devsnek** [comment]
I'd be interesting in figuring out a script that can be included in pages to automagically replace flash content with ruffle (site authors can include this script directly) and then all the extension has to do is inject the script into pages that don't have it.

**Comment by Herschel** [comment]
Thank you both, I think having a browser extension will be fantastic, and also make it way easier for us to test various sites (without having to view-source-download-SWF)!

I think it's good to attack it from multiple angles. I picture all three of these use cases being supported:
 * Native JS API to create a Ruffle instance.
    * the current method, Ruffle.new()
    * I picture the big sites like NG, Kongregate, etc. using this for maximum control.
 * Script that can be included on a page which auto-replaces old static/dynamic/SWFObject Flash embeds with Ruffle.
    * Good for legacy site owners who want to quickly keep an old content accessible.
 * Extension which injects the above script automatically onto every page.
    * For end-users to be able to view content even on sites that haven't updated.

It seems like you are both interested in the bottom two, I would love help in this regard as web development is not my area of expertise. I hope you can team up on it! I picture having CI building bundles for the desktop player, the web module, the demo page, and the extension on each tagged release.

@devsnek, the main issue I see with your extension currently is that it hotlinks to the script on ruffle.rs; we should bundle all relevant code with the extension.

@kmeisthax, I'm still not sure on the necessity of using webpack or another bundler for the extension. I can see using it for developer-targeted packages, but what benefit does it gives us for an extension? (I am not super familiar with Webpack, so bear with me!)

Very naive question, but is there any way we can temporarily set `__webpack_public_path__ `, and then switch it back to what webpack normally expects? I guess this is impossible because everything is loading async at once.

I know some people have used [Parcel](https://github.com/rustwasm/rust-parcel-template) with Rust and wasm-pack, but I haven't tried.

**Comment by devsnek** [comment]
I'm working on a bundle that is entirely self-contained.

**Comment by kmeisthax** [comment]
Webpack is only in use because I copypasted the build system from the extension. I have no particular allegiance to webpack and probably wouldn't have used it if that wasn't what the demo site shipped with. We *do* need a bundler, though, since wasm-pack leaves us with a couple of different ES6 module files and I wrote a bunch more. Site operators are really going to want a single file they can just add to their site to polyfill Flash. You can technically use ES6 modules without a bundler, but that would only work for the extension version, and there's additional path restrictions I'd need to work around. e.g. no `import '../../js-src/element.js'`

Replacing the webpack public path after the fact won't work because the load order of scripts isn't guaranteed. We'd need some way to outright hold all script loads on the target site from the moment `lv0` runs all the way to the resolution of `index`, which I don't think we can actually do.

I'm going to investigate parcel tomorrow, if it can at least give me a way to customize how modules are loaded on the client side, then I can fix everything else to work behind the extension sandbox, and I can kill the `lv0` hack.

**Comment by devsnek** [comment]
@kmeisthax  I've found a way to set the proper base path at runtime without interfering with other webpacks on the page.

The current code I have pushed works for people to pull into websites manually, but the extension has a permissions problem due to how webpack loads chunks. As far as I know, the only way to get the wasm into the same file as the main script would be manually copying it somehow. I am currently exploring this more.

**Comment by kmeisthax** [comment]
So, I wound up doing just that. Specifically, we have to have two chunks because Webpack wants it's own `async` context. Well, if I'm going to be `async`, I might as well just load the WASM and helper module myself, so that's exactly what I did.

In order to do this, I have to make use of the `no-modules` mode of `wasm-pack`, which means I have to trigger it manually. I added a `build.sh` file to very inelegantly duct-tape the two build systems together. The result works but I hate it; if I can find a way to get `WasmPackPlugin` to do the same thing then maybe I'll bring it back.

I like your approach of generating the manifest file in a Webpack plugin; although you'll need to expand `web_accessible_resources` to the entire `dist` directory or you won't be able to get at the WASM.

see commit f098d30e26a26a6098c51f3635fc0caaa6a1dba1 for details

**Comment by Herschel** [comment]
Closing in favor of #53, thanks for your work!

**Pull request closed without merging**
