### PR TITLE
ActionScript 2 OOP operations

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR contains support for various things used by ActionScript 2. We didn't strictly need these for Object Prototyping because we can basically define the entire system object hierarchy without these features.

The following is provided in `as2-oop`:

 * `ActionExtends` impl
 * `ActionInstanceOf` impl + instance field on prototypes
 * `ActionImplementsOp` impl
 * `ActionCastOp` impl
 * Support for the undocumented `ASSetPropFlags` function 
  In their infinite wisdom, Macromedia decided implementing an undocumented callable would be a better option than a new action to define an object property.
 * Constant pool closures
   AS2 class definitions run in init actions. Flash MX 2004 at least seems to also define a new constant pool for each init action. This means functions need to close over the current constant pool.
   The current way that multiple constant pools are managed is mostly a best-guess; further hand-crafted opcode testing may be required.
 * `super`
   This is actually implemented with a native object impl that wraps over the current one, and skips one layer of prototyping. I may still need to modify this - long `extends` chains probably won't take too kindly to creating multiple layers of `super`.
   * [x] Run some tests in Flash to determine exactly what `super` is - how does it handle unexpected operations, and the like?
    You can't iterate keys on `super`. This PR currently allows that, because we actually invoke super constructors and methods with `SuperObject` as `this`. For total accuracy we would need to invoke all methods in the chain with the same `this`, and then somehow determine how many levels of `super` have already been invoked. I'm not sure if this is worthwhile.
   * [x] Support all `Object` trait methods on `super`
   * [x] Realize `super` doesn't support ANY trait methods and completely redo how it works
 * Tests
   These don't pass yet, which is why this is a draft PR.
   * [x] Get @Dinnerbone's tests working

### CODE REVIEW

**Comment by kmeisthax** [comment]
So I got all our tests working again.

`as2-oop` had some dependence on `Function.prototype.toString` thanks to ECMA Abstract Compare, so I had to cherry-pick that from an upcoming PR that I didn't even PR yet.

`extends_chain` had a bunch of surprises:

 * AS2 classes that use `extends` have their `constructor` be the *parent* class. This is contrary to regular functions (and thus, AS1 OOP) where `constructor` is the function that holds the prototype. Somehow, I managed to implement both behaviors correctly, but failed to notice the discrepancy.
 * Interfaces can extend other interfaces, which is implemented with another prototype chain. So `instanceOf` has to check every instance's prototype chain. We can technically even handle instances on instances, though this isn't possible to generate using Macromedia's AS2 compiler.
 * `ActionExtends` was implemented incorrectly. Turns out I am not immune to mixing up `prototype` and `__proto__`.
 * `SuperObject` needs to hold a reference to itself so that constructor calls get the `SuperObject` as `this`. This allows chains of `super` calls to work.

That last bit is the thing keeping me from releasing this for review: `super` doesn't yet implement a couple of `Object` methods that it really can't without access to an `UpdateContext`. I originally hoped to be able to just get away with not implementing them on `super`, but because I need to hand supercalled constructors the super object as `this`, it likely needs to support all `Object` trait methods.

**Comment by kmeisthax** [comment]
I implemented the remaining `Object` methods on `super`. This is necessary because, for supercalls, we use `super` as the new `this`, so that we can keep track of how many levels of prototyping we need to remove in order to keep going up the prototype chain.

I'm starting to think this approach may be a problem, though. Base methods that call other methods on `this` should get the derived methods again, not their own; and holes in the prototype chain will probably throw off our careful nesting. Ideally, `super` would just magically know what the next prototype in the chain is based on the currently called function, and we could use the same `this`, but I'm not sure how to accomplish that...

**Comment by kmeisthax** [comment]
I *de*implemented most of `super`'s trait methods, because it turns out Flash doesn't support most any of them. From the perspective of `TObject`, only the following actually do anything:

 * `call` - calls the constructor of the current method in the chain
 * `proto` - gets the prototype of the parent class. (Actually, at least in Flash 8, this appears to return a bespoke prototype chain that does not `===` against the original one)
 * `new` - Yes, you can totally `new super()` and everything works as expected
 * `as_display_object` - Yes, you can totally `MovieClip.prototype.unloadMovie.call(super)` (within a linked `MovieClip` subclass) and the native impl of that method will correctly unload the clip

All other methods are trivially implemented (e.g. `get_local` always returns `undefined`, `set` silently fails, `delete` returns `false` etc). The only remaining mystery is what Flash does with `super`'s prototype chain, but I don't think this should hold up this PR.

**Comment by Herschel** [comment]
Thank you!

Rebased onto master and re-arranged `Attribute` enum so we can use `EnumSet::from_bits` in `as_set_prop_func`. It'd be nice to use an `Iterator` for `object::interfaces`, but it's a little annoying (have to make an `InterfacesIter` wrapper type) and this code doesn't run that often.

**Pull request merged**
