### PR TITLE
web: Don't report extension URL on error

### PR DESCRIPTION
**Pull request by relrelb**

### CODE REVIEW

**Comment by Dinnerbone** [comment]
For what it's worth, this is useful to find extensions that are ruffle-in-a-skin

**Comment by n0samu** [comment]
Looks like you also made some minor changes related to #11678. Do you want to also implement @Toad06's suggestion from https://github.com/ruffle-rs/ruffle/pull/11678#discussion_r1238682372?

**Comment by relrelb** [comment]
> Looks like you also made some minor changes related to #11678. Do you want to also implement @Toad06's suggestion from [#11678 (comment)](https://github.com/ruffle-rs/ruffle/pull/11678#discussion_r1238682372)?

Done. Let me know what you think.

**Comment by n0samu** [comment]
Looks good! 👍

**Pull request merged**
