### PR TITLE
tests: Increased tolerance of stage3d tests

### PR DESCRIPTION
**Pull request by Dinnerbone**
This makes the tests pass on my machine

### CODE REVIEW

**Review by Aaron1011 — APPROVED** [review]

**Comment by torokati44** [comment]
I still get this failure:
```
---- avm2/stage3d_raytrace ----
Number of outliers (6) is bigger than allowed limit of 3. Max difference is 76
```

**Comment by Dinnerbone** [comment]
@torokati44 if you increase the tolerance to 2 there, is it enough?

**Comment by torokati44** [comment]
@Dinnerbone Nope.

**Comment by torokati44** [comment]
This works though:
```toml
[image_comparison]
tolerance = 1
max_outliers = 6
```

**Comment by Dinnerbone** [comment]
> @Dinnerbone Nope. The max difference of 76 hints at this.

Not really, it's easily misunderstood. There can be a bunch of 2-delta pixels and a single one of 76. The outliers should catch the crazy high value, and the rest we allow with a tolerance.

**Comment by torokati44** [comment]
Oh, I see... That's really not intuitive...

**Comment by Dinnerbone** [comment]
Nope it's not but that's statistics 😅

**Comment by torokati44** [comment]
Couldn't find any lower limits than the above 1 - 6...

**Comment by Dinnerbone** [comment]
@torokati44 all good now?

**Comment by torokati44** [comment]
I was able to confirm now, all the tests (including visual) are indeed passing on my machine with these tolerances.

**Pull request merged**
