### PR TITLE
web: Add `detect_chromedriver_version` to `web/.npmrc`

### PR DESCRIPTION
**Pull request by Aaron1011**
This should prevent CI failures when Github updates Chrome on the runner images.

### CODE REVIEW

**Comment by relrelb** [comment]
Actually, such file already exists: https://github.com/ruffle-rs/ruffle/blob/master/web/packages/selfhosted/.npmrc

**Comment by Aaron1011** [comment]
@relrelb: I don't think that will apply when chromedriver is installed from `web/package.json`

**Comment by relrelb** [comment]
> @relrelb: I don't think that will apply when chromedriver is installed from `web/package.json`

Well, if it works, I think https://github.com/ruffle-rs/ruffle/blob/master/web/packages/selfhosted/.npmrc can be deleted.

**Comment by Aaron1011** [comment]
Looks like it succeeded - I'll remove the other file.

**Comment by danielhjacobs** [comment]
Well, it did succeed, but unfortunately, the two workflows that could end up failing (ubuntu-22 web tests) both ran on the old image version, so they would succeed without this change too.

So we can't be sure it worked.

**Review by relrelb — APPROVED** [review]

**Pull request merged**
