### PR TITLE
avm2: Implement AsTypeLate opcode

### PR DESCRIPTION
**Pull request by EmperorBale**
Adds the `AsTypeLate` opcode which is used for the `as` keyword.

There is also the `AsType` opcode but I couldn't implement it because I couldn't figure out how to get my flash compiler to generate that opcode :/

### CODE REVIEW

**Review by Herschel — APPROVED** [review]
Looks good here, if you wanted to implement `astype`, you could use FFDec to edit the byte code to say `astype QName(...)`.

**Comment by EmperorBale** [comment]
While adding the `AsType` opcode I found a bug with the `IsType` opcode, so i'll fix that in this PR too

**Review by kmeisthax — APPROVED** [review]
Looks good. I'll leave the PR open just in case @EmperorBale wants to try for `astype` again; if not either me or @Herschel can merge.

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Looks good here!

**Pull request merged**
