### PR TITLE
Revert "build: Freeze rustc for nightly builds to 1.80.1"

### PR DESCRIPTION
**Pull request by torokati44**
Reverts ruffle-rs/ruffle#17810

Merge once the Vector.sort situation is _sorted out_.

### CODE REVIEW

**Comment by torokati44** [comment]
Related: https://github.com/ruffle-rs/ruffle/issues/17785 and https://github.com/rust-lang/rust/issues/129561#issuecomment-2336413186

**Comment by danielhjacobs** [comment]
Rebased. This is probably good to merge, but it should be tested to make sure https://github.com/ruffle-rs/ruffle/issues/17785 works properly still.

**Comment by torokati44** [comment]
I actually can't reproduce that even before https://github.com/ruffle-rs/ruffle/pull/17846... :/ On desktop at least.

**Comment by danielhjacobs** [comment]
Just to be sure, though, I assume so, you're testing with building with rust 1.81, right?

**Comment by torokati44** [comment]
Of course. The AVM trace is really helpful in suggesting that this is supposed to happen near the "end game screen", but for me, it didn't.

**Review by adrian17 — APPROVED** [review]

**Pull request merged**
