### PR TITLE
ci: Cache Cargo output on Github Actions

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Herschel** [comment]
How does using the native GH cache action compare to https://github.com/marketplace/actions/rust-cache ?

**Comment by Aaron1011** [comment]
I'm not sure - I'll test that out in a separate PR.

**Comment by Herschel** [comment]
I ask because I remember clean our own artifacts from the `target` folder (https://github.com/rust-lang/cargo/issues/5885), causing the cache to have to be re-uploaded on practically every build. Not 100% sure if this is still an issue with either `cache` or `rust-cache` methods.

**Comment by relrelb** [comment]
Can you please prefix the commit message with `ci:` (or prepend it on merge using squash)?

**Comment by adrian17** [comment]
FYI when using `rust-cache`, I had issues with some jobs still "ignoring the cache" - as in, they restore the cache, but the actual build still starts with all the dependencies from scratch.
See: https://github.com/adrian17/ruffle/runs/7819309280?check_suite_focus=true
Some of the jobs do clippy and test build fast, others in 5x the time due to dependencies.
I didn't figure this out, unfortunately.

**Comment by adrian17** [comment]
Looks like indeed they try redownloading and rebuilding the crates :/ Even wasm-bindgen.

**Comment by Herschel** [comment]
Ok, took some time to look at the behavior of GitHub Actions here and how to avoid redownloading things:
 * All of the jobs on the same OS were using the same cache, despite being matrixed for different targets/Rust versions.
 * Unlike some other CIs, GitHub Actions caches are immutable once created.
 * This means on the initial cache, one job would "win" and create the cache. This specific job would be nice and cached on future runs.
 * But the other jobs on that same OS would have none of their cached dependencies.
 * These jobs would end up redownloading different parts of the stack.

So  I made these changes:
 * Add `web`, `desktop`, and `matrix.rust_version` to the cache key, so there are separate caches for each of these builds.
 * Skip the `install wasm-bindgen` step if the cache was hit.

I'm sure there are some improvements here -- for example, possibly wasm-bindgen could be in its own cache and doesn't need to be built separately per Rust version -- but fiddling with CI is probably my least favorite thing. 😆

**Comment by Herschel** [comment]
Looked over `rust-cache` a bit, and it's by default keyed with rustc version as I described above. I believe the reason it was acting up in @adrian17's examples was that it was keyed via `job_id`, and both our desktop and web workflows have a job_id of `build`. Things are working good now that I changed this to an explicit `desktop`/`web` key.

https://github.com/Herschel/ruffle/runs/8085728266?check_suite_focus=true

`rust-cache` has some smarts to clean to cache of stale artifacts etc., so let's go with that.

**Pull request merged**
