### PR TITLE
avm1: Fix function closures inside `with`

### PR DESCRIPTION
**Pull request by Herschel**
When creating a scope for a closure, any `with` scopes were being filtered out, but this seems incorrect; `with` scopes are still on the scope chain when the function is called.

### CODE REVIEW

**Comment by Herschel** [comment]
@kmeisthax Is this right? I'm not sure what the original reasoning was here; I looked through the ES spec to see if there was some mention of filtering out `with` scopes but didn't see anything.

**Review by kmeisthax — APPROVED** [review]
Honestly, I don't remember why I exempted with scopes from closures; I might have tested something in Flash and wrote the test wrong.

**Comment by Herschel** [comment]
Thanks! I've been looking to some SWFv5 issues related to #5502 that might have been what you were seeing -- hopefully I'll solve these in PRs.

**Comment by Toad06** [comment]
For reference, this fixed #5882.

**Pull request merged**
