### PR TITLE
avm2: Mouse event support

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR aims to support dispatching mouse events into AVM2, which will at least hypothetically allow basic games to work.

It changes a number of internal things relating to event dispatch, much like the previous interactive object PR. One thing to explain first is that there are actually four patterns of event dispatch across three different representations. Those look like the following:

| Pattern | Recipient | Example | `InteractiveObject` | AVM1 | AVM2 |
| - | - | - | - | - | - |
| Broadcast | All interested objects | `enterFrame`, `exitFrame`, `frameConstructed` | Certain `DisplayObject` methods | Global objects such as `Mouse`, `Key`, etc<br/><br/>`onXYZ` on interested objects | `addEventListener` on any object that exposes the broadcast |
| Anycast | First object to handle the event | `mouseMove`, `mouseDown`, `mouseUp` | `handle_clip_event` | `onXYZ` on interested objects | Not available |
| Targeted | A specific DisplayObject only | `press`, `release` | `handle_clip_event` | `onXYZ` on interested objects | `addEventListener` |
| Bubble/&ZeroWidthSpace;Capture | The ancestor of a targeted event recipient | N/A | Not available | Not available | `addEventListener` | 

Notably, AVM2 expects certain events to be targeted, while AVM1 wants them to be broadcasts or anycast. We're using the existing `InteractiveObject` and `ClipEvent` machinery to deliver events to AVM2, which means that we need three new event types:

 * `MouseWheel`. In AVM1 this is a broadcast, so there's no `ClipEvent` equivalent.
 * `MouseMoveInside`. The existing `MouseMove` event has anycast semantics, so we need a targeted equivalent.
 * `MouseUpInside`. The existing `MouseUp` event has anycast semantics, so we need a targeted equivalent.

The remaining event types already available had compatible dispatch semantics, so we're reusing them. All AVM2 event dispatch for clip events currently occurs in `InteractiveObject.event_dispatch_to_avm2` and all existing object types now punt to it if they hold a valid AVM2 object to dispatch on. The new event mappings are as follows:

| `ClipEvent` | AVM2 | Notes |
| - | - | - |
| `Press` | `mouseDown` | |
| `MouseUpInside` | `mouseUp` | |
| `Release` | `click`, `doubleClick` | Double-click tracking is currently handled by `InteractiveObject` |
| `ReleaseOutside` | `releaseOutside` | |
| `RollOut`, `DragOut` | `mouseOut`, `rollOut` | A `to` parameter has been added to the corresponding `ClipEvent`s<br /><br/>AVM2 does not distinguish between `RollOut` and `DragOut`<br /><br />`rollOut`/`rollOver` tracking is handled by `InteractiveObject` |
| `RollOver`, `DragOver` | `rollOver`, `mouseOver` | ibid |
| `MouseWheel` | `mouseWheel` | Flash Player appears to report a delta of 3/-3 on my machine when Ruffle reports 1/-1 |
| `MouseMoveInside` | `mouseMove` | |

No attempt has been made to support middle- or right- mouse button events yet, as we don't get `PlayerEvent`s for them.

# Progress

- [x] MouseEvent
  - [x] Constructor
  - [x] `altKey`
  - [x] `buttonDown`
  - ~~`clickCount`~~ nevermind this is AIR only
  - [x] `commandKey`
  - [x] `controlKey`
  - [x] `ctrlKey`
  - [x] `delta`
  - [x] `isRelatedObjectInaccessible` (stub)
  - [x] `localX`/`localY`
  - [x] `movementX`/`movementY` (accessors only, not dispatched)
  - [x] `relatedObject`
  - [x] `shiftKey`
  - [x] `stageX`/`stageY`
  - [x] `toString`
- [x] Mouse event dispatch
  - [x] Internal event data representation
  - [x] `click`
  - [x] `doubleClick`
  - ~~`middleClick`~~ Player does not have support for these events
  - ~~`middleMouseDown`~~
  - ~~`middleMouseUp`~~
  - [x] `mouseDown`
  - [x] `mouseMove`
  - [x] `mouseOut`
  - [x] `mouseOver`
  - [x] `mouseUp`
  - [x] `mouseWheel`
  - [x] `releaseOutside`
  - ~~`rightClick`~~
  - ~~`rightMouseDown`~~
  - ~~`rightMouseUp`~~
  - [x] `rollOut`
  - [x] `rollOver`

### CODE REVIEW

**Comment by danielhjacobs** [comment]
While I know you already did the work on them, aren't controlKey and commandKey also AIR only?

https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/MouseEvent.html#commandKey

**Comment by kmeisthax** [comment]
I've released the draft lock, this PR is ready for review.

This involves some changes to event handling, so I'm specifically requesting @Toad06 test AVM1 games with known event-handling bugs.

**Comment by Toad06** [comment]
There is an issue that seems to affect any file on the Web target. Basically, when clicking anything but a button (or something that triggers an action), Ruffle crashes with the following message:
`panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:13:9`

For instance, in [Garfield Coop Catch](https://img-hws.y8.com/cloud/y8-flash-game/contents/item_versions/flash_games/1864/original/garfield_coop_catch.swf?1521285924):
- if you click "click here to play", then the game keeps running as expected.
- if you click Garfield, Ruffle panics.

This issue doesn't happen on desktop targets (tested on Windows).

**Comment by kmeisthax** [comment]
@Toad06 I think that might be ultimately because of the double-click detection I added. I'm genuinely surprised wasm doesn't support `Instant`, but I can work around that.

**Comment by Toad06** [comment]
I'm surprised too. Looks like Dinnerbone also faced this issue in c51a7d1a21e2a9c8f597ebf14560ea34b559ee46 and fixed it with `use instant::Instant;`.

**Comment by Toad06** [comment]
Apart from that, this looks good to me, I haven't noticed any regressions. 👍

**Comment by kmeisthax** [comment]
I *think* I got web working again. I'm not 100% sure, because I get a Webpack error when I try to build selfhosted. (specifically something like "HookWebpackError: Only file and data URLs are supported by the default ESM loader")

However, the extension builds fine so I'm assuming this is just me being on an old Node version. @Toad06 can you confirm? One of the tests is failing but that's because of a new nightly lint.

**Comment by Toad06** [comment]
I had that error too the first time I tried to compile. Your assumption is correct, updating Node and its dependencies fixes that Webpack error (someone on Stackoverflow suggested to do that which is fortunate as I didn't know the meaning of that error 🙃). So I confirm the selfhosted build compiles and runs as expected.

**Review by Herschel — COMMENTED** [review]
Thank you!

**Pull request merged**
