### PR TITLE
Run `update_drag` earlier in the update cycle.

### LINKED ISSUE #1511: Dragging Doesn't work
I have attached a file to test. A short education game. The first question requires you to drag to answer. However, dragging doesn't work when used with Ruffle.

[perim-bots (1).swf.zip](https://github.com/ruffle-rs/ruffle/files/5503908/perim-bots.1.swf.zip)

### PR DESCRIPTION
**Pull request by desuwa**
Should fix #1511

### CODE REVIEW

**Comment by kmeisthax** [comment]
I'm tempted to merge this right away, but before I do so: is it possible to have any kind of regression test for this behavior? If not, I'll just merge it.

**Comment by desuwa** [comment]
> regression test

Probably not possible without some way to simulate mouse movements.

I've made some changes so it only ignores actually duplicate calls.
In that perim-bot game, startDrag is called inside a onEnterFrame callback so it's more of a timing issue in Ruffle I think. For example, calling self.update_drag() before the closure up here also solves it https://github.com/ruffle-rs/ruffle/blob/5d198952e89819286d9cb560c750b1678bc02e1d/core/src/player.rs#L1381

**Comment by kmeisthax** [comment]
I wouldn't be surprised - just getting the AS3 order-of-events for frame progression right was a challenge, and I *know* some of them get triggered before or after frames are incremented in ways that broke AS2 when I tried to add them into Ruffle. I still don't understand it fully and I don't think I will until I implement `Loader` and start writing mixed-movie networks.

Is there any particular reason why only `update_drag`, and not `update_roll_over`, would need to run before the other frame events?

**Comment by desuwa** [comment]
> Is there any particular reason why only `update_drag`, and not `update_roll_over`, would need to run before the other frame events?

No idea really, but for this particular case, the dragging operation gets restarted on every frame with new offsets so the object never actually moves. But if you do a startDrag with the lockCenter flag enabled, it'll work fine.

Though update_roll_over also has some order execution issue too. Feels like mouse events should be queued ideally.

**Comment by kmeisthax** [comment]
Alright. Normally I'd merge this, but I just noticed that the original change you made got lost when you rebased - I'm only seeing the event order change now, and not the `startDrag` change.

If this wasn't your actual intent - please cherrypick ebbb44a926e6f7bb84bdc0dcf48204e846ec3241 or go here to get your diff back: https://github.com/ruffle-rs/ruffle/commit/ebbb44a926e6f7bb84bdc0dcf48204e846ec3241

**Comment by desuwa** [comment]
Yeah I changed the execution order instead.
Skipping startDrag was a pretty bad idea when I think about it. It's defintiely not how flash player does it.

**Comment by kmeisthax** [comment]
Gotcha. In that case I'll merge.

**Pull request merged**
