### PR TITLE
web: Update to manifest v3 where supported (Chrome/Edge)

### PR DESCRIPTION
**Pull request by Dinnerbone**
Doesn't take advantage of any new v3 stuff, just gets it working as-is

### CODE REVIEW

**Comment by danielhjacobs** [comment]
In testing, mostly works, except the `injectScriptRaw` on Chromium on many websites, as mentioned on Discord.

**Comment by n0samu** [comment]
Testing this in Edge, it definitely seems to have worsened the "extension loads too late" situation. On http://www.g2conline.org/ and Toad06's swfobject test from #448, navigating to and from the page using the browser's Back and Forward buttons almost always causes the Flash detection scripts to fail, whereas on the current nightly build, this almost never happens.

**Comment by n0samu** [comment]
Also, this breaks the "Open in a new tab" feature for URLs not ending in .swf, such as Itch.io Flash pages. ([Here's an example](https://rarykos.itch.io/hug-me-im-cold) from #6119.) We should make the "Open in a new tab" button link directly to the extension's internal player page (for both the Chrome and FF extension, because why not).

**Comment by Dinnerbone** [comment]
> Also, is there a reason to make the internal player page load SWFs either via the `url` parameter or the hash fragment? I think we should stick to one or the other.

The previous way was `?url=foo`, but that won't work with the redirect options we have available, as we can't uri encode the swf url. Hash works, and imo looks so much cleaner too.

I'll switch Firefox to using hash too soon, but didn't want to change how Firefox worked in this PR.

**Comment by Dinnerbone** [comment]
> Also, this breaks the "Open in a new tab" feature for URLs not ending in .swf, such as Itch.io Flash pages. ([Here's an example](https://rarykos.itch.io/hug-me-im-cold) from #6119.) We should make the "Open in a new tab" button link directly to the extension's internal player page (for both the Chrome and FF extension, because why not).

I had a try at this, but Chrome (at least, I didn't try the others) blocks URLs that lead directly to extension pages.

**Comment by Dinnerbone** [comment]
Chrome should now run the plugin polyfill immediately

**Comment by n0samu** [comment]
> I had a try at this, but Chrome (at least, I didn't try the others) blocks URLs that lead directly to extension pages.

I guess the only solution then is to send a message to the background script and have it open the player page when it receives the message. I guess it would be ok to leave that for a separate PR but I hope we can get it done soon, so people don't start noticing stuff breaking.

**Review by danielhjacobs — APPROVED** [review]
Just tested this in Chromium and it seems to be working well. Also had a quick look over the code and it LGTM. Hopefully n0samu's suggestion can be implemented for non-swf direct links, but that can be a follow-up PR. Guess we should keep a close eye on https://bugzilla.mozilla.org/show_bug.cgi?id=1687755 so we can use this manifest for Firefox.

**Pull request merged**
