### PR TITLE
xml: Use forked quick-xml to support loose entity parsing

### PR DESCRIPTION
**Pull request by adrian17**
Fixes https://github.com/ruffle-rs/ruffle/issues/4699 , possibly others.

Things of note:
1. ~~The cargo crate is linked to fork's branch instead of specific tag/commit. Not sure which way is the better one here.~~
2. ~~Should `process_entity` bool paramater also matter when deciding to unescape the attribute?~~
3. ~~There are minor whitespace differences between FP and Ruffle when pretty-tracing the XML. I decided to put the Ruffle version in the test, but this means that the test will fail if it ever gets run with real FP. Not sure if there's a better way. (...I could just not test this particular trace, as it's not critical to the test?)~~

### CODE REVIEW

**Comment by midgleyc** [comment]
1\. commit is probably safer, in that branch changes won't automatically update the build here. However, as Ruffle owns the fork anyway, it's unlikely to matter.
3\.  I think it'd be best to only test the ones that are the same in FP and Ruffle. The "data  label" (two spaces) whitespace in Ruffle looks wrong, and feels like a bug.

**Comment by adrian17** [comment]
Thanks, updated.

**Comment by danielhjacobs** [comment]
Not directly related to this PR, but worth noting as mentioned on Discord, https://github.com/ruffle-rs/ruffle/blob/master/core/src/xml/tree.rs#L303 should be changed to use https://docs.rs/quick-xml/0.22.0/quick_xml/events/attributes/struct.Attribute.html#method.unescaped_value in a future PR.

**Comment by adrian17** [comment]
That's what I did in this PR, in https://github.com/ruffle-rs/ruffle/pull/5166/files#diff-a7f53aef6232719c6074cd573398a8ae7a8f49f3cf452a81a29a5430d748a5afR303 :)
What's also what note 2 refers to.

**Comment by midgleyc** [comment]
For 2., I think it should matter: it affects how the attributes are interpreted, assuming I read it correctly.

It's only called in two places, both in `replace_with_str`, so it shouldn't be too hard to add.

**Pull request merged**
