### PR TITLE
web: Avoid double polyfilling embed-inside-object

### PR DESCRIPTION
**Pull request by Herschel**
The standard method of embedding an SWF uses an embed-inside-object, and would incorrectly get polyfilled twice, creating two Ruffle instances:

```
<object>
  <param name="movie" value="TrailForSnail.swf" />
  <embed src="TrailForSnail.swf" />
</object>
```
This was especially noticeable with the new autoplay functionality. Avoid copying over embed tags from within a polyfilled object tag.

### CODE REVIEW

**Review by WumboSpasm — DISMISSED** [review]

**Comment by Dinnerbone** [comment]
The code/tests look good but huh I assumed the inner would take precedence, not the outer. Never tested it though!

**Review by Dinnerbone — DISMISSED** [review]

**Comment by Toad06** [comment]
```
<object>
  <param name="movie" value="coopcatch.swf" />
  <embed src="goldminer.swf" />
</object>
```

Using the Flash Player, it plays "goldminer.swf" in Chrome, Firefox and IE.
Ruffle plays "coopcatch.swf" (this is what also happened in the previous builds).

**Comment by Herschel** [comment]
Looks like the outer object uses the older `classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"` method, which worked on IE10 and earlier(?). if you replace this with the newer `type="application/x-shockwave-flash"` attribute, the object tag does take precedence.

**Comment by Herschel** [comment]
Okay, the polyfill will now try to mimic what Chrome etc. does, so there are four cases:
 * `embed` replaced with `ruffle-embed`
 * `object` replaced with `ruffle-object`
 * `object`-with-`embed`, `object` replaced with `ruffle-object` and `embed` removed, when object takes precedence
 * `object`-with-`embed`, inner `embed` replaced with `ruffle-embed` when embed takes precedence

For the object-with-embed case, the object normally takes precedence unless it has the Flash classid parameter, in which case the inner embed takes precedence.

Please give this another look, thank you!

**Review by WumboSpasm — APPROVED** [review]
Tested with a variety of embeds and they all work well on my end.

**Comment by Toad06** [comment]
Phew, that's more complex than I would have imagined!

I just noticed a regression with SWFObject:
`Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node`
This is because Ruffle now seems to polyfill elements with src or data attributes which wasn't the case since PR #556.

Here's a sample: [swfobjTest.zip](https://github.com/ruffle-rs/ruffle/files/5602417/swfobjTest.zip) (I recommend using the self-hosted files to test this, as the extension can run the polyfills too late at the moment - especially on Chrome)

Apart from that, all good! 👍

**Comment by Dinnerbone** [comment]
Can we add that as a test to the suite?

**Comment by Toad06** [comment]
I think these tests should be good: [tests.zip](https://github.com/ruffle-rs/ruffle/files/5604961/tests.zip)

**Comment by Herschel** [comment]
Okay, I think this is good now, thanks for the tests!

Would probably be useful to add an SWFObject test or too, as well.

**Pull request merged**
