### PR TITLE
chore: Update chromedriver

### PR DESCRIPTION
**Pull request by danielhjacobs**

### CODE REVIEW

**Review by relrelb — APPROVED** [review]

**Comment by danielhjacobs** [comment]
Actually, looking again, they may fail, in which case I'll close this. I thought this was needed because https://github.com/ruffle-rs/ruffle/actions/runs/2819761760 failed, but that may have just been a fluke, since https://github.com/ruffle-rs/ruffle/actions/runs/2819762991 succeeded, and https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#browsers-and-webdrivers and https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers say Chrome 103, not 104.

**Comment by danielhjacobs** [comment]
Yeah, very strange fluke. No idea how the CI could have a different Chrome driver for just one run.

**Comment by danielhjacobs** [comment]
Mentioned in Discord:

https://github.com/ruffle-rs/ruffle/runs/7731010612?check_suite_focus=true ran with this image: https://github.com/actions/runner-images/blob/ubuntu20/20220807.1/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers, but that image is created by commit https://github.com/actions/runner-images/commit/3c5935f2a2208ebca95da6a10be038acd9f153be, which is part of https://github.com/actions/runner-images/pull/6031, which is un-merged.

Apparently https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220807.1 exists despite the PR being unmerged, so I can't help but suspect that has something to do with this. 

Opened https://github.com/actions/runner-images/issues/6034

**Comment by danielhjacobs** [comment]
https://github.com/actions/runner-images/issues/6034#issuecomment-1208665143

**Comment by danielhjacobs** [comment]
Marking as draft until CI more consistently uses the updated runner.

**Comment by danielhjacobs** [comment]
CI is now consistently running on the new runner image.

**Comment by relrelb** [comment]
Going to merge this, thanks!

**Pull request merged**
