### PR TITLE
chore: Update quick-xml to 0.35.0

### PR DESCRIPTION
**Pull request by torokati44**
Split from https://github.com/ruffle-rs/ruffle/pull/16769 / https://github.com/ruffle-rs/ruffle/pull/16870 / https://github.com/ruffle-rs/ruffle/pull/16871.
Changelog:
 https://github.com/tafia/quick-xml/releases/tag/v0.32.0
 https://github.com/tafia/quick-xml/releases/tag/v0.33.0
 https://github.com/tafia/quick-xml/releases/tag/v0.34.0
 https://github.com/tafia/quick-xml/releases/tag/v0.35.0
I'm not 100% sure I did all the `UnexpectedEof` replacements correctly.

### CODE REVIEW

**Comment by torokati44** [comment]
See also, for deduplication: https://github.com/Smithay/wayland-rs/pull/736

**Comment by torokati44** [comment]
Hmm, one of the errors is:
```patch
     HTML set:    <b>a<i>b</b>c</i>d</b>e
<    HTML get:    <P ALIGN="LEFT"><FONT FACE="Noto Sans" SIZE="6" COLOR="#000000" LETTERSPACING="0" KERNING="0"><B>a</B><B><I>bc</I></B><B>d</B></FONT></P>
<    Text get:    abcd
>    HTML get:    <P ALIGN="LEFT"><FONT FACE="Noto Sans" SIZE="6" COLOR="#000000" LETTERSPACING="0" KERNING="0"><B>a</B><B><I>bc</I></B><B>d</B>e</FONT></P>
>    Text get:    abcde
     HTML get ml: <!-- the same -->
<    Text get:    abcd
>    Text get:    abcde
```

**Comment by torokati44** [comment]
TODO: change to `0.33`

**Comment by torokati44** [comment]
I just realized, just because `quick-xml` reports it as an error, we are free to handle it in whatever way we want... 🤦‍♂️

**Comment by danielhjacobs** [comment]
Looking at https://github.com/tafia/quick-xml/issues/770#issuecomment-2191734067, it sounds like they'd accept a PR to add a new option (maybe `check_unclosed_end_tags`) to bring back the old behavior. Do we want to open that PR?

**Comment by torokati44** [comment]
There you go: https://github.com/tafia/quick-xml/pull/772

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
