### PR TITLE
ECMA abstract compare

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR implements ECMAScript compliant type coercions, abstract comparison, and abstract equality. This PR is a draft, it's merging is blocked until #113 is merged.

# ECMA Type coercions are terrible

In ECMA-262 2ed, there are three kinds of runtime-specified type coercions:

 * `ToPrimitive`. This calls either `toString` or `valueOf` on objects, whichever is defined first. Which is called first is determined by it being a "hint Number" or "hint String" primitive coercion. Primitive values are unmodified by this operation.
 * `ToNumber` - called whenever the ActionScript runtime wants an `f64` value.
 * `ToString` - called whenever the ActionScript runtime wants a string value.

ActionScript 1/2 inherit this system, but with a quirk: `ToPrimitive` does not treat the coercion hint as a hint. Normally, if you perform a `ToNumber` coercion, that first performs a `ToPrimitive` coercion with "hint Number". That means it's supposed to call `valueOf` first, but if that doesn't exist, then it tries `toString`. Flash forgets to do the latter, so we have to forget, too.

(I am not aware if this was fixed in ActionScript 3. I also haven't checked to see if `ToString` falls back to `valueOf` or not.)

In Ruffle, we further break down these pieces a bit:

 * `ToPrimitive` with hint `Number` is implemented by `Value::to_primitive_num`.
 * There is no bare implementation of `ToPrimitive` with hint `String`.
 * `ToString` is implemented by `Value::coerce_to_string`.
 * `ToNumber` is implemented by `Value::as_number`.
 * An outdated implementation of `ToString` is currently present in `Value::into_string`. This is called by `Value::coerce_to_string` after objects have been coerced to primitive values. Several runtime functions still call this as `ToString`, that should be fixed.

# ECMA Equality is a federal misdemeanor

In ECMA-262 2ed, equality operators (`==` and `!=`), after some faffing about with evaluation order that we as a stack-based virtual machine don't have to deal with, invoke the "abstract equality comparison algorithm". This massive, overwrought 22-step algorithm first applies a number of type coercions to try and get two values of the same type, then applies a number of different comparison rules for each resulting type. I've implemented this in `Value::abstract_eq` and configured the runtime to use it.

# ECMA Relational Operators are a crime against humanity

In ECMA-262 2ed, comparison operators (`<`, `>`, `<=` and `>=`, also called "relational operators" by spec) are structured similarly to equality ones. There is an "abstract relational comparison algorithm" that feeds each operator `true`, `false`, or `undefined`... wait, what? Yes, it uses `undefined` to signal NaN and every operator filters that to `false`. This algorithm specifically calculates `<`, so the `>` operator flips the order of the operands internally. To compute `<=` and `>=`, they flip the order of the operands again and invert the boolean case.

What this means is that `a <= b` is implemented as `!isNaN(a) && !isNaN(b) && !(a > b)`. This actually shouldn't be surprising to anyone here, though, since Flash also uses that as a reason to not implement separate actions for `<=` or `>=`. (They used to not even support `>`.) Still, I find this whole system a complete mess to actually implement, although I eventually did it.

This system is implemented in `Value::abstract_lt` and `ActionLess2` and `ActionGreater` use it.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
This passes every test in #141 except for `_global == null` and `_global == undefined`

**Comment by kmeisthax** [comment]
Huh. How does *that* work? Is there a `_global.valueOf` that returns `null`? Or is the global object just special cased?

**Comment by Dinnerbone** [comment]
Haha, your guess is as good as mine. It doesn't apply to anything else as far as I could see, so I specialcased it in #141.

**Comment by kmeisthax** [comment]
@Dinnerbone I started looking into the test failures. `strictequals_swf6` actually changes behavior depending on what version of Flash it runs in. Macromedia forgot to version-gate this one.

In Flash Player 7 (and below), `NaN !== NaN` as per IEEE and ECMA spec.

In Flash Player 8, they changed this so that `NaN === NaN`. I'm not sure why - this goes against ECMA and modern JavaScript. I can assume that this was either an oversight, or ES4 was supposed to change this behavior at some point. But it's definitely not version-gated behavior at least in FP8.

Unfortunately I don't have access to any newer versions of Flash. (At least, *versions that will load, compile, and trace on AVM1 projects...*) Is there anyone with access to one of the Creative Suite versions of Flash that could check and see if Adobe fixed Macromedia's mistake? (Or tell me how to get trace output from a freely downloadable version of the player?)

**Comment by kmeisthax** [comment]
So I got all of Dinnerbone's tests to pass. Note that, in order to do so, I had to implement `valueOf` on all objects except `_global` - this will need to be adjusted, reverted, or redone after Object Prototyping lands. I know I implemented `Object.prototyping.valueOf` over there, but I don't remember if `_global` is bare over there...

also CircleCI is bugged again

**Comment by kmeisthax** [comment]
Literally as I write that, @Herschel merges in Prototyping lol

**Comment by kmeisthax** [comment]
I rebased onto the newest master now that Prototypes is merged in; everything is all ready to merge assuming CircleCI doesn't choke again.

**Pull request merged**
