### PR TITLE
chore: Update translations

### PR DESCRIPTION
**Pull request by RuffleBuild**
New Crowdin pull request with translations 🎉

### CODE REVIEW

**Comment by torokati44** [comment]
Look, labels!

**Comment by kjarosh** [comment]
(and properly translated metainfo and the desktop file!)

**Review by torokati44 — APPROVED** [review]
The strings themselves LGTM, and the structure too, I think. If you could verify the latter, @kjarosh, then I say let's merge.

**Comment by kjarosh** [comment]
Looks good! I did not want to approve it because I produced most of the strings present here :smile:

**Pull request merged**
