### PR TITLE
core: Handle key events in core

### LINKED ISSUE #4603: Key.isDown should also listen to mouse inputs
In Flash, `Key.isDown(1)` can be used to check if the left mouse button is down.
`Key.isDown(2)` does it for the right button.

In Ruffle, none of these work, as they always return `false`. This makes [this game](https://github.com/ruffle-rs/ruffle/files/6672910/bird.zip) impossible to play.
All backends are affected.

### PR DESCRIPTION
**Pull request by relrelb**
* Move the implementations of `UiBackend::is_key_down` and `UiBackend::last_key_code` to `core` using a newly-introduced `InputManager` helper class. This eliminates a decent amount of code and simplifies it.
* Remove `UiBackend::last_key_char` as it was only used in AVM1's `Key.getAscii()`.
* Fix #4603 by adding `KeyCode::MouseLeft`, `KeyCode::MouseRight` and `KeyCode::MouseMiddle`.
* General refactors and cleanups along the way.

Supersedes #4640.

### CODE REVIEW

**Comment by Toad06** [comment]
Thanks for your work.

I've observed a couple of regressions in the following files, affecting desktop and web backends.

[Steppenwolf 3-3](https://www.y8.com/games/steppenwolf_chapter_3_episode_3)
- Press I to open the inventory.
- Click on an item. Notice it becomes invisible (which shouldn't happen) but becomes visible again when you release the mouse.

[Incriminati](https://uploads.ungrounded.net/38000/38654_incriminati.swf?1008182125)
- Click on a item to hide. Notice it becomes invisible (which shouldn't happen) and remains invisible when you release the mouse.

**Comment by relrelb** [comment]
> Thanks for your work.
> 
> I've observed a couple of regressions in the following files, affecting desktop and web backends.
> 
> [Steppenwolf 3-3](https://www.y8.com/games/steppenwolf_chapter_3_episode_3)
> 
> * Press I to open the inventory.
> * Click on an item. Notice it becomes invisible (which shouldn't happen) but becomes visible again when you release the mouse.
> 
> [Incriminati](https://uploads.ungrounded.net/38000/38654_incriminati.swf?1008182125)
> 
> * Click on a item to hide. Notice it becomes invisible (which shouldn't happen) and remains invisible when you release the mouse.

Thanks for testing! These should be fixed now. It happened because of a mistake in refactoring...

**Review by Herschel — COMMENTED** [review]
I'm not sure that switching `getAscii` to be based on the key code is the right way to go. An issue with our key handling is that Flash key codes change based on keyboard layout in the official player. The AS2 reference says that `getAscii` returns "English keyboard values," but this isn't the case. Worse, it's a mix of both layout and non-layout dependent behavior.

This means that using only scancode/physical key location isn't accurate (web does this with `KeyboardEvent.code`), nor is using only virtual key (desktop does this with `winit::VirtualKeyCode`).

For example, on AZERTY, pressing A produces a Key.getCode() of 65 and getAscii() of 'a', matching the AZERTY layout.  But typing " on a UK keyboard layout (shift+2 on US layout) would still produce the keycode 50 and ascii for @ (matching US layout). Typing & on AZERTY (1 on a US layout) produces the keycode 49 but the ascii for `&`, match US layout for keycode but AZERTY for ascii. Additionally, `getAscii` can return some extended chars, such as ö on a German layout.

Some of this is waiting on keyboard improvements in winit (making it similar to KeyboardEvent on the web, providing both printable character and key code in the same event).

All that being said, I think the Flash's behavior is often undesired! French players of Flash games suffered with awkward controls on AZERTY keyboards. So even if we emulated this accurately, we'd eventually want a toggle to make it use scancodes/virtual keys -- or customizable bindings solve the problem completely.

It'd be helpful if some people with various keyboard layouts to help verify this behavior on the actual Flash Player; not sure if any of the above depends on OS/locale settings.

(cc #1046)

**Comment by Herschel** [comment]
Sorry for the delay here, thinking about it more, let's go ahead with this. It won't be 100% accurate, but I think it's fine for now, and the actual solution that users will want is custom keybindings, anyway. We can also tweak this when winit keyboard events can give us both keycode and text character in a single event.

Could you rebase on master? I also think indexing into a byte string is cleaner than the large match statement for `avm1::globals::get_ascii`. Thank you!

**Comment by relrelb** [comment]
I prefer splitting this PR to multiple, new PRs, instead of rebasing it. So closing.

**Pull request closed without merging**
