### PR TITLE
Very basic dynamic text support

### PR DESCRIPTION
**Pull request by kmeisthax**
image

This PR implements some very basic text layout and AVM access that should allow games that rely on dynamic text to run. I must stress how basic this is: the actual `EditText` is a somewhat extensive subset of HTML 3 with the ability to layer stylesheet rules onto it, and it will likely take 4 or 5 PRs to make it anywhere close to "complete".

What this does contain is:

 * `MovieClip.createTextField`
 * `TextFormat` objects
 * `TextField.getNewTextFormat`/`TextField.setNewTextFormat` - for *storage only*, no formatting will actually be respected yet
 * `TextField.multiline`
 * `TextField.wordWrap`
 * `TextField.textWidth`/`TextField.textHeight`
 * Layout of multi-line and word-wrapped dynamic text
 * Layout caching... sorta - renders cannot cache anything as they don't get a `MutationContext`, but they can use the cache

I should point out that it probably would not be a good idea to implement proper formatting using this approach - the current formatting code will likely require significant adjustment to support what is basically an HTML WYSIWYG editor from 20 years ago.

### CODE REVIEW

**Comment by kmeisthax** [comment]
I was originally going to hold off entirely on HTML parsing until another PR, but then I realized we actually need to parse HTML in order for word-wrap to work. Stuff like the HSR global nav outright doesn't render at all if HTML tags hit the text layout engine. So that's part of this PR now: we parse the entire HTML tree into an `XMLDocument`, and then concatenate the text content of all nodes into a string, which we use to actually render with.

**Comment by Herschel** [comment]
Thanks for your work, this is a big improvement.

I'd rather strip out the HTML tags in this PR than cram it into an XML parser. `TextField.text` should be cached anyways (particularly `text` is what the most SWFs fiddle with), so it's not a big deal to strip out the HTML tags when it's set. Then we can pass `text` sans HTML into `line_breaks`/the other metrics functions for now.

**Comment by kmeisthax** [comment]
I moved all the HTML/XML representation stuff into a separate branch; we're now using the old HTML stripper in this branch.

**Comment by Herschel** [comment]
Looks good, thank you!

**Pull request merged**
