### PR TITLE
Fix String.substr with negative second value

### PR DESCRIPTION
**Pull request by Lord-McSweeney**

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Please include a test for this

**Comment by Lord-McSweeney** [comment]
Currently, this progresses #1883 but the regression tests fail.

**Comment by relrelb** [comment]
@Lord-McSweeney Please include a `avm2: ` prefix in your commit message.

**Comment by Lord-McSweeney** [comment]
Closing as I have been unable to determine the cause of the original issue with the tests, and this breaks the current regression tests.

**Comment by Lord-McSweeney** [comment]
Obsoleted by #11465.

**Pull request closed without merging**
