### PR TITLE
avm1: Big cleanup to reduce the "exposed" footprint of the AVM

### PR DESCRIPTION
**Pull request by Dinnerbone**
Not critical at all, but this helps untangle the avm1 and core code a bit - the surface area of avm1 that core can access is now very small and very explicit:

```rust
pub use activation::{start_drag, Activation, ActivationIdentifier};
pub use debug::VariableDumper;
pub use error::Error;
pub use function::ExecutionReason;
pub use globals::context_menu::make_context_menu_state;
pub use globals::shared_object::flush;
pub use globals::system::SystemProperties;
pub use object::array_object::ArrayObject;
pub use object::script_object::ScriptObject;
pub use object::sound_object::SoundObject;
pub use object::stage_object::StageObject;
pub use object::xml_node_object::XmlNodeObject;
pub use object::{Object, ObjectPtr, TObject};
pub use property::Attribute;
pub use property_map::PropertyMap;
pub use runtime::Avm1;
pub use value::Value;
```

Core can only access these things, and refactoring from here becomes much easier.

A future step, if we wish, is to have an optional feature flag to toggle most of the exposed structs with null implementations.

### CODE REVIEW

**Comment by Herschel** [comment]
@Dinnerbone Could you take a quick peek to make sure I rebased this correctly?

**Comment by Dinnerbone** [comment]
Taking a look!

**Comment by Dinnerbone** [comment]
Looks great! Thanks for rebasing it for me <3

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
