### PR TITLE
Improve TextField.autoSize, implement TextField.background

### PR DESCRIPTION
**Pull request by adrian17**
First commit makes TextField better respect properties of autoSize: with "left", it extends to the right from `_x`; with "right", it extends to the left from `_x+_width`. This doesn't affect text layout; just where the text field appears in the end.
This is not a full fix of any issue; in fact, this doesn't fix completely any issues, just improve them a bit. In particular, various missing parts I noticed:
- there are minor margin-related differences from Flash (you can see the last digit "0" being cut off on screenshots below; that's also why tests run in approximate mode)
- text re-layout should occur lazily (think like `console.log(el.offsetLeft)` triggers reflow in JS), not on each property set
- autoSize="right" should overrule `textFormat.align` and align text to right;
- In #3156, it still sometimes behaves weirdly and I don't fully understand why.

As for improvements:
- #1095 - tooltips no longer appears on top of cursor, so buttons are finally clickable (the layout is still as broken as before though)
- #1440 - "new record" etc appear where it should, but slightly overlap with the "m"
- #3156 - text appears closer to where it should be, but still not 100% correct.
- makes borders refresh on re-layout if `autoSize` is enabled
- implements `TextField.background` flag - before, we would draw background whenever `border=true`, which wasn't correct.

Screenshots:
- test, Flash Player (respectively: reference text, dynamic text with no autoSize, then texts with autoSize=left, center, right):

- test, Ruffle, before PR:

- test, Ruffle, with PR:

- Sonny:

- #3156 no hover:

- #3156 on hover (better than before but sometimes still weirdly too much too the right):

#1440:

### CODE REVIEW

**Review by seanpm2001 — COMMENTED** [review]
It looks good. Everything is clean and functional.

**Comment by kmeisthax** [comment]
Same here.

I'll point out that you should also make sure the other `EditText` tests don't have a rendering regression. I structured them to double as both traceable and renderable regression tests, so you should run them on Desktop & compare with Flash Player or `ruffle/master`. I don't know if your own tests are structured that way or not.

**Comment by craniumcadoo** [comment]
As the author of #3156 this looks promising, though obviously it would be better for me if it fully fixed that issue. I added more SWF files with the same problem to my initial issue. They are nearly identical files, so I doubt they will help, but I thought it better to add them in case they give some clue as to the other issue that you "don't fully understand". I thought and still think they are redundant, but better to include too much detail than too little.

**Comment by adrian17** [comment]
> I'll point out that you should also make sure the other EditText tests don't have a rendering regression

I hoped the existing tests would "handle themselves" without having me actually look at them (especially if they pass) :)
But sure, I can take a look at them (I don't think most of them actually use `autoSize`, so hopefully they shouldn't be affected).

**Comment by adrian17** [comment]
@craniumcadoo FYI:

> Upon moving the mouse to hover over (4), then (5), then back to (4), then ... repeatedly, the text just keeps moving further right, until it is eventually offscreen completely.

From what I see, my patch seems to fix this particular behavior.

**Comment by adrian17** [comment]
Also none of the existing EditText tests are affected, from visual inspection.

**Review by Herschel — APPROVED** [review]

**Pull request merged**
