### PR TITLE
More Efficient Dynamic Insertion Detection & Return Dynamic Polyfill to Default Polyfills

### PR DESCRIPTION
**Pull request by Justin-CB**

### CODE REVIEW

**Comment by Herschel** [comment]
@kmeisthax Is this better than MutationObserver? Seems a little bit of a kludge; would be good to benchmark it in some way to see if it's faster. My only other thought is to use a different property than opacity -- I'd be afraid changing opacity would trigger some sort of expensive redraw/caching inside the browser. Could it animate another property, or at least does it work if you make the initial and final values the same,1.0 to 1.0?

**Comment by Justin-CB** [comment]
I'm afraid that I'm not good enough to make a benchmark. It is a kludge from before the MutationObserver API, but I think that this would probably be triggered less often by Web Apps, which were the main disadvantage that @kmeisthax mentioned.

**Comment by Herschel** [comment]
I wrote up a quick test of different ways of observing and replacing:

[observeTest.zip](https://github.com/ruffle-rs/ruffle/files/4368357/observeTest.zip)

1) Using a `MutationObserver`, checking for objects in `addedNodes` and children
2) Using a `MutationObserver` to detect a change, but finding the objects using a live collection returned by `document.getElementsByTagName`
3) Using the CSS `animationstart` event on the tag in question

On my machine:
Chrome: All nearly the same:
HTMLCollection (1238s) < animationstart (1383ms) <   MutationObserver (1395s)

Firefox:
HTMLCollection (27ms) < MutationObserver (98ms) < animationstart (225ms)
(Interestingly this runs massively faster in Firefox than Chrome, it seems to be a little smarter about deciding when to reflow?).


Given the above, I think using the `HTMLCollection` is the best course of action, as it has simplest code and is performant. The current `MutationObserver` method has to recurse down any added subtree with `getElementsByTagName` anyway, so might as well just do it once on the whole document and reuse it. The times are dominated by the replacement of the object anyway, so the method of detecting an object isn't so important regardless. Feedback welcome, as I'm not a web person and JS benchmarks are finicky.

**Comment by Justin-CB** [comment]
Another thing to test would be the # of times each is triggered on various real-world sites. If 1 method is twice as fast but is triggered 4 times as often by web apps, it would cause more of a slowdown.

**Comment by Justin-CB** [comment]
I might try to make an extension to find out how many (potentially) spurious events each method would have to filter out. I think that spurious events may have more of a performance impact for the extension than the time to actually replace an embed because the number of embeds is not likely to be very large, while the number of DOM insertions made & CSS animations used by webapps is potentially much larger.

**Comment by Justin-CB** [comment]
I've hacked up an extension to test the amount of CSS animations & the amount of DOM mutation events that each approach would need to process:
https://github.com/Justin-CB/DOMwatcher-test

**Comment by Justin-CB** [comment]
It would probably need some of the code from lv0.js to be able to actually insert the CSS, so only CSS animations from the site's CSS trigger the script's event handler.

**Comment by Justin-CB** [comment]
It seems that CSS animations are relatively rare, but your version might still be better.

**Comment by Herschel** [comment]
Closed in favor of #466, thank you for looking into this with me!

**Comment by Justin-CB** [comment]
You're welcome. I'll test it whenever the new extension build is pushed.

**Pull request closed without merging**
