### PR TITLE
Implement Avm1String

### PR DESCRIPTION
**Pull request by Dinnerbone**
This sets us up for optimisations such as:
- Not having the same string cloned many times per operation
- De-duplicating strings in memory, popping and pushing strings should still refer to the same string
- Being able to substr strings efficiently by storing range too, so `"aaaaaa".substr(1)` still refers to `"aaaaaa"` but with a start pos of 1
- Caching hashes
- More efficient equality by checking identity before contents
- Static strings don't need to be in the heap

Some followup ideas that we should explore:
- Priming string constants as `Avm1String`s immediately, as we're going to store them in at least 1 (potentially many more) `Avm1String`s anyway
- Object keys as `Avm1String`. They start out as one, they can end up as one (enumeration)

And allows for us to better improve our invalid utf8 handling in the future.

This PR doesn't contain much of any of those optimisations, however, and just lays the groundwork for it to be its own type. We can build off this easier once it's separated out.

### CODE REVIEW

**Comment by Herschel** [comment]
bikeshed: Maybe we call this `AvmString` since it's already in `avm1` module, and there will be a similar `avm2::AvmString`? Or do we prefer that it's `Avm1String` vs `Avm2String`?

**Comment by Dinnerbone** [comment]
I thought there may perhaps be specific avm optimisations that could be at play, such as the case insensitivity not mattering in AVM2 (as far as I know?) or lifetimes back to AbcFile

**Comment by Herschel** [comment]
I think we'll definitely have separate struct per AVM, I'm just wondering about the naming, `avm1::Avm1String` and `avm2::Avm2String` vs. `avm1::AvmString` and `avm2::AvmString`.

**Comment by Dinnerbone** [comment]
Aha sorry, I misunderstood. Originally I was going to call this `String` but realistically everything would alias it as we're still using std strings for keys and cows. I think both of those will be replaced with this, at which point I don't really imagine any code inside of AVM1 or AVM2 would be using std string over str or this struct. Even the string builtins potentially may not use it.

So I'd say long term we should be looking at just naming this `String`, similar to how everything calls their error `Error`. If something imports it and it conflicts, they'd alias it to disambiguate.

**Comment by Herschel** [comment]
I agree we'll end up replacing most `std::String` with our own String as well, the aliasing is what worries me a bit. `Error` isn't in the std prelude so it's a little different (you have to explicitly import it). Although I guess `Result` is similar. Personally I think it's a bit more explicit and clear to call it `AvmString`.

**Comment by Dinnerbone** [comment]
Ok, AvmString it is!

**Pull request merged**
