### PR TITLE
avm2: Implement Op::TypeOf

### PR DESCRIPTION
**Pull request by CUB3D**
This implements the TypeOf instruction for AVM2, to be able to fully test this I also needed to create a minimal stub for both XML and XMLList as these have a different result ("xml") compared to other objects ("object").

### CODE REVIEW

**Review by seanpm2001 — COMMENTED** [review]
It looks good. However, on `core/src/avm2/activation.rs` on line 2288, there appears to be a unclosed parentheses. Is this type safe in Rust, or should this be fixed? Other than that, it looks pretty good.

**Comment by torokati44** [comment]
The automatic tests passed, so there can't really be any syntactical errors in the code.
It might look confusing at first, but in Rust, putting the condition in `()` is not necessary - discouraged, even -, while the `{}` around each arm is mandatory. Almost opposite of how it is in C.
And I'm not exactly sure how this would relate to type safety anyways.

**Comment by seanpm2001** [comment]
Thank you for the reply. This helps clarify it for me. I was originally wondering how it passed the test with the syntax. Now I know why. I am just so used to the strict syntax in Python when it comes to whitespace and parentheses and most other programming languages requiring a paranthese to always have a closing paranthese. example:
``` python
foo = str(input("Sample")) # Correct
bar = str(input("Sample") # Incorrect
```
Also, I used the word type safety, as I mistook it for a type of syntax error. I will try to get a better definition of type safety and just say "possible syntax error" from now on.

**Comment by Herschel** [comment]
I don't believe you should use the prototypes to check for XML/XMLList, here's a test:
[XMLproto.zip](https://github.com/ruffle-rs/ruffle/files/5968220/XMLproto.zip)
Outputs "xml" twice in Ruffle, "object" and then "xml" in Flash Player.

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
