### PR TITLE
render,desktop: Update to `wgpu` `v22.1.0` and `egui` from `git`, remove `exclude_warp`

### PR DESCRIPTION
**Pull request by torokati44**
Deduplicates the `base64` dependency (by dropping `ron`) and `libloading` (by updating `ash`).

I don't know how important is it to wait for the `trace` feature to be added back.

Also see the commit messages for a bit more info.

### CODE REVIEW

**Comment by torokati44** [comment]
Referencing https://github.com/gfx-rs/wgpu/issues/5991 and https://github.com/gfx-rs/wgpu/pull/5988.

**Comment by torokati44** [comment]
Marked as ready for review.
Should we wait for https://github.com/gfx-rs/wgpu/issues/5974 to keep the `render_trace` feature, or can we live without it for a while?

**Review by Dinnerbone — APPROVED** [review]
I'm fine with losing tracing support, it's super situational - I used it a lot in the early days but never since 😅

**Comment by torokati44** [comment]
TBH I'm not even sure this is the `profiling`/`tracing`/`tracy` kind of "trace" that they removed. Looks more to be a standalone file dumper thing...? 🤔

**Comment by torokati44** [comment]
Or is that also what you meant...?

**Comment by Dinnerbone** [comment]
Yeah it's tracing rendering calls to a file, which can be played back by a wgpu executable.

**Pull request merged**
