### PR TITLE
web: Mark the Firefox extension as compatible with Android upon AMO submission

### PR DESCRIPTION
**Pull request by torokati44**
See for reference:
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-create
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-compatibility-examples

The minimum version is from: https://github.com/ruffle-rs/ruffle/wiki#web

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]

**Comment by Dinnerbone** [comment]
Tried to set these values in the UI and got this error:
Invalid version range. For Firefox for Android, you may only pick a range that starts with version 121.0a1 or higher, or ends with lower than version 79.0a1.

**Comment by torokati44** [comment]
Oh, dang, ouch, pardon.
Thanks for checking! And well in time. 😰
Well then let's set the android min version to "121.0a1"?

**Comment by Dinnerbone** [comment]
Either "121.0a1" or "121" should work, from what I can tell!

**Comment by torokati44** [comment]
Well 121 is a lot cleaner IMHO.

**Comment by torokati44** [comment]
>Tried to set these values in the UI and got this error:
> Invalid version range. For Firefox for Android, you may only pick a range that starts with version 121.0a1 or higher, or ends with lower than version 79.0a1.

On the other hand, uBlock Origin has this set:

> Latest version
> Version 1.54.0
> Released Nov 22, 2023 - 3.46 MB
> Works with firefox 78.0 and later, *android 113.0 and later*

**Pull request merged**
