### PR TITLE
avm1: Apply autosize to a new `EditText` from an SWF `DefineEditText` tag

### PR DESCRIPTION
**Pull request by Toad06**
Small fix for #5648, assuming it's correct.

### CODE REVIEW

**Comment by adrian17** [comment]
I understand the `autosize` fix, but why the `relayout` change?

**Comment by Toad06** [comment]
I had to do the change in `relayout` to prevent another issue on the same file with the following text:
ff

Without the change, the text in this snapshot would be displayed at an incorrect position (0,0 - which are the values of `xmin` and `ymin`) because it wouldn't have applied its PlaceObject tags.

But there's certainly a better and cleaner way to do this.

**Comment by Herschel** [comment]
Could we set the `transformed_by_script` flag either in `EditText::set_autosize` or `avm1::globals::text_field::set_autosize`? This would avoid the need to change `relayout`.

**Comment by Herschel** [comment]
After looking into it a bit more, I'm thinking that `autoSize` should not set `transformed_by_script` at all. Here's an example:
[text.zip](https://github.com/ruffle-rs/ruffle/files/8312120/text.zip)
`textField.autoSize` is set to `"left"` via script, but in the Flash Player, the subsequent PlaceObject tag still moves the original textfield, which means we shouldn't set `transformed_by_script` at all in this case.

**Review by Herschel — APPROVED** [review]
Thank you!

**Pull request merged**
