### PR TITLE
avm1: Migrate more filters to `NativeObject`

### PR DESCRIPTION
**Pull request by relrelb**

### CODE REVIEW

**Comment by moulins** [comment]
I notice that with this change all the 'data' structs are `#[collect(require_static)]`.

This may best be done in a separate PR, but this enables removing the `GcCell` in favor of a plain `Cell` on every field, which is a little cleaner and a (theoretical) perf win.

**Comment by relrelb** [comment]
> I notice that with this change all the 'data' structs are `#[collect(require_static)]`.
> 
> This may best be done in a separate PR, but this enables removing the `GcCell` in favor of a plain `Cell` on every field, which is a little cleaner and a (theoretical) perf win.

Great idea! I changed the PR to use `Box<GcCell<T>>` instead, to keep the size of `NativeObject` small (basically a discriminant + one pointer). This pattern indeed seems convenient, so it's worth updating the other `NativeObject` variants to follow it as well. I prefer to do that in a separate PR though.

**Comment by relrelb** [comment]
Okay, actually `Box<RefCell<T>>` doesn't work because it makes `object.native()` return a new clone that disallows mutations. For now I switched over to `Rc<RefCell<T>>` in hope that it solves the problem, but I think we should take a more general approach - Maybe split `TObject::native()` into `TObject::native()` and `TObject::native_mut()`, which return `Ref<NativeObject<'gc>>` and `RefMut<NativeObject<'gc>>` respectively? This way the underlying `NativeObject` wouldn't be cloned each time, allowing the use of `Box<RefCell<T>>`.

**Comment by relrelb** [comment]
Switched back over to `GcCell<T>`, since `Box<RefCell<T>>` is inherently malformed, per https://github.com/ruffle-rs/ruffle/pull/10594#issuecomment-1500202105.

**Pull request merged**
