### PR TITLE
web: Avoid double polyfilling object-inside-object

### PR DESCRIPTION
**Pull request by Toad06**
Some sites like the ones in #1667 and ~#1882~ [issue no longer exists - site was: https://newheredigitaltoys.xyz] use conditional comments (only supported in IE 9 and below) to detect which embed a browser can support:

```
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%">
	<param name="movie" value="game.swf" />
	<param name="quality" value="high" />
	<param name="menu" value="true" />
	<!--[if !IE]>-->
	<object type="application/x-shockwave-flash" data="game.swf" width="100%" height="100%">
		<param name="movie" value="game.swf" />
		<param name="quality" value="high" />
		<param name="menu" value="true" />
		<!--<![endif]-->
		<a href="http://www.adobe.com/go/getflash">
			<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
		</a>
	<!--[if !IE]>-->
	</object>
	<!--<![endif]-->
</object>
```

This code results in a double-polyfilling in Ruffle. ~This PR would only polyfill the second `<object>` tag, quite similarly to what  #1695 already does with embeds inside objects.~

~To that end, I had to change the `RuffleObject.isInterdictable` method to return an HTMLElement (or null if not polyfillable) instead of a boolean. `RuffleEmbed.isInterdictable` has also been changed, just for consistency.~

Hopefully everything will be ok now and we won't have to touch all this polyfill stuff before a while. 😄

### CODE REVIEW

**Comment by Herschel** [comment]
Does Chrome end up using the deepest `object` inside the conditional in this case?

**Comment by Toad06** [comment]
I've made additional testings and it's fortunate that you asked this because... I was completely wrong.

If the `object` has the `classid` attribute and its value is neither `null` nore an empty string, then Chrome will check for the next `object`. In all other cases, Chrome will use the first `object`.

So yeah, in the example above, Chrome will use the second `object` but only because it doesn't support the classid style embed that is set on the first `object`. Well, I should have realized that sooner...

Maybe we should just remove the children `object` tags in the `fromNativeObjectElement` method instead?

**Comment by Herschel** [comment]
Yes, I guess we should remove any inner objects when replacing, similar to the embed-inside-object case.

**Review by Herschel — APPROVED** [review]

**Comment by NewhereDigitalToys** [comment]
The code was written according to how the .swf file works in the flash player via .html (Which works fine in older/new browsers)........... what you are seeing in the first picture example from: https://github.com/ruffle-rs/ruffle/issues/1882 is just the problem that happens when you load the .swf itself into the ruffle demo itself on the ruffle.rs site.

**Pull request merged**
