### PR TITLE
avm2: Always unbox primitives on the stack.

### PR DESCRIPTION
**Pull request by kmeisthax**
Because primitive types are still object values, it's necessary to coerce them into objects. This is accomplished via `PrimitiveObject`, which represents an immutable non-object value in contexts where object methods are needed. However, this means that the `Value` machinery can represent the same value by one of two ways, which necessitates kludges like `is_boxed_primitive`.

To avoid that, we're going to unbox primitives where feasible. The most obvious chokepoint is stack pushes, as this is the only way that user instructions can access values. So every call to `push` also checks for a primitive, and unboxes it at that point. This also means we don't need `is_boxed_primitive` anymore.

(For those wondering how user code would even *get* a `PrimitiveObject`, consider that those types have constructors. Currently, all methods have to accept an `Object` receiver; and all types have to return an `Object` when constructed. So `new String()` will return an object, not a string - but automatic unboxing ensures user code never sees this.)

### CODE REVIEW

**Comment by torokati44** [comment]
In the second commit, perhaps some checks could be added to explicitly disallow boxed primitives on the stack?
Or would that be overly paranoid, and just hurt performance? Sure, it can't happen now, but we can't be sure that it never will.

Otherwise, LGTM!

**Comment by adrian17** [comment]
I think ideally, long-term, we shouldn't need boxed values at all - it's just that current design dictates it, right?

**Comment by kmeisthax** [comment]
The check for boxed primitives runs at push time, because that's the only way to actually get anything on the stack at all. There's no need for further checks.

The main reason why boxed primitives even exist is for three reasons:

- Methods on classes take an `Object` receiver
- Bound methods need an `Object` receiver to bind to
- `Object.construct` has to return an `Object` and constructors cannot return a different value to override this behavior

The first problem can be solved by changing the signature of `NativeMethodImpl` to have it take a `Value<'gc>` instead of an `Option<Object<'gc>>`.

Second problem could be solved by changing `Option<Object<'gc>>` to `Option<Value<'gc>>`, and having it unwrap into `Value::Undefined`. (Or `null`, I don't remember exactly which represents a missing receiver...)

Third problem is a little thornier, because there's no way for primitive class constructors to do anything with the primitive values they get. All ES constructors (ES3, ES4, or modern) do not get to return a value. Which means that you wouldn't be able to have a `new String`, `new Boolean`, etc that actually do anything useful. I'll definitely have to do further research (especially with how it handles subclassing) to figure out a good plan for this...

**Review by adrian17 — APPROVED** [review]
LGTM, with assumption that this will be revisited in the future anyway

**Pull request merged**
