### PR TITLE
demo: Add option to reload the current SWF

### PR DESCRIPTION
**Pull request by danielhjacobs**
Reload icon created based on https://www.svgrepo.com/svg/138915/reload (which is licensed with a CC0 license, which is the same license held by the information icon added in #7534).

### CODE REVIEW

**Review by n0samu — APPROVED** [review]
Works perfectly, thank you!

**Comment by n0samu** [comment]
On second thought... reloading the SWF after a panic doesn't seem to work. Might there be a fix?

**Comment by danielhjacobs** [comment]
Well, not with the code working as it does currently. But it may work to make data a global `let` variable and have this call `load({ data: data, swfFileName: file.name, ...defaultConfig }` instead of `player.load(player.loadedConfig)` when a local fileis reloaded. Though I haven't tested that:

https://github.com/ruffle-rs/ruffle/blob/d969358a200132c1d3bacaa4c2d690640cf836df/web/packages/demo/www/index.js#L147-L148

**Comment by n0samu** [comment]
I think there are more fundamental issues preventing `player.load` calls from working after a panic, see the recent discussion in #dev-general on Discord

**Review by Herschel — APPROVED** [review]
Works great, thank you!

To gracefully deal with panic I suspect we'd have to trash and re-instantiate the entire wasm module, which might be painful but should theoretically be possible (clearing `lastLoaded` in `load-ruffle.rs`). We can always revisit that for a future PR.

**Pull request merged**
