### PR TITLE
web: Change style of context menu (close #3078)

### LINKED ISSUE #3078: Change appearance of web context menu a bit
4, maybe 5 px (or maybe 0.6em?) border radius for both the context menu and the hovered state of menu items.

Light gray instead of gray border.

Exo 2 instead of Arial.

image

image

image

Looks softer and maybe even macOS-like. 

What're your thoughts?

### PR DESCRIPTION
**Pull request by Poopooracoocoo**

### CODE REVIEW

**Comment by adrian17** [comment]
Personally I prefer a more "classic" look, but maybe that's just me; let's see others' opinion :)

**Comment by relrelb** [comment]
@Poopooracoocoo I guess you agree with @adrian17 because you reacted :+1:. So can we close this PR as well as #3078?

**Comment by Poopooracoocoo** [comment]
I didn't necessarily agree. I felt that was a totally valid view. Design is super subjective. :)

**Comment by Poopooracoocoo** [comment]
but i guess you agree so i'mma close this. i wonder where mike went :/

**Pull request closed without merging**
