### PR TITLE
Ruffle WebExtension

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR contains a minimum-viable WebExtension build of Ruffle. This allows Ruffle to be used to replace Flash on any website. I believe this extension is ready to merge and have shown it to @Herschel in the past on Discord.

## Mode of operation
This Web Extension port currently operates by replacing `<object>` and `<embed>` tags with custom elements that read the parameters or attributes for the Flash element and launch Ruffle in a shadow DOM. This provides a reasonable level of isolation and emulation of a Flash-enabled web browser.

We also replace the page's `navigator.plugins` and `navigator.mimeTypes` properties with a polyfill that includes Flash as an installed plugin. This should be significant enough to fool SWFObject, though I haven't been able to test that yet (see below).

### Alternative approaches
At one point, Firefox shipped with a WebExtension hook to enable extensions to directly define new object MIME types. This was intended to enable Shumway, and would have been perfect for Ruffle, but as far as I'm aware that particular extension hook is broken and there is no intent to fix in Firefox.

I tried defining custom elements for `<object>` and `<embed>` directly, but it is forbidden by spec to register custom elements without a hyphen in the name. A handful of native HTML elements are spec'd to support customization in this manner, but it requires they be tagged with an `is=""` attribute matching your custom element, and `<object>` and `<embed>` are excluded from the element whitelist. Furthermore, it is outright prohibited to subclass `HTMLObjectElement` and `HTMLEmbedElement`.

Another approach would have been to directly modify the prototype of `HTMLObjectElement` and `HTMLEmbedElement` to proxy Flash content to a Ruffle instance. However, there is nowhere for Ruffle's canvas to live. Neither element is allowed to host Shadow DOM (the whitelist is the same as the one mentioned above for customizing built-in HTML elements). Objects can have fallback content inserted inside them, but not embeds, which renders this approach insufficient.

### Competing implementations
@devsnek had another web extension PR (issue #35) but development on that effort seems to have stalled.

## Dynamic behavior
Current support for polyfilling dynamic Flash is limited. We currently have a `MutationObserver` to interdict dynamically-added Flash content, but that is not the only way a page can interact with Flash. The following scenarios currently are not supported, and would be grounds for a future PR if necessary:

 * Creating an object or embed tag via `document.createElement`. We would have to replace this builtin with a function that interdicts newly created objects with Ruffle equivalents.
 * Loading `ruffle_web.js` late. Currently, if Ruffle loads later than other scripts that interact with Flash, they may store a native object or embed in memory, which we cannot replace after-the-fact. As an extension, we can guarantee early execution, but websites that wanted to host Ruffle themselves would have to take care to either load Ruffle first, which may impact performance; or alter their Flash detection to load Ruffle itself.
 * It is possible to create Flash via `innerHTML`. Ostensibly, the `MutationObserver` should detect and interdict such elements as they are added, but I have not tested this, and it's plausible that the observer would run after the current event was processed.
 * Interacting with Flash by spawning it as an ActiveX component. SWFObject contains code to check in this manner, but I haven't implemented it as we already polyfill `navigator.plugins`. I want to hold off on polyfilling ActiveX until we discover a website that actually needs it.

## Website testing
I have tested this extension on three sites so far:

 * Homestar Runner contains static Flash content and correctly loads Ruffle for all Flash elements.
 * Albino Black Sheep uses a static fallback (child content in `<object>`) to a video derivative, which we override, and thus get the Flash content.
 * Newgrounds attempts to dynamically detect Flash using SWFObject but their site appears to fail to load that library and thus always serves a video derivative of the one animation I tested with (B). Hence, I was unable to test SWFObject, which should work in principle.

## Browser support
88% of users (according to caniuse) use a browser that supports the form of Web Components used in this PR. However, they also need WebExtension support, which is more restrictive. In order of market share, the following users cannot use Ruffle:

 * Chrome for Android (35% of the web) does not support WebExtensions and cannot use Ruffle. In order to ship Ruffle to Chrome users, we would either need to convince them to switch to Firefox for Android, launch our own browser on Android, or have users open a bookmarklet for each page.
 * iOS Safari (11% of the web) does not support WebExtensions and cannot use Ruffle. In order to ship Ruffle to iOS users, we would have to launch our own Safari shell, or have users open a bookmarklet for each page.
 * Internet Explorer, which somehow still has more market share than Edge, supports neither Web Extensions nor Web Components. The only way to ship Ruffle to IE users would be as an ActiveX object.
 * Edge has never shipped Web Components and requires additional polyfilling to use Ruffle. Web Components will be supported when the next version of Edge releases, because it's based on Chromium.
 * Opera Mini, which has as much market share as Opera, does not support Web Extensions or Web Components. It is unlikely that anyone using it would want Ruffle.
 * Android Browser does not support Web Extensions or Web Components. On some versions of Android, this browser could use plugins, which is how Flash was delivered to Android users. However, it is unclear if Ruffle would be worth using on such old devices.
 * A handful of browser forks which show up as unsupported on caniuse, but I know nothing about.

Some of these can be fixed by launching site-hosted or bookmarklet versions of Ruffle, which is outside the scope of this PR, but would work identically to the extension version.

### CODE REVIEW

**Comment by wizzwizz4** [comment]
Most of these aren't valid text files (no trailing newline). This is minor pedantry, but it could trip up some build processes on obscure operating systems.

**Comment by Herschel** [comment]
Unfortunately I'm still getting errors running the demo page. After `npm run serve`, I get this error immediately when the page loads:

(Chrome 76.0.3809.132 64-bit on OSX)
```
Uncaught (in promise) ReferenceError: runtime_path is not defined
    at fetch_ruffle (load-ruffle.js:20)
    at load_ruffle (load-ruffle.js:58)
    at new RufflePlayer (ruffle-player.js:26)
    at new RuffleEmbed (ruffle-embed.js:8)
    at Function.from_native_embed_element (ruffle-embed.js:43)
    at wrap_tree (element.js:30)
    at eval (element.js:43)
    at Module.../js-src/element.js (0.index.js:11)
    at __webpack_require__ (index.js:64)
    at eval (index.js:2)
:8080/test.swf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ruffle-player.js:96 SWF load failed: 404 Not Found for test.swf
```

and trying to load a Local SWF fails with:

```
index.js:57 Uncaught TypeError: Cannot read property 'play_swf' of null
    at playSwf (index.js:57)
    at FileReader.fileReader.onload (index.js:28)
```

The demo page needs to remain functional before I can merge.

I'm also wondering whether the demo page should use the Ruffle JS API vs. the embed-replacement. Part of me wants to keep the demo page straightforward, although I expect many people will use the embed-replacement method as well. Maybe we have two demo pages showing each method...?

As far as coding style for the JS scripts,  that's up to you, @kmeisthax!

Thanks again for your work on this. This is totally outside of my experience, so having someone to help out here is great! I'm excited to merge.

**Comment by kmeisthax** [comment]
I fixed the demo site.

Native element replacement is the intended use case for Ruffle so our demo site should also use it.

Manually instantiating a player onto a canvas element probably shouldn't be a supported usecase: it ties us into using a single canvas element. While the canvas element can do a lot, we still need to handle things like accessibility, which may require sticking additional elements into the DOM for certain use cases. Keeping everything inside of a shadow DOM isolates Ruffle's HTML machinery from the rest of the page.

This is outside the scope of the PR, but we could create a dedicated `<ruffle-player>` element that exposes custom APIs to new sites embedding Ruffle for themselves that specifically want to take advantage of that functionality. Right now, the demo site actually still uses this: because of subclassing, all our objects and elements expose `stream_swf_url` and `play_swf_data`, which the demo site has to actually use, since I'm pretty sure you can't slap a file upload directly into an `<object>` or `<embed>` (at least, as far as I know).

**Comment by Herschel** [comment]
Ok, seems good now!

To me, manually instantiating is the primary use case -- you're right in that it shouldn't just be into a canvas, and we should toss things a shadow DOM object (I was already polluting the DOM with dummy SVG elements!). Perhaps that DOM element is what `Ruffle.new()` should return. I only feel that magically-replacing elements with `MutationObserver` should be opt-in. I'd prefer the base API to be a simple JS API that you manually call.

(I'm not a web dev, so feel free to correct me on any of these if I'm totally off-base!)
1) Isn't `MutationObserver` heavy on performance for sites that do a lot of DOM manipulation? If so, it should definitely be opt-in.
2) Sites like NG are already using code to dynamically instantiate SWFs. It seems silly to have them instantiate an old SWF embed which we then swap out with a Ruffle instance when they can just instantiate Ruffle directly.
3) NG is preparing content metadata to flag files as working-in-emulation, and they'll dynamically choose whether to use a Ruffle instance or a classic SWF embed based on the file. So it's not just a blanket "replace everything". They'd have to dynamically add/enable the script anyway.
4) There will be extra params (beyond the classic embed params) that you can pass to Ruffle to control things, per instance. Easy with a JS API.
5) Yes, we can also use a custom element for the above, maybe that's where we go long term. (Will users prefer to do `document.createElement("ruffle-player")...` vs. `Ruffle.new()`...?)

(cc @PsychoGoldfishNG)

Thanks again for your work!

**Comment by kmeisthax** [comment]
So, taking your comments in mind, the next step would be a proper self-hosted version with the ability to configure the level of Flash emulation requested (e.g. full dynamic replacement vs. static only vs. only register `<ruffle-player>` and do nothing else), and a corresponding change to the WebExtension version to respect settings provided by the site. I'll start working on a PR for that later tonight.

`document.createElement("ruffle-player")` will instantiate your shadow DOM and everything while `Ruffle.new()` requires you to have a canvas to attach to. Or, at least, it will once I make a self-hosted version. Right now `RufflePlayer` is just a superclass that isn't instantiable on it's own.

**Pull request merged**
