### PR TITLE
avm2: Implement geom.Matrix3D.interpolate and geom.Matrix3D.interpolateTo

### PR DESCRIPTION
**Pull request by MartySVK**
progress https://github.com/ruffle-rs/ruffle/issues/10259

### CODE REVIEW

**Comment by MartySVK** [comment]
Also helps to https://github.com/ruffle-rs/ruffle/issues/10009

**Comment by evilpie** [comment]
I feel like someone mentioned before that this doesn't match Flash?

**Comment by MartySVK** [comment]
I couldn't find any mention of them.

**Comment by evilpie** [comment]
So this code:
```as3
import flash.geom.Matrix3D;

var a = new Matrix3D(Vector.<Number>([
    1, 0, 0, 97,
    0, 1, 0, 50,
    0, 0, 1, 20,
    0, 0, 0,  1
]));

var b = new Matrix3D(Vector.<Number>([
    1, 0, 0, 80,
    0, 1, 0, 20,
    0, 0, 1, 10,
    0, 0, 0,  1
]));

var mat =  Matrix3D.interpolate(a, b, 0.0)
trace("mat: " + mat.rawData);
var mat =  Matrix3D.interpolate(a, b, 0.1)
trace("mat: " + mat.rawData);
var mat =  Matrix3D.interpolate(a, b, 0.5)
trace("mat: " + mat.rawData);
var mat =  Matrix3D.interpolate(a, b, 1.0)
trace("mat: " + mat.rawData);
```

Produces the following output in Flash, that I don't quite understand: 
```
mat: 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
mat: 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
mat: 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
mat: 1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1
```

**Comment by appgurueu** [comment]
This looks like a confusion between column-major and row-major order.

`new Matrix3D` uses column-major order:

> A Vector of 16 Numbers, where each four elements is a column of a 4x4 matrix.

Hence `97, 50, 20` and `80, 20, 10` aren't translations, but rather components which are multiplied with X, Y and Z respectively and added to W.

`Matrix3D.interpolate`(`To`) interpolates translation, rotation and scale, none of which these values are, so they are ignored.

That said, the implementation in this PR looks dubious to me: It just interpolates matrix components? I fail to see how this would produce the correct behavior (note e.g. that a "slerp" is guaranteed).

I believe a proper implementation would have to decompose the matrix into translation (vector), rotation (quaternion) and scale (vector) in order to then interpolate each of those individually (note: quaternion interpolation should be a slerp), reassembling the matrix afterwards.

**Comment by emergence75** [comment]
just played with flash and modified the example a little bit

```
import flash.geom.Matrix3D;

var a = new Matrix3D(Vector.<Number>([
    1, 0, 0, 0,
    0, 1, 0, 0,
    0, 0, 1, 0,
    97, 50, 20, 1
]));

var b = new Matrix3D(Vector.<Number>([
    1, 0, 0, 0,
    0, 1, 0, 0,
    0, 0, 1, 0,
    80, 20, 10,  1
]));

trace("mata: " + a.rawData);
trace("matb: " + b.rawData);

var mat0 =  Matrix3D.interpolate(a, b, 0.0)
trace("mat0: " + mat0.rawData);

var mat1 =  Matrix3D.interpolate(a, b, 0.5)
trace("mat1: " + mat1.rawData);

var mat2 =  Matrix3D.interpolate(a, b, 1.0)
trace("mat2: " + mat2.rawData);
```

Produces the following output in Flash

```
mata: 1,0,0,0,0,1,0,0,0,0,1,0,97,50,20,1
matb: 1,0,0,0,0,1,0,0,0,0,1,0,80,20,10,1
mat0: 1,0,0,0,0,1,0,0,0,0,1,0,97,50,20,1
mat1: 1,0,0,0,0,1,0,0,0,0,1,0,88.5,35,15,1
mat2: 1,0,0,0,0,1,0,0,0,0,1,0,80,20,10,1
```

**Comment by MartySVK** [comment]
can you upload swf, please? @emergence75

**Comment by emergence75** [comment]
hmm... i've played arround a little bit and have a .fla for you...
tried to emulate the flash method, but i get different output to flash when scale is in effect...

```
import flash.geom.Matrix3D;
import flash.geom.Vector3D;
import flash.geom.Orientation3D;

function interpolate(thisMat:Matrix3D, toMat:Matrix3D, percent:Number):Matrix3D {
	
	//var method:String = 'quaternion'; // eulerAngles, axisAngle, quaternion
	var method:String = Orientation3D.QUATERNION;
	
    var decomposedA:Vector.<Vector3D> = thisMat.decompose(method);
    var decomposedB:Vector.<Vector3D> = toMat.decompose(method);
	
	// 0 = translation, 1 = rotation, 2 = scale
	
	var v0:Vector3D = decomposedA[1];
	var v1:Vector3D = decomposedB[1];
	var cosOmega:Number = v0.w * v1.w + v0.x * v1.x + v0.y * v1.y + v0.z * v1.z;
	if (cosOmega < 0) {
		v1.x = -v1.x;
		v1.y = -v1.y;
		v1.z = -v1.z;
		v1.w = -v1.w;
		cosOmega = -cosOmega;
	}
	var k0:Number, k1:Number;

	if (cosOmega > 0.9999) {
		k0 = 1 - percent;
		k1 = percent;
	} else {
		var sinOmega:Number = Math.sqrt(1 - cosOmega * cosOmega);
		var omega:Number = Math.atan2(sinOmega, cosOmega);
		var oneOverSinOmega:Number = 1 / sinOmega;
		k0 = Math.sin((1 - percent) * omega) * oneOverSinOmega;
		k1 = Math.sin(percent * omega) * oneOverSinOmega;
	}
	
	var scale_x:Number = decomposedA[2].x * (1 - percent) + decomposedB[2].x * percent;
	var scale_y:Number = decomposedA[2].y * (1 - percent) + decomposedB[2].y * percent;
	var scale_z:Number = decomposedA[2].z * (1 - percent) + decomposedB[2].z * percent;

	var tx:Number = decomposedA[0].x * (1 - percent) + decomposedB[0].x * percent;
	var ty:Number = decomposedA[0].y * (1 - percent) + decomposedB[0].y * percent;
	var tz:Number = decomposedA[0].z * (1 - percent) + decomposedB[0].z * percent;

	//trace(decomposedA[2].x, decomposedB[2].x, scale_x);

	var x:Number = v0.x * k0 + v1.x * k1;
	var y:Number = v0.y * k0 + v1.y * k1;
	var z:Number = v0.z * k0 + v1.z * k1;
	var w:Number = v0.w * k0 + v1.w * k1;
	var _q:Vector.<Number> = new Vector.<Number>(16, true);

	_q[0] = 1 - 2 * y * y - 2 * z * z;
	_q[1] = 2 * x * y + 2 * w * z;
	_q[2] = 2 * x * z - 2 * w * y;
	_q[3] = 0;
	_q[4] = 2 * x * y - 2 * w * z;
	_q[5] = 1 - 2 * x * x - 2 * z * z;
	_q[6] = 2 * y * z + 2 * w * x;
	_q[7] = 0;
	_q[8] = 2 * x * z + 2 * w * y;
	_q[9] = 2 * y * z - 2 * w * x;
	_q[10] = 1 - 2 * x * x - 2 * y * y;
	_q[11] = 0;
	_q[12] = tx;
	_q[13] = ty;
	_q[14] = tz;
	_q[15] = 1;
	//trace(_q);

	if (0) {
		var v:Vector3D = new Vector3D(v0.x * k0 + v1.x * k1, v0.y * k0 + v1.y * k1, v0.z * k0 + v1.z * k1, v0.w * k0 + v1.w * k1);

		var txyz:Vector3D = new Vector3D(tx,ty,tz);
		var m:Matrix3D = new Matrix3D();
		//m.recompose(Vector.<Vector3D>([txyz, v, new Vector3D(scale_x,scale_y,scale_z)]), method);
		m.recompose(Vector.<Vector3D>([txyz, v, new Vector3D(1,1,1)]), method); // ??? scale must be set to 1,1,1 ???
		trace('recomposed ' + m.rawData);
	}

	return new Matrix3D(_q);
}

// Beispielnutzung der Funktion
var a:Matrix3D = new Matrix3D();
a.appendTranslation(100, 50, 20);

// Skalierung
a.appendScale(2, 2, 2); // Skaliert um den Faktor in allen Achsen * dann stimmt es nicht mehr...

var angle:Number = 30; // Winkel in Grad
var rotationAxis:Vector3D = new Vector3D(0, 1, 1); // Z-Achse
a.appendRotation(angle, rotationAxis);

//a.appendScale(0.5, 0.5, 0.5); // Skaliert um den Faktor in allen Achsen * dann stimmt es nicht mehr...

var b:Matrix3D = new Matrix3D();
b.appendTranslation(30, 20, 10);
//b.appendScale(3, 3, 3);

var t:Number = 0.5;

trace('Matrix A');
trace(a.rawData);
trace('Matrix B');
trace(b.rawData);

trace('********\n');

var interpolatedMatrix:Matrix3D = Matrix3D.interpolate(a, b, t);

trace("Interpolierte Matrix Matrix3D.interpolate:");
trace(interpolatedMatrix.rawData);

trace('********');

trace("Interpolierte Matrix interpolate:");
var interpolateMy:Matrix3D = interpolate(a, b, t);
trace(interpolateMy.rawData);

```


[Matrix3D_playground.zip](https://github.com/user-attachments/files/16833753/Matrix3D_playground.zip)

**Comment by emergence75** [comment]
please take a look here
https://github.com/emergence75/ruffle/blob/master/core/src/avm2/globals/flash/geom/Matrix3D.as
public function pointAt
public function interpolateTo
public static function interpolate

includes an extended version of recompose and decompose (with skew and perspective)
and
https://github.com/emergence75/ruffle/blob/master/core/src/avm2/globals/flash/geom/Utils3D.as
public static function pointTowards

might be useful...

**Comment by evilpie** [comment]
@emergence75 I am probably not the right person to really judge what you are doing, but it certainly seems impressive! Would you mind opening a real, potentially draft, pull request so it's easier to keep track of your work?

**Comment by emergence75** [comment]
I'm not very familiar with GitHub pull requests, drafts, or the general workflow. If you could point me to an easy-to-follow guide or description on how to handle this, I'd be happy to give it a try.

Some notes on the code:

The extended decompose and recompose methods:

The decompose method now also returns skew and perspective information.
The recompose method can process these additional parameters as well.

These changes are implemented in a way that should not cause any issues with older flash code.

The interpolate methods in my code use this logic from recompose and decompose to eliminate duplicate code (such as converting quaternion to matrix).

Additionally, I’ve added an optional correct parameter, which is set to false by default. This ensures compatibility with older code.

This project is a hobby for me to better understand Matrix3D operations, and along the way, I discovered an issue in the original Flash implementation, as mentioned in this discussion:

https://github.com/airsdk/Adobe-Runtime-Support/discussions/3506

How this will be resolved is still to be seen.

Regardless, these matrix calculations should be as accurate as possible, otherwise, they become fairly useless. This might also be why many other projects build or use their own Matrix3D implementations instead of relying on the Flash version.

Regarding matrix interpolation in general: https://www.w3.org/TR/css-transforms-2/#matrix-interpolation

As for pointAt and pointTowards, they are still experimental at the moment, but the initial tests look quite promising.

The class has also undergone some variable clean-up for better readability and maintainability.

I would like to mention that I don’t work with Rust and am not familiar with your internal logic for it. My background is more in ActionScript and JavaScript, so there may be Rust-specific considerations that I haven't accounted for.

Thank you for your time and the work you've put into this codebase!

**Comment by evilpie** [comment]
I am not sure if this is a great introduction, but this shows the [git workflow](https://github.com/git-guides#getting-started-with-the-git-workflow) to opening a pull request.

You could probably even do it just using the github web UI: https://docs.github.com/en/get-started/start-your-journey/hello-world#step-2-create-a-branch.

**Comment by emergence75** [comment]
hmm... hope this is correct
https://github.com/ruffle-rs/ruffle/pull/18495

**Pull request closed without merging**
