### PR TITLE
avm2: Don't hold GcCell read ref open for Loader.loadBytes

### PR DESCRIPTION
**Pull request by Aaron1011**
We were holding this open while dispatching an event, leading to a panic if anything attempted to modify the ByteArray.

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Can you add a test?

**Comment by Aaron1011** [comment]
I updated an existing test to print out `bytearray.position` from event handlers.

**Comment by Lord-McSweeney** [comment]
Are you sure that the test panics on current master? The panic issue was a result of a mutable borrow (`readUnsignedInt` or whatever it was needs to update `position`) after the immutable borrow in the `load_bytes`, but the test only calls `bytearray::get_position`, which immutably borrows the bytearray.

**Comment by torokati44** [comment]
I had the same concerns, so I downloaded the updated test SWF, and started it in the desktop player and the web demo, got an error in both.

**Comment by Aaron1011** [comment]
Yes, I confirmed that this errors on `master`. `bytearray.position` ends up mutating bytearray in order to attach the bound method.

**Review by Lord-McSweeney — APPROVED** [review]

**Pull request merged**
