### PR TITLE
AS3 Sound

### PR DESCRIPTION
**Pull request by kmeisthax**
This implements AS3's view of audio processing, at least to the same level that we currently have implemented in AS2.

This PR is not intended to implement dynamically generated or network loaded sounds. Only library sounds will be supported as I anticipate significant refactoring work or additional AS3 class implementations to support non-movie sounds. I may amend this if I determine that other sound sources may be implementable.

- [x] `Sound` class
  - [x] Subclass association for library sounds
  - [x] `bytesTotal` property (incl `bytesLoaded` stub)
  - [x] Stub `isBuffering`, `isURLInaccessible`, and `url` properties
  - [x] `length` property
  - [x] ~~`extract` method~~ Holding off on this to avoid conflicting with other PRs, stubbed for now.
  - [x] `play` method
  - [x] Stub `close`, `load`, `loadCompressedDataFromByteArray`, and `loadPCMFromByteArray` methods
  - [x] ~~Determine if library sounds fire events (and implement them if so)~~ They do not appear to fire any events.
- [x] `SoundTransform` class
  - [x] `pan` property
  - [x] Determine proper caching & interpretation of sound transforms on display objects
  - [x] `SimpleButton.soundTransform` property
  - [x] `Sprite.soundTransform` property
- [x] `SoundChannel` class
  - [x] ~~`leftPeak`/`rightPeak` properties~~ Holding off on this to avoid conflicting with other PRs, stubbed for now.
  - [x] ~~`position` property~~ Currently not implemented correctly by any audio backends, stubbed for now.
  - [x] `soundTransform` property
  - [x] `stop` method
  - [x] `soundComplete` event
- [x] `SoundMixer` class
  - [x] `bufferTime` static property (maybe?)
  - [x] `soundTransform` static property
  - [x] `stopAll` static method
  - [x] Stub `areSoundsInaccessible` (we don't implement Flash's internal security rules and do not plan to)

### CODE REVIEW

**Comment by ousia** [comment]
@kmeisthax, since some features are also missing from AS2 (such as `Sound.position()`), I wonder whether it would make sense to merge #4273 into a larger contribution.

**Comment by kmeisthax** [comment]
I will definitely want to change some things with AS2 sound while I'm in here, because I've noticed things like AS2 `Sound.start`'s start-position parameter is almost certainly being calculated incorrectly. I'm not sure if I want to merge it with #4273 given that's still heavily in progress and most of my code should remain orthogonal to that. The only thing that will conflict are the handful of methods I added to `AudioBackend` for getting sound data size and format, but it looks like re-adding those methods in a rebase should be easy enough.

However, I'll probably cross off anything that requires adding new decoding features to `NullAudioBackend`, given that audio decoding is going to change. I will point out that working `extract` in AS3 Sound *would* make our audio decoders fully testable, but I'm going to hold off on that method until after all these other decoding PRs land.

**Comment by kmeisthax** [comment]
Update: I'm giving up on `SoundChannel.position` because all of the audio backends currently do not report the position of playing sounds. I also can't implement it in `NullAudioBackend` because it doesn't have a reference for the current test's playback timing.

**Comment by ousia** [comment]
I was about to suggest the implementation of `Sound.position()` for AS2, but it seems that it will have to wait a bit longer.

Many thanks for your contributions, @kmeisthax.

**Comment by danielhjacobs** [comment]
Might it be a better idea for the Sound.position stub to just return 0 for now? I just looked at some code on an SWF that I maintain (which was since replaced with a YouTube video but still exists):

https://dnasubway.cyverse.org/files/tour/tour-all.swf:

Opened with jpexs, it says:

      public function pauseMusic(param1:Event) : void
      {
         if(isPlaying)
         {
            pos = sc.position;
            sc.stop();
            isPlaying = false;
            stop();
         }
      }
      
      public function playMusic(param1:Event) : void
      {
         if(!isPlaying)
         {
            sc = music.play(pos);
            isPlaying = true;
            play();
         }
      }

Which means if I understand this correctly, once this and MouseEvent.CLICK are supported, the pause button will error out, position will attempt to be set to an error, and play will not work either. If position were set to 0, the movie would restart, but at least the animation would continue to function, just somewhat inaccurately.

**Review by adrian17 — APPROVED** [review]
LGTM.
(do you think this could be squashed a little bit? At least the extra "missed test" commits?)

**Pull request merged**
