### PR TITLE
Allow for dynamic properties in Object

### PR DESCRIPTION
**Pull request by Dinnerbone**
Nothing uses them yet, but we will need to change any versioned global method to use it.

Opening a PR before then in case anyone else wants to go make that change, and to avoid conflicts in Object

### CODE REVIEW

**Comment by Herschel** [comment]
Thank you! Instead of using `NativeFunction`, do you think we should have a `type Getter = fn(...) -> Value<'gc>` and `type Setter = Option<fn(..., Value<'gc>)>` for `Property::Virtual { get, set }` ?

**Comment by Dinnerbone** [comment]
I imagine it'll be `Executable<'gc>` once #63 is in. It will be either a native or user defined function, so the typedef would be `type Getter = Executable<'gc>` and `type Setter = Option<Executable<'gc>` - I'm not sure that'll be beneficial.

**Comment by Dinnerbone** [comment]
One other thing: I actually disagree with the clippy lint about preferring to using `..` for the debug method as it's deliberate that `get` is ignored, and it should error if other properties are added (they should likely be printed too).

**Comment by Herschel** [comment]
> I imagine it'll be `Executable<'gc>` once #63 is in. 
So then the question is whether to add `Exectuable::NativeGetter` etc. Not sure it's that beneficial -- my thought is it gets rid of the bounds check when accessing the args in a setter.

> One other thing: I actually disagree with the clippy lint about preferring to using `..`
Makes sense! Actually looks like [this lint might be removed altogether](https://github.com/rust-lang/rust-clippy/issues/1741). I might just allow this lint globally.

Merging, thank you!

**Pull request merged**
