### PR TITLE
Start moving away from `Box<dyn std::error::Error>`

### PR DESCRIPTION
**Pull request by Dinnerbone**
Part 1 of what's probably going to be a bunch of PRs, yay!

Notable changes:
- Removed a bunch of infallible error paths
- Use a real Error enum in audio, render video and UI backends
- Use anyhow on desktop for better & chainable errors

### CODE REVIEW

**Review by Aaron1011 — APPROVED** [review]

**Review by adrian17 — APPROVED** [review]
Can we keep the `unregister_bitmap` one? Pretty sure it's a bug that we never actually free the GPU bitmap :)

**Comment by Dinnerbone** [comment]
Unregistering should still be infallible though. If it doesn't happen, that's the backends concern - as far as the api goes it should pretend that it worked

**Comment by Aaron1011** [comment]
@adrian17 At least in wgpu, we already free the gpu texture by dropping `wgpu::Texture` in `unregister_bitmap`

**Comment by adrian17** [comment]
My bad, just noticed that on webgl side, `delete_texture` is also infallible.

**Comment by relrelb** [comment]
Personally, I like the removal of infallible error paths, but I don't see a real benefit of replacing `Box<dyn std::error::Error>` with `Error` enums. If we were to take different paths based on a particular error type, then it makes sense. But since these errors are ultimately only for logging, it feels like enums just complicate things, and neither contribute to code readability, even just making it worse by repeating the error identifier and its message. Is there some different consideration that I miss?

**Comment by Dinnerbone** [comment]
> Personally, I like the removal of infallible error paths, but I don't see a real benefit of replacing `Box<dyn std::error::Error>` with `Error` enums. If we were to take different paths based on a particular error type, then it makes sense. But since these errors are ultimately only for logging, it feels like enums just complicate things, and neither contribute to code readability, even just making it worse by repeating the error identifier and its message. Is there some different consideration that I miss?

Few primary benefits:
- Much much more informative errors (x caused by y caused by z) as opposed to just z right now
- Errors become send/sync which makes for easier refactoring with async code
- You can catch specific errors and handle them
- Marginal speed improvement as we're mostly not allocating new strings anymore
- Better code readability - you know what can go wrong in a method, vs before "anything"

**Comment by Aaron1011** [comment]
> Errors become send/sync which makes for easier refactoring with async code

I support moving to individual error enums, but note that this is possible with `Box<dyn std::error::Error + Send + Sync>`

**Comment by Dinnerbone** [comment]
> I support moving to individual error enums, but note that this is possible with `Box<dyn std::error::Error + Send + Sync>`

Sometimes, when the error you're boxing supports send & sync. Sometimes they don't, so it means sprinkling a `map_err(|e| e.to_string())` and losing some info. This approach loses info too, of course, but it's less messy and can preserve much more.

**Pull request merged**
