### PR TITLE
ci: Ignore just the Docker package files in the reproducible build

### PR DESCRIPTION
**Pull request by danielhjacobs**

### CODE REVIEW

**Comment by torokati44** [comment]
I'm almost certain that this is a good solution, but at this point, I'm afraid of actually pushing the green button before quadruple cross-checking with an independent verification board of 7 independent experts, and an omniscient entity with transcendental consciousness. 🫠

**Comment by torokati44** [comment]
Maybe the `approval_notes` in `submit_xpi.js` should also be amended to `rm` only this folder instead of `docker_builds/*`. It shouldn't matter in practice (as the `docker_builds` folder will still be there, empty), just for consistency's sake.

**Comment by torokati44** [comment]
This would've been also useful: https://github.com/moby/moby/issues/20920#issuecomment-1710778527
But oh well: https://github.com/moby/moby/pull/20927

**Comment by danielhjacobs** [comment]
Approval notes updated.

**Comment by danielhjacobs** [comment]
Since that's a comment on a closed issue, opened https://github.com/moby/moby/issues/47880 as a new issue.

**Review by Dinnerbone — APPROVED** [review]
Thanks for dealing with this!

**Comment by danielhjacobs** [comment]
Well, nothing to do but to merge and see I suppose.

**Pull request merged**
