### PR TITLE
extension: Migrate to TypeScript

### PR DESCRIPTION
**Pull request by relrelb**

### CODE REVIEW

**Comment by adrian17** [comment]
Nit: the TODOs don't really explain what to do about them, whether that's a thing to investigate, improve or just make sure it's correct.

I was also wondering about the compatibility layer in `utils.js`, for `tabs`, `runtime` etc - do you think that https://github.com/mozilla/webextension-polyfill/ could replace this custom code? Not saying in this PR in particular, but in general - that could replace like 95% of utils.js and simplify typing, right?

**Comment by relrelb** [comment]
@adrian17 Thanks for commenting! I turned these TODOs into just comments. They're supposed to explain non-trivial workarounds I had to do for TypeScript to compile (and for which I consider to file an issue to TypeScript).

[webextension-polyfill](https://github.com/mozilla/webextension-polyfill/) looks suitable. I will try to experiment with it when I have time, but that's belongs to a separate PR of course.

**Comment by adrian17** [comment]
Cool. It's just my general opinion that stuff like 

```
export let tabs: {
    reload(tabId: number): Promise<void>;
    query(
        query: chrome.tabs.QueryInfo & browser.tabs._QueryQueryInfo
    ): Promise<chrome.tabs.Tab[] | browser.tabs.Tab[]>;
    sendMessage(
        tabId: number,
        message: unknown,
        options?: chrome.tabs.MessageSendOptions &
            browser.tabs._SendMessageOptions
    ): Promise<any>; // eslint-disable-line @typescript-eslint/no-explicit-any
};
```
Shouldn't belong to "end-user" application code like Ruffle.

But aside from the opinion that ideally this code wouldn't exist, I think it looks nice :)

One extra thing:
```
"target": "es2017",
```

We're actually already using `object.fromEntries` here: https://github.com/ruffle-rs/ruffle/blob/04d80e5e4e5a3023117e0410378fc623a8bfbbf5/web/src/lib.rs#L1049 which according to this mapping: https://www.typescriptlang.org/tsconfig#lib means we might as well target ES2019, right? (Or maybe just ESNext, considering wasm and wasm-bindgen make us stick to bleeding edge anyway.)

**Comment by relrelb** [comment]
> which according to this mapping: https://www.typescriptlang.org/tsconfig#lib means we might as well target ES2019, right? (Or

We can target ES2019 (or even later as you suggested), but I'm not really sure what the benefits would be. Currently no feature of ES2019 is in use of the extension, and the target can be bumped very easily on-demand.
Also [core](https://github.com/ruffle-rs/ruffle/blob/master/web/packages/core/tsconfig.json#L6) currently targets ES6 (a.k.a. ES2016).

**Comment by Herschel** [comment]
Thank you!

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
I agree that exploring the web extensions polyfill would be a good idea.

**Pull request merged**
