### PR TITLE
renovate: Include winit, egui-winit, and raw-window-handle in the wgpu dep group

### PR DESCRIPTION
**Pull request by torokati44**
So I can finally stop being the best bot:tm: (https://github.com/ruffle-rs/ruffle/pull/13487#issuecomment-1753976182).

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Our best bot is retiring :(

**Review by Dinnerbone — APPROVED** [review]

**Comment by Benman2785** [comment]
strange problems with web-selfhosted now:

1. performance of loading of https://hoffmeister.li/flash-games/swf/Sierra-7mod.swf is SLOW/LAGGY on Chrome (gameplay is fine) BUT "normal" at FireFox
2. https://hoffmeister.li/flash-games/swf/Highway_of_the_Dead.swf wrong "gameplay graphics" in FireFox - but correct in Chrome

**Comment by Benman2785** [comment]
tested with older versions: startet at 23-10-10 - so not related to this update ;)

**Comment by torokati44** [comment]
Well it would have been _really strange_ if this change was the problem, because it didn't actually change Ruffle itself at all... 😅

**Pull request merged**
