### PR TITLE
web: Re-try getting obfuscated_event_prefix to prevent errors

### LINKED ISSUE #1311: "obfuscated_event_prefix" uninitialized variable error on some sites

### PR DESCRIPTION
**Pull request by Justin-CB**
Fix #1311

### CODE REVIEW

**Comment by Herschel** [comment]
Why exactly does this occur? Feels like a little bit of a kludge; instead of polling for when obfuscated_event_prefix exists, could the code the sets obfuscated_event_prefix instead signal the extension to make the event handler?

**Comment by Justin-CB** [comment]
Well, that would require `index.js` to export the function for `lv0.js` to call & `index.js` imports the Ruffle API ES modules, which causes an error when trying to export the function as a commonjs module, which `lv0.js` imports `util.js` as.

**Comment by Herschel** [comment]
@Toad06 Could you look into this and see if it's still an issue with your latest changes? Thank you!

**Comment by Toad06** [comment]
This doesn't seem to happen anymore, at least on the sites where I know it did happen. I suppose the `async`/`await` stuff added in lv0.js prevents the issue from happening.

**Comment by Herschel** [comment]
@Justin-CB Could you try and see if you can recreate the issue now? Thanks!

**Comment by Herschel** [comment]
Closing as it appears this issue is no longer occurring.

**Pull request closed without merging**
