### PR TITLE
wgpu: Some optimisations, some refactors, much less buffers

### PR DESCRIPTION
**Pull request by Dinnerbone**
This reduces the amount of buffers needed to run Heartcore from about 8k to 3k peak, which should improve performance and reduce memory usage. We also don't need a second command buffer per draw anymore. Filters, especially, should be cheaper to do now.

It also simplifies the codebase a lot since we no longer have to juggle lifetimes with our old staging belt system, and we also don't specialcase push constants since the performance should be comparable now. This opens up future improvements, especially to BMD draws (and making BMD operations on gpu viable, to avoid readbacks)

### CODE REVIEW

**Comment by SN902** [comment]
[pony-creator-v3-generalzoi.zip](https://github.com/ruffle-rs/ruffle/files/14031204/pony-creator-v3-generalzoi.zip)

`thread 'main' panicked at render\wgpu\src\mesh.rs:413:10:
Mesh uniform buffer was too large!: BufferFull`

**Comment by Dinnerbone** [comment]
@SN902 web or desktop? Do they look normal to you before this PR, no rendering artifacts or crashes??

**Comment by SN902** [comment]
> @SN902 web or desktop? Do they look normal to you before this PR, no rendering artifacts or crashes?

I tested your PR on the desktop build, these games works fine on the latest nightly 2024-01-24

**Comment by Dinnerbone** [comment]
Try now. I think I misunderstood the max_uniform_buffer_binding_size limit.

**Comment by SN902** [comment]
> Try now. I think I misunderstood the max_uniform_buffer_binding_size limit.

Fixed, now works perfectly.

**Comment by Lord-McSweeney** [comment]
This doesn't fix #9229 for me

**Review by Aaron1011 — APPROVED** [review]

**Pull request merged**
