### PR TITLE
core/avm1: don't run onLoadInit handler if movie loading failed

### LINKED ISSUE #2123: [AVM1] MovieClipLoader bug when loading non-existant SWF
Tested on commit `9e46757f` of Ruffle.

When using a `MovieClipLoader` to load a SWF which doesn't exist, both `onLoadInit` and `onLoadError` are called on Ruffle:
ruffle

With the Flash Player, only `onLoadError` is called, as expected. (note the different error message)
flash

Here's the relevant .swf, together with its Haxe sources (compiled with Haxe v3.1.3 for AVM1 support).
[loading-missing-swf.zip](https://github.com/ruffle-rs/ruffle/files/5745417/loading-missing-swf.zip)

### PR DESCRIPTION
**Pull request by moulins**
Replace Loader::Movie::loader_complete flag by an enum to distinguish between success and failure.

Fixes #2123.

There's no tests for now, because I don't know how to edit .fla files without a copy of Adobe Flash :(

### CODE REVIEW

**Comment by Herschel** [comment]
Thank you and welcome! I believe this should fire `onLoadError` as well -- any chance you'd want to take a crack at that?

**Comment by Herschel** [comment]
Whoops, looks like we already support `onLoadError`! Looks good to me, if you'd like to add a small tests loading a bogus SWF using swftools or MTASC, or I could make one for you.

**Comment by moulins** [comment]
I've added the `loadmovie_fail` regression test, made with MTASC.

**Comment by Herschel** [comment]
Thanks!

**Pull request merged**
