### PR TITLE
chore(deps): update node.js dependencies

### PR DESCRIPTION
**Pull request by torokati44**
Same as https://github.com/ruffle-rs/ruffle/pull/15365, but excluding the `chai` and `chai-html` bumps.

### CODE REVIEW

**Comment by Oldarg** [comment]
How do I update it? I am not a programmer or even a coder. A link to GitHub won't help me, especially if I'm using android. Is there at least an updated .apk file that I can run and install the updated version?10:02, 4 марта 2024 г., "TÖRÖK Attila" ***@***.***>:Same as #15365, but excluding the chai and chai-html bumps.



You can view, comment on, or merge this pull request online at:
  https://github.com/ruffle-rs/ruffle/pull/15417

Commit Summary

  052a086  chore(deps): update node.js dependencies


File Changes  (5 files)

  
    M
    web/package-lock.json
    (982)
  
  
    M
    web/package.json
    (6)
  
  
    M
    web/packages/demo/package.json
    (4)
  
  
    M
    web/packages/extension/package.json
    (2)
  
  
    M
    web/packages/selfhosted/package.json
    (2)
  


Patch Links:

  https://github.com/ruffle-rs/ruffle/pull/15417.patch
  https://github.com/ruffle-rs/ruffle/pull/15417.diff


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by torokati44** [comment]
I quite understand why you replied _here_, of all places, but either way - for use in desktop/web/browser, of course, you can get a new build every day from the home page, https://ruffle.rs.
For Android, the updates  are entirely on an ad-hoc schedule, and there haven't been any new builds in the recent past.
I'll try to push one out soon-ish though.

**Comment by Oldarg** [comment]
I replied in an email, and the reply came to GitHub. But that's not the point, the point is that I can't exchange one type of tokens for others. Why do I have to sit here with you in GitHub and learn about development and how to run .json files on my computer to update one application to exchange tokens? I don't need to do that at all. My job as a user is to download the application, click one button, confirm the transaction for exchange and get other tokens, not to sit on GitHub and  study comments and look for how to update the fucking application to exchange tokens. Can you understand that? I've already installed Nomo app on two devices, downloaded the program to my computer and neither of them are exchanging ERC 20 to Zen 20. Do I have to learn app development and running .json files for the sake of it, or what?10:02, 4 марта 2024 г., "TÖRÖK Attila" ***@***.***>:Same as #15365, but excluding the chai and chai-html bumps.



You can view, comment on, or merge this pull request online at:
  https://github.com/ruffle-rs/ruffle/pull/15417

Commit Summary

  052a086  chore(deps): update node.js dependencies


File Changes  (5 files)

  
    M
    web/package-lock.json
    (982)
  
  
    M
    web/package.json
    (6)
  
  
    M
    web/packages/demo/package.json
    (4)
  
  
    M
    web/packages/extension/package.json
    (2)
  
  
    M
    web/packages/selfhosted/package.json
    (2)
  


Patch Links:

  https://github.com/ruffle-rs/ruffle/pull/15417.patch
  https://github.com/ruffle-rs/ruffle/pull/15417.diff


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by Oldarg** [comment]
here, i'm approving transaction
 
Sign transaction    X
The WebOn wants to sign the following
transaction:
0xf86980850eec8f8db882ea6094flca9cb74685755965c74585
28a36934df52a3ef80b844a9059cbb000000000000000000
 
And nothing happens.

**Pull request merged**
