### PR TITLE
core: Fix wrong frame rate  issue #3020 #3663

### PR DESCRIPTION
**Pull request by haraldbre**
Fixes the wrong frame rate when an other swf is referenced via GetUrl2 (issue #3020) or GetUrl (#3663).
This is done via an optional frame_rate in the players UpdateContext. The optional frame_rate is set by the loader if the depth parameter of the loaded movie is less then AVM_DEPTH_BIAS / 2. AVM_DEPTH_BIAS is the bias for the depth of a new empty movie clip, allowing for a negative depth of movies loaded into a new clip to be down to -AVM_DEPTH_BIAS / 2 to ignore the frame rate in the swf header.

### CODE REVIEW

**Comment by adrian17** [comment]
This feels kinda hacky? I may be wrong though.
Doesn't the new logic mean we will call `set_frame_rate` on every `Player::update()`, after `GcRootData::frame_rate` gets set?

I also don't really understand where `AVM_DEPTH_BIAS / 2` came from.

**Comment by haraldbre** [comment]
Re hack: Yes, this still might be some hack. I haven't found  a reference to when the frame rate must be adjusted on GetUrl/GetUrl2.
Re set_frame_rate: The new logic  will call set_frame_rate on every Player::update(), only if in the UpdateContext a frame_rate is specified. This will normally not be the case.
Re AVM_DEPTH_BIAS/2: In the as2loader example, loadee.swf is referenced via
>>
[00c]        71 DOACTION
                 (   37 bytes) action: Constantpool(3 entries) String:"mc" String:"createEmptyMovieClip" String:"loadee.swf"
                 (   14 bytes) action: Push int:1 Lookup:0 ("mc") int:2 Lookup:1 ("createEmptyMovieClip")
                 (    0 bytes) action: CallFunction
                 (    0 bytes) action: Pop
                 (    4 bytes) action: Push Lookup:2 ("loadee.swf") Lookup:0 ("mc")
                 (    1 bytes) action: GetUrl2 65
                 (    0 bytes) action: End
<<
The ruffle implementation of createEmptyMovieClip  adds an offset of AVM_DEPTH_BIAS to the depth of the clip to avoid a negative depth. This offset is handed on to the new movie. So the fix is using a depth less than AVM_DEPTH_BIAS/2 to discern between movies running in the main clip and movies running in there own clip.
Works for issues #3020 #3663 and also for the example in as2loader.

**Comment by adrian17** [comment]
> The new logic will call set_frame_rate on every Player::update(), only if in the UpdateContext a frame_rate is specified. This will normally not be the case.

Context's frame_rate is a reference to GcRootData::frame_rate. Once it gets set to Some(...), it'll never be unset, so `set_frame_rate` will be called every time, right?

> So the fix is using a depth less than AVM_DEPTH_BIAS/2 to discern between movies running in the main clip and movies running in there own clip.

Okay, but I'm still not seeing where the "/2" part came from, as opposed to - say "/3" or "/1". At a glance I didn't see any ratios like this in the current codebase.

**Comment by haraldbre** [comment]
Re set_frame_rate: Yep, though calling set_frame_rate only sets two variables (frame_rate in player and frame_rate in  audio) and hence is no great overhead unnecessary calls  should be avoided. Is there a way to unset GcRootData::frame_rate?
Re AVM_DEPTH_BIAS: Since AVM_DEPTH_BIAS is added to the empty movie clip depth to avoid negative depth I assume an empty movie clip can have a depth less than AVM_DEPTH_BIAS. So testing for AVM_DEPTH_BIAS/2 seems a good compromise to divide depth between root clips and new clips.

**Comment by adrian17** [comment]
> Yep, though calling set_frame_rate only sets two variables (frame_rate in player and frame_rate in audio) and hence is no great overhead unnecessary calls should be avoided. Is there a way to unset GcRootData::frame_rate?

Even then, I imagine it'd make sense for it to only be called once. About overhead, actually log::info() on web might actually be the bigger issue ;) 
Would it be possible to - instead of indirectly propagating the frame_rate value through several layers - directly call `set_frame_rate` via `context.player`? If not, maybe only call it if the framerate changed?

> Re AVM_DEPTH_BIAS: Since AVM_DEPTH_BIAS is added to the empty movie clip depth to avoid negative depth I assume an empty movie clip can have a depth less than AVM_DEPTH_BIAS. So testing for AVM_DEPTH_BIAS/2 seems a good compromise to divide depth between root clips and new clips.

I'm not 100% convinced here, but also not knowledgeable enough to tell either way :( So I'll leave this to others.

**Comment by haraldbre** [comment]
Following your suggestion set_frame_rate is called on update only if the frame rate has changed

**Comment by Herschel** [comment]
Unfortunately this is fix is not correct, please see my comments here:
https://github.com/ruffle-rs/ruffle/pull/3485#issuecomment-806190758

The movie frame rate is not changed by loading a movie itself. The frame rate is being affected by the "stream" sound (SoundStreamBlock) in the loaded movie, which tells the Flash Player to sync the animation to the playing audio.

The frame rate of the SWF itself does not change in this case, because if the stream sound stop, the normal frame rate resumes. (You can also verify this doesn't change by tracing `Stage.frameRate` in AS3). Instead it's the syncing behavior of the SoundStreamBlock that is causing the player to slow down or speed up. Also see #3958.

Some examples:
[as2loader_audio.zip](https://github.com/ruffle-rs/ruffle/files/6330095/as2loader_audio.zip)
`test.swf` (4fps) loads `loadee.swf` (24fps). The movie still plays back at 4fps. This runs at the incorrect framerate with these changes.

`test2.swf` (4fps) loads `loadee2.swf` (24fps with a stream sound playing). The "stream" sound create "SoundStreamBlock" tags in the SWF, and these tags trigger the syncing behavior, causing the player to display at a different framerate. Notice that when the sound stops playing, the player resumes the normal framerate. This runs incorrectly on the current Ruffle master.

**Comment by haraldbre** [comment]
As has been pointed out (#3485 (comment)) not the depth controls the frame rate, but rather the sound being played. So while this fix will work with some swf, it won't work for others. In issues #3020 #3663 the root swf contains only the controls for a movie while the movie itself is loaded via GetUrl(2). Since the frame rate of the root is of no great importance in these examples, the fix works.

**Pull request closed without merging**
