### PR TITLE
web: Simplify a source string

### PR DESCRIPTION
**Pull request by Toad06**
Some users are confused about what a "sol" is (see https://discord.com/channels/610531541889581066/1099002553661919232/1105851375126069260).

### CODE REVIEW

**Comment by n0samu** [comment]
Can we say "save files" ?

**Comment by iwannabethedev** [comment]
I did not know what SOL meant either, but, if it was renamed to: `Backup all saves (download all .sol Flash cookie files)`, it would be clearer to me.

For reasons I do not know, when I searched for "sol flash wikipedia", the Wikipedia page did not mention "SOL" in the text, only "LSO", despite several of the tools linked on that Wikipedia page using "SOL".

**Comment by iwannabethedev** [comment]
But I think `Download all save files` is fine as well.

Maybe `Download all save files (.sol files)` ?

**Review by n0samu — APPROVED** [review]
Looks good, I don't think any further change is needed

**Review by danielhjacobs — APPROVED** [review]

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
