### PR TITLE
core: Switch from libflate to flate2

### LINKED ISSUE #1248: LoZ: Forgotten Battle: Unkown Panic on menu screen
LoZ: Forgotten Battle was previously noted for the Play button not working. In the latest Ruffle build, it gets an Unknown panic error when the menu screen appears.

https://www.newgrounds.com/portal/view/296880/format/flash?emulate=flash

# Error Info
Error name: Error
Error message: Unknown panic
Error stack:
```
Error: Unknown panic
    at Object.Y (https://www.newgrounds.com/js/ruffle/lib/core.ruffle.4ed2bf53bae7fdd931e6.js:1:31344)
    at __wbg_new_df6e6ab7a65c4c4d (<anonymous>:1:808)
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[1409]:0x22f6bd
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[1315]:0x221253
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3452]:0x2c0d23
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[2724]:0x2a6576
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3623]:0x2c3d00
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3748]:0x2c57ea
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[3554]:0x2c2a92
    at https://www.newgrounds.com/js/ruffle/lib/0a18b3847e4a6bbdeb64.module.wasm:wasm-function[700]:0x19373f
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.newgrounds.com/portal/view/296880/format/flash?emulate=flash

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63
OS: Win32

# Ruffle Info
Ruffle version: 0.1.0
Ruffle source: undefined

### PR DESCRIPTION
**Pull request by Herschel**
Switch from libflate to flate2 for zlib decompression.

We switched to libflate back in https://github.com/ruffle-rs/ruffle/commit/ee534374c9891c51744d983fea16111be0ee8dbe for ease of compiling on WebAssembly. Since then, flate2 has added a pure Rust backend via miniz_oxide, so this isn't an issue anymore. libflate also seems to be slower and fails in some cases (#1248) that flate2 doesn't.

Fixes #1248 (was missing frames in horse animation on title screen as the image failed to decompress).

### CODE REVIEW

**Comment by Herschel** [comment]
@Dinnerbone if you get a spare few moments, could you run this through scanner and see if this regresses/fixes other files?

**Comment by Dinnerbone** [comment]
Scanning a before and after now. Results should be available tomorrow.

**Comment by Dinnerbone** [comment]
Full SWF decompression had no change. Possibly ran faster (94,136 files took 1:43:4 for libflate, 1:36:24 for flate2) but it's close enough that it could just be a fluctuation.

For JPEG3 with alphas, there are 64 images that now successfully load in flate2 which errored in flate2. No regressions. There are still 11,944 images that Ruffle still can't parse for whichever reason.

For DefineBitsLossless images, there were too many images to actually count (oops, lack of foresight here. It's in the millions haha). I didn't see any regressions and some seem to be fixed. All images took 02:10:44 to parse in libflate, vs 01:55:36 in flate2.

**Comment by Herschel** [comment]
Thanks!

**Pull request merged**
