### PR TITLE
Use eslint

### LINKED ISSUE #570: Linting/formatting for JS code
Since the project has a non-negligible amount of JS code, it might be useful to enforce linting and formatting for the JS files and add this to the automated CI builds.

I'm not a web developer, so I'm not sure what the standard tools are here -- I guess ESLint (https://eslint.org/)?

### PR DESCRIPTION
**Pull request by Dinnerbone**
Most rules have been left as recommended. Let's discuss if we should change them.

Go commit by commit to make sure I haven't broken anything. There are a couple of bugs that were caught by eslint that I've fixed - maybe @kmeisthax should take a look at those to double check.

If we don't want to pull this in, I'll move the bug fixes into their own PR.

This closes #570.

### CODE REVIEW

**Comment by Justin-CB** [comment]
Is the prettier configurable? There are a couple things that I would rather be different. Particularly, I prefer having `}` on its own line & `{` after function declarations.

**Comment by Herschel** [comment]
Thanks, this is a big help.

Since both the Rust recommended style and the eslint/prettier default style is brackets-on-same-line, I don't see a compelling reason to shift away from that. (Upon a quick look, it seems like prettier doesn't have an option to change brackets-on-same-line vs. next-line regardless and this setting would have to be set via eslint).

The only formatting option I feel is important to decide is naming conventions, because this affects user-facing API, i.e. whether to use `camelCase` or `snake_case` for JS methods/properties.

**Comment by Justin-CB** [comment]
I personally prefer `snake_case`, but JavaScript seems to use `CamelCase` a lot more.

**Comment by Justin-CB** [comment]
Maybe `CamelCase` for user-facing API's & `snake_case` for internal stuff?

**Comment by Dinnerbone** [comment]
eslint only supports enforcing camelCase out of the box, and from my experience camelCase is more-preferred-than-not in the world of Javascript. We should be consistent within the same language so I wouldn't want to see half of the js be snake_case and half be camelCase, but we should also be consistent with our users expectations.

My vote is camelCase for javascript.

**Comment by Herschel** [comment]
I'm leaning toward camelCase for all JS as well.

Only have to be careful of the JS<->Rust boundary; I guess the transition point will be on the Rust side either using `#[wasm_bindgen(js_name = CamelCase)]` or `#[allow(non_snake_case)]`.

**Comment by Dinnerbone** [comment]
As there's a few other JS PRs pending, and a lot of the JS codebase isn't camelCase right now, my recommendation is to wait on that specific change as it'll hurt. We can open an issue for it.

**Comment by Justin-CB** [comment]
#576 is going to have to be rebased either way if it's merged after this. In fact, I might end up redoing the changes manually.

**Comment by Justin-CB** [comment]
Actually, the rebase wasn't as bad as I was worried that it would be. I now have a branch rebased against this, so I can rebase #576 as soon as this is merged.

**Comment by Dinnerbone** [comment]
Style changes (especially automatable ones like this) should be easy to do after other things land, too. I don't mind redoing this PR if things land. It's just that renames, at least in weakly typed languages, are a "substantial" change and need to be manually verified. Since we have zero tests in the javascript projects, I really wouldn't want to do those right now - especially juggling other PRs.

**Pull request merged**
