### PR TITLE
avm2: Implement missing enums

### PR DESCRIPTION
**Pull request by golfinq**
This PR would add 48 classes partially generated by [this tool I made](https://github.com/golfinq/ActionScript_Event_Builder) across the flash packages which are enums - as identified by @huwdp in [this issue](https://github.com/golfinq/ActionScript_Event_Builder/issues/1#issue-1360831816).

### CODE REVIEW

**Comment by huwdp** [comment]
Apologies if I'm wrong. Do we need to add them to globals.as here (https://github.com/ruffle-rs/ruffle/blob/master/core/src/avm2/globals/globals.as) for them to be added on runtime?

**Comment by Aaron1011** [comment]
@huwdp You're correct

**Comment by golfinq** [comment]
Thanks for the reminder! It's been added

**Comment by huwdp** [comment]
@golfinq  CurrencyParseResult and I believe another similar class has sneaked into the commit. Best to have these in a future PR :)

**Comment by golfinq** [comment]
> @golfinq CurrencyParseResult and I believe another similar class has sneaked into the commit. Best to have these in a future PR :)
> 
> One of the files has empty quotes so may be good to remove them

Thanks for the heads up, it's now fixed

**Review by EmperorBale — APPROVED** [review]
LGTM. That tool is definitely saving us a lot of time

**Pull request merged**
