### PR TITLE
core: Implement TextField control characters

### PR DESCRIPTION
**Pull request by JMcKiern**
This pr implements some control character handling for text fields (eg CtrlC, CtrlV).

I'm submitting this as a draft to make sure that I'm going about this the right way.

## TODO

- [ ] - <kbd>Up</kbd>, <kbd>Down</kbd> - Should move caret between lines
- [ ] - <kbd>Home</kbd>, <kbd>End</kbd> - Should go to the start/end of the line
- [ ] - <kbd>Ctrl+Left</kbd>, <kbd>Ctrl+Right</kbd> - Should go to the start/end of the previous/next word

### CODE REVIEW

**Comment by Herschel** [comment]
I was thinking maybe we should add a separate enum to handle keyboard control/navigation commands, i.e. something like PlayerEvent::TextControl that would have MoveLeft, SelectAll, Copy, PageUp, etc., and this could be handled by a separate handler on the textfield. This way these commands are explicit, as opposed to being dumped into the ASCII control characters (e.g. on Mac, where Cmd+C is different from Ctrl+C, Ctrl+Ins for copy on Windows).

**Comment by JMcKiern** [comment]
Hey, sorry for the wait. I've added the `TextControl` event, a `TextControlCode` enum and implemented SelectAll, Copy, Paste and Cut.

I couldn't figure out how to check if Ruffle is running on MacOS on web so I've just left this as a TODO.

Also, should I move the following to this `TextControl` implementation?
- <kbd>Backspace</kbd> and <kbd>Delete</kbd> - currently handled in `text_input()`
- <kbd>Left</kbd> and <kbd>Right</kbd> - currently handled in `handle_clip_event()`

**Comment by Herschel** [comment]
Yes, I'd say lets try to get all of the navigation and control commands into one code path. 
For Copy/Paste on Web, I wonder if it should hook into https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event instead of explicitly looking for keys.

**Comment by JMcKiern** [comment]
I've moved <kbd>Delete</kbd> and <kbd>Backspace</kbd> to `text_control_input()` but I just want to note here that I need to look into the onKeyDown and similar listeners. For example, it fires for <kbd>Backspace</kbd> but not for <kbd>Ctrl+C</kbd>.

For those copy events, it looks like we'd need to enable the unstable apis in `web_sys`: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.ClipboardEvent.html

**Comment by Herschel** [comment]
I think enabling the unstable APIs is fine (we are somewhat on the bleeding edge of things, so we can deal with APIs breaking from time to time).

**Comment by Txori** [comment]
Hello, you forgot to add <kbd>Page Up</kbd> and <kbd>Page Down</kbd> to the TODO list :)

**Comment by allancoding** [comment]
Is there any update on progress?

**Comment by n0samu** [comment]
I updated and finished this PR in #11059. Thanks so much for your work on this!

**Pull request closed without merging**
