### PR TITLE
avm1: reference displayObjects parents if parent is a button

### LINKED ISSUE #2181: Prizma Puzzle Challenges always shows score of 99999
SWF URL: http://i.notdoppler.com/files/prizmapuzzlechallenges.swf

The level select screen always shows a score of 99999 for each level, regardless of whether the level has been played or not.
Below is an image showing the incorrect behavior.
image

To see this behavior, load the game and click "Start Game," then mouse over Level 1.

### PR DESCRIPTION
**Pull request by michiel2005**
avm1: reference displayObjects parents if parent is a avm1button. 
Fixes #2181, #4088, #5579, #7979 And possibly more.

This felt as a too easy fix.

### CODE REVIEW

**Comment by danielhjacobs** [comment]
Does this fix #5579, which Toad06 thought might be the same issue?

**Comment by michiel2005** [comment]
Indeed it does, thanks :)

**Comment by waspennator** [comment]
Seems to fix the scores showing up as "9999999" when hovering over levels in the level select.

**Comment by torokati44** [comment]
There's a collection of possibly related issues here: https://github.com/ruffle-rs/ruffle/issues/11317

**Comment by Lord-McSweeney** [comment]
Related, but not the exact same issue: #1029
I wonder if this behavior is SWF-version gated, but the relevant issues include SWFv6, v7, and v9 (though noticeably not v4 and v5, which #1029 states as having different behavior because Button doesn't exist in those SWF versions).

**Comment by Dinnerbone** [comment]
Does this specifically only apply to text variables, or are all our paths wrong when it comes to buttons?

**Comment by michiel2005** [comment]
No problem, did that before :)

**Review by Dinnerbone — APPROVED** [review]

**Comment by Dinnerbone** [comment]
Thank you!

**Pull request merged**
