### PR TITLE
ci: Refactor nightly release script

### PR DESCRIPTION
**Pull request by Herschel**
* Specify `--package ruffle_desktop` on the desktop builds to avoid extraneous compiling
 * Move the web build into its own job so it can run parallel with the desktop jobs.
 * Make a build for Apple Silicon Macs, and generate universal binaries
   * Build matrix includes both `x86_64-apple-darwin` and `aarch64-apple-darwin` targets.
   * A following job takes both binaries and [lipo](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary)s them into a universal binary (needs testing)
 * Make a 32-bit Windows build (`i686-pc-windows-msvc` target)

Questions/TODO:
 * ~I don't have an M1 Mac, so need someone to verify the binary actually works~ (a friend verified that M1 works, thanks!)
 * Do we want a 32-bit Windows build? There has been at least one or two issues about it. (#1850)
 * Windows build naming: Currently using `win_x86` and `win_x64`, but open to other choices (win32/win64, i686/x86_64, ...)
 * Web build naming: Maybe we should go with `web_extension`, `web_selfhosted`, `web_firefox` to be more clear?
 * Need to update the release table code in the ruffle.github.io repo if builds are added/renamed

Sample workflow run/releases:
https://github.com/Herschel/ruffle/actions/runs/781871081
https://github.com/Herschel/ruffle/releases/tag/nightly-2021-04-25

### CODE REVIEW

**Comment by danielhjacobs** [comment]
https://github.com/ruffle-rs/ruffle-rs.github.io/pull/44

**Comment by relrelb** [comment]
+1 for `win_x86` and `win_x64`.
How about renaming `linux` to `linux_x64` and `mac_x86_64` to `mac_x64` for consistency?
Note that renaming `linux` would require to update [`PKGBUILD`](https://github.com/ruffle-rs/ruffle/blob/master/PKGBUILD).

**Comment by danielhjacobs** [comment]
https://github.com/ruffle-rs/ruffle-rs.github.io/pull/44/

**Comment by Herschel** [comment]
> How about renaming `linux` to `linux_x64` and `mac_x86_64` to `mac_x64` for consistency?

Mac is a weird one because its a universal binary for both x86_64 and aarch64, but "x64" would make me think it's only for "x86_64".

**Comment by Herschel** [comment]
After thinking for a while, I like this:

 * `ruffle-nightly-$DATE-$PLATFORM-$ARCH` for desktop builds
   * `$PLATFORM` (matches Rust `target_os`)
     * `macos`
     * `windows`
     * `linux`
   * `$ARCH` (mostly matches Rust `target_arch`)
     * `aarch64`
     * `x86_32` (instead of `i686` or `x86`)
     * `x86_64`
     * `universal` (macos universal builds)
 * `ruffle-nightly-$DATE-web-$COMPONENT` for web packages
   * `$COMPONENT`
     * `extension`
     * `extension-firefox`
     * `selfhosted`

Going with the Rust target architecture for consistency, with the exception of `x86_32` instead of `i686`/`x86`. Mainly, I like the symmetry of `x86_32` better.  Secondly, `i686` is a bit of a misnomer; Rust uses `i686` to mean generic 32-bit x86, but other projects use it more strictly for Pentium Pro class x86 (no SSE2, etc.). So using `x86_32` is clearer (matches the linux kernel's current naming conventions).

Of course, the ruffle.rs site has human-readable labels for these, so the filenames aren't so important in the end.

**Pull request merged**
