### PR TITLE
Always build LZMA support and remove the feature flag

### PR DESCRIPTION
**Pull request by evilpie**
From what I've heard LZMA support was not enabled by default because it used to require building C/C++ code.

### CODE REVIEW

**Comment by evilpie** [comment]
https://crates.io/crates/swf also has an optional dependency on LZMA, I wasn't sure if we wanted to change that as well.

**Comment by torokati44** [comment]
If there's no actual reason against having the feature flag, and the project builds and runs with it disabled, I see no point in removing it. It's just additional flexibility in case someone might want a smaller build. But I'm not really attached to it either.

**Comment by evilpie** [comment]
All feature flags introduce complexity and LZMA is not an optional part of Actionscript. Personally I just keep forgetting to enable this flag.

**Comment by torokati44** [comment]
Ah, I thought this was only for SWC (compressed SWF) support. (Is that not even LZMA?! 😵‍💫) Pardon my ignorance, never mind then.

**Comment by n0samu** [comment]
SWC (CWS in the file header) is zlib compression. The rare LZMA-compressed SWFs are SWZ (ZWS in the header). But I still don't think this really needs a feature flag. Who wants Ruffle to not be able to open a few random SWFs?

**Comment by evilpie** [comment]
@Dinnerbone also seems to like having it optional. How about adding LZMA to the default feature for ruffle_desktop at least?

**Pull request closed without merging**
