### PR TITLE
web: Refactor SWF file type and MIME type detection

### PR DESCRIPTION
**Pull request by n0samu**
- Move MIME type detection to an exported function `isSwfMimeType` in ruffle-player.ts, like the existing `isSwfFilename` function.
- Make the extension's file type and MIME type detection more thorough by using those same exported functions.
- Correct the IANA Flash MIME type: we had `application/vnd.adobe.flash-movie`, but [IANA specifies](https://www.iana.org/assignments/media-types/application/vnd.adobe.flash.movie) that it is `application/vnd.adobe.flash.movie` (with a dot, not a dash!)

With these changes, the extension automatically opens these Flash files in its internal player page:
- https://www.browsergames.fm/flashgames/canyon-defense.swf (the server sends the `application/vnd.adobe.flash.movie` MIME type)
- http://web.archive.org/web/20020327110830id_/http://www.cloudberryjam.se/spl/forstasidan1.spl (FutureSplash file, the server sends the `application/futuresplash` MIME type)

### CODE REVIEW

**Comment by Herschel** [comment]
LGTM! Are there any cases of `application/vnd.adobe.flash-movie` in the wild, or is this simply a mistake? Looks like this was added way back in #474 but I don't see a mention of any actual instances of it.

**Comment by n0samu** [comment]
I think it was a mistake due to the Archive Team file formats wiki listing `application/vnd.adobe.flash-movie`, and their mistake propagating to other places: http://fileformats.archiveteam.org/index.php?title=SWF&oldid=26128
(I fixed it there as well!)
Searching online, the only place I can find `application/vnd.adobe.flash-movie` actually in use is here: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_object_type
It works in a Flash-enabled browser, but only because the Flash plugin seems to play any embedded `.swf` without even checking the MIME type.

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
> It works in a Flash-enabled browser, but only because the Flash plugin seems to play any embedded `.swf` without even checking the MIME type. (Or maybe it's checking the MIME type from the header sent by the server? Not sure)

Hmm, I wonder if we should do the same? It's difficult because it also probably varied based on browser/time, for example, I wonder if it was the same with `<object>` in IE.

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
