### PR TITLE
build(deps): bump the cargo-minor group across 1 directory with 2 updates (`rfd` and `ashpd`)

### PR DESCRIPTION
**Pull request by torokati44**
Manually extracted from https://github.com/ruffle-rs/ruffle/pull/18617 (which got superseded by https://github.com/ruffle-rs/ruffle/pull/18644, and later https://github.com/ruffle-rs/ruffle/pull/18647), because these needed a little extra attention.

Let's do a `@dependabot unignore rfd` and `@dependabot unignore ashpd` after this. Referencing https://github.com/dependabot/dependabot-core/issues/10286 again.

----

Bumps the cargo-minor group with 2 updates in the / directory:

| Package | From | To |
| --- | --- | --- |
| [rfd](https://github.com/PolyMeilex/rfd) | `0.15.0` | `0.15.1` |
| [ashpd](https://github.com/bilelmoussaoui/ashpd) | `0.9.2` | `0.10.2` |

Updates `rfd` from 0.15.0 to 0.15.1
- [Release notes](https://github.com/PolyMeilex/rfd/releases)
- [Changelog](https://github.com/PolyMeilex/rfd/blob/master/CHANGELOG.md)
- [Commits](https://github.com/PolyMeilex/rfd/compare/0.15.0...0.15.1)

Updates `ashpd` from 0.9.2 to 0.10.2
- [Release notes](https://github.com/bilelmoussaoui/ashpd/releases)
- [Commits](https://github.com/bilelmoussaoui/ashpd/compare/0.9.2...0.10.2)

### CODE REVIEW

**Comment by torokati44** [comment]
Also see: https://github.com/ruffle-rs/ruffle/pull/18617#pullrequestreview-2440367952

**Comment by torokati44** [comment]
Re: @adrian17 (https://github.com/ruffle-rs/ruffle/pull/18617#discussion_r1849086376):

We have used `async-std` until now. However, see https://github.com/PolyMeilex/rfd/pull/161.
By switching it to `tokio` instead, which we depend on anyway, we can drop the entire `async-*` suite!

**Comment by torokati44** [comment]
I tried to check whether everything still works in Flatpak (and with GameMode), but I had no luck building the former [^1], and don't use the latter ... so, hlep, @kjarosh? O.O

[^1]:
	```
	error: failed to select a version for the requirement `clap = "^4.5.20"` (locked to 4.5.20)
	candidate versions found which didn't match: 4.5.21
	location searched: directory source `/run/build/ruffle/cargo/vendor` (which is replacing registry `crates-io`)
	```

**Comment by kjarosh** [comment]
I'm coming!

Did you remember to regenerate cargo sources? It has to be done every time the dependencies change.

I've just finished testing this PR, and GameMode, file pickers, theme integration all work properly both in Flatpak and outside of it :tada:

**Comment by torokati44** [comment]
> Did you remember to regenerate cargo sources? It has to be done every time the dependencies change.

Yes, but maybe not hard enough...?!

**Comment by kjarosh** [comment]
Hmm... That's interesting.

All I did was:

1. Run `make regenerate-sources RUFFLE_COMMIT=11710684d4f61554d5ae4ab30487a7dfaee8476b`
2. Replace commit in the descriptor with `11710684d4f61554d5ae4ab30487a7dfaee8476b`, comment out tag
3. Run `make`

**Comment by torokati44** [comment]
Yeah, well, step 2 is not in the README of the FlatHub repo... :no_mouth:

**Comment by torokati44** [comment]
Not skipping that, it built fine for me too! :partying_face:

Does this mean it's merge o'clock, @adrian17?

**Comment by kjarosh** [comment]
This should be useful:

* https://github.com/flathub/rs.ruffle.Ruffle/pull/28

**Review by adrian17 — APPROVED** [review]

**Pull request merged**
