### PR TITLE
demo: Add visual indicator to file picker for dragging and dropping

### LINKED ISSUE #2776: demo: Add visual indicator to file picker for dragging and dropping

### PR DESCRIPTION
**Pull request by danielhjacobs**
Close #2776

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]

**Review by relrelb — APPROVED** [review]
Thanks!

**Comment by Poopooracoocoo** [comment]
I don't know what this changes. To be clear, in my issue I was referring to dragging and dropping over the local file input area and that not having a visual indicator. 

Cheers :)

**Comment by relrelb** [comment]
> be clear, in my issue I was referring to dragging and dropping over the local file input area and that not having a visual indicator.

This change makes the file picker show a filename when a file is dropped onto the player area (it haven't rolled into the demo page yet so you are welcome to test it locally). Just to understand, do you mean the visual indicator should be shown on the player area when a file is dragged over the local file input?

**Comment by Poopooracoocoo** [comment]
>This change makes the file picker show a filename when a file is dropped onto the player area (it haven't rolled into the demo page yet so you are welcome to test it locally).

Oh understood. That's cool!

>Just to understand, do you mean the visual indicator should be shown on the player area when a file is dragged over the local file input?

Yeah that's what I mean but not over the player area and instead over the local file input area. It's a tiny thing though :)

**Comment by adrian17** [comment]
I still can't visualize what you mean by indicator :( The current indicator is very strongly visible.

**Comment by Poopooracoocoo** [comment]
I'm referring to when you drag and drop over the local file input area and not the player, Adrian. I didn't know that you could drag and drop to that area until right before I created that issue.

**Comment by adrian17** [comment]
> I'm referring to when you drag and drop over the local file input area and not the player, Adrian. I didn't know that you could drag and drop to that area until right before I created that issue.

I actually still don't know what you mean. Admittedly I didn't look at the PR yet.

**Comment by danielhjacobs** [comment]
He's referring to dragging and dropping over the file input, which is not actually code we wrote support for but is something that most browsers apparently support inherently.

**Comment by adrian17** [comment]
Yeah, they support it... but why would it need an indicator? :P 
On desktop, generally I just drag the file straight to the main area, so only people who would try dragging to the fileinput element are ones who already know this feature, right?

**Comment by danielhjacobs** [comment]
Yeah I'm not totally sure it's needed either, but I figured it didn't hurt so I added it, but with the further changes suggested by relrelb in that PR I linked, this becomes a moot point anyway.

**Pull request merged**
