### PR TITLE
desktop: Bump `egui` to latest `master`, set theme instead of visuals

### PR DESCRIPTION
**Pull request by torokati44**
Aiming to fix https://github.com/ruffle-rs/ruffle/issues/17986.

Please verify, @kjarosh.

### CODE REVIEW

**Comment by kjarosh** [comment]
Confirmed working, thank you!

Reading the rationale behind these changes in egui I see that we now should be able to easily integrate with the accent color too, not only dark/light mode!

**Review by kjarosh — APPROVED** [review]

**Comment by torokati44** [comment]
Whoo! Should our accent color be dark blue or orange? The former for dark theme, latter for light? Or the other way around?

**Comment by kjarosh** [comment]
I was rather thinking about https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.portal.Settings.xml#L43 with a possibility to set a custom one (similarly to the dark/light mode).

**Comment by torokati44** [comment]
Oh, so it's a global setting, chosen by the user, rather than a way for applications to subtly customize an otherwise cohesive UI design... gotit!

**Pull request merged**
