### PR TITLE
wgpu: Use intermediate buffer for Context3DCommand::CopyBitmapToTexture

### PR DESCRIPTION
**Pull request by Aaron1011**
In a previous PR, I introduced an optimization that used `copy_texture_to_texture` to copy directly from a BitmapData GPU texture to a Stage3D GPU texture.

Unfortunately, this optimization is incorrect. A BitmapData GPU texture can be modified at any time by normal AVM2 code - in particular, in might be modified before we submit the encoded `copy_texture_to_texture` command. This shows up in Sniper Team, which re-uses BitmapData objects for multiple distinct textures. The previous 'optimization' resulted in the wrong BitmapData contents getting uploaded to a texture (since it was changed before the copy command was submitted).

### CODE REVIEW

**Comment by n0samu** [comment]
This regresses all of the Kings Kollege games ([Stacko](https://arcadespot.com/game/stacko/), [Nambers](https://arcadespot.com/game/nambers/), [Fillz](https://arcadespot.com/game/fillz/), [Hivex](https://arcadespot.com/game/hivex/)). They panic with this error:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_buffer_to_texture
    Copy error
    Number of bytes per row is less than the number of bytes in a complete row

', C:\Users\nosamu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.16.0\src\backend\direct.rs:3019:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
AVM2 stack trace:
        at flash.display3D.textures::Texture/flash::display3D::textures::Texture::uploadFromBitmapData()
        at starling.textures::ConcreteTexture/uploadBitmapData()
        at starling.textures::Texture$/fromBitmapData()
        at starling.textures::Texture$/fromData()
        at Function/process()
        at Function/complete()
```

**Comment by Aaron1011** [comment]
@n0samu Those SWFS should now be fixed

**Review by Dinnerbone — APPROVED** [review]

**Comment by torokati44** [comment]
I suppose this could have been squashed, but no big deal...

**Comment by Aaron1011** [comment]
@torokati44 Good catch - I squashed it.

**Pull request merged**
