### PR TITLE
core: Drop Option<> from TDisplayObject::movie()

### PR DESCRIPTION
**Pull request by Dinnerbone**
This removes a bunch of unwraps!

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Can you remove unwraps from core/src/display_object/container.rs? I can count at least ten of them there.

**Comment by Dinnerbone** [comment]
> Can you remove unwraps from core/src/display_object/container.rs? I can count at least ten of them there.

There's a lot, everywhere :D Trying not to do too many big hitters at once, but I can take a look.

**Review by Aaron1011 — APPROVED** [review]
The Clippy failures are unrelated to this PR, and will be fixed by https://github.com/ruffle-rs/ruffle/pull/8975

**Comment by Aaron1011** [comment]
@Dinnerbone Would it make sense to movie the `Arc<SwfMovie>` field to `DisplayObjectBase`, instead of storing it in each `DisplayObject` struct?

**Review by kmeisthax — APPROVED** [review]
Looks good to me.

I'm not 100% sold on using `activation.context.swf` in non-movie (i.e. spawned from AS3) contexts, but I doubt this will break anything.

I also concur on moving `Arc<SwfMovie>` to `DisplayObjectBase`; but that can be a separate PR.

**Pull request merged**
