### PR TITLE
docs: test guidelines

### PR DESCRIPTION
**Pull request by midgleyc**
Some notes about tests, mostly so the `mtasc` information is more accessible, but also I think it helps to note down what's required for tests instead of letting people figure it out by convention.

There are lots of other `.as` files in the tests, some folders have both a `.as` and a `.fla` file, but I don't know what's going on there so I just documented the ones I understood.

### CODE REVIEW

**Comment by adrian17** [comment]
> creating a .as file in a text editor, and compiling it using `mtasc`

AFAIK this only supports AVM1 - such a note would be nice to have.

**Comment by midgleyc** [comment]
Updated. There's one avm2 test -- `domain_memory` -- that has only a `.as` file and no `.fla`. It'd be nice to know how that one was made.

**Comment by Herschel** [comment]
Thanks for documenting this!

mxmlc/asc from the [Adobe AIR SDK](https://airsdk.harman.com/download) can be used to build AVM2 test SWFs from the command-line: `mxmlc Test.as`. This only works for code-only tests, same with `mtasc`; timeline/graphic tests require an FLA created in Adobe Flash/Animate CS6 or higher for AVM2. I would like to change all of our code-only AVM2 tests to only be an AS file compiled with mxmlc.

Long term in a perfect world, we have our own meta-language + compiler for building test SWFs from a single text file. But this is a significant effort. This would also help with making tests for, e.g., #4195 where we want to test specific malformed/weirdo ops, and we can only create these by hand currently.

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
