### PR TITLE
desktop: Add --trace-avm command-line flag

### PR DESCRIPTION
**Pull request by relrelb**
It prints AVM traces to stdout, for debugging convenience.

### CODE REVIEW

**Comment by adrian17** [comment]
Not sure if I understand. What does that give over running with `RUST_LOG=info`?

**Comment by relrelb** [comment]
> Not sure if I understand. What does that give over running with `RUST_LOG=info`?

`RUST_LOG=info` outputs much more verbose and irrelevant information such as GPU allocations etc.
The `--trace` flag in contrast focuses only on AVM traces.

**Comment by adrian17** [comment]
> RUST_LOG=info outputs much more verbose and irrelevant information such as GPU allocations etc.
> The --trace-avm flag in contrast focuses only on AVM traces.

You can use RUST_LOG env var to filter the logs by target too. For example

```
RUST_LOG=warn,ruffle_core=debug,avm_trace=info
```

**Comment by Herschel** [comment]
Yes, `RUST_LOG=avm_trace=info` was the desired way to do this and the reason for tossing it in a separate log category. I'm not opposed to having a convenience parameter for this, but I think it should be done by configuring `env_logger` instead of making a custom log adapter: https://docs.rs/env_logger/0.8.2/env_logger/

**Pull request closed without merging**
