### PR TITLE
render: Handle PNG and GIF data in DefineBitsJPEG tags (fix #530)

### LINKED ISSUE #530: define_bits_jpeg2 panics on garbage prefixes
Example SWFs:
https://www.newgrounds.com/portal/view/643240/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/622285/format/flash?emulate=flash
https://www.newgrounds.com/portal/view/654178/format/flash?emulate=flash

Panic message: "first two bytes is not a SOI marker"

### PR DESCRIPTION
**Pull request by Herschel**
According to the specs, DefineBitsJPEG2/3 tags can sometimes contain GIF and PNG data. This PR adds the ability to decode PNG data out of these tags.

I'm still not sure how to generate these tags using the Flash IDE, but there are examples in #530. I'm guessing it's some incantation of `[Embed]`, for example, `[Embed(source="test.gif")]`. This may depend on the version of the authoring software (this metadata was first added in Flex Builder and didn't make it over to Flash until ~CS5).

Added `determine_jpeg_tag_format` and `decode_define_bits_jpeg` helper methods to handle the SWF tags. `decode_define_bits_jpeg` will verify the format of the image data and decode it appropriately.

GIF is currently unimplemented (we haven't seen a case of this in the wild yet), but a better error will now be returned.

### CODE REVIEW

**Comment by Herschel** [comment]
@Dinnerbone could you try running this through `scanner`?

**Comment by Dinnerbone** [comment]
Scanning now, so far it's successfully parsing some PNGs and there's no errors. Should be finished in a few hours, but I'll know of any errors before then.

**Comment by Dinnerbone** [comment]
I hit a panic early in the scan whilst parsing https://www.newgrounds.com/portal/view/524451/format/flash?emulate=flash:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Format("TEM marker found where not allowed")', core\src\backend\render.rs:242:5


Before that, there was one JPEG that was broken: https://www.newgrounds.com/portal/view/586108/format/flash?emulate=flash
> 4 components without Adobe APP14 metadata to tell color space

**Comment by Dinnerbone** [comment]
# DefineBitsJPEG2 scan results
## Detected JPEG but couldn't parse
- [586108_TacticalForce1_14202c.swf](https://www.newgrounds.com/portal/view/586108_TacticalForce1/format/flash?emulate=flash)
- [524451_missing_numbers_1_unprotec202c.swf](https://www.newgrounds.com/portal/view/524451_missing_numbers_1/format/flash?emulate=flash)
- [615438_100by100highway_bash_play_202c.swf](https://www.newgrounds.com/portal/view/615438_100by100highway_bash_play/format/flash?emulate=flash)
- [607391_City_Parking202c.swf](https://www.newgrounds.com/portal/view/607391_City/format/flash?emulate=flash)
- [613062_CityParking_LevelPack202c.swf](https://www.newgrounds.com/portal/view/613062_CityParking/format/flash?emulate=flash)
- [578819_MLP_Freindship_is_magic.202c.swf](https://www.newgrounds.com/portal/view/578819_MLP_Freindship_is/format/flash?emulate=flash)
- [472387_Space_Cross__Jack_202c.swf](https://www.newgrounds.com/portal/view/472387_Space_Cross__Jack/format/flash?emulate=flash)
- [50280_britney_s_beach_house202c.swf](https://www.newgrounds.com/portal/view/50280_britney_s_beach/format/flash?emulate=flash)
- [634155_Pots_joydbff.swf](https://www.newgrounds.com/portal/view/634155_Pots/format/flash?emulate=flash)
- [118412_The_Misadventures_of_Hadji202c.swf](https://www.newgrounds.com/portal/view/118412_The_Misadventures_of/format/flash?emulate=flash)
- [116793_Sm3202c.swf](https://www.newgrounds.com/portal/view/116793/format/flash?emulate=flash)
- [405980_clay_tutorial202c.swf](https://www.newgrounds.com/portal/view/405980_clay/format/flash?emulate=flash)
- [312282_cosanostrafinal202c.swf](https://www.newgrounds.com/portal/view/312282/format/flash?emulate=flash)
- [299754_Tetravex202c.swf](https://www.newgrounds.com/portal/view/299754/format/flash?emulate=flash)
- [57140_pooper_s_pub202c.swf](https://www.newgrounds.com/portal/view/57140_pooper_s/format/flash?emulate=flash)
- [59299_bib_3202c.swf](https://www.newgrounds.com/portal/view/59299_bib/format/flash?emulate=flash)

## Detected PNG but couldn't parse
- [616345_paperwings202c.swf](https://www.newgrounds.com/portal/view/616345/format/flash?emulate=flash)

## Detected GIF (and we don't have a parser)
- [647141_racefieldversus0-9-2d028.swf](https://www.newgrounds.com/portal/view/647141/format/flash?emulate=flash)
- [616768_Rhythos202c.swf](https://www.newgrounds.com/portal/view/616768/format/flash?emulate=flash)
- [674253_week-55a34c.swf](https://www.newgrounds.com/portal/view/674253/format/flash?emulate=flash)
- [644274_gammachallengeae65.swf](https://www.newgrounds.com/portal/view/644274/format/flash?emulate=flash)
- [674252_grib-world-light-55e99f.swf](https://www.newgrounds.com/portal/view/674252/format/flash?emulate=flash)
- [645985_huzzahapplication718d.swf](https://www.newgrounds.com/portal/view/645985/format/flash?emulate=flash)
- [659046_spicey-pizza0331.swf](https://www.newgrounds.com/portal/view/659046/format/flash?emulate=flash)
- [655775_mqopenfl0f3a.swf](https://www.newgrounds.com/portal/view/655775/format/flash?emulate=flash)
- [660643_potato-chip-factory5ef0.swf](https://www.newgrounds.com/portal/view/660643/format/flash?emulate=flash)
- [656746_minigame1274.swf](https://www.newgrounds.com/portal/view/656746/format/flash?emulate=flash)
- [639997_gravityswitcha6e3.swf](https://www.newgrounds.com/portal/view/639997/format/flash?emulate=flash)
- [653070_fudge-brownie25c6.swf](https://www.newgrounds.com/portal/view/653070/format/flash?emulate=flash)
- [653781_easter-gamea7d5.swf](https://www.newgrounds.com/portal/view/653781/format/flash?emulate=flash)
- [652842_pepperoni-pizza96a3.swf](https://www.newgrounds.com/portal/view/652842/format/flash?emulate=flash)
- [604699_EvenOrOdd202c.swf](https://www.newgrounds.com/portal/view/604699/format/flash?emulate=flash)
- [662565_snailmuncher0d0b.swf](https://www.newgrounds.com/portal/view/662565/format/flash?emulate=flash)

**Comment by Dinnerbone** [comment]
# DefineBitsJPEG2 scan results
Data source is Newgrounds dump via Flashpoint.

## Detected JPEG but couldn't parse
- [574511_embed_uk202c.swf](https://www.newgrounds.com/portal/view/574511/format/flash?emulate=flash)
- [659479_jurassic-hunteredf7.swf](https://www.newgrounds.com/portal/view/659479/format/flash?emulate=flash)
- [662815_highwayzombies3387.swf](https://www.newgrounds.com/portal/view/662815/format/flash?emulate=flash)
- [622191_WorldCup_PK4b31.swf](https://www.newgrounds.com/portal/view/622191/format/flash?emulate=flash)
- [627984_Bitzy_Blitz0a34.swf](https://www.newgrounds.com/portal/view/627984/format/flash?emulate=flash)
- [664201_messicanplay4480.swf](https://www.newgrounds.com/portal/view/664201/format/flash?emulate=flash)
- [638479_neymarcanplayb844.swf](https://www.newgrounds.com/portal/view/638479/format/flash?emulate=flash)
- [626378_top_Strikerfbce.swf](https://www.newgrounds.com/portal/view/626378/format/flash?emulate=flash)
- [657504_ninja-rope-jumpc041.swf](https://www.newgrounds.com/portal/view/657504/format/flash?emulate=flash)
- [641017_k2t2-flyladybirdb5a7.swf](https://www.newgrounds.com/portal/view/641017/format/flash?emulate=flash)
- [620344_neymar202c.swf](https://www.newgrounds.com/portal/view/620344/format/flash?emulate=flash)
- [622253_secure_neymar9be9.swf](https://www.newgrounds.com/portal/view/622253/format/flash?emulate=flash)
- [646043_suarez804a.swf](https://www.newgrounds.com/portal/view/646043/format/flash?emulate=flash)
- [618150_TheImpossibleDream202c.swf](https://www.newgrounds.com/portal/view/618150/format/flash?emulate=flash)
- [629634_hockey_CPMStar6bb8.swf](https://www.newgrounds.com/portal/view/629634/format/flash?emulate=flash)
- [629612_SDMRPG4a09.swf](https://www.newgrounds.com/portal/view/629612/format/flash?emulate=flash)
- [586108_TacticalForce1_14202c.swf](https://www.newgrounds.com/portal/view/586108/format/flash?emulate=flash)
- [632884_WorldCupLeague_CPMStar17a8.swf](https://www.newgrounds.com/portal/view/632884/format/flash?emulate=flash)
- [638672_fgl-super-baby-fgl426e.swf](https://www.newgrounds.com/portal/view/638672/format/flash?emulate=flash)
- [644235_spanishleague336f.swf](https://www.newgrounds.com/portal/view/644235/format/flash?emulate=flash)
- [667516_santa-no9538e.swf](https://www.newgrounds.com/portal/view/667516/format/flash?emulate=flash)
- [575672_secure_ToxieRadd3D_FPUPDAT202c.swf](https://www.newgrounds.com/portal/view/575672/format/flash?emulate=flash)
- [642965_beetle-bob539b.swf](https://www.newgrounds.com/portal/view/642965/format/flash?emulate=flash)
- [649657_sroguelegend6320.swf](https://www.newgrounds.com/portal/view/649657/format/flash?emulate=flash)
- [629614_Home3845.swf](https://www.newgrounds.com/portal/view/629614/format/flash?emulate=flash)
- [623545_secure_domainNeedWater_NG3e5f.swf](https://www.newgrounds.com/portal/view/623545/format/flash?emulate=flash)
- [628967_cubis0b0e.swf](https://www.newgrounds.com/portal/view/628967/format/flash?emulate=flash)
- [625051_awesomePirates_nga97c.swf](https://www.newgrounds.com/portal/view/625051/format/flash?emulate=flash)
- [628639_Dragooner_NG_v14141.swf](https://www.newgrounds.com/portal/view/628639/format/flash?emulate=flash)
- [664028_office-escapere7b3.swf](https://www.newgrounds.com/portal/view/664028/format/flash?emulate=flash)
- [102454_fling202c.swf](https://www.newgrounds.com/portal/view/102454/format/flash?emulate=flash)
- [602249_RotGut_MaxGames202c.swf](https://www.newgrounds.com/portal/view/602249/format/flash?emulate=flash)
- [643332_worldcupallstars1b21.swf](https://www.newgrounds.com/portal/view/643332/format/flash?emulate=flash)
- [651790_ballondorronaldonoads7b74.swf](https://www.newgrounds.com/portal/view/651790/format/flash?emulate=flash)
- [625106_frog-love-candy-ng_sedd4.swf](https://www.newgrounds.com/portal/view/625106/format/flash?emulate=flash)
- [623684_ZombienationNGv75b8a.swf](https://www.newgrounds.com/portal/view/623684/format/flash?emulate=flash)
- [636962_publish_panda-restaurant3-d784.swf](https://www.newgrounds.com/portal/view/636962/format/flash?emulate=flash)
- [647853_herovsmagidc7a.swf](https://www.newgrounds.com/portal/view/647853/format/flash?emulate=flash)
- [650073_santa-go-adventure-s22174.swf](https://www.newgrounds.com/portal/view/650073/format/flash?emulate=flash)
- [637088_Quadroscope_secure9034.swf](https://www.newgrounds.com/portal/view/637088/format/flash?emulate=flash)
- [619986_bear_killer_ng_1_s202c.swf](https://www.newgrounds.com/portal/view/619986/format/flash?emulate=flash)
- [610251_Toesamoe202c.swf](https://www.newgrounds.com/portal/view/610251/format/flash?emulate=flash)
- [622639_secure_MyMonsterExsa2ee.swf](https://www.newgrounds.com/portal/view/622639/format/flash?emulate=flash)
- [662042_simbro-v-0-211a40.swf](https://www.newgrounds.com/portal/view/662042/format/flash?emulate=flash)
- [621074_Atlantis2_NGv3202c.swf](https://www.newgrounds.com/portal/view/621074/format/flash?emulate=flash)
- [612985_GiveUp_newgrounds_secure202c.swf](https://www.newgrounds.com/portal/view/612985/format/flash?emulate=flash)
- [635568_CrashPlanet51a3.swf](https://www.newgrounds.com/portal/view/635568/format/flash?emulate=flash)
- [650813_s-santa-delivery-gift-esc4c49.swf](https://www.newgrounds.com/portal/view/650813/format/flash?emulate=flash)
- [618713_defend_your_cabin_s202c.swf](https://www.newgrounds.com/portal/view/618713/format/flash?emulate=flash)
- [619145_zombie_like_brain_noad_s202c.swf](https://www.newgrounds.com/portal/view/619145/format/flash?emulate=flash)
- [622415_secure_FootballWeb5cb4.swf](https://www.newgrounds.com/portal/view/622415/format/flash?emulate=flash)
- [617337_redball4v2202c.swf](https://www.newgrounds.com/portal/view/617337/format/flash?emulate=flash)
- [651106_clausdca3.swf](https://www.newgrounds.com/portal/view/651106/format/flash?emulate=flash)
- [592100_NotLD_secure91a3.swf](https://www.newgrounds.com/portal/view/592100/format/flash?emulate=flash)
- [628945_secure_DropLabWeb3f58.swf](https://www.newgrounds.com/portal/view/628945/format/flash?emulate=flash)
- [657992_kendonoadsd72d.swf](https://www.newgrounds.com/portal/view/657992/format/flash?emulate=flash)
- [660046_candycompany1285.swf](https://www.newgrounds.com/portal/view/660046/format/flash?emulate=flash)
- [660990_globexplorerd923.swf](https://www.newgrounds.com/portal/view/660990/format/flash?emulate=flash)
- [655483_the-night-rider4dd6.swf](https://www.newgrounds.com/portal/view/655483/format/flash?emulate=flash)
- [123300_catflash202c.swf](https://www.newgrounds.com/portal/view/123300/format/flash?emulate=flash)

## Other types
Every single tag contained a JPEG, there were 0 PNGs, GIFs or Unknowns. [The warning about alpha + non-JPEG](https://github.com/ruffle-rs/ruffle/pull/532/files#diff-b1a81b171e0229a618f9841f287da3beR173) was never triggered.

**Comment by Herschel** [comment]
Added GIF support (this also fixes #27).

Interestingly these all seem to be generated by OpenFL, so maybe you can't generate these using Flash IDE directly after all.

**Comment by Dinnerbone** [comment]
All gifs successfully parse 👍

**Pull request merged**
