### PR TITLE
avm2: report more correct Capabilities.os

### PR DESCRIPTION
**Pull request by Mesteery**
Not very accurate but probably better than nothing

### CODE REVIEW

**Comment by n0samu** [comment]
See also: #10469
I think it was never merged because we weren't able to agree on how much information we want to expose, how accurate it should be, etc :(

**Comment by Mesteery** [comment]
Yes I can understand. Some AIR applications rely on `os` to for example, find an OS-specific path, or use FileStream instead of URLLoader for macOS platforms (in case of Dofus), so for theses applications a correct os value is important and can possibly break the game

**Comment by evilpie** [comment]
We could do this for AIR only. I also think this changes to OS for everything running on the web/extension to Linux, which we most likely don't want to do. Windows is a much much larger market.

**Comment by Mesteery** [comment]
What if we put Windows instead of Linux in the else?

**Comment by Mesteery** [comment]
Closing in favor of https://github.com/ruffle-rs/ruffle/pull/17590

**Pull request closed without merging**
