### PR TITLE
avm1: Fix string-to-number octal and whitespace handling

### PR DESCRIPTION
**Pull request by hthh**
This conversion allows negative octal values, but not negative hex values, and ignores only leading ASCII whitespace. A test for this behavior is included.

The test was written using *swfc* from [swftools](https://github.com/matthiaskramm/swftools) - is that acceptable? I gave it a try as it's a free, open-source, command-line tool with plain-text input, and I don't have Adobe Animate. It's quite flexible and powerful, but feels a bit flakey and poorly documented.

### CODE REVIEW

**Comment by Herschel** [comment]
Thanks for the contribution and welcome!

I'm not sure about adding tests using swftools -- anyone else have an opinion? On one hand it's annoying to have to require Flash/Animate to build tests. On the other hand, I'm not sure if using possibly unsupported third-party tools is better, and we'll probably need at least some FLA files regardless.

Fortunately we can avoid the question for now! You could add these tests along with the others in `number_function` in `core\src\avm1\globals.rs` (this has support for versioning, so it can test that octal does not apply to SWFv5 as well.)

**Comment by ROBERT-MCDOWELL** [comment]
I think the best is to ask to his author Mathias Kramm
https://github.com/matthiaskramm/swftools

**Comment by ousia** [comment]
I think https://github.com/jindrapetrik/jpexs-decompiler can convert Flash files to FLA source files.

This could avoid the issue of having `swfc` sources.

**Comment by Herschel** [comment]
After some discussion in Discord, we're okay with using `swfc`, possibly with an eye on writing our own similar AVM1 scripting/mini-compiler in the future. This allows people to contribute even without the various versions of the Flash IDE.

For this specific PR however, there are already tests existing at  https://github.com/ruffle-rs/ruffle/blob/master/core/src/avm1/globals.rs#L459-L507 -- could you move your octal tests over there, @hthh?

**Comment by hthh** [comment]
Thanks for the feedback - that sounds good :) Updated as requested, sorry about the delay!

**Comment by Herschel** [comment]
Thanks!

**Pull request merged**
