### PR TITLE
Move AvmString type to ruffle_core::string

### PR DESCRIPTION
**Pull request by moulins**
Following the discussion on #4285, this PR move `ruffle_core::avm1::string::AvmString` to `ruffle_core::string::AvmString` to better reflect the fact that the same string type is used by both AVM1 and AVM2.

### CODE REVIEW

**Comment by Herschel** [comment]
LGTM, everyone okay with pulling the trigger on this change?

**Review by kmeisthax — APPROVED** [review]
👍

**Review by torokati44 — APPROVED** [review]
I don't see anything wrong with it either, and it will certainly look cleaner this way, instead of `avm2` reaching over to `avm1` for this type.

**Review by relrelb — APPROVED** [review]
LGTM! This reminds me of an idea I had to pull out separate crates for `avm1` and `avm2`, that will contain all ActionScript-specific logic (like `avmplus` does). Then `core` embeds them and adds Flash's objects (`Sound`, `BitmapData` etc.). An addditional `avm_common` crate will be needed to share common logic exactly like `AvmString`.
This model has few advantages such as:
* Better code structure using a well-defined API between its components, and less room to make mess.
* Ability to build `avm1` and `avm2` standalone for testing purposes, or just getting an interactive shell like `avmplus`.

**Comment by Herschel** [comment]
Yep, long term I'd like to be able to selectively enable avm1 and avm2 in the player as well -- one use case is that there are standalone Flash games on Steam, and in a perfect world they could make a build that does not include the VM they aren't using.

Thank you!

**Pull request merged**
