### PR TITLE
web: Get rid of move-file-cli

### PR DESCRIPTION
**Pull request by relrelb**
As of #2482, `web/packages/core/package.json` uses `move-file-cli` in its `build:wasm-opt` script. I think it's unnecessary, as it seems to work without it by letting `wasm-opt` optimize `ruffle_web_bg.wasm` in-place.
@torokati44 Am I missing something?

### CODE REVIEW

**Comment by torokati44** [comment]
I explained the reason for this in https://github.com/ruffle-rs/ruffle/pull/2482#issuecomment-761164183 :

> I had some issues with an 'alternative' wasm-opt command somehow being left over from the npm cache or something, and for some reason, that silently did not overwrite the file, but still returned 0...
> That's why I went with the intermediate *.opt.wasm approach.

I have no idea what could have caused that, so I went the safe route.
If you don't think this could reasonably happen to anyone anymore, feel free to drop it

**Comment by torokati44** [comment]
It might have had something to do with https://github.com/WebAssembly/binaryen/issues/1907 or https://github.com/WebAssembly/binaryen/pull/1908 ...

**Comment by Herschel** [comment]
@torokati44 Do you think the issue can still occur? I'm inclined to leave this be if there are circumstances where it could still break, particularly if the failure is silent.

**Comment by torokati44** [comment]
The only scenario I can imagine this (silent failure) still resurface is when someone has an archaic `wasm-opt` lingering around (from before the issues linked above were fixed); like I had when it was still in the npm cache/PATH(?), probably put there by the late `wasm-pack` stuff.

**Comment by Herschel** [comment]
Thanks！

**Pull request merged**
