### PR TITLE
chore: Update translations

### PR DESCRIPTION
**Pull request by RuffleBuild**
New Crowdin pull request with translations 🎉

### CODE REVIEW

**Comment by torokati44** [comment]
As of right now, this is a hecking regression because of  https://github.com/actions/runner-images/issues/10636#issuecomment-2417293457 😩

**Comment by torokati44** [comment]
Restored all the lost translations from the project's Translation Memory (at least where other contributors weren't quicker ^^), so this can be closed now.

----

BTW @kjarosh, this might need a `git commit --allow-empty` or something...

> `nothing to commit, working tree clean`

https://github.com/ruffle-rs/ruffle/actions/runs/11373857437/job/31649359286#step:9:11

**Comment by kjarosh** [comment]
> this might need a `git commit --allow-empty` or something...
> 
> > `nothing to commit, working tree clean`

We would have to check `git diff --exit-code` before staging files and ignore further steps in case there are no changes.

**Comment by torokati44** [comment]
Sure, or that... :)

**Pull request closed without merging**
