### PR TITLE
ci: Temporarily pin to Node 22.4

### PR DESCRIPTION
**Pull request by danielhjacobs**
See https://github.com/nodejs/node/issues/53902

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]

**Comment by torokati44** [comment]
Node 22.5.1 is now out with the fix, so I guess this can be reverted now?

**Comment by danielhjacobs** [comment]
Not yet, it's not yet in https://github.com/actions/node-versions/releases/

**Comment by torokati44** [comment]
If I see correctly, that repo is updated automatically every 12 hours, so it should be there in either 10 or 70 minutes.

**Comment by Algiuxs** [comment]
It's there

**Comment by torokati44** [comment]
Yes, see: https://github.com/ruffle-rs/ruffle/pull/17181#issuecomment-2239527084
Now we're waiting for https://github.com/actions/node-versions/pull/182.

**Pull request merged**
