### PR TITLE
avm1: implement BitmapData.applyFilter

### LINKED ISSUE #11912: holy guadalupe!: BitmapData Issue
### Describe the bug

image
image
image
image
image
```
2023-07-05T14:52:16.716909Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.717154Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.717806Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.718108Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.718385Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.718697Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.718935Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:16.719229Z  WARN run_frame: ruffle_core::avm1::runtime: Avm1::pop: Stack underflow
2023-07-05T14:52:49.216385Z  WARN run_frame: ruffle_core::stub: Encountered stub: AVM1 BitmapData.applyFilter()
2023-07-05T14:52:50.996956Z  INFO avm_trace: eo
2023-07-05T14:52:54.684166Z  INFO avm_trace: eo
2023-07-05T14:52:58.382956Z  INFO avm_trace: eo
2023-07-05T14:53:02.022976Z  WARN ruffle_core::avm1::globals::bitmap_data: Invalid BitmapData size: 0x0
```

### Expected behavior

image
image
image
image
image

### Affected platform

Desktop app

### Operating system

Windows 10

### Browser

_No response_

### Additional information

https://www.pouet.net/prod.php?which=25593

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #11912. Seeking feedback.

### CODE REVIEW

**Comment by MartySVK** [comment]
it was already implemented a few days ago - https://github.com/ruffle-rs/ruffle/pull/12176

**Comment by SuchAFuriousDeath** [comment]
Yeah, just noticed. Feel free to close this then

**Comment by Dinnerbone** [comment]
Sorry about that! 😅

**Comment by n0samu** [comment]
Your effort is much appreciated though! Welcome to the project 😃

**Pull request closed without merging**
