### PR TITLE
core,tests: Fix socket test backend

### PR DESCRIPTION
**Pull request by sleepycatcoding**
This was hiding the fact that the test technically did not run and failed, as it only happened very rarely in some scenarios.

Partially fixes the problem in #12383.

### CODE REVIEW

**Comment by sleepycatcoding** [comment]
I redesigned the socket system to use async-channel when sending data out. This allows the removal of timeouts in test backend.

**Comment by sleepycatcoding** [comment]
@Dinnerbone Now that the socket tests actually work, there is still something wrong AMF0 writeObject, so maybe we can split the Socket writeObject into a separate test and use `known_failure`?

**Comment by Dinnerbone** [comment]
> maybe we can split the Socket writeObject into a separate test and use `known_failure`?

Will it always fail? If not it'll be flaky just with opposite chances. If it will always fail though, this sounds good!

**Comment by sleepycatcoding** [comment]
This will always fail. The reason it was so unpredictable before was that the timeouts were too high, so basically the test did not run. It only ran on MacOS runner correctly is because the runner seems to be fairly slow.

**Comment by sleepycatcoding** [comment]
There should probably be a flag to make test runner execute async tasks to completion after running all ticks as that would have shown that the socket write test did not run correctly.

**Comment by sleepycatcoding** [comment]
There should probably be a flag to make test runner execute async tasks to completion after running all ticks as that would have shown that the socket write test did not run correctly.

**Review by Dinnerbone — APPROVED** [review]

**Comment by SN902** [comment]
#12466

**Pull request merged**
