### PR TITLE
render: Bump wgpu to 0.17 and naga to 0.13

### PR DESCRIPTION
**Pull request by Aaron1011**
This requires forked versions of several dependencies, and egui doesn't yet compile on wasm due to the `!Send/!Sync` wgpu changes.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Wait why are we compiling egui for web? We only use it on desktop?

**Comment by Aaron1011** [comment]
Oh, that's right - I forgot that we only enable the `ruffle_core` feature on desktop.

**Comment by torokati44** [comment]
Just cross-referencing: https://github.com/bevyengine/naga_oil/pull/40

**Comment by danielhjacobs** [comment]
Also cross-referencing https://github.com/emilk/egui/pull/3170

**Comment by Aaron1011** [comment]
I've updated this to use my merged PR in egui, which ended up using the fragile-send-sync feature for wgpu.

**Comment by torokati44** [comment]
https://github.com/bevyengine/naga_oil/pull/40 Just got merged!

**Review by adrian17 — APPROVED** [review]
LGTM, just one question: what's that about increased outliers?

**Comment by Aaron1011** [comment]
@adrian17 Those outliers were due to an issue with my local setup - I removed them, and CI is still passing.

**Pull request merged**
