### PR TITLE
web: Add webgl backend through wgpu

### PR DESCRIPTION
**Pull request by Dinnerbone**
This uses wgpu API entirely on web (NOT webgpu), which translate into webgl. One less custom renderer for us to maintain.

The downside is that we stop using WebGPU (the experimental rendering tech) as this is a compile time switch.

My proposal is to try this out for a while, and if we want WebGPU back then we can build our binary twice - one for webgl and one for webgpu - and load the correct one depending on the existence of `navigator.gpu`.

Opinions and thoughts from all maintainers are welcome. Is this something we should try?

### CODE REVIEW

**Comment by Herschel** [comment]
Thank you! This is the definite medium-to-long term plan! But I'd like significant testing before being made the default -- I wouldn't want to flat out remove the WebGL renderer right away. At least as a first step, we should enable this on the demo site for some time (similar to what we do with the WebGPU support now).

To explain my hesitancy: as the one who's had to deal with `wgpu`'s churn over the past two years, it has been a quite common occurrence for `wgpu` and `naga` to be broken in different ways, even recently, for our fairly basic usage. This then involves dealing with an extra layer of debugging, submitting an issue upstream, adding a git rev dependency to our Cargo.toml, while users suffer. Add to the fact that `WebGPU`, and thus `wgpu`, is a moving target, and it becomes quite frustrating.

That said, we already deal with this on desktop. And we definitely want to do this at some point. But our user base on web is much larger, and I want to be very, very sure that this works correctly. I would also feel a better about it if we had already implemented some of the fancier features like filters.

We at least need a concrete plan for testing this in some way. It'd be nice to have some performance metrics as well!

An example of something that might be an issue: at least on desktop, there are often cases where wgpu panics on initialization for various reasons (maybe a certain backend is supported, or some surface format isn't available, or...), and I suspect this is worse on a relatively recent backend like WebGL. On web especially, we would want to fall back to the canvas backend. So I'd want to be sure we can recover in these situations.

**Comment by Dinnerbone** [comment]
> At least as a first step, we should enable this on the demo site for some time (similar to what we do with the WebGPU support now).

Would that be in addition to webgpu, or instead of? Unfortunately for now it's one or the other, a compile time flag on wgpu. We can of course investigate building both and switching out the wasm binary though.



> We at least need a concrete plan for testing this in some way. It'd be nice to have some performance metrics as well!

I agree on both fronts, yes!



> An example of something that might be an issue: at least on desktop, there are often cases where wgpu panics internally for various reasons (maybe it tries and fails to use some backend such as vulkan on linux, or some surface format isn't available, or...), and I suspect this is worse on a relatively recent backend like WebGL. On web especially, we would want to fall back to the canvas backend. So I'd want to be sure we can recover in these situations.

So from what I've seen, a lot of the panics we had (and have) are "user error" in a way - we're not respecting the limits of the platform. I'm trying to correct for this as I see them appear. There's also tools for handling the more panicky errors inside wgpu, but we don't use those.

I want to redo a lot of how we use wgpu (and our rendering API in general) to allow for more stability and performance, but I've been holding off whilst people are working on it (like the draw PR)

**Comment by Dinnerbone** [comment]
I've change the PR to not change any defaults and not delete the webgl crate, but to allow for us to build wgpu-webgl when needed.

No changes to demo site for now though.

**Comment by Herschel** [comment]
Let's enable wgpu-webgl on the demo site in lieu of wgpu-webgpu, because WebGPU got pushed back to next year (ugh), and it's also [being temporarily removed from origin trial in September anyway](https://groups.google.com/a/chromium.org/g/blink-dev/c/gBMsYQ1Aurw/m/xl1znc7fAAAJ).

Possibly we could convince Newgrounds to use a wgpu-webgl for good testing as well, before pushing it to everyone. (Thoughts, @TomFulp ?)

**Comment by Dinnerbone** [comment]
I added a line in the debug text to say the renderer type, and switched the demo job to use wgpu-webgl.

**Comment by adrian17** [comment]
For the record, copying from Discord: for me, on FF, this introduces a ~7s hang when initializing the player, due to pipeline (75%) and shader (20%) creation.

**Comment by torokati44** [comment]
Do you think the `wgpu-webgl` backend should be used on the demo page even when building and running the demo locally?
So, in `package.json` instead of in the GitHub workflow definition.

**Comment by Herschel** [comment]
> Do you think the `wgpu-webgl` backend should be used on the demo page even when building and running the demo locally? So, in `package.json` instead of in the GitHub workflow definition. Should be a lot easier to test and experiment with.

Yes, that sounds like a good idea!

**Comment by Dinnerbone** [comment]
Per discord discussion - I've removed the commit that enables this by default, and I'll make that a new PR in the future when we think this is ready to go.

This PR now only adds support for wgpu-webgl, it doesn't enable it anywhere by default. It also improves the wgpu renderer and fixes some desktop crashes

**Comment by Herschel** [comment]
Thank you!

**Comment by adrian17** [comment]
FYI

```
    #[cfg(not(any(feature = "canvas", feature = "webgpu", feature = "wgpu-webgl")))]
    std::compile_error!("You must enable one of the render backend features (e.g., webgl).");
```
It's missing `webgl`, so trying to build Ruffle with only webgl currently fails.

**Pull request merged**
