### PR TITLE
core/mp3: More lenient MP3 buffer underrun detection

### LINKED ISSUE #7524: Regression in z0r.de/1988 - sound became choppy
### Describe the bug

In Nightly 2022-07-31 the audio in z0r.de/1988 became choppy.
I believe this is the nightly build where this change came about (at least for the web extension): https://github.com/ruffle-rs/ruffle/pull/4273
And F12 spams with "Bad MP3" stuff:

image

### Expected behavior

A non-choppy audio.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Chrome 103.0.5060.134

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by torokati44**
This should fix #7524.
Regression testing in progress, re: #5486 #6546

(Sorry for being so terse for now, I just had to get this out of my brain ASAP.)

### CODE REVIEW

**Comment by Herschel** [comment]
I'd add a comment to the code that this is a quick fix and that we're not sure of the exact behavior.

**Comment by torokati44** [comment]
Sure, that's also part of why I marked it as draft.

**Comment by Herschel** [comment]
Mainly checking that this change doesn't make things worse for any cases. If it's strictly an improvement or no change, then I think this is fine to merge.

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
