### PR TITLE
Wire in DefineVideoStream smoothing flag to the renderer

### PR DESCRIPTION
**Pull request by torokati44**
This is how it's "supposed to" work, according to the docs (and common sense as well), but more experimentation is needed to determine how and why exactly Flash Player actually enables smoothing on videos.
In Flash Player, on my hand-crafted tiny test videos, this flag worked as expected; but when enabling this flag on videos in SWFs found in the wild, it did nothing, the picture stayed pixelated.

### CODE REVIEW

**Comment by torokati44** [comment]
At least for H.263 video, the smoothing flag takes effect iff the video has exactly 1 frame. :man_facepalming:
Why? :confused: 
Do we want to replicate this? :thinking: 
Here are a couple of random test files I made to discover this: [h263_frame_smoothing_tests.zip](https://github.com/ruffle-rs/ruffle/files/7221230/h263_frame_smoothing_tests.zip)

**Comment by torokati44** [comment]
And it looks like it always applies to VP6 videos, regardless of the number of frames it has: [vp6_frame_smoothing_tests.zip](https://github.com/ruffle-rs/ruffle/files/7221262/vp6_frame_smoothing_tests.zip)

**Comment by torokati44** [comment]
For Screen (V1, I think) video, the same logic applies as for H.263.
And to make matters worse, in both cases, the _actual number of frames_ counts, not the `numFrames` attribute of the `DefineVideoStream` tag.

**Comment by torokati44** [comment]
Okay, I have added the weird logic for this flag, and provided a whole bunch of handcrafted files above to verify matching behavior.
Although, the `num_frames` attribute always matches the number of frames in the file, that could also be perturbed for more complete coverage.
For ScreenV2, I have no idea what happens, as I have no material to test it, and found no way to create any either.

Note that with the smoothing flag off, Flash Player produces major vertical glitching when magnifying videos, but there's no way I'm replicating that, as it appears to clearly be a programming mistake.

**Comment by Herschel** [comment]
Seems like this depends on at least the SWF version: changing nemderulki_h263_2frames_smooth.swf to SWF version 8 allows it to be smoothed.

**Comment by Herschel** [comment]
This is actually due to the way `_quality` works in pre-FP8. With the default `_quality = "HIGH";`, bitmaps/videos will only obey the smoothing parameter if they are static -- so I think this explains the case of 1-frame videos being smoothed. (In the case of bitmaps, they'd be unsmoothed if they were moving, say, via a tween).

The bitmaps and videos will be always smoothed if `_quality = "BEST";` is added to frame 1.

In FP8+, the default "HIGH" quality was changed to always obey the smoothing settings for bitmaps and videos.

**Comment by torokati44** [comment]
For completeness, the table above also has a first half in the spec:

image

And indeed, the codec used wasn't the discriminator, it was the SWF version - which was set by ffmpeg depending on the chosen codec...

**Review by kmeisthax — APPROVED** [review]

**Pull request merged**
