### PR TITLE
core: add framerate to SWF load log

### LINKED ISSUE #8531: Add a way to print exif info for .swf
Over at tasvideos, we use libTAS to record [replay files for ruffle](https://tasvideos.org/EmulatorResources/Ruffle). Before starting a recording, one needs to set framerate properly, to match what a given game has. To know this info, users have to install and run a separate program (exiftool). Since the setup for TASing Flash games is already quite complex, users may forget to do the extra step and set the framerate, which will result in mismatch between when a game is expecting new input and when we can send it (libTAS recordings are videoframe based).

It would be extremely useful if ruffle had a way to print exif into to console upon launching a game, or at the very least the game's framerate and resolution. This is only relevant for the desktop version of ruffle, specifically when ran from console.

### PR DESCRIPTION
**Pull request by vadosnaprimer**
Prints information about the loaded SWF. Outputs:
- version
- resolution
- framerate
- url

fixes #8531

### CODE REVIEW

**Comment by relrelb** [comment]
Welcome! Personally I prefer this should be a `desktop`-only feature, without involving `core`.
That `print!` can be "duplicated" to the `on_metadata` closure, that should have all needed data available in `swf_header`:
https://github.com/ruffle-rs/ruffle/blob/master/desktop/src/main.rs#L285

**Comment by vadosnaprimer** [comment]
I tried doing this

```rust
            let on_metadata = move |swf_header: &ruffle_core::swf::HeaderExt| {
                let _ = event_loop_proxy.send_event(RuffleEvent::OnMetadata(swf_header.clone()));

                if opt.print_swf_info {
                    println!(
                        "Loaded SWF version {}, resolution {}x{} @ {} FPS",
                        swf_header.version(),
                        swf_header.stage_size().width(),
                        swf_header.stage_size().height(),
                        swf_header.frame_rate(),
                    );
                }
            };
```

But that way, there's no SWF info report when the game consists of several SWF files and loads them consecutively (Samorost). And I don't understand where to get movie URL from.

**Comment by Herschel** [comment]
This is tricky because we fire `on_metadata` once on initial load, and not when the root movie is replaced via a `loadMovie`/`loadMovieNum` call. We could fire it again when the root movie is replaced, although this is potentially a breaking change (someone using our web API could be relying on `onMetadata` only being called once). Do you have any thoughts @relrelb?

We could also simply always print the SWF info by default on desktop.

In general with regards to #8531, a Flash movie can change its framerate dynamically in many odd ways, so printing the SWF info isn't a perfect catch-all solution either. Ideally in the future we'd have some desktop debug UI that can display the current stage framerate. Thanks for working on this, I do want to add features to support the TAS community!

**Comment by vadosnaprimer** [comment]
Can resolution also dynamically change during the movie? Sounds like those can instead be printed whenever the new value is set.

**Comment by kmeisthax** [comment]
We could introduce a separate `onRootMovieChange` event that always fires when level0 is replaced, and mark `onMetadata` as being for the initial load only.

My limited knowledge of resizes is that, at least in Flash Player (i.e. not AIR), resizes always propagated from the containing element onto the Stage. The only way to resize the Stage from within a SWF is to use ExternalInterface to ask JavaScript to do it for you. We could still fire an event for that if it were necessary - perhaps an `onStageParametersChanged` that covers resizes, frame rate changes, and alignment parameters.

**Comment by n0samu** [comment]
`onRootMovieChange` might also be useful for #6308, I think.

**Comment by n0samu** [comment]
@vadosnaprimer Sorry for the late comment. It'd be great to get this PR finished up and merged!

I think a nice path forward would be to change this PR to simply add more detail to the existing message:
https://github.com/ruffle-rs/ruffle/blob/37ec94f95bfa5c1f83f481962600d04ab2497b74/core/src/player.rs#L327-L332

Since your original issue specifically mentions framerate, you could just add the `@ {} FPS` part. Side note: seeing the framerate when launching the SWF probably would have helped me find the real issue with #9325 a bit sooner! 😄 

That way there's no need to add a new command-line option to the desktop app, and the message continues to show up on web, which I think is a good thing. Note that the message is only shown if you set the log level to `info` or above:
- On desktop, you can set this with the `RUST_LOG` environment variable, as explained in [CONTRIBUTING.MD](https://github.com/ruffle-rs/ruffle/blob/HEAD/CONTRIBUTING.md#debugging-actionscript-content).
- On selfhosted (web) builds, you can use the [`logLevel` option](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#list-of-options).
- With the extension, you can set this on the Settings page.
image

What do you think?

**Comment by vadosnaprimer** [comment]
I tried using `export RUST_LOG=info` and here's my impression.

As mentioned in #8531, the primary goal of my request is to make it easy for users to see what framerate they need to set in libTAS. The current way to know it is opening the SWF in a decompiler like `JPEXS FFDec`, or running `libimage-exiftool-perl` on it. If it was possible to see SWF header info by adding a command line switch, users would just include it in the libTAS command for ruffle.

The problem with using `RUST_LOG=info` for that, is that it prints out an insane, ever growing wall of text, and one has to know exactly where to find the SWF header info, or to log it to a file and use text search. If the game consists of multiple SWF files, the log file gets quite huge, which adds to the complications for regular users. In my opinion using this method is harder for them than what we have right now.

So yeah, I thought having a dedicated command line switch for this (and only this) extra info would be a neater addition.

Alternatively, maybe there's a way to make ruffle only log out a single piece of info that we need, instead of everything?

**Comment by n0samu** [comment]
> Alternatively, maybe there's a way to make ruffle only log out a single piece of info that we need, instead of everything? Like, only print if the line contains "Loaded SWF", even if we have to use regex.

This can be accomplished with the following command:
`RUST_LOG=ruffle_core=info ./ruffle filename.swf | grep "Loaded SWF version"`

**Comment by vadosnaprimer** [comment]
That actually works great! Though it looks like not all games make it behave ideally. With Samorost I properly get:

```sh
$ RUST_LOG=ruffle_core=info libTAS | grep "Loaded SWF version"
[1970-01-01T00:00:01Z INFO  ruffle_core::player] Loaded SWF version 7, with a resolution of 950x750
[1970-01-01T00:01:02Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 800x660
[1970-01-01T00:02:55Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 950x750
[1970-01-01T00:04:13Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 950x750
[1970-01-01T00:05:35Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 829x750
[1970-01-01T00:06:34Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 879x750
[1970-01-01T00:07:35Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 879x750
[1970-01-01T00:08:50Z INFO  ruffle_core::player] Loaded SWF version 6, with a resolution of 950x750
```

But Tower Bloxx gives this:

```sh
$ RUST_LOG=ruffle_core=info libTAS | grep "Loaded SWF version"
[1970-01-01T00:00:01Z INFO  ruffle_core::player] Loaded SWF version 7, with a resolution of 640x480
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::runtime] Avm1::pop: Stack underflow
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::object::stage_object] Unimplemented property _focusrect
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::activation] Cannot enumerate Undefined
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowInsecureDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowInsecureDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowInsecureDomain() not implemented
[1970-01-01T00:00:01Z WARN  ruffle_core::avm1::activation] Cannot enumerate Undefined
[1970-01-01T00:00:01Z ERROR ruffle_core::loader] Error during movie loading: FetchError("HTTP status is not ok, got 404 Not Found")
[1970-01-01T00:00:04Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowDomain() not implemented
[1970-01-01T00:00:04Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowDomain() not implemented
[1970-01-01T00:00:04Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowInsecureDomain() not implemented
[1970-01-01T00:00:04Z WARN  ruffle_core::avm1::globals::system_security] System.security.allowInsecureDomain() not implemented
[1970-01-01T00:01:10Z INFO  ruffle_core::focus_tracker] Focus is now on Some(EditText(EditText(GcCell(Gc { ptr: 0x561b7a1841f8 }))))
[1970-01-01T00:01:13Z INFO  ruffle_core::focus_tracker] Focus is now on None
[1970-01-01T00:01:13Z INFO  ruffle_core::focus_tracker] Focus is now on Some(EditText(EditText(GcCell(Gc { ptr: 0x561b7a1841f8 }))))
```

**Review by n0samu — APPROVED** [review]
Awesome, thanks for your contribution! 😃

**Comment by n0samu** [comment]
Oh and by the way, you can change the title of your PR using the edit button to the right of it.
image

**Comment by vadosnaprimer** [comment]
Fixed.

**Review by adrian17 — APPROVED** [review]

**Review by Lord-McSweeney — APPROVED** [review]

**Review by relrelb — APPROVED** [review]

**Pull request merged**
