### PR TITLE
web/audio: Dynamic buffer size

### PR DESCRIPTION
**Pull request by torokati44**
~This is not done yet, just pushing for visibility.~

The goal is to:
 - Make demanding content (especially on mobile) as stutter-free as possible
 - Reduce latency on lighter content (or on powerful hardware) as much as possible

### CODE REVIEW

**Comment by torokati44** [comment]
Thank you for the suggestions @ousia! Once I get something that actually works, I might test those too!

**Comment by torokati44** [comment]
At least in my limited testing, this now appears to do what it's supposed to:
 - z0r.de/690 no longer stutters sometimes
 - z0r.de/6268 now feels more "responsive" to music

More investigation is needed though, to make sure.

**Review by Dinnerbone — APPROVED** [review]
Looks good to me but I'm definitely not an expert in this area :D

**Comment by torokati44** [comment]
Thanks for checking it out! And, well, neither am I! 😅

**Comment by torokati44** [comment]
Code is one thing, but it'd be great if this could get some more testing, to make sure it doesn't cause any regressions by being too opportunistic with short buffers.

@Toad06 or @n0samu, could either of you please try it out on some of your content, if you have the time of course?

**Comment by Toad06** [comment]
Forgot to mention it but I tried the PR right after it was no longer a draft. 

I tested many files (including #6611 and #1673 which had issues only affecting the web build) and haven't found any regression. So this looks good to me.  😉

**Comment by torokati44** [comment]
That's great to hear, thank you! ☺️

**Comment by n0samu** [comment]
I just did a few quick tests and this seems to be working exactly as intended! In Bloons 2, which previously had very choppy audio, now the audio is delayed but mostly smooth, except in the very most demanding sections. And games that ran smoothly seem unchanged, with no additional audio delay introduced. Nicely done! 😃

**Comment by torokati44** [comment]
Thanks to you too, and also good to hear! ^^

**Pull request merged**
