### PR TITLE
avm2: Implement RegExp

### PR DESCRIPTION
**Pull request by paq**
This PR aims to implement `RegExp` class in AVM2.

The following crate is used to implement the ECMA-like regular expression.
https://github.com/ridiculousfish/regress
However, this crate is not equal to AVM2's regular expression, so it may not work correctly in some cases.
(UPDATED) The `extended` flag is currently not supported because the crate doesn't.

### CODE REVIEW

**Comment by madsmtm** [comment]
Just for reference, the [Developers Documentation](https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7fdb.html) states that the implementation they use is [ECMAScript edition 3 language specification (ECMA-262)](https://www-archive.mozilla.org/js/language/E262-3.pdf)

**Comment by kmeisthax** [comment]
So, aside from the failing CI tests on nightly compilers the code here looks fine and doesn't have any major oversights I can see. However, there do not appear to be any regression tests - while you are using a standards-compliant library, it's entirely possible that AS3 winds up doing something weird with regexes that you'd only encounter during the test-writing process. I'd recommend writing a few and adding them.

If you don't have access to Adobe Animate or some other AS3 compiler I can write them for you.

**Comment by paq** [comment]
Hi kmeisthax, thank you for checking.


I'll add the test codes, though I cannot do it right now.
I haven't written it yet, so I'm making this PR as a Draft.

> If you don't have access to Adobe Animate or some other AS3 compiler I can write them for you.

Don't worry. I'm an ex-flash developer, so I think I understand Flash and AS3 stuffs pretty well. 😆

**Comment by paq** [comment]
I'm soryy. There was a misunderstanding in the previous statement. 
I meant to write flash "game" developer, not flash developer, and I'm not affiliated with adobe.

**Comment by paq** [comment]
I've added some tests.

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
