### PR TITLE
Implement a timeout for script execution, defaulting to 15 seconds

### LINKED ISSUE #554: 600kb swf uses 50gb+ of memory
I don't know what the cause is, but this swf will just eat all of the memory available to the system and not load (or perhaps will eventually load given enough time and memory): https://www.newgrounds.com/portal/view/1734/format/flash?emulate=flash

This happens in desktop, but it crashes much sooner in web (possibly same issue but the browser isn't letting it get that bad)

### PR DESCRIPTION
**Pull request by Dinnerbone**
This doesn't implement any kind of user prompt to continue execution, I just want to fix exporter hanging on scripts that infinitely loop. We can open an issue for that.

This also doesn't respect the timeout encoded within swfs - it doesn't seem like the flash player actually respects it? How should we handle that?

Fixes #554

### CODE REVIEW

**Comment by Herschel** [comment]
My local copy of CS6, at least right now, obeys the timeout limit set in the SWF. I don't know if we should respect it anyway (15 seconds might even be too long of a default...!)

**Comment by ROBERT-MCDOWELL** [comment]
this can also be set in CS6, on some computers sometimes it takes more than 60s when AV devices are detected.

**Comment by Herschel** [comment]
Thanks!

The only bummer here is that this adds a check to the inner VM loop; unfortunately I'm not sure of a better way to do this on web. Might be good to know how much this could affect performance (particularly if Instant calls out to JS on he web side).

**Comment by Dinnerbone** [comment]
Hmm that's a great point, I think it does. Ideally we'd have another thread jump in and stop it after a schedule but that's not an option yet.

Perhaps we can rate limit the check, every so many operations - realistically it's going to be used in infinite loops where they'll be spewing a lot.

**Pull request merged**
