### PR TITLE
wgpu: Use intermediate non-sRGB frame buffer

### PR DESCRIPTION
**Pull request by Herschel**
By default, Flash does rendering and alpha blending directly in sRGB space. When you request an sRGB surface format, this does blending in linear space, which causes the resulting colors to be incorrect. This became apparent when we switched the surface format to `Surface::get_preferred_format` in #6292.

If the surface format is sRGB, then render to an intermediate non-sRGB frame buffer and then copy over to the surface doing the color space conversion in the process.

 * Use non-sRGB intermediate render target when surface is sRGB.
   * Ideally we could directly request a non-sRGB surface when possible, but this varies by platform+backend and wgpu currently doesn't provide a good way to determine which surface formats are allowed (https://github.com/gfx-rs/wgpu/issues/1925).
 * Don't create these intermediate buffers if they aren't necessary (no MSAA, surface is linear).
 * Use BlendState::ALPHA_BLENDING const instead of writing out the blend states.
 * Disable depth writes on all pipelines (we don't use depth buffer).

Incorrect ([65d58f4](https://github.com/ruffle-rs/ruffle/commit/65d58f4733c6181152d262d25f383a6a0a87c72b)):
alpha-bad

Correct:
alpha-good

Flash:
alpha-flash

SWF:
[alpha.zip](https://github.com/ruffle-rs/ruffle/files/8497140/alpha.zip)

### CODE REVIEW

**Comment by Herschel** [comment]
@torokati44 Could you test this out on your platforms?

**Comment by torokati44** [comment]
Sure, I'll try to test them later today.

**Comment by torokati44** [comment]
Not off to a great start...
image

**Comment by torokati44** [comment]
Oh, I suppose the zipped `.swf` is just out of date compared to your screenshots.

**Comment by Herschel** [comment]
Whoops, sorry! I updated the SWF zip and screenshots in the OP.

**Comment by torokati44** [comment]
Can confirm that the example SWF in the desktop application now looks "correct" on all 8 of `[OpenGL, Vulkan] x [software, hardware] x [Wayland, XWayland]` combinations, and the window is no longer transparent at all anywhere.
At least on my particular setup, with the surface format[s] it prefers to choose by default, on KDE Plasma.
Haven't tested native `X11`, but I doubt it would make a difference.
Also TBD is the Android platform, which I'm getting to next.

**Comment by torokati44** [comment]
Yep, this also turns the sample from "incorrect" to "correct" in the Android app as well.
Not entirely sure which WGPU backend, but I bet it's Vulkan.

**Pull request merged**
