### PR TITLE
canvas: Use canvas drawing commands for gradients

### LINKED ISSUE #6969: Amorphous+ - Newly loaded sprites flicker for a few seconds, only with canvas renderer
### Describe the bug

SWF: [Amorphous+](https://cache.armorgames.com/files/games/amorphous-plus-2044.swf)

When loading this SWF in the online demo, the game itself works as intended, but some sprites flicker.

It seems to me that it happens for sprites for at most 5 seconds from the first time they are loaded, and after that all future uses of the same sprite don't flicker anymore.

In the video you can see the red plus at the top-right of the menu screen flicker, the menu items as I hover over them (they change to their "hovered" sprite), the player character, and also the green enemies.

https://user-images.githubusercontent.com/26556598/168320439-41938695-8c19-43e6-9d17-f2b91b324753.mp4

The game also runs very slow which is apparent in the video, as opposed to the same SWF running on native flashplayer on the same machine which is considerably faster. This is not the main point of the issue but if it can be profiled somehow it would be awesome

### Expected behavior

Expected the red plus to stay visible at all times, the menu items to switch to a hovered state without disappearing, the player character to be visible, and also the green enemies always come from beyond the edge of the screen so you can see that 2 of them appear in the middle of screen, because they were invisible and then suddenly rendered.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Edgium 101

### Additional information

Ruffle version: nightly 2022-05-13

Issue number: nice

### PR DESCRIPTION
**Pull request by Herschel**
This is an attempt to remove the SVG drawing paths from the canvas renderer. The SVG path is necessary because the canvas drawing API does not easily support all of the features Flash needs, such as arbitrarily transformed gradients. In those cases, we were falling back to generating an SVG image and drawing that to the canvas (SVG has all of the necessary features). However, this is problematic because the browser's loading of the SVG image is async, which causes a delay between when we create the shape and when we can actually draw it to a canvas (#6969). It's also quite a bit slower.

For the case of "simple" gradients (no skewing in the transform), we can use the `CanvasGradient` directly. For complex cases, we can push the gradient transform with `canvas.transform`, and then draw the path using the gradient transform's inverse. This should transform the gradient while still drawing the un-transformed path.

JSFiddle example:
https://jsfiddle.net/mwelsh/jundgr70/11/
Seems like this works on Chrome and FF (need to test Safari).

 - [x] For "simple" gradients, use standard `CanvasGradient` fills
 - [x] For "complex" gradients, use `CanvasGradient`, transform the canvas by the gradient matrix, then un-transform the path
 - [x] Handle repeat/pad modes (add extra color stops to mimic these?)

Fixes #6969.

### CODE REVIEW

**Comment by Herschel** [comment]
Actually I think I can use [`Path2D.addPath(path, transform)`](https://developer.mozilla.org/en-US/docs/Web/API/Path2D/addPath) to use Path2d even in the complex gradient case; if I pass the inverse of the gradient transform, the shape path would be untransformed.

**Comment by torokati44** [comment]
The game linked in https://github.com/ruffle-rs/ruffle/issues/6976 might also benefit from this (just cross-referencing).

**Comment by Herschel** [comment]
Ok, I think this is good now. A few issues popped up:
 * Linear RGB interpolation is unsupported. I don't think this is a big deal as it's not used often at all (sRGB is the default), and the gradient will still look decently close to what it should be.
 * The "repeat" and "reflect" spread modes are faked by adding a duplicating the color stops in the gradient. This was annoying because `CanvasGradient.addColorStop` throws an error if you give it values <0.0 or >1.0, so I had to scale up the gradient and chop up the (0.0, 1.0) interval to do this. It will also only mirror the gradient up to a certain # of times (I chose 25 times). Possibly a better solution is to consider the size of the path itself.
 * The "complex transform" technique doesn't work for strokes, because in HTML5 canvas, a transform will transform the entire stroke (including endcaps, etc.), compared to Flash which re-strokes using the transformed coordinates. This is actually a problem for all strokes in the canvas renderer; I'll fix this in a later PR.  For now I just always use the "simple transform" case for strokes.

**Comment by Herschel** [comment]
Took a look at #6976 in the canvas renderer, and that issue is related to masking; I'll look at that in a later PR as well (the way masking is handled in canvas needs to be improved).

**Comment by Toad06** [comment]
For some reason, there are many files that display the following warning, for instance in [Winter Bells](http://www.ferryhalim.com/orisinal/g3/bells.htm):
`Unable to create bitmap pattern for bitmap ID 76`

This prevents the related sprites from being displayed (in the case of Winter Bells, this affects the background). Refreshing the page "fixes" the issue unless the cache is disabled in the Network tab.

Tested in Firefox.

**Comment by Herschel** [comment]
Hmm, what Firefox version/OS? Not getting it on my side, but it might be a similar issue (image loading being async vs. the renderer wanting to be sync).

**Comment by Herschel** [comment]
I see it now in Firefox too, thanks! This is a similar problem with bitmap loading being async vs. the renderer wanting to be sync. Going to see if I can shoehorn it to work in Firefox for now, but ideally we want a way to handle this, either making `register_bitmap` async (scary) or using some other method to register the bitmaps (making separate canvases with `putImageData`?)

**Comment by Herschel** [comment]
Ok, this is the time for deleting half of the canvas backend. :-) I gutted out `BitmapDataStorage::ImageElement` which was the code path used sometimes for registering JPEGs. Instead this now uses only the `CanvasElement`, which is thankfully both simpler and synchronous, and the bitmaps should render now! It may be slower to decode the JPEGs on the Rust side instead of relying on the browser, but we were `base64`ing these JPEGs anyway, so it's likely a wash.

**Comment by Toad06** [comment]
This is also working on my end. 👍

Just observed a very, very minor issue on the [Orisinal main page](https://www.ferryhalim.com/orisinal/): a few pixels in the top left corner of the small pics can sometimes be unexpectedly white (or transparent?).

With this PR:
frogB

Nightly 2022-05-16:
frogG

**Comment by Herschel** [comment]
Hmm, that's odd, I'm not seeing that on my side on either the current master or this PR.

**Comment by Herschel** [comment]
Scratch that, I see it now, thanks!

**Comment by Herschel** [comment]
Hopefully fixed now.

**Comment by Toad06** [comment]
Yes, this is also good on my end. 👍

**Pull request merged**
