### PR TITLE
web: Add options to allow file autoplay

### LINKED ISSUE #429: There should be a way in js to start (and stop) 'Play'
web-player:
When a swf-file is handled by ruffle, it needs to be started manually by clicking on it.
There should be a way to start it from javascript (and may be stop it again).

See i.e. www.webgeo.de/k_024_en/

### PR DESCRIPTION
**Pull request by Toad06**
This PR implements file autoplay with several options, including a global behavior and a per-file behavior.
This can be useful for sites using many Flash files on a same page.

For instance, a user with a site full of Flash animations as part of the webdesign may want them to autoplay. However, a few other files would require a specific behavior, especially games and very small or invisible files. So he may write the following:

```
<script>
window.RufflePlayer.config = {
	"autoplay": "always"
};
window.RufflePlayer.config.files = {
	"GameWithSoundEffects.swf": { "autoplay": "never" },
	"InvisibleAudio.swf": { "autoplay": "autodetect" }
};
</script>
```

All files would then autoplay but "GameWithSoundsEffects.swf" and "InvisibleAudio.swf": "GameWithSoundEffects.swf" would require a click on the "Play" button; "InvisibleAudio.swf" would require a click anywhere on the page.

-----

Possible values for "autoplay" are:
- "never": The user must click on the "Play" button to play the file. This is the default behavior.
- "always": The file will autoplay. The user should be aware that this may introduce issues with audio.
- "usergesture": A user gesture is required to play the file but it can be done anywhere on the page, not specifically on the "Play" button. Any Flash file available in the DOM and using this behavior will then start.
- "autodetect": Ruffle tries to detect if it is safe to autoplay the file, checking if the browser allows autoplay. If it is, then the file is autoplayed, otherwise a user gesture will be required somewhere on the page.

Demo:
[demo.zip](https://github.com/ruffle-rs/ruffle/files/5210537/demo.zip)

Would resolve #429 (unless a way to stop files is really a mandatory thing).

### CODE REVIEW

**Comment by Herschel** [comment]
Thanks for giving some love to the JS side!

I'm not sure if we need to allow specifying per-SWF settings for the polyfill. I feel like a single global setting should suffice for most cases, and if someone needs that level of control, they probably want to use the pure JS API. (any thoughts, @Dinnerbone ?)

Another possibility is allowing our own custom parameters in the object/embed tags, but I don't know if this is really necessary either.

For autoplay/audio, I think we should only consider gestures on the Ruffle player itself, not anywhere on the page. The best might be if we display a "Click to unmute" overlay if audio is prevented from playing.

**Comment by Toad06** [comment]
Thanks for the feedback.

The PR has been made with full Flash-based websites (cut into several parts) in mind (even though I admit they're probably rare these days) and also thinking that the global and per-SWF settings could eventually be extended to other options in the future (eg. setup a custom Play button, hide the right-click context menu, etc.).

Just to be sure, the PR also covers the JS API, using the same setup as in the first post.

Good idea for the unmute overlay, especially for Safari mobile I think.

**Comment by Dinnerbone** [comment]
I'm very hesitant about the per-swf config in the global config, using filename as key. It breaks a few API principles and I'm worried that it's going to be a potential pain point. We're essentially splitting the setup for a single thing into two different places, and that's never a good thing.

I don't think we should add any custom elements/attributes to the polyfill, so we shouldn't solve it that way. That does mean that, for these cases, they would have to use the API. However, would that be so bad? At the point where you're doing more than Flash allowed, why limit the setup to what Flash required? At the very least I'm sure they could use the polyfill and then get it and `.doSomething()` or whatever they want to do, with `<script>getElementById('flashthing').doSomething()</script>`.

I vote to remove the swf specific config. Allow it to be set through the JS player API.

For the API proposed in this PR, I think we'd probably want more options but at the same time I'm really worried about solving usecases that don't exist, and locking ourselves into supporting a complex API long term. If we add a `play` method, it puts the power into the hands of the website owner and allows our API to stay modest.

I'd probably rename `usergesture` into `pageClick` because I had to look up what exactly constituted a gesture. It wasn't what I expected. That also then solves the 'gesture on swf' question because, well, the default value is to click on the swf.

I'm also thinking about if `autoplay` is the right term for this. `autoplay: autodetect`? If we go with something like `playOn`, it could allow: `playOn: 'click'` (autoplay: never), `playOn: 'pageClick'` (autoplay: usergesture), `playOn: 'load'` (autoplay: always), `playOn: 'allowed'` (autoplay: autodetect, 'allowed' meaning 'the browser allows us').

What do you think?


(I love API design and I'm excited to finally discuss it 😉 Thanks for this PR, @Toad06!)

**Comment by Toad06** [comment]
Thanks for your comments Dinnerbone, appreciated!

I'll remove the per-SWF config, as it's an horrible thing. :)
I'm also OK with the renamings, I agree the ones you suggested are way more explicit.

As a completely different approach, I wonder if we could just have some light event listeners (for instance when an instance of RufflePlayer is created) and add some methods (like "play", as Dinnerbone suggested). This way, Ruffle wouldn't integrate options anymore, it would be up to the website owner to write the appropriate code. This would give more control and be easier for us to maintain (I think!).

So, a global configuration for both the polyfill and the API could look like this:
```
<script>
RufflePlayer.config.onplayercreated = PlayerCreatedGlobal;

function PlayerCreatedGlobal(ruffle_player, container_dom, file_url) { // Ruffle would provide these arguments
	switch (file_url) {
		case "file.swf":
			ruffle_player.play();
			break;
		default:
			container_dom.style.backgroundColor = "yellow";
			break;
	}
}
</script>
```

The API could also permit a specific configuration, overwriting the global behavior if defined:
```
<script>
let player = ruffle.create_player();
player.onplayercreated = function(ruffle_player, container_dom) { // same idea };
</script>
```

**Comment by Herschel** [comment]
I agree with minimizing the API surface area; it's easy to add things to the public API, but hard to take away, and adds more burden for maintenance. So let's keep it simple until we see actual use cases.

Let's start with only global settings on the `window.RufflePlayer` object. Per-instance settings can be set via the JS API on a `RufflePlayer` instance.

I prefer `autoplay` to `playOn`, it seems clearer and matches HTML5 audio/video APIs.
For autoplay, these 3 settings:
 * `auto`: the default, auto-plays if audio context allowed by browser, otherwise shows play button.
 * `on` or `true`: auto-play, doesn't display play button, may play without audio at first.
 * `off` or `false`: display play button

The `userGesture` option doesn't seem necessary to me; the Flash should either auto-play or not. Instead, I'd rather just display a "click-to-unmute" overlay if the audio context is blocked, similar to Twitch:
image
There could be a separate option to control displaying this, `displayMuteOverlay` or similar, and it could default to on.

**Comment by chichilatte** [comment]
I'd love to be able to pass a config object to the player on creation...

    window.RufflePlayer.newest().create_player( {playOn: "load"} )

Or maybe more suitable when specific to a stream?

     player.stream_swf_url("my.swf", {playOn: "load"} )

Feels much simpler for such a commonly used feature than messing around with callbacks, events or awaits. But i appreciate it's tough finding a solution for all the ways Ruffle is used!

Right now I'm making do with hacking `ruffle.js` functions `ensure_fresh_instance()` and `stream_swf_url()` to hide the `play_button` and play immediately.

**Comment by Toad06** [comment]
Is there a way to access to the AudioContext object? This would be useful for the unmute button to display/hide accordingly and possibly also for `autoplay: auto` (currently a temporary AudioContext object is created).

**Comment by Herschel** [comment]
On the Rust side, a `Player::audio` can return the audio backend; so you'd need to add a getter method to `Ruffle` in `web/lib.rs` to expose this to the JS. And you'll need to add a getter method to get the context state to `WebAudioBackend`.

I think you'll want something like:
```
    #[wasm_bindgen(getter)]
    pub fn audio_state(&mut self, swf_data: Uint8Array) -> Result<AudioContextState, JsValue> {

        INSTANCES.with(|instances| {
             let instances = instances.borrow();
             let instance = instances.get(self.0).unwrap();

             let audio = instance.audio().downcast_mut::<WebAudioBackend>();
             // From here you can ask the WebAudioBackend for info.
        })
    }
```

You can msg me on Discord if you have questions about the Rust side, thank you! (Sorry for the delay in responding!)

**Comment by Toad06** [comment]
Thanks! Unfortunately, I'm getting these errors when compiling:
```
error[E0412]: cannot find type `AudioContextState` in this scope
   --> web\src\lib.rs:175:67
    |
108 | impl Ruffle {
    |     - help: you might be missing a type parameter: `<AudioContextState>`
...
175 |     pub fn audio_state(&mut self, swf_data: Uint8Array) -> Result<AudioContextState, JsValue> {
    |                                                                   ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `AudioContextState` in this scope
   --> web\src\lib.rs:175:67
    |
175 |     pub fn audio_state(&mut self, swf_data: Uint8Array) -> Result<AudioContextState, JsValue> {
    |                                                                   ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `audio` found for reference `&std::cell::RefCell<RuffleInstance>` in the current scope
   --> web\src\lib.rs:181:35
    |
181 |              let audio = instance.audio().downcast_mut::<WebAudioBackend>();
    |                                   ^^^^^ method not found in `&std::cell::RefCell<RuffleInstance>`

error: aborting due to 3 previous errors
```

I've tried to fix them but it actually makes things worse, whoops... Sorry for being that noobish! 👶

However I went ahead and implemented the JavaScript part. So currently, `autoplay` works when it's set to `on` or `off`; `auto` will need to check the AudioContext.state. `displayUnmuteOverlay` is implemented as well but will also need the AudioContext.state to hide or display accordingly.

Both polyfill and JS APIs support global configuration:
```
window.RufflePlayer.config = {
	"autoplay": "auto", // <- also the default behavior in Ruffle
	"displayUnmuteOverlay": "on" // <- also the default behavior in Ruffle - only when "autoplay" is "on"
};
```

The JS API also supports per-instance settings. If an option is not set here, the global one will be used if it exists, otherwise the default Ruffle's setting will be used.
```
let player = ruffle.create_player({
	"autoplay": "on",
	"displayUnmuteOverlay": "off"
});
```

Unless changes are requested now, here are the things that would be needed to complete the implementation:
- accessing the `AudioContext.state` property.
- calling the `AudioContext.resume()` method when the unmute overlay is clicked.
- using the `AudioContext.onstatechange` event, as the browser may resume audio even if the user has clicked anywhere on the page but the overlay.

These TODOs are all in the `ruffle-player.js` file.

**Comment by Herschel** [comment]
Thanks for the patience, I'll try to take a look at this over the weekend!

**Comment by Herschel** [comment]
Thank you! I added a `Ruffle.audio_context()` method to the JS side that returns the AudioContext. I haven't looked over everything too much yet but this should be enough to let you test and verify that everything works. One issue I was worried about is if use_unmute_overlay might run a little too soon, before the AudioContext is created; it might need to run after the instance is created.

**Comment by Toad06** [comment]
Thanks a lot for your work and help! 😉

I'll do the testings tomorrow on various browsers and devices and let you know if everything is fine.

**Comment by Toad06** [comment]
OK, I've done some testings on Windows (Firefox and Chrome), Android (Chrome) and iPadOS (Safari). I've fixed/changed some things.

- The config was set before the instance was actually created. Things that relied on AudioContext checks didn't work as expected. I think this is what you've noticed in your last post.

- In Firefox (on Windows at least), `AudioContext.state` is always "suspended" when the object has just been created. It may change by itself to "running" some milliseconds later. So if the state is suspended, we wait some milliseconds before applying the config.

- When `autoplay` was set to "on" and `displayUnmuteOverlay` to "off", it wasn't possible to resume audio. An invisible overlay is now displayed to resume audio when clicked.

Here's a demo:
[demo-autoplay.zip](https://github.com/ruffle-rs/ruffle/files/5409878/demo-autoplay.zip)
(it's possible to change the config on page load, using for instance: `demo-autoplay.html?autoplay=on&overlay=off`)

**Comment by Toad06** [comment]
> When `autoplay` was set to "on" and `displayUnmuteOverlay` to "off", it wasn't possible to resume audio. An invisible overlay is now displayed to resume audio when clicked.

I was wondering if it wouldn't be better to provide an `audio_resume` method or something similar, instead of doing this?

**Comment by Dinnerbone** [comment]
@Toad06 I was a bit daunted by rewriting my Typescript branch onto this, so I did it the other way around. I hope that's ok? Would you mind testing to see if it's still good? It's mostly the same code but I simplified it a bit.

https://github.com/ruffle-rs/ruffle/pull/1556

**Comment by Toad06** [comment]
No worries at all, that's great! 👍 I don't know Typescript anyway.
I'll try your PR, does it need new requirements to compile?

**Comment by Dinnerbone** [comment]
Make you do `npm run bootstrap` again and it should build just fine!

**Comment by Herschel** [comment]
Subsumed by #1556, thanks for fleshing out the APIs!

**Pull request closed without merging**
