### PR TITLE
ci: Run nextest with profile "ci", add a test-specific override to allow retries for `avm2/pixelbender_shaderdata`

### PR DESCRIPTION
**Pull request by torokati44**
I'm not saying this is a nice solution (because it's not at all), but the flaky CI annoyed me too much...
Somewhat related: https://github.com/ruffle-rs/ruffle/pull/17385

### CODE REVIEW

**Comment by Dinnerbone** [comment]
but it has hit other tests too... :(

**Comment by torokati44** [comment]
But wasn't that super-duper rare...? :|

**Comment by torokati44** [comment]
Okay I guess we could perturb the test order and see if anything changes...

**Comment by Dinnerbone** [comment]
> But wasn't that super-duper rare...? :|

I mean, we've noticed this for a few days, and it's happened at least once. Scaling that up, that means at least one flake per 3 days.

maffs.

**Comment by torokati44** [comment]
> Scaling that up, that means at least one flake per 3 days.

At _least_, or at _most_? :thinking:

Anyway:
https://github.com/torokati44/ruffle/commit/3841deb3e21ef26969e76d52c7404471ddf6af85
https://github.com/torokati44/ruffle/actions/runs/10334595741

**Comment by torokati44** [comment]
In light of the previous comment, what do you think now, @Dinnerbone?

**Comment by Dinnerbone** [comment]
Sure thing, go for it!

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
