### PR TITLE
avm2: Add tests for looking up properties on Class objects

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by adrian17** [comment]
I don't think this is correct. These should be accessible on the class object's vtable as-is, there shouldn't be a need to copy them to dynamic properties.
In fact, I would have sworn your test SWF would have worked already in Ruffle, as of the vtable refactor or earlier. I'll take a look at it.

**Comment by adrian17** [comment]
And yeah, the failing test is essentially:

```as
class MyClass {
	public static var pubVar;
}

var obj:Class = MyClass;
obj.setPropertyIsEnumerable("pubVar", true);
trace(obj.propertyIsEnumerable("pubVar")); // false in FP

obj.asdf = 1;
obj.setPropertyIsEnumerable("asdf", true);
trace(obj.propertyIsEnumerable("asdf")); // true in FP
```
The first is `false` because there's no dynamic property so setPropertyIsEnumerable fails.

**Comment by adrian17** [comment]
> In fact, I would have sworn your test SWF would have worked already in Ruffle, as of the vtable refactor or earlier. I'll take a look at it.

Actually... yeah, the test passes without your changes in `class_object.rs`.

**Comment by Aaron1011** [comment]
Interesting - it looks like the Starling issue I was debugging was actually caused by something else (unimplemented XML methods), but I interpreted it as class object properties being unimplemented.

**Comment by Aaron1011** [comment]
@adrian17 I've updated the PR to just add tests for the existing behavior.

**Review by adrian17 — APPROVED** [review]

**Pull request merged**
