### PR TITLE
avm1: Implement TextField.textColor (close #1863)

### LINKED ISSUE #1863: problem with text color on Yojijukugo Flash (四字熟語 Flash)
With Ruffle, text of panel is displayed in not BLACK but GREEN.
I tested with Ruffle Nightly 2020-12-06 on Windows 10 Home 64bit.

Yojijukugo Flash (四字熟語 Flash): https://www.gamedesign.jp/flash/yojifla/yojifla.html

Adobe Flash Player 32:
capture_06122020_191757

Ruffle Nightly 2020-12-06:
capture_06122020_191912

### PR DESCRIPTION
**Pull request by JMcKiern**
This PR adds the TextField.textColor property (cc #280). It also closes #1863.

I used the `with_text_field_props!()` macro to add the property. The only difference I could see between using `attach_virtual_properties()` and `with_text_field_props!()` is with the `attributes` of the object's property. I couldn't find any resource to explain these and both methods worked equally well in my testing. I went with the `with_text_field_props!()` solution since it was cleaner. If this is incorrect, I can change it.

### CODE REVIEW

**Comment by Herschel** [comment]
Looks great, thank you and welcome!

**Comment by JMcKiern** [comment]
Thanks!

Any chance you could briefly explain what's going on with `attach_virtual_properties()` and `with_text_field_props!()`?

**Comment by Herschel** [comment]
I think `attach_virtual_properties` is actually a mistake; looks like it assumes that the properties are directly to the TextField object, but all(?) of these properties should be attached to the prototype instead, which is what `with_text_field_props` does.

**Comment by JMcKiern** [comment]
Ah ok, that makes sense. Thanks

**Pull request merged**
