### PR TITLE
Update swf/README.md

### PR DESCRIPTION
**Pull request by Zageron**
- Remove invalid references to docs and crates.io
- Correct dependency line.

### CODE REVIEW

**Comment by relrelb** [comment]
IMO we should keep the crates.io badges, and just publish `swf` once in a while. Maybe we can even publish it nightly as part of CI.

**Comment by Zageron** [comment]
> IMO we should keep the crates.io badges, and just publish `swf` once in a while. Maybe we can even publish it nightly as part of CI.

FYI, the swf crate is not ruffle's swf crate. (It is someone elses)
Thought I totally agree, I would rather use a crate than a git reference.

**Comment by n0samu** [comment]
> FYI, the swf crate is not ruffle's swf crate. (It is someone elses)
Hmm, it looks like @Herschel never moved it to the Ruffle org, although [the cargo.toml was updated to point to it](https://github.com/Herschel/swf-rs/commit/e788381200039530cbe551700a62ca3ced30b522)

**Comment by Herschel** [comment]
Eek, yeah, we should add the org as an owner of this crate and publish a new version. I'll do that this week.

**Comment by Herschel** [comment]
Sorry for the delay here, new version of `swf` published in #7670, thank you!

**Comment by Zageron** [comment]
Awesome thank you!

**Pull request closed without merging**
