### PR TITLE
Throw appropriate errors when recursing too deep in functions or properties

### PR DESCRIPTION
**Pull request by Dinnerbone**
Here's a fun fact! This is actually relied on by anything that uses MX. It turns out that MX has an infinite loop with `watch()` in the `enabled` property, something that nobody notices because flash silently stops after so many tries. `enabled = true` calls a method which, ultimately, calls `enabled = true`.

Unfortunately, in debug mode I cannot get Ruffle to recurse as deep as 256, I'm panicking around 97. ~It's fine when `opt-level` is at least 1, so I've made debug mode run with that for now.~

### CODE REVIEW

**Comment by Herschel** [comment]
Oof, maybe it was a bit premature to move away from managing our own stack.  Instead of defaulting opt-level to 1, I think it'd be better to skip these tests in debug builds: `#[cfg_attr(debug_assertions, ignore)]` (I just worry about my debugger getting even more confused than it already is with any optimization).

Also, ostensibly the ScriptLimits SWF tag can change these recursion limits, although last time I tried it had no effect. I'll try again and report back.

**Comment by Herschel** [comment]
Looks like indeed changing the recursion limit/timeout limit in the ScriptLimits tag affects this. (Not sure what I did wrong when I tried this a few months ago and nothing happened).

In the IDE, you can change the timeout in File->Publish Settings, but there doesn't appear to be a way to change the recursion limit; I had to hex edit the SWF to do that. I guess the MX case you mention would just explode if you happened to have a big ScriptLimits?

In any case, I don't think it's a huge deal for now, so I'm okay with merging in this PR -- but maybe a TODO to keep in mind for the future.

**Comment by Dinnerbone** [comment]
Oh I totally forgot about ScriptLimits... maybe I can use that to limit this test to something like 40 levels, and keep it in the standard test rotation. I'll take a look.

(looking at how many flash files use ScriptLimits, there's 14,142 of 83,462 in the newgrounds collection that contains at least one. Some have up as much as 9 ScriptLimits... huh)

**Comment by Herschel** [comment]
I think certain flavors of the IDE always output a ScriptLimits tag, but I think generally they will be the default value (15sec/256 recursions?)

**Comment by Dinnerbone** [comment]
I've add ScriptLimits support (for depth only) and used that to make the test pass in debug without any optimisations, so I've popped that commit off too.

**Pull request merged**
