### PR TITLE
Update to wgpu 0.18, naga 0.14, naga_oil 0.11, egui 0.24.1

### PR DESCRIPTION
**Pull request by torokati44**
~~Currently blocked by, and~~ mostly based on: https://github.com/emilk/egui/pull/3505
~~EDIT: This is now merged, waiting for a new release.~~
EDIT: egui 0.24 is now out.
 
~~Also blocked by https://github.com/bevyengine/naga_oil/pull/63, which is in turn, by https://github.com/gfx-rs/wgpu/issues/4569~~.
~~EDIT: The latter is now merged, also waiting for a new release.~~
~~EDIT: A backport of the  latter is in v0.18: https://github.com/gfx-rs/wgpu/pull/4693~~
EDIT: naga_oil 0.11.0 and wgpu-core 0.18.1 are now out with these fixes.

Feel free to force-push this branch if any of you continue working on this!

### CODE REVIEW

**Comment by torokati44** [comment]
Some remaining issues:
 - The Windows CI runner sometimes gets stuck and the job is terminated after a few hours. I don't know which test causes this.
 - The close button (X) of the desktop player window doesn't work - probably sends a different event now that we are not handling yet.
 - I'm not entirely sure about all those added `..Default::default()`-s. I think they are fine, but also maybe some fields are still also explicitly set to their defaults, which could be cleaned up.

**Comment by Aaron1011** [comment]
The close button issue will be fixed by https://github.com/emilk/egui/pull/3627 (though we can easily work around it on our end if we want)

**Comment by torokati44** [comment]
Marking as draft for a short time again, see the comments under https://github.com/gfx-rs/wgpu/pull/4778.

**Comment by torokati44** [comment]
I haven't seen the Windows CI runner failure for a while now.
The close button (X) is fixed.
I'll leave the judgement of the `..Default::default()`s to the reviewers. It's at least not worse than it was.
The `web-sys` situation is resolved.

**Pull request merged**
