### PR TITLE
Revert "ci: Temporarily pin to Node 22.4"

### PR DESCRIPTION
**Pull request by danielhjacobs**
Reverts ruffle-rs/ruffle#17169

### CODE REVIEW

**Comment by danielhjacobs** [comment]
Waiting on Node 22.5.1 to be added to https://github.com/actions/node-versions/releases/

**Comment by torokati44** [comment]
It's on there now.

**Comment by danielhjacobs** [comment]
Still falling, we may need the manifest update: https://github.com/actions/node-versions/pull/182

**Comment by torokati44** [comment]
Yeah, that's possible.

**Comment by torokati44** [comment]
This is finally unblocked.

**Review by torokati44 — APPROVED** [review]

**Pull request merged**
