### PR TITLE
Add additional Flash MIME types

### PR DESCRIPTION
**Pull request by Justin-CB**
Apparently, there are at least 2 more flash MIME types. I don't know the prevalence of them, & there may also be MIME types with the version attached with a semicolon. I undid my changes to dynamic embeds, but I added undoing them as a commit, in case there's any confusion.

### CODE REVIEW

**Comment by Justin-CB** [comment]
I also added .DS_Store which are created automatically by the Mac OS X Finder to the .gitignore

**Comment by Herschel** [comment]
Good catch! Could you rebase your changes onto master? Your PR contains unrelated commits from your previous PR. Ideally it should only be commits 182cf12 and dd95d6d.

[You can add .DS_Store to your global gitignore config instead, as this is often preferred to adding it to the repo .gitignore.](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c)

Thank you!

**Comment by Herschel** [comment]
Also, if we can find instances of these MIME types used on the web in the wild, it'd be helpful for testing.

**Comment by Justin-CB** [comment]
I've rebased.

**Comment by Justin-CB** [comment]
182cf12 was undoing my changes to the polyfill code, so it should probably just be this commit.

**Comment by Herschel** [comment]
Thanks!

**Pull request merged**
