### PR TITLE
wgpu: Fix gradient regression

### PR DESCRIPTION
**Pull request by torokati44**
This fixes some regressions introduced in #9821.

There were two problems:
 - The computation if `a` (the lerp parameter) could underflow  `u8`.
 - The `last` variable was not set to the index of the last record after the ratio of the last record was surpassed.
 
~Regression tests to follow soon.~
Thanks to @AllinolCP for the repro case, which served as the basis of the visual regression test!

### CODE REVIEW

**Comment by torokati44** [comment]
While we already have a regression test for simple radial gradients, the critaria for failures were:
The first record was not at ratio `0` and/or the last record was not at ratio `255`.
The test added now also covers linear/srgb interpolation.
But it seems a bit unorganized to just put it where it is, in itself.

**Comment by AllinolCP** [comment]
off topic:
> Thanks to @Allinol (on Discord) for the repro case, which served as the basis of the visual regression test!
hi so @Allinol is actually my alt

**Comment by n0samu** [comment]
I can confirm that this fixes gradient regressions in Nanaca Crash, Papa's Burgeria, and Bob the Robber - thank you!

However this does not fix the regression I observed in Ninja Painter. When hovering over the Main Menu button on the level select screen, here is what it is supposed to look like: 
image

But here's what it looks like ever since Dinnerbone's PR was merged:
image

Here is the SWF: http://i.notdoppler.com/files/ninjapainter.swf

**Comment by torokati44** [comment]
I think ninjapainter issue is fixed, would you please be so kind as to re-test all regressions?

**Comment by torokati44** [comment]
(Another set of changes pushed, sorry.)

**Review by Dinnerbone — APPROVED** [review]

**Comment by torokati44** [comment]
Thanks for testing, @Bale001 and @n0samu (and others)!

**Pull request merged**
