### PR TITLE
avm1: Implement MovieClip.setMask - #17 #263

### PR DESCRIPTION
**Pull request by davidar**
This fixes some (but not all) of the rendering bugs in #1098 

@Dinnerbone offered to make some tests as I have no idea where to even start with that

### CODE REVIEW

**Comment by Toad06** [comment]
👍

This also makes [Bill The Demon](https://www.y8.com/games/bill_the_demon) playable (just remains an issue with yellow background on some objects, but this may be unrelated to this PR?).

**Comment by Herschel** [comment]
Thank you and welcome!

Some issues from me eyeballing it:
 * A masker clip should no longer be visible. (i.e. after `mc1.setMask(masker)`, masker should no longer render normally).
 * A masker clip can be anywhere in the display hierarchy, but needs to render at the correct position. For example, `mc1.setMask(_root.mc2.mc3.masker);` works, so need to verify that this renders at the proper position. I expect there needs to be something like this before rendering the mask:
     ```
    context.transform_stack.push(Transform {
            matrix: masker.global_to_local_matrix() * self.local_to_global_matrix();
            ..Default::default(),
        });
    ```
 * A clip may only setMask one other clip, i.e. after `mc1.setMask(masker); mc2.setMask(masker);`only mc2 will be masked. So I suppose DisplayObject should also have a `maskee` field to be able to switch off a previous mask.
 * Will need to do some testing to understand how these interact with normal timeline masks; I believe if `mc2` was used as a timeline mask, `mc1.setMask(mc2)` will disable all of these timeline masks (changes clip_depth to 0?)

(Take this with a grain of salt because I haven't tested this yet! 😄 )

**Comment by davidar** [comment]
I think those first three issues should be fixed now, but I'll need someone else to do the testing for the last one

**Comment by Dinnerbone** [comment]
So I did some basic testing and the lesson for today is that you may only have one script-set mask, and it's AND'ed onto any authored mask.

Here's a test swf: http://media.dinnerbone.com/uploads/2020-11/files/test.swf


| Description | Flash | Ruffle |
| ----------- | ----- | ------ |
| Authored (left) mask only | image | image |
| setMask(right) | image | image |
| setMask(bottom) | image | image |
| setMask(null) | image | image |

**Comment by davidar** [comment]
Hm, that test.swf doesn't seem to be working for me (in either flash or ruffle), ruffle gives this error:

```
[2020-11-05T22:40:50Z ERROR ruffle_core::avm1] Prototype recursion limit has been exceeded
[2020-11-05T22:40:50Z ERROR ruffle_core::avm1] No more actions will be executed in this movie.
```

I think the problem is that I forgot to remove the maskee from the old masker when a new one is set, should be an easy fix.

**Comment by Dinnerbone** [comment]
I think my file uploader got confused and linked to an old test for something else. Here's a zip: [avm1_set_mask.zip](https://github.com/ruffle-rs/ruffle/files/5497862/avm1_set_mask.zip)

**Comment by davidar** [comment]
Thanks, fixed!

**Comment by Toad06** [comment]
I'm getting a crash in this [old Mario game](https://github.com/ruffle-rs/ruffle/files/5501786/mariocoin.zip) (web and desktop):

> panicked at 'already borrowed: BorrowMutError', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/cell.rs:867:31

I don't know why it panicks but I can tell that without the latest commit (https://github.com/ruffle-rs/ruffle/pull/1483/commits/1c8ca7cb75760a0ff66f11703cc81e3375ec7797), the game works as intended.

**Comment by davidar** [comment]
I'm not sure why it was being triggered by that game in particular, but removing the redundant write to the maskee field of the new mask seems to have fixed it.

**Comment by Toad06** [comment]
👍

**Comment by Herschel** [comment]
Thanks for your work on this!

 * Be sure to trace the `masker` and maskee` in `impl Collect`: `self.masker.trace(cc);`
 * In AS3 land, you can set a mask on any `DisplayObject` (https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/DisplayObject.html#mask), so let's move `masker`, `maskee`, `set_mask` to `DisplayObject` in anticipation of that.
   * For now, it's okay that only `MovieClip::render` renders using `masker`, since that's the only case in AS2. Eventually we'll want to reorganize things so there's a base `render` on `DisplayObject` that takes care of this consistently for all display objects (this might link up with the DisplayObjectContainer stuff).

**Comment by Herschel** [comment]
Fixed these two issues:
 * `clip1.setMask(clip2)`: If `clip1` was previously masking any timeline clips, these masks should be disabled (`clip.set_clip_depth(0);`).
  * Sample: [setmask-masker.zip](https://github.com/ruffle-rs/ruffle/files/5507313/setmask-masker.zip)

 * The mask was not rendered at the correct position in the case of nested clips, as described above: `clip1.clip2.clip3.setMask(_root.clip4.clip5);` needs to render `clip5` with the proper position.
  * Sample: [setmask-nested-clips.zip](https://github.com/ruffle-rs/ruffle/files/5507312/setmask-nested-clips.zip)

Could use some testing on these fixes.

This is still an issue but will take a little more work:
  * Non-movieclips should be allowed as maskers: `clip.setMask(button);`
   * Sample: [setmask-button.zip](https://github.com/ruffle-rs/ruffle/files/5507317/setmask-button.zip)
   * Need to split `render` into something like `render` and `render_self`
   * `render` does the common stuff; visibility checks, push transform, dynamic mask
   * `render_self` does the specific rendering for that subclass

**Comment by davidar** [comment]
Fixed:

image

The only thing I'm not sure about is whether the fact that EditText pushed a clone of the transform is a detail that should be retained?

**Comment by Herschel** [comment]
Holding off on this until #1347 is fixed, because it will probably change how masks are rendered a bit (i.e. the `context.allow_mask = true/false` lines will probably change).

Re: the visibility checks, I think this should include both culling and checking `display_object.visible()`, and probably all objects should do it; but lets keep it simple for this PR and not move it, and keep this PR only focused on masks.

**Comment by Herschel** [comment]
Sorry for the delay on this one; I'll get back to this, clean up the masking code, and merge this in.

**Comment by Herschel** [comment]
Ok, rebased this into the latest changes. I still have to fix a few things with the masking in general, but I'd rather get this in now so it's not just sitting in the PR queue. Thanks for the patience and work, @davidar !

**Pull request merged**
