### PR TITLE
core: Respect ratio field for non-morph shapes (fix #1291)

### LINKED ISSUE #1060: ridesims.com Taron Simulator Frame Skipping?
When playing a simulator on ridesims.com The Taron Simulator doesn't seem to like a variable being counted or it skips a frame? 

**Ways to reproduce this bug:**
https://ridesims.com/ride-simulators/Taron
Open up the Taron Sim, power on, maintenance mode, turn on the blocks, send the train, add another train (it doesn't mater what one), press up, press space to put it into the station and then your notice a change in the frames as if something has happened. (the bar go down and the simulator becomes useless) 

The code that's run when this happens is the following: 

onFrame (1828) {
    _root.ESTOPTrain1=0;
    if (_root.ESTOP==0 && _root.BlockA==0 && _root.HoldBlockF==0 && _root.SystemMode!=0  && _root.UnloadDispatch==1) {
        play();
        _root.BlockA=1;
    } else {
        stop();
        BLOCKCHECK.gotoAndPlay("BlockA");
    }

### LINKED ISSUE #1291: Handle PlaceObject ratio field for non-morph shapes
The "ratio" field in the SWF PlaceObject tag has additional behavior for movie clips: it specifies the initial frame that the object was created on. This is used when doing a rewinding goto to determine whether the clip should be recreated or reused.

When doing a rewind, the display object should be reused if new_id == old_id and new_ratio == old_ratio. Otherwise, it should recreated. This behavior isn't documented in the SWF specs; it only mentions this field being used for shape tweens. But this field serves the double purpose of handling rewind-gotos.

Currently Ruffle handles this implicitly; Ruffle manually stores the placement frame of a display object when it's instantiated, and uses this during rewinds to determine whether an object should be recreated. However, Ruffle always recreates the object in this case. In the official Flash Player, if an SWF had the ratio field was manually removed, the clip would not be recreated and would instead be re-used (the animation wouldn't restart).

The Flash IDE always seems to generate the appropriate ratio fields, so this isn't an issue in normal SWFs; however, it could occur in SWFs generated by third-party tools (maybe causing #1060?).

More info:
http://wahlers.com.br/claus/blog/hacking-swf-2-placeobject-and-ratio/

Thanks to @TylerGlaiel for tipping me off on this one.

Samples:
[frames.zip](https://github.com/ruffle-rs/ruffle/files/5360391/frames.zip)
frames.swf: Unmodified SWF. The clip never reaches the bottom right corner, because it gets recreated as the timeline loops back to frame 1.
frames_edited.swf: Hex edited to remove ratio field. The clips reaches the bottom right corner, because it does not get recreated; the ratio of both clips matches when the rewind happens, and the clip gets reused.

### PR DESCRIPTION
**Pull request by Herschel**
This changes the logic for rewind-gotos to respect the ratio field inside the PlaceObject tags. See #1291 for a full description.

Previously we would manually keep track of the placement frame for a display object whenever it was instantiated. A rewind would immediately remove all objects that were created after the target frame (because they should not exist on that frame). However, now we need to inspect the ratio field of the final PlaceObject tag to decide whether to remove an object; so now we defer the decision of whether to remove an object until after we churn through all the frames.

Still needs some more research+testing to verify this doesn't regress anything. I need to add a test case to verify the new behavior. My initial tests indicate this does fix #1060, which makes sense because this SWF is made by a 3rd party tool.

### CODE REVIEW

**Comment by Toad06** [comment]
There are some issues where things remain on screen while they shouldn't:

- In _DTunnel_ (https://www.newgrounds.com/portal/view/161144), click "Instructions", then "Back". The instructions will remain on screen.

- In _Honey Bunny_ (https://www.newgrounds.com/portal/view/182750), start a game. Press Up and get the yellow key, then go down and enter the "Sweet home". Click "Give honey", the button doesn't disappear while it should; click "Leave cottage", the game will resume but what is drawn on screen will not change, so the game becomes unplayable.

- In _Luigi's Day_ (https://www.newgrounds.com/portal/view/44505), start the game and fall in the water. The audio should stop (but  doesn't - that's a regression but doesn't seem to be related to this PR?). Click "Replay", the button will remain on screen.

- In _Ratman Ralph_ (https://www.newgrounds.com/portal/view/67006), when you click "Options" or "Instructions", then "Next" (at least one time) and "Close", the text remains on screen. However, the PR fixes the last issue described in #815.

**Comment by Herschel** [comment]
Thx for testing! Could you try again with the latest changes?

**Comment by Toad06** [comment]
Hmm, I'm still observing the same issues (is it because the PR seems to miss a piece of code from commit 04e3f1ecea9572801a92ac6596134fa5a174b5ba? I'm not seeing the `if is_rewind {` code in "movie_clip.rs").

**Comment by Herschel** [comment]
Whoops, you're right, I futzed up a rebase. Should be okay now.

**Comment by Toad06** [comment]
Almost all of the games above work as intended now! 👍 Only _Zed_ still has issues with transitions (for the audio stuff on _Luigi's Day_, I will open a bug report).

I've also tested other files, unfortunately it turns out some of the games by Ferry Halim have issues:

_Starry Night_ (http://www.ferryhalim.com/orisinal/g3/starry.htm)
No stars to light up appear.

_Critical Zone_ (http://www.ferryhalim.com/orisinal/g2/criticalzone.htm)
The game no longer works.

_The Bottom of the Sea_ (http://www.ferryhalim.com/orisinal/g3/sea.htm)
The more the character gets down in the water, the more the background gets truncated (or doesn't repeat itself).

**Comment by Herschel** [comment]
Thx for the testing!

Upon thinking about this some more, I think better would be to change `GotoPlaceObject` to be an enum with a `Remove` variant, and keep track of removes as well as gotos. For a rewind, we can initialize the goto command list with a remove for every current display object (because a rewind starts from an empty frame 1). This removes the need for the awkward "GotoPlacedObject" flag. I also think this will be more accurate for the order of clip unloading (we haven't really paid attention to this yet).

**Comment by Herschel** [comment]
Closing in favor of #5431.

**Pull request closed without merging**
