### PR TITLE
web: Add config to enable/disable context menu

### LINKED ISSUE #1972: Disable right-click menu on mobile
On many mobile phones, tap & hold is equivalent to right click. This opens the Ruffle menu. But many games also use a click & hold mechanic (e.g. [the classic Helicopter game](https://archive.org/details/helicoptergame_flash)). So, these games at the moment work perfectly on mobile devices, except for the menu appearing unwanted.

Proposed solution:
* disabling the menu on mobile

Other possible solutions:
* removing the right-click menu and moving it to a menu bar or something like that
* giving developers using the Ruffle library an option to disable the menu on right-click

### LINKED ISSUE #1977: Add options to disable right-click context menu
Similar to #1972, users may want to disable the right-click menu completely. Adding a JS config option for this would be useful.

`showContextMenu: true/false`

### PR DESCRIPTION
**Pull request by relrelb**
Fixes #1977.
This PR adds a new config called `contextMenu` that controls whether or not to show a context menu when right-clicking a Ruffle instance.
I did some refactors along the way, <s>including removal of the unused `Ruffle.prototype.config` member</s>.
A follow-up PR needs to handle #1972 by defaulting to `false` on mobile instead of always `true`.

### CODE REVIEW

**Comment by Toad06** [comment]
This doesn't work on my end on Firefox: `Uncaught TypeError: setting getter-only property "contextMenu"`
For some reason, renaming the `contextMenu` property to anything else in ruffle-player.ts prevents the issue from happening. Weird.

Also, I believe that removing the config stuff make codes like this one inoperative:
```
let player = ruffle.createPlayer();
player.config = {
   autoplay: "off",
   contextMenu: false,
};
```

**Comment by relrelb** [comment]
It doesn't happen on my end on both Chrome 88.0.4324.104 and Firefox 84.0.2. Can you please provide some more details (maybe you're not using the same versions)?
As for your second point you are right. I didn't know this is a possible use-case. Anyway it seems to me somewhat odd to have 3 distinct levels of of config (`window.RufflePlayer.config`, `RufflePlayer.prototype.config`, `RufflePlayer.prototype.load`). Maybe we should keep only the first 2 and remove the `config` parameter of `RufflePlayer.prototype.load`?

**Comment by Herschel** [comment]
Let's put the config refactorings in a separate PR and keep this one only for the context menu setting.

**Comment by Toad06** [comment]
I'm using the same versions, on Windows in case that matters. It actually works on Chrome, so the issue remains exclusive to Firefox. Ruffle crashes on this line: `this.contextMenu = this.shadow.getElementById("context-menu");`. It seems like there's a native `contextMenu` property in Firefox:

```
"use strict"
var p = document.createElement("p");
console.log(p.contextMenu); // null in Firefox, undefined in Chrome
p.contextMenu = "This will crash in Firefox";
```

If you run this sample in the Firefox console, does it trigger a TypeError?

**Comment by relrelb** [comment]
@Toad06 Thanks for your feedback! This should be fixed now. Can you please confirm?

**Comment by Toad06** [comment]
Yes, it's working perfectly on Firefox now. 👍

**Review by Herschel — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
