### PR TITLE
[web] slightly improved message about Ruffle (#1557)

### PR DESCRIPTION
**Pull request by ousia**
@Dinnerbone & @Herschel,

this could be the first step into a localized message about Ruffle (as displayed in the web extension).

Many thanks for your help.

### CODE REVIEW

**Comment by ousia** [comment]
Sorry for not providing what could be the `$(about)` variable (I don’t know how to do that).

I included `about` messages for English and Spanish.

**Comment by Dinnerbone** [comment]
Thank you for this!

I do think we'd want to handle this differently though, a few thoughts:
- We need this to work on web without extension, and we only provide translations on extension atm. This is a separate issue, we absolutely should have web translations, I want to investigate this after my big typescript refactor lands
- We should never translate something like: `translate("about") + " Ruffle " + version`, but rather something that can take parameters so that in languages where you might reorder the words or add stuff between "ruffle" and "version", that can be done.

I think we should hold off until we have a system for localisation on the web, which should be prioritized as I know there's many non-english speaking fans of Flash. Ideally we can back the actual translations with a service like Crowdin so everybody can go and contribute without needing to know how to program :D

**Comment by ousia** [comment]
> All that said - I'm all for adding "About ..." to the menu item. If you change this PR to just that, it'd be an easy accept I think!

@Dinnerbone, not sure that my first excursion on JS coding might be even right.

I hope at least that the `"about_ruffle"` might follow the basic idea of your second comment.

**Comment by Herschel** [comment]
Let's hold off on this until we have a better i18n system for the self-hosted JS, and the switch to TypeScript is complete. Hopefully you can help use with translations @ousia  :-)

**Pull request closed without merging**
