### PR TITLE
Move back to upstream wgpu repository

### PR DESCRIPTION
**Pull request by Aaron1011**
We're relying on unreleased changes, so we depend on the latest commit from their repository.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Upstream doesn't have the GL startup time fix yet, should do tomorrow when I get a chance to clean up the PR.

Does this run? Last time I tried to update us, the naga update broke our shaders, I suspect something with naga oil.

**Comment by danielhjacobs** [comment]
https://github.com/gfx-rs/wgpu/pull/3380 is in master now. Probably best to switch to the latest commit to pull that in too.

**Comment by danielhjacobs** [comment]
That commit was apparently after another naga bump, which is probably what's causing the new CI failures: https://github.com/gfx-rs/wgpu/pull/3405.

**Comment by Aaron1011** [comment]
naga previously allowed duplicate struct definitions in wgsl input, but it now prevents that. `naga_oil` has been creating duplicate struct definitions due to the way it handles nested imports, but naga was accepting it until now.

I'm trying to come up with a simple way to fix this.

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
