### PR TITLE
avm2: Implement PrintJobOptions

### PR DESCRIPTION
**Pull request by huwdp**
Implements PrintJobOptions class :)

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]

**Comment by Lord-McSweeney** [comment]
`pixelsPerInch` and `printMethod` are AIR-only properties, so I think those should be removed.

**Comment by huwdp** [comment]
> `pixelsPerInch` and `printMethod` are AIR-only properties, so I think those should be removed.

This is done. I also implemented the getter/setter

**Comment by Lord-McSweeney** [comment]
It seems that Flash doesn't actually implement a getter/setter for this (it's a normal property). Also, there are unused imports for `__ruffle__.stub_getter`/`setter`.

**Comment by huwdp** [comment]
> It seems that Flash doesn't actually implement a getter/setter for this (it's a normal property since there are no restrictions on it). Also, there are unused imports for `__ruffle__.stub_getter`/`setter`.

Thankf for this. I've made the changes

**Review by Lord-McSweeney — APPROVED** [review]

**Pull request merged**
