### PR TITLE
core: Implement right & middle click events, fix disappearing context menu on desktop

### PR DESCRIPTION
**Pull request by kjarosh**
Fixes https://github.com/ruffle-rs/ruffle/issues/16991, fixes https://github.com/ruffle-rs/ruffle/issues/10288, fixes https://github.com/ruffle-rs/ruffle/issues/10389, progresses https://github.com/ruffle-rs/ruffle/issues/11009, fixes https://github.com/ruffle-rs/ruffle/issues/10612, fixes https://github.com/ruffle-rs/ruffle/issues/11810.

This PR implements the following events:
* `rightMouseDown`,
* `middleMouseDown`,
* `rightMouseUp`,
* `middleMouseUp`,
* `rightClick`,
* `middleClick`.

Additionally this PR fixes disappearing context menu on desktop by changing its trigger from key release to key press (as in FP). Opening context menu on press is important, because events consume right click on press, not on release.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I'm a little worried about web. We have no tests for context menu on web (as much as I constantly wish otherwise... one day!), and it's pretty convoluted because of ios (and mobile in general, but mostly ios iirc)

Testing this on web on a desktop and it works as expected - but testing it on firefox on android, the right click action doesn't seem to trigger and the context menu shows up instead :( Specifically testing #10389 and #10389

If you want to say mobile is for another time and this gets desktop working - then I'm okay with that, as long as we don't introduce any regressions.

**Comment by kjarosh** [comment]
I'm aware that right clicking does not currently work on mobile, matter of fact not introducing regressions was my reason for not implementing it in this PR as it already includes a lot of changes.

I tried implementing it for mobile, but currently we handle the context menu a little differently for mobile and desktop, and unifying the behavior requires some more work. I've just added a TODO comment about that.

**Comment by danielhjacobs** [comment]
The main issue is this one: https://bugs.webkit.org/show_bug.cgi?id=213953

**Comment by Dinnerbone** [comment]
> I'm aware that right clicking does not currently work on mobile, matter of fact not introducing regressions was my reason for not implementing it in this PR as it already includes a lot of changes.

That's fine, thank you! Just wanted to know if that was intentional or not. I'm 100% okay with it not being here in this PR, as long as it's understood that that isn't the case.

**Comment by yangyangdaji** [comment]
Maybe this can be fixed
 https://github.com/ruffle-rs/ruffle/issues/10578

**Comment by yangyangdaji** [comment]
Maybe be fixed https://github.com/ruffle-rs/ruffle/issues/10578

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
