### PR TITLE
Stub opaque background for DisplayObject.

### PR DESCRIPTION
**Pull request by Lord-McSweeney**
Progresses Bloons 2.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
This should be really easy to actually implement, no?

**Comment by Lord-McSweeney** [comment]
Unfortunately I have practically no Rust experience. If you want to make changes to the branch, feel free to do so!

**Comment by adrian17** [comment]
I'm perfectly happy with having it be stubbed, but let's use the stub macro Dinnerbone merged just earlier today :)

**Review by Dinnerbone — APPROVED** [review]

**Comment by n0samu** [comment]
This does get rid of one error message from Bloons 2 but I don't think it's related to why the game is stuck. The error spam is coming from calls to `scene.update()`, since the `scene` variable seems to be declared but never initialized. Yet even if I remove all `scene` method calls, I get nothing but a blank screen, while Flash Player still plays the intro. In conclusion, I have no idea what's going on with this game, but I don't think your PR helps.

**Comment by adrian17** [comment]
(for the future, I think future PRs like this can totally get squashed on merge :) )

**Comment by Dinnerbone** [comment]
Yep regretted it the moment I saw the commits land!

**Pull request merged**
