### PR TITLE
Fully implement ExternalInterface

### LINKED ISSUE #806: Will ExternalInterface.call("JavaScript Function") be implemented ?
The usage is SO SIMPLE, it boggles the mind:
load_data = ExternalInterface.call("HelloFunction",50,50); //load_data will now contain the number 10.

Somewhere inside the HTML file, you have the script:
<script>
		function HelloFunction(arg1, arg2)
		{
			return (arg1+arg2);
		}
</script>

I literally just tested it on the actual Flash player, blank Flash file, contains nothing, just this, and...it simply just works, MAGIC.

If Ruffles have this single feature, it will open up Pandora's box, suddenly all the new JavaScript framework's power (JavaScript Artificial Intelligence Frameworks, QR Code generation, basically all of modern JavaScript power) will be bestowed/gifted back to our love, Flash ! 

What's old will be new again, Flash as an AMAZING GUI framework, will be back in FULL FORCE.

### PR DESCRIPTION
**Pull request by Dinnerbone**
Defaults to 'sameOrigin' for objects, or false otherwise.

Javascript can access exposed flash methods by `object.methodToCall(args)`, and Flash can access Javascript via `ExternalInterface.call("console.log", "HELLO WORLD")`.

I'm sure there may be some edge cases I've missed, but I'm hoping this is good enough for most use cases (ie checking `ExternalInterface.call("window.location.toString")`)

No automated tests for the web part yet, we're hindered by the ability to control movie playback first. I've manually tested everything there.

Closes #806

### CODE REVIEW

**Comment by ROBERT-MCDOWELL** [comment]
return an object right? also a params are allowed too..

**Comment by Dinnerbone** [comment]
Arguments and return values are kept and translated over.

**Comment by ROBERT-MCDOWELL** [comment]
excellent job!

**Comment by ROBERT-MCDOWELL** [comment]
excellent job!

**Comment by Herschel** [comment]
Thanks!

**Pull request merged**
