### PR TITLE
avm2: Call Sound.load in constructor when passed a URLRequest

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Can you add a test for this?

**Comment by waspennator** [comment]
Should effect #9171, #9693, and #12055?

**Comment by n0samu** [comment]
Unfortunately this does not seem to fix any of those issues.

**Review by danielhjacobs — CHANGES_REQUESTED** [review]
Not directly related, but change https://github.com/ruffle-rs/ruffle/blob/c829d797ce567666a5779a33121cf56c461d8fd4/core/src/avm2/globals/flash/media/sound.rs#L246 to `let _sound_context = args.try_get_object(activation, 1);`. It's currently never `None`, so the stub message always appears when `load` is called.

**Comment by danielhjacobs** [comment]
Together with #12967, should fix https://dnasubway.cyverse.org/files/tour/tour-all.swf

**Comment by danielhjacobs** [comment]
Test for this PR added in #13005.

**Review by danielhjacobs — APPROVED** [review]
If this is merged as-is, in a follow-up PR I'll rebase #13005 on it and remove `known_failure`, and in another follow-up I'll change this to `let _sound_context = args.try_get_object(activation, 1);` https://github.com/ruffle-rs/ruffle/blob/c829d797ce567666a5779a33121cf56c461d8fd4/core/src/avm2/globals/flash/media/sound.rs#L246

**Review by adrian17 — APPROVED** [review]

**Pull request merged**
