### PR TITLE
AVM2 DisplayObjectContainer

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR includes the `DisplayObjectContainer` APIs as well as any internal refactoring necessary to support their use. Turns out, there's a whole lot that needed refactoring! There's also a handful of new container types, but I am going to consider that out-of-scope. We will only re-architecture the display object system to the point where we can implement `Sprite`, `Loader`, etc; actually implementing those object types is out-of-scope.

- [x] Consolidate child management into `Container` struct
  - [x] Remove existing child management code from `MovieClip` and `Button`
  - [x] Add secondary trait/methods for working with object children generically for future PRs
  - [x] Switch existing AS3 impls to use said trait instead of looking for `MovieClip`
- [x] Split render list from depth list
  - [x] Add tests for depth/render list interactions
  - [ ] Regression test AVM1 content
- [x] Impl `addChild`
- [x] Impl `addChildAt`
- [x] Impl `getChildAt`
- [x] Impl `numChildren`
- [x] Impl `removeChild`
- [x] Impl `getChildByName`
- [x] Impl named instance properties (e.g. `this.child`)
- [x] Impl `contains`
- [x] Impl `getChildIndex`
- ~Impl `Point`~
  - [x] Stub `getObjectsUnderPoint` (won't work without Point)
  - [x] Stub `areInaccessibleObjectsUnderPoint` (useless without crossdomain policy etc)
- [x] Impl `removeChildAt`
- [x] Impl `removeChildren`
- [x] Impl `setChildIndex`
- [x] Impl `stopAllMovieClips`
- [x] Impl `swapChildren`
- [x] Impl `swapChildrenAt`

### CODE REVIEW

**Comment by kmeisthax** [comment]
Unresolved question: `set_state` on `Button` appeared to be constructing execution lists for each button state "backwards". i.e. instead of pushing to the top of the list, it constructed the list back-to-front and then set the list head on the container at the end.

To support this behavior in the container refactoring, I had to keep the ability to set the list head and add a flag to `replace_at_depth` to avoid touching the execution list (else it quickly became circular). I've removed that code outright, but it meant having to move `Button` to constructing standard-order execution lists. Do we know of any case in which we need `Button` to construct reversed execution lists?

**Comment by Herschel** [comment]
Yea, I think it's an oversight. Here's a test that prints in the incorrect order on Ruffle master (should print `instance3` then `instance2`):
[button-order.zip](https://github.com/ruffle-rs/ruffle/files/5520944/button-order.zip)

**Comment by kmeisthax** [comment]
Thanks. I've incorporated the button order test into this PR. Funny, I didn't expect AVM1 to benefit from an AVM2 PR, but here we go.

**Comment by kmeisthax** [comment]
`Point` is complicated enough to be it's own PR, so instead of half-assing it to get `getObjectsUnderPoint` to work, I'm going to move it out of this PR's scope.

That only leaves timeline instances, which appear to have some amount of magic to them that I'll have to implement. I assumed it'd desugar down to `var clipname = this.getChildByName('clipname');`, but no, it appears to actually have dynamic properties for each clip.

**Comment by kmeisthax** [comment]
I'm releasing the draft lock on this PR as I believe it to be feature complete. I still want to regression test some AVM1 content, purely due to how invasive this refactor got, but other than that this should be ready for review.

All display objects that hold other display objects must now implement a `TDisplayObjectContainer` trait and enumerate into the `DisplayObjectContainer` enum. This has been done for `Button` and `MovieClip` as this appears to be the only two containers so far in the project. Implementing a second rung in our """class""" hierarchy for containers was very straightforward, although it's technically not possible to upcast a container to a display object right now, so we can't have methods that statically require containers yet.

Inside each container is a set of three lists: render, depth, and execution. AVM1 and the movie timeline only interact with the depth and execution lists, but AVM2 uses the render list, and expects the render list to be the source of truth for the rendering order of objects. Thus, we bend over backwards to ensure that mutations of the depth list also reorder the render list as the timeline would expect. This introduces a number of unusual invariants which are accounted for in the test suite and enforced (mostly) by `ChildContainer`:

 * When a display object is added to a container by AVM2, it gains the `PlacedByScript` flag. This flag is separate from `TransformedByScript` currently; this may turn out to be unnecessary. (We currently treat render list swaps, such as `setChildIndex`, `swapChildrenAt`, or `swapChildren`, as "adding" and set the flag, even though I don't have test coverage for this.)
 * Placement of an object into the depth list can remove an existing object from that list with the same depth. This removal will propagate over to the render list unless the object was placed by AVM2, in which case it will only be removed from the depth list.
 * Removal of an object from the timeline will fail if AVM2 locked the child after it was placed in the timeline. (This can also fail if AVM2 caused the child to fall off the depth list for some other reason.) This includes children that would ordinarily be removed during a goto command which AVM2 can issue. (There is currently no test coverage for the interaction between container contents and AVM2 gotos)
 * Most AVM1 child removal does not check the `PlacedByScript` flag; however, this is unnecessary as AVM1 and AVM2 display objects cannot legally interact.

Methods that require `Point` have been stubbed. They will be implemented when it comes time to implement `Point`, which may not be for a while. `DisplayObject` itself doesn't appear to use it outside of `hitTest` and the coordinate transform helpers; and there's a few other classes we need like `EventDispatcher`, too.

**Review by Herschel — CHANGES_REQUESTED** [review]
Thanks, this is great!

* I think all `TDisplayObject`/`TDisplayObjectContainer` methods should take `&self` instead of `&mut self` because they are designed to use interior mutability and don't require an exclusive borrow (see #1034)
* All methods that use an index should `coerce_to_i32` (even though it's unlikely to ever be a problem :-) )
* Personally I would use `index` instead of `id` (matches other Rust conventions, and `id` makes me think of charcter ID or some given ID.)

Thinking out loud about long-term ideas:
* The `ChildContainer` lists will probably simplify as we get a better idea of things; for one, my testing shows that the exec list is probably a global linked-list among all display objects. 
* I wonder if the `PlacedByScript` flag might actually be controlled by setting the `Depth` to `0` or `None`, and then these display objects naturally can't be targeted by any SWF tags and will stick-in-place in the lists.
 * As our "inheritance" hierarchies grow, I've been wondering if we make our own object model with a hand-rolled vtable, instead of trying to glue things together with the trait system. I've seen some other crates do this, such as `bytes`. (This probably applies more to the VM objects than the display tree).

**Comment by Herschel** [comment]
@Toad06 could you give this a quick test to see if there might be any regressions for AVM1 content? Thanks!

**Comment by Toad06** [comment]
I think I've tested many games and the only regression I noticed is in [Super Mario 63](https://www.newgrounds.com/portal/view/498969): start a new game (skip the intro), Mario will get stuck in the air, so the game softlocks.

Good news: it also turns out this PR fixes #1140 (you may want to use one of the tests available there) and #1701.

Thanks a lot for your work!

**Comment by kmeisthax** [comment]
I wasn't able to reproduce the Steppenwolf bug, but I fixed the Super Mario 63 one. The problem is that AS3 expects children to lose their parent when they are removed from their parent; while AS2 does not alter the parent. I just special-cased this one; I don't think there's some grand principle behind it. I tried writing a test for it but it doesn't fail with the incorrect behavior for some reason.

I also attempted to add your test case for #1140 but it fails with this PR - I think it may have been passing accidentally due to the incorrect AS2 parent behavior.

**Comment by Toad06** [comment]
For Steppenwolf 1-1, the bug only occurs on the Web backend (and only on this specific site?) but it turns out this is not related to your PR (I'll try to see what happens here). I think this issue has been introduced very recently, so I got confused. My bad!

#1701 is no longer fixed now which makes sense considering the change to `_parent`. I'm more surprised to see that #1140 still works: running "test_samedepth.swf" traces different results:
```
_level0.A0 - movieclip
_level16385 - movieclip [_level0.A0 in master]
_level16385 - movieclip [_level0.A0 in master]
```


Finally, in [Jump Girl](https://www.y8.com/games/jump_girl), when the character gets hit by a rock, the rock remains on screen forever.

**Comment by kmeisthax** [comment]
Figured out the problem with Jump Girl. It swaps things to 0 before removing the clip, and the swap-depths code was missing code to remove the rock from the render list at it's old location if it was the highest depth in the container. That's been fixed, children are always swapped in the render list in all cases.

So, regarding #1140, I had actually remade your test and merged both cases together. (I didn't have an FLA for your files) The same-depth part of the test gives the same output in Flash as yours, and Ruffle also does the same thing where it's pulling `_level16385` somehow. However, I don't want to commit that behavior to our test repository yet, since it's technically wrong and smells like changing one bug for another.

**Comment by Toad06** [comment]
All good to me. 👍

**Comment by Herschel** [comment]
Let's go! Thanks!

**Pull request merged**
