### PR TITLE
avm1: Reverse iteration when applying filters - fixes #12272

### LINKED ISSUE #12272: Test failure: avm1/from_shumway/filters
Test path: `tests/tests/swfs/avm1/from_shumway/filters`

# Expected
```
Filters (7)
DropShadowFilter
  distance 5
  angle 0
  color 0
  alpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  inner false
  knockout false
  hideObject false
BlurFilter
  blurX 5
  blurY 5
  quality 1
GlowFilter
  color 16711680
  alpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  inner false
  knockout false
BevelFilter
  distance 5
  angle 0
  highlightColor 16777215
  highlightAlpha 1
  shadowColor 0
  shadowAlpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  type inner
  knockout false
GradientGlowFilter
  distance 5
  angle 0
  colors 16777215,0
  alphas 0,1
  ratios 0,255
  blurX 5
  blurY 5
  strength 1
  quality 1
  type outer
  knockout false
GradientBevelFilter
  distance 5
  angle 0
  colors 16777215,16711680,0
  alphas 1,0,1
  ratios 0,128,255
  blurX 5
  blurY 5
  strength 1
  quality 1
  type inner
  knockout false
ColorMatrixFilter
  matrix 1,0,0,0,50,0,1,0,0,50,0,0,1,0,50,0,0,0,1,0
Filters (9)
BevelFilter
  distance 1
  angle 1
  highlightColor 12
  highlightAlpha 1
  shadowColor 34
  shadowAlpha 1
  blurX 2
  blurY 3
  strength 1
  quality 1
  type inner
  knockout false
BlurFilter
  blurX 2
  blurY 3
  quality 1
ColorMatrixFilter
  matrix 1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0
ConvolutionFilter
  matrixX 3
  matrixY 3
  matrix 1,2,3,4,5,6,7,8,9
  divisor 1
  bias 1
  preserveAlpha false
  clamp false
  color 123
  alpha 1
DisplacementMapFilter
  mapBitmap [object Object]
  mapPoint (x=1, y=2)
  componentX 1
  componentY 1
  scaleX 2
  scaleY 2
  mode clamp
  color 2
  alpha 1
DropShadowFilter
  distance 2
  angle 1
  color 23
  alpha 1
  blurX 4
  blurY 2
  strength 1
  quality 1
  inner true
  knockout true
  hideObject false
GlowFilter
  color 321
  alpha 1
  blurX 4
  blurY 2
  strength 1
  quality 1
  inner false
  knockout false
GradientBevelFilter
  distance 2
  angle 1
  colors 23,12,42
  alphas 0,1,1
  ratios 0,25,255
  blurX 5
  blurY 4
  strength 5
  quality 2
  type full
  knockout true
GradientGlowFilter
  distance 1
  angle 1
  colors 3,4,5
  alphas 1,1,1
  ratios 0,50,255
  blurX 1
  blurY 2
  strength 1
  quality 1
  type inner
  knockout false
```

# Actual
```
Filters (7)
DropShadowFilter
  distance 5
  angle 0
  color 0
  alpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  inner false
  knockout false
  hideObject false
BlurFilter
  blurX 5
  blurY 5
  quality 1
GlowFilter
  color 16711680
  alpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  inner false
  knockout false
BevelFilter
  distance 5
  angle 0
  highlightColor 16777215
  highlightAlpha 1
  shadowColor 0
  shadowAlpha 1
  blurX 5
  blurY 5
  strength 1
  quality 1
  type inner
  knockout false
GradientGlowFilter
  distance 5
  angle 0
  colors 16777215,0
  alphas 0,1
  ratios 0,255
  blurX 5
  blurY 5
  strength 1
  quality 1
  type outer
  knockout false
GradientBevelFilter
  distance 5
  angle 0
  colors 16777215,16711680,0
  alphas 1,0,1
  ratios 0,128,255
  blurX 5
  blurY 5
  strength 1
  quality 1
  type inner
  knockout false
ColorMatrixFilter
  matrix 1,0,0,0,50,0,1,0,0,50,0,0,1,0,50,0,0,0,1,0
Filters (9)
GradientGlowFilter
  distance 1
  angle 0.999283996329546
  colors 3,4,5
  alphas 1,1,1
  ratios 0,50,255
  blurX 1
  blurY 2
  strength 1
  quality 1
  type inner
  knockout false
GradientBevelFilter
  distance 2
  angle 0.999283996329546
  colors 23,12,42
  alphas 0,1,1
  ratios 0,25,255
  blurX 5
  blurY 4
  strength 5
  quality 2
  type full
  knockout true
GlowFilter
  color 321
  alpha 1
  blurX 4
  blurY 2
  strength 1
  quality 1
  inner false
  knockout false
DropShadowFilter
  distance 2
  angle 0.999283996329546
  color 23
  alpha 1
  blurX 4
  blurY 2
  strength 1
  quality 1
  inner true
  knockout true
  hideObject false
DisplacementMapFilter
  mapBitmap undefined
  mapPoint (x=1, y=2)
  componentX 1
  componentY 1
  scaleX 2
  scaleY 2
  mode clamp
  color 2
  alpha 1
ConvolutionFilter
  matrixX 3
  matrixY 3
  matrix 1,2,3,4,5,6,7,8,9
  divisor 1
  bias 1
  preserveAlpha false
  clamp false
  color 123
  alpha 1
ColorMatrixFilter
  matrix 1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0
BlurFilter
  blurX 2
  blurY 3
  quality 1
BevelFilter
  distance 1
  angle 0.999283996329546
  highlightColor 12
  highlightAlpha 1
  shadowColor 34
  shadowAlpha 1
  blurX 2
  blurY 3
  strength 1
  quality 1
  type inner
  knockout false
```

# Difference
```diff
67c67
< BevelFilter
---
> GradientGlowFilter
69,75c69,74
<   angle 1
<   highlightColor 12
<   highlightAlpha 1
<   shadowColor 34
<   shadowAlpha 1
<   blurX 2
<   blurY 3
---
>   angle 0.999283996329546
>   colors 3,4,5
>   alphas 1,1,1
>   ratios 0,50,255
>   blurX 1
>   blurY 2
80,104c79,92
< BlurFilter
<   blurX 2
<   blurY 3
<   quality 1
< ColorMatrixFilter
<   matrix 1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0
< ConvolutionFilter
<   matrixX 3
<   matrixY 3
<   matrix 1,2,3,4,5,6,7,8,9
<   divisor 1
<   bias 1
<   preserveAlpha false
<   clamp false
<   color 123
<   alpha 1
< DisplacementMapFilter
<   mapBitmap [object Object]
<   mapPoint (x=1, y=2)
<   componentX 1
<   componentY 1
<   scaleX 2
<   scaleY 2
<   mode clamp
<   color 2
---
> GradientBevelFilter
>   distance 2
>   angle 0.999283996329546
>   colors 23,12,42
>   alphas 0,1,1
>   ratios 0,25,255
>   blurX 5
>   blurY 4
>   strength 5
>   quality 2
>   type full
>   knockout true
> GlowFilter
>   color 321
105a94,99
>   blurX 4
>   blurY 2
>   strength 1
>   quality 1
>   inner false
>   knockout false
108c102
<   angle 1
---
>   angle 0.999283996329546
118,119c112,120
< GlowFilter
<   color 321
---
> DisplacementMapFilter
>   mapBitmap undefined
>   mapPoint (x=1, y=2)
>   componentX 1
>   componentY 1
>   scaleX 2
>   scaleY 2
>   mode clamp
>   color 2
121,123c122,136
<   blurX 4
<   blurY 2
<   strength 1
---
> ConvolutionFilter
>   matrixX 3
>   matrixY 3
>   matrix 1,2,3,4,5,6,7,8,9
>   divisor 1
>   bias 1
>   preserveAlpha false
>   clamp false
>   color 123
>   alpha 1
> ColorMatrixFilter
>   matrix 1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0
> BlurFilter
>   blurX 2
>   blurY 3
125,139c138
<   inner false
<   knockout false
< GradientBevelFilter
<   distance 2
<   angle 1
<   colors 23,12,42
<   alphas 0,1,1
<   ratios 0,25,255
<   blurX 5
<   blurY 4
<   strength 5
<   quality 2
<   type full
<   knockout true
< GradientGlowFilter
---
> BevelFilter
141,146c140,146
<   angle 1
<   colors 3,4,5
<   alphas 1,1,1
<   ratios 0,50,255
<   blurX 1
<   blurY 2
---
>   angle 0.999283996329546
>   highlightColor 12
>   highlightAlpha 1
>   shadowColor 34
>   shadowAlpha 1
>   blurX 2
>   blurY 3
```

### PR DESCRIPTION
**Pull request by Dinnerbone**
Had to remove `mapBitmap [object Object]` as we can't represent that currently, same as avm2 test. Otherwise the test passes.

### CODE REVIEW

**Comment by torokati44** [comment]
Other than the mismatch in the relevant test output, shouldn't this have also caused visual difference when multiple filters were applied to an object? :thinking: I can't seem to get any issue of that sort either before or after this PR, in either AVM1 or AVM2...

**Comment by Dinnerbone** [comment]
Yes, when applied via avm1. Add two glow filters of different colours and you should see the order.

**Comment by torokati44** [comment]
This is what I've been experimenting with: 
[filterordertest.zip](https://github.com/ruffle-rs/ruffle/files/12144125/filterordertest.zip)

It's three large and strong glows of different colors on a square... I would have expected to see the rings reverse in some way...?
image

**Comment by torokati44** [comment]
> Yes, when applied via avm1.

Oh, that is, when _setting_ `filters` from AS?

**Comment by Dinnerbone** [comment]
> > Yes, when applied via avm1.
> 
> Oh, that is, when _setting_ `filters` from AS?
> 

Yes!

**Comment by torokati44** [comment]
But of course, the fix itself is in `set_filters`... :facepalm:

**Comment by torokati44** [comment]
Hah, that's so random... why would they reverse the array here? :D Could simply be an oversight?

**Review by Lord-McSweeney — APPROVED** [review]

**Comment by torokati44** [comment]
Okay, I was able to repro it using this test:
[avm1_filters_order.zip](https://github.com/ruffle-rs/ruffle/files/12144308/avm1_filters_order.zip)

**Comment by torokati44** [comment]
> Had to remove mapBitmap [object Object] as we can't represent that currently, same as avm2 test. 

I see you left this in the test code commented out, but do we also have this limitation recorded by some issue? Would be nice to not forget about it, and uncomment this sometime, when it's fixed.

**Review by torokati44 — APPROVED** [review]

**Comment by Dinnerbone** [comment]
> > Had to remove mapBitmap [object Object] as we can't represent that currently, same as avm2 test. 
> 
> I see you left this in the test code commented out, but do we also have this limitation recorded by some issue? Would be nice to not forget about it, and uncomment this sometime, when it's fixed.

I don't think there's an option issue yet

**Pull request merged**
