### PR TITLE
avm2: Fix property_is_enumerable on arrays

### PR DESCRIPTION
**Pull request by adrian17**

### CODE REVIEW

**Review by sleepycatcoding — APPROVED** [review]

**Comment by torokati44** [comment]
Just searching for `>= index` in the codebase, I see a few really similar lines in `get_enumerant_name`, and also not only in `array_object.rs`, but in `dictionary_object.rs`, `vector_object.rs`, and `xml_list_object.rs` as well.
Should those be updated as well?

**Comment by adrian17** [comment]
Will check these out tomorrow, thanks for pointing it out.

**Comment by adrian17** [comment]
@torokati44 turns out the implementation for Vector shouldn't exist at all :D 

The remaining ones are in `get_enumerant_name/value` which I assume are correct.

**Comment by torokati44** [comment]
> turns out the implementation for Vector shouldn't exist at all :D

Well, now we know! :D

> The remaining ones are in get_enumerant_name/value which I assume are correct.

Why the assumption? To me, any comparison that handles the `length == index` (which is usually over-indexing) the same way as `length > index` (not over-indexing), as opposed to as `length < index` (obviously over-indexing). Unless the thing is indexed starting from 1 for some reason.

**Comment by adrian17** [comment]
It does a `>=`  comparison, but then subtracts 1 from the index.
I didn't try to understand exactly how enumeration works, but I checked that replacing the comparison by `>` breaks array enumeration so I'm assuming everything currently works as it should :D

**Comment by torokati44** [comment]
> but I checked that replacing the comparison by > breaks array enumeration so I'm assuming everything currently works as it should :D

Okay, that's good enough for me! :D

**Review by Dinnerbone — APPROVED** [review]

**Review by Aaron1011 — APPROVED** [review]

**Pull request merged**
