### PR TITLE
avm1: Add `trace` to globals

### PR DESCRIPTION
**Pull request by Toad06**
`trace` compiles to `Action::Trace` but also exists on `_global`.

```
trace(typeof _global.trace); // "function" in Flash, "undefined" in Ruffle
```

---

Here is a sample made with JPEXS: [global_trace_test.zip](https://github.com/ruffle-rs/ruffle/files/8048458/global_trace_test.zip) (includes a .fla)

It would be interesting to check in Flash Professional if:
- this actually logs anything. JPEXS outputs the traces but the Flash projector debugger doesn't write anything to "flashlog.txt".
- if the CRLF behaviour is the same as #5738 (JPEXS and the Flash projector debugger are a bit different here).

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]

**Comment by adrian17** [comment]
(for the record, it does work in Flash editor's trace window, so maybe it's only enabled in "debugging mode"...?)

**Comment by relrelb** [comment]
> (for the record, it does work in Flash editor's trace window, so maybe it's only enabled in "debugging mode"...?)

So I wonder what it could do different. Isn't it simply the same executable as the Flash projector?

**Comment by Toad06** [comment]
I agree to the general idea but `trace` (`Action::Trace` / `_global.trace`) is specific, it _is_ a debugging feature and as such it becomes pointless once the file is compiled as no one will see the messages (apart from the guys working on an emulator...). So it makes sense to me if we follow the behaviour of the Flash editor's trace window here. In Ruffle, `trace` calls don't log anything by default anyway.

The Flash projector also doesn't log anything to "flashlog.txt" by default, this is only possible by setting a poorly documented option in a file that the user has to create himself, so it's not so standard.

**Comment by relrelb** [comment]
Okay, 

> I agree to the general idea but `trace` (`Action::Trace` / `_global.trace`) is specific, it _is_ a debugging feature and as such it becomes pointless once the file is compiled as no one will see the messages (apart from the guys working on an emulator...). So it makes sense to me if we follow the behaviour of the Flash editor's trace window here. In Ruffle, `trace` calls don't log anything by default anyway.
> 
> The Flash projector also doesn't log anything to "flashlog.txt" by default, this is only possible by setting a poorly documented option in a file that the user has to create himself, so it's not so standard.

Okay, you convinced me. So let's just add a comment that documents this...

**Review by relrelb — APPROVED** [review]

**Pull request merged**
