### PR TITLE
ci: Make the crowdin PR with the rufflebuild user

### PR DESCRIPTION
**Pull request by Dinnerbone**
I'm going to save @torokati44 so many minutes.

### CODE REVIEW

**Comment by torokati44** [comment]
Was it really _this simple_?! What?! :joy:

**Comment by torokati44** [comment]
Thank you so much! :face_holding_back_tears:  Although, a comment would be appreciated there, as for why it is what it is. :pleading_face:

**Review by torokati44 — APPROVED** [review]

**Comment by torokati44** [comment]
>

**Comment by torokati44** [comment]
Oh frickety fudge.

**Comment by Dinnerbone** [comment]
You don't want it. I get it. It's fine.


😭

**Comment by torokati44** [comment]
Of all the PRs I could have misclicked on, why this one?! :sob:

**Comment by torokati44** [comment]
Also, aww, that branch name! :blush:

**Pull request merged**
