### PR TITLE
core: Fix some issues with `hitTest`

### PR DESCRIPTION
**Pull request by Herschel**
Fixes some issues with our winding # calculation which would cause incorrect results for `hitTest`.

 * The convention for handling an intersection at endpoints was not the same between lines and bezier curves.
 * The bezier curve winding # function was not properly handling some cases where the curve was strictly y-monotonic.
 * Simplify the code a bit so that ray-curve intersections are returned in a consistent order based on upward/downward crossing.

### CODE REVIEW

**Comment by Herschel** [comment]
I'll add a test case for this tomorrow; this could use some testing as games are very sensitive to changes here.

@Aaron1011 Could you check if this solves the issue in Wonderputt?
@Toad06 Could you check if there are any regressions, particularly in platform games like Ultimate Flash Sonic?

**Comment by Aaron1011** [comment]
@Herschel While this branch does fix the specific point tested in my SWF, it unfortunately doesn't seem to resolve the full issue. By moving my mouse around inside the largest empty region, I was able to generate many more incorrect 'hit' points. I've updated https://github.com/Aaron1011/ruffle/tree/hittest-debug to test for these points by default, and to mark each with a purple pixel. Running the SWF in Flash Player traces 'false' for all of those points, while running in on this branch traces 'true' for all of them except the first one (which was fixed by this PR).

**Comment by torokati44** [comment]
(FWIW this also doesn't fix https://github.com/ruffle-rs/ruffle/issues/4064 yet.)

**Comment by Toad06** [comment]
This fixes an issue in [Steppenwolf 3-1](https://www.y8.com/games/steppenwolf_chapter_3_episode_1). It was impossible to hide behind the tunnel without jumping:

https://user-images.githubusercontent.com/14274782/184868986-4390e341-9323-453c-96f3-9aa46bce3ca0.mp4

---

In [Ultimate Flash Sonic](https://www.y8.com/games/ultimate_flash_sonic), the character seems to get stuck less often. But I also noticed a few regressions:

https://user-images.githubusercontent.com/14274782/184869517-893f0b9b-25dd-4b3d-ad13-f7156c51154f.mp4

https://user-images.githubusercontent.com/14274782/184877418-f7fd1d22-54a5-494c-a6bf-72fdee5f327c.mp4

---

The game in #5481 (which is not a platformer) doesn't seem to like these changes, as unexpected collisions happen more often even when the file is displayed in its natural dimensions.

**Comment by Aaron1011** [comment]
Wonderputt holes 1 and 14 no longer have false-positive hits with this PR.

**Comment by Herschel** [comment]
Thanks for testing! I checked with all of the above cases and it seems okay -- @Toad06 could you give this a bit more testing?

**Comment by Herschel** [comment]
Looks like #4064 still has some issues.

**Comment by Herschel** [comment]
Looking at #4064, it actually seems to be a case of #5492, where the ground being hitTested is the ground from level1 even on level2. I was able to hack in a fix on the SWF to re-get `_root.game.map.ground` and I was able to  complete level 2 successfully.

**Comment by Toad06** [comment]
No regression found. 👍

This also fixes [Monkey Lander](https://uploads.ungrounded.net/81000/81467_monkeylander.swf), NoName Game (#5481), [NoName Game 2](https://www.jeux-jouer.fr/swf/noname2sm.swf) which were impossible to complete.

**Review by Aaron1011 — APPROVED** [review]

**Review by relrelb — APPROVED** [review]

**Pull request merged**
