### PR TITLE
chore: Run `cargo update`, but carefully

### PR DESCRIPTION
**Pull request by torokati44**
This lets us deduplicate `event-listener` and `event-listener-strategy`.

```
    Updating addr2line v0.21.0 -> v0.22.0 (latest: v0.23.0)
    Updating async-executor v1.11.0 -> v1.12.0
    Updating async-io v2.3.2 -> v2.3.3
    Updating async-lock v3.3.0 -> v3.4.0
    Updating async-process v2.2.2 -> v2.2.3
    Updating async-signal v0.2.6 -> v0.2.7
    Updating backtrace v0.3.71 -> v0.3.72
    Updating block2 v0.5.0 -> v0.5.1
    Updating blocking v1.6.0 -> v1.6.1
    Updating bytemuck_derive v1.6.0 -> v1.7.0
    Updating cc v1.0.97 -> v1.0.98
    Updating clang-sys v1.7.0 -> v1.8.1
    Updating crc32fast v1.4.0 -> v1.4.2
    Updating crossbeam-utils v0.8.19 -> v0.8.20
    Updating euclid v0.22.9 -> v0.22.10
    Removing event-listener v4.0.3
    Removing event-listener v5.3.0
      Adding event-listener v5.3.1
    Removing event-listener-strategy v0.4.0
    Updating gimli v0.28.1 -> v0.29.0 (latest: v0.30.0)
    Updating h2 v0.4.4 -> v0.4.5
    Updating hyper-util v0.1.3 -> v0.1.5
    Updating instant v0.1.12 -> v0.1.13
    Updating libc v0.2.154 -> v0.2.155
    Updating lyon_tessellation v1.0.14 -> v1.0.15
    Updating miniz_oxide v0.7.2 -> v0.7.3
    Updating objc-sys v0.3.3 -> v0.3.5
    Updating objc2 v0.5.1 -> v0.5.2
    Updating objc2-app-kit v0.2.0 -> v0.2.2
    Updating objc2-core-data v0.2.0 -> v0.2.2
      Adding objc2-core-image v0.2.2
    Updating objc2-encode v4.0.1 -> v4.0.3
    Updating objc2-foundation v0.2.0 -> v0.2.2
      Adding objc2-metal v0.2.2
      Adding objc2-quartz-core v0.2.2
    Updating object v0.32.2 -> v0.35.0 (latest: v0.36.0)
    Updating parking_lot v0.12.2 -> v0.12.3
    Updating piper v0.2.2 -> v0.2.3
    Updating polling v3.7.0 -> v3.7.1
    Updating raw-window-handle v0.6.1 -> v0.6.2
    Updating tinystr v0.7.5 -> v0.7.6
    Updating wayland-backend v0.3.3 -> v0.3.4
    Updating wayland-client v0.31.2 -> v0.31.3
    Updating wayland-cursor v0.31.1 -> v0.31.3
    Updating wayland-scanner v0.31.1 -> v0.31.2
    Updating wayland-sys v0.31.1 -> v0.31.2
    Updating wide v0.7.19 -> v0.7.21
    Updating winnow v0.6.8 -> v0.6.9
    Updating zbus v4.2.1 -> v4.2.2
    Updating zbus_macros v4.2.1 -> v4.2.2
    Updating zeroize v1.7.0 -> v1.8.1
    Updating zvariant v4.1.0 -> v4.1.1
    Updating zvariant_derive v4.1.0 -> v4.1.1
    Updating zvariant_utils v1.1.1 -> v2.0.0
```

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I guess there's a breaking change to somethings behaviour?

**Comment by Dinnerbone** [comment]
Ah, it's a change to Lyon's tesselation

Master
output expected

This PR
output actual-linux-Vulkan

Difference
output difference-color-linux-Vulkan

Likely https://github.com/nical/lyon/commit/825b98cb93c3d54f6f3688ef686d70c9196a2b73

**Comment by Dinnerbone** [comment]
I'd say the new version looks *closer* to Flash, so let's take it

**Comment by torokati44** [comment]
Thank you for checking it out, I've updated the test image.

**Review by Dinnerbone — APPROVED** [review]

**Pull request merged**
