### PR TITLE
chore: Update to wasm-bindgen 0.2.93

### PR DESCRIPTION
**Pull request by torokati44**
Have to keep things consistent by hand with this one.

https://github.com/rustwasm/wasm-bindgen/blob/main/CHANGELOG.md#0293

### CODE REVIEW

**Comment by evilpie** [comment]
I am currently looking into updating web-sys and js-sys so that we can remove `--cfg=web_sys_unstable_apis`.

**Comment by torokati44** [comment]
Okay, cool! Is that directly relevant here though? Sorry if I'm missing something, but isn't that a bit independent of this?

Also, wouldn't we have to re-add it for #16794 anyway?

**Comment by evilpie** [comment]
> Okay, cool! Is that directly relevant here though? Sorry if I'm missing something, but isn't that a bit independent of this?

Updating wasm-bindgen is a requirement for doing that update.

>Also, wouldn't we have to re-add it for https://github.com/ruffle-rs/ruffle/pull/16794 anyway?

You are right, quite annoying.

**Comment by torokati44** [comment]
> Updating wasm-bindgen is a requirement for doing that update.

Okay, so not the other way around at least - meaning, that doesn't block this PR.

> You are right, quite annoying.

Yes, we had to go back and forth on this a couple times already, as we were leapfrogging new features with stabilized APIs...

**Comment by torokati44** [comment]
> I am currently looking into updating web-sys and js-sys

Is it okay to go ahead with this one until then?

**Pull request merged**
