### PR TITLE
Self-hosted Ruffle

### PR DESCRIPTION
**Pull request by kmeisthax**
This PR adds a third web target: self-hosted. This also includes a system wherein multiple versions of Ruffle from different sources can interact and negotiate which version applies polyfills. Furthermore, there is now limited multi-version support for manually-created Ruffle elements.

* [x] Declarative extension opt-out (`data-ruffle-optout` on `<html>` tag) used to indicate compatibility issues
* [x] Better webpack isolation
* ~User-facing extension pop-up with basic page status~ Moved to future PR
* ~User toggle to enable/disable Ruffle~ Moved to future PR
* ~Fix for Ruffle breaking certain webapps that use strict content security~ Needs more investigation
* [x] `window.RufflePlayer` public API w/ arbitrary numbers of named sources
* [x] Opt the demo page out of the Ruffle extension
* [x] "Interdictions" are now polyfills
* [x] Semantic version parser
* [x] Newest version negotiator for sources and the public API itself
* [x] `<script async>` support (assuming you configure Ruffle beforehand)
* [x] Ahead-of-time Ruffle configuration for default polyfills and source directory
* [x] Multiple version support
* [x] Dynamic RufflePlayer element creation
* [x] Remove `dynamic-content` polyfill due to performance issues
  * Replacements for this polyfill will be included in a future version
* ~Some way to schedule code to run after Ruffle loads~ Not necessary right now/out of scope

# How do I configure this?

Simple: Somewhere in your main HTML page, you need to declare `window.RufflePlayer.config`. Since Ruffle may or may not be loaded yet, you need to do something like this:

```
window.RufflePlayer = window.RufflePlayer || {};
window.RufflePlayer.config = {"polyfills": ["static-content"], "public_path": "/ruffle_dist"};
```

This enables the "Static content" polyfill, and tells Ruffle where it's files are stored. This is sufficient for very basic operation: Just make sure this script is somewhere on the page, and that `ruffle.js` is loaded after. Flash content on your page will be automatically played with Ruffle.

# I don't want your stupid extension! Get it off!
The WebExtension version of Ruffle respects the configuration mentioned above. However, if you really just want the Ruffle extension to go away, there's an extremely simple way to do this: attach `data-ruffle-optout` to your `<html>` tag, and the extension will not load any code into your page.

However, this shouldn't be necessary for people using Ruffle on their own: the extension and self-hosted versions are designed to pull from and respect the same config.

# How do I dynamically create content?
Ruffle ships with a custom element that you can stick into any part of your page dynamically. The name of this element is not guaranteed and shouldn't be statically used (especially in multi-version scenarios). Instead, you first need to get a Ruffle source, by calling `window.RufflePlayer.newest()`. This will return the source, which has a method called `create_player` which returns a RufflePlayer element. This element can be added directly into the DOM.

# How do I use multiple versions of Ruffle?
Note that, by interacting directly with sources, you lose some compatibility guarantees - we may add or remove methods to sources or the elements they create. We used `newest` in the example above, but you can also request a specific version using `.satisfying()`. This method accepts semantic version requirements similar to npm. For example, if you specifically want Ruffle version 0.2.3, then you would type `window.RufflePlayer.satisfying("0.2.3").create_player()`.

(TODO: Write explanation on how to compile multiple Ruffle versions as separately named sources)

### CODE REVIEW

**Comment by Herschel** [comment]
Thanks for your work on this! Can you clarify what happens when the user visits a site with the self-hosted version and also has the extension installed? Which version ends up running?

The multi-version/opt-out features seem unnecessary:

For the multi-version features:
 * I don't think having multiple versions on a site is an actual use case. From talking with NG developers, for example, they aren't going to juggle multiple versions. Even if a newer Ruffle were to break something, they'd just stick with one version or the other until the issue was resolved.
 * Maybe semver is useful to determine whether to use the extension or the self-hosted version when both are available (is this the motivation behind it?) But I think this should be handled internally and not exposed in a public API.

For data-ruffle-optout:
 * If I'm a user of the extension, I don't want a website to disable it. By installing the extension, the user is opting in to using it (and any issues resulting from it), so they should have the authority in whether it runs or not.
 * As long as the self-hosted version and extension can co-exist, I don't see any reason for the extension to be disabled.
 * I don't foresee any sites caring enough to add this.

**Comment by kmeisthax** [comment]
So, if both the extension and the self-hosted version are present, they'll negotiate the most recent version to run polyfills on. Polyfills will always try to be compatible with what Flash always supported, so we can always run the latest version's polyfills. However, sites that want to dynamically create a player element are going to have to interact with more API surfaces that we might want to change in the future. (Especially if we go along with far-future plans to expose the Flash stage to JavaScript.) Hence, we need semantic versioning so that we don't accidentally hand a website a RufflePlayer it doesn't know how to interact with.

To be clear: a site that wants to dynamically create Ruffle content probably shouldn't call `RufflePlayer.newest().create_player()`, it should at least call `RufflePlayer.satisfying('^0.1.0').create_player()`. After all, we're *are* going to be changing some of the APIs for, say, feeding SWF data into the player once we get streaming support working - that would be a semver breaking change and sites using Ruffle dynamically would need to opt into that.

That being said, the multi-version support isn't necessarily something that's a priority. It's something I realized I had already made when I was figuring out how to get the extension and self-hosted versions to play nice.

The Ruffle opt-out is primarily intended to avoid breaking sites. The inspiration for this was when I realized that Mega breaks with Ruffle enabled because the way we load files trips CSP. If we were to ship a version of Ruffle that just outright breaks a site for whatever reason, then there needs to be a way for users to turn off Ruffle and a way for sites to indicate that they aren't compatible with the extension. After taking your comments into account I'm starting to think it might be good to have a second toggle on the extension popup for "ignore opt-out, run Ruffle anyway" though.

**Comment by Herschel** [comment]
My thought is that both the self-hosted version and the extension know their versions, so Ruffle can negotiate the semver within itself without the user providing a version. It would pick the most recent version that's semver compatible with the website's version (so this would favor the website's version if the user had a new extension of Ruffle with a changed API). That is, `RufflePlayer.new()` would just act like `RufflePlayer.satisfying(^websiteversion)`. In my mind, the way a website opts-in to a new breaking version is by downloading it and installing it on their server?

Thanks for considering the versioning guarantees, it's not something that was on my radar.

For the opt-out, I like the idea of having a toggle in the extension itself. Breaking sites will be kind of moot when they are all broken in 2020 anyway :-)

**Comment by kmeisthax** [comment]
I've pulled a bunch of work onto another future PR for the extension pop-up. This particular PR now only covers self-hosting use cases. The future PR already has the opt-out toggle implemented, and I decided to specifically call it a "compatibility warning" rather than an "opt-out". (e.g. the user-facing toggle is called "Ignore website compatibility warnings".) I'm also considering making the opt-out a version constraint (e.g. you have to opt-out a specific version or range of versions).

I'm going to add two new Public API methods:

 * `local` - Load any source with the exact same version as the `local` version, if it exists.
 * `local_compatible` - Load any source with a version compatible with the `local` version, if it exists.

These default to `newest` if no `local` source is present, but that shouldn't happen for the standard use-case. Furthermore, I'm wording those definitions very carefully to allow, say, preferring the extension version even for `local` when the versions match. We don't do that just yet, but we should. Ruffle is fairly large already (~7MB) and will only get bigger as we add more features needed for games. The more resources we can load from the extension, the better on the site's bandwidth bills.

Furthermore I'm taking this PR out of draft, since I moved all the extension popup stuff to a future PR and I really need to start getting some of these PRs merged in.

**Comment by Herschel** [comment]
Rebased onto master and merged, thank you! I'm going to get this built on CI and add docs right away, as this is the last "big piece" to allow people to start playing with Ruffle.

Newgrounds is starting to experiment with it. Here's some feedback:
 * Their first instinct was to use `newest`, which would be incorrect; they probably want to use `local` or `local_compatible`.
 * `local` and `local_compatible` names are a little confusing, we weren't sure at first if this meant local from the website's point of view (the self-hosted version) or local from the visitor's point of view (the extension). A quick search through the source cleared it up, but it wasn't immediately obvious.
 * In general, they don't want to think about the extension, because the amount of users that would have the extension installed relative to their visitor count would be close to 0.

Documentation would help solve the above. Another suggestion is to make the common case obvious: If someone is using the JS API, they probably want to use `local_compatible` to keep the site working as usual. So rename `Ruffle.local_compatible` to `Ruffle.new`, and this would do the Right Thing and be the obvious main entrypoint for JS API users.

Overrides to force-use the `newest` version could be opt-in on the extension side; I could see having a checkbox "Always use extension version" so that we can test stuff on the latest dev build regardless. I favor having options on the extension side rather than to website side, because extension users are more likely to be "power users".

Next step would be to allow more config parameters on the Ruffle instance:
   * "autoplay" is the big one we should have for the first release; to optionally enable/disable to "Click to Play" banner. Most Flash content already has some sort of preloader that requires click to play, so being able to enable/disable Ruffle's click-to-play is useful.
   * Specify in window.RufflePlayer.config (global default, for polyfill?), or in RufflePlayer instance (per-instance, for JS API?)
   * On the NG side, they would allow creators/moderators to specify the config as a JSON blob for each specific project using NG's project system.
   * Possible config parameters long term:
      * "show_mute_indicator": Show "Click to unmute" prompt when audio context is muted by browser (see Twitch for an example)
      * "letterbox_stage": Ruffle will draw letterboxes/pillarboxes to fit the stage into the viewport (this is currently the Ruffle default, but the Flash default behavior is to show content beyond the edges of the stage).
      * "virtual_gamepad": This would be an object to define a virtual gamepad layout and bindings for mobile, allowing keyboard games to be playable.

A release build of web Ruffle is only ~1.5MB (`npm run build -- --mode=production`), so not too bad! We should probably default to release builds because debug builds aren't useful at all in WASM land currently.

**Pull request merged**
