### PR TITLE
Adding Clang to dependency list

### PR DESCRIPTION
**Pull request by sombraguerrero**
This is now a requirement on account of jpegxr.

### CODE REVIEW

**Review by sleepycatcoding — APPROVED** [review]

**Review by Lord-McSweeney — APPROVED** [review]

**Comment by tsunamistate** [comment]
Could you please add instructions for installing Clang on Windows, maybe in another PR?
I have Clang compiler installed in Visual Studio 2022, but cargo doesn't find it

**Comment by tsunamistate** [comment]
> https://github.com/llvm/llvm-project/releases

That link has no builds for Windows 😕 

For those that Clang compiler installed in Visual Studio 2022, add LIBCLANG_PATH variable with the following path:
`%VCINSTALLDIR%\Tools\Llvm\x64\bin\`

Change %VCINSTALLDIR% to the MSVC 2022 installation path, for example the default path is: `C:\Program Files\Microsoft Visual Studio\2022\Community\VC`

**Comment by sombraguerrero** [comment]
> That link has no builds for Windows 😕
It does, but you have to "show more assets." It's buried in the middle of the list. Windows is not the center of C's universe, after all ;)

**Comment by sombraguerrero** [comment]
Superceded by #13348

**Pull request closed without merging**
