### PR TITLE
avm2: Stub flash.text.engine.FontMetrics

### PR DESCRIPTION
**Pull request by MartySVK**
[Pre-Civilization: Marble Age](https://www.gameflare.com/online-game/pre-civilization-marble-age/) looks playable with this stub.
https://data.gameflare.com/games/7934/Qm7DbTq9VBoiZJ.swf

Before it was stuck after clicking on language with the error:

```
RustError("Failed to lookup class Multiname { ns: Single(Namespace(Namespace(\"flash.text.engine\"))), name: Some(\"FontMetrics\"), param: None, flags: MultinameFlags(0x0) } during coercion")" when constructing AVM2 side of movie clip of type cityAssets_fla::sponsorOptionLogo_216
```

### CODE REVIEW

**Comment by torokati44** [comment]
Would you like to flesh this class out a bit more? Based on the docs, it's a fairly simple data class. No big deal if not, of course, but while we are here...

**Comment by torokati44** [comment]
Awesome, thanks! You left out the `lineGap` parameter of the constructor, at the end. And I don't think it even needs to be a stub, setting all the members to the right value should be all it does. But FIXME if I'm wrong.

Also, I think this should be squashed at/before merging.

**Comment by Lord-McSweeney** [comment]
#13226 is going to add `FontMetrics`, and from Discord, it looks like it'll be merged soon. Can we implement it in that PR?

**Comment by MartySVK** [comment]
@Lord-McSweeney Oh, I did not notice that. Sure, I am closing this PR

**Comment by torokati44** [comment]
Oof, I wasn't aware of that either, sorry about it!

**Pull request closed without merging**
