### PR TITLE
core+tests: Socket testing and improvements

### PR DESCRIPTION
**Pull request by sleepycatcoding**
Add support in SWF regression testing framework to mock a socket. Also some improvements to the general socket framework.

List of things left to do:

- [x] Better name for `socket_mock` utility.
- [x] Allow specifying socket mock file path in the utility.
- [x] Add tests for `Socket` now that the backend exists

### CODE REVIEW

**Comment by torokati44** [comment]
> Better name for socket_mock utility

mocket

**Comment by Dinnerbone** [comment]
> > Better name for socket_mock utility
> 
> mocket

Darnit I saw that text and immediately scrolled down to comment mocket too.

+1 for mocket.

**Comment by torokati44** [comment]
Sadly we're not the first ones to make this portmanteau:
https://github.com/mindflayer/python-mocket

**Review by Dinnerbone — APPROVED** [review]
Awesome work once again!

I think I'd quite like some utility stuff in the socket format, for texts/floats/common data types, so we don't need to write out everything in bytes. But that's a nit and can come at any time later.

This all looks great to me, thank you!

**Pull request merged**
