### PR TITLE
Fix AVM1 error: Expected Number, found String(...)

### LINKED ISSUE #55: AVM1 error: Expected Number, found String(...)
Hi,
I encounter a error below.

```
[2019-09-03T04:38:16Z ERROR ruffle_core::avm1] AVM1 error: Expected Number, found String("4")
[2019-09-03T04:38:16Z ERROR ruffle_core::avm1] AVM1 error: Expected Number, found String("4")
```

### PR DESCRIPTION
**Pull request by utsudashinou**
Fix #55

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I think a better fix would be to change the caller to use `into_number` which does the parsing already, `as_f64` is when you know it's a Number and want an `f64` out of it.

**Comment by Herschel** [comment]
I agree with @Dinnerbone, it sounds like `into_number` or `into_number_v1` is missing in the action. What action is causing the issue?

**Comment by WillBrindle** [comment]
@Herschel looks like it's coming from [action_get_property](https://github.com/ruffle-rs/ruffle/blob/master/core/src/avm1.rs#L577).

**Comment by Herschel** [comment]
Should be fixed by 5ee7b9c8aa9ced8ccfea90b87d77ddf88e02ad31. Flash 4 always pushed strings on the stack, so all SWF4 actions should use `into_number_v1` when expecting a number. This game is a good test case for early Flash 4 actions, thank you!

**Pull request closed without merging**
