### PR TITLE
core/avm2: Remove some unnecessary warning logs

### PR DESCRIPTION
**Pull request by Lord-McSweeney**

### CODE REVIEW

**Comment by moulins** [comment]
Why not keep the logs as `tracing::info!`? You never know when these could be useful.

**Comment by evilpie** [comment]
Why not change it to `tracing::debug` or `tracing::trace` instead?

**Comment by evilpie** [comment]
Haha collision. `tracing::info` is still our default log level, so we probably shouldn't use that.

**Comment by Lord-McSweeney** [comment]
Seems like this was worked out over Discord.

**Pull request merged**
