### PR TITLE
avm1: Implement Sound.getVolume and Sound.setVolume

### LINKED ISSUE #1251: setVolume Support, with example games
Ruffle doesn't appear to have setVolume support. It's important to note that in AS2, setVolume will set the volume for everything unless you are setting the volume for a sound attached to a dedicated movieclip.

In Dad 'n Me, you will hear two songs playing at once - one of these songs is meant to have a volume of zero, so the game can crossfade between them. Both songs are playing at all times so they remain in-sync.

https://www.newgrounds.com/portal/view/254456/format/flash?emulate=flash

In The Room, when you enter a shop you will hear both songs play for a moment during what should be the crossfade transition:

https://www.newgrounds.com/portal/view/547307/format/flash?emulate=flash

There may be similar issues with support for getVolume, getPan and setPan.

### LINKED ISSUE #1646: "Sound.setVolume: Unimplemented"- Sounds continue to play at full volume after they should end, multiple games
I've come across this problem in two games:

- [FlyGuy](https://archive.org/details/flyguy_flash) (nearby objects will continue to make noise at full volume, rather than fading as you move away)
- [Nanaca Crash](https://archive.org/details/nanaca-crash_v110) (Intro menu music continues to play after a game begins, at the same time as in-level-music)

The warning `Sound.setVolume: Unimplemented` is printed in the javascript console. This is happening in both Firefox and Chromium, on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by relrelb**
Fixes #1646
Fixes #1251

## TODO

- [x] Desktop backend
- [x] Web backend:
  - [x] AudioBuffer
  - [ ] Decoder

### CODE REVIEW

**Comment by Herschel** [comment]
The actual behavior of the Sound object is significantly more complicated. First, if no instance was specified for the Sound object in the constructor, adjusting the volume and pan adjusts it globally for all sound instances:
```
var sound = new Sound();
sound.setVolume(0); // mutes all sound
```

If a clip is specified in the constructor, the volume and pan apply recursively and concatenate across all child clips of that instance. For example:
```
var sound = new Sound(clip1);
var sound2 = new Sound(clip1.clip2);
sound.setVolume(50); // Sets the volume to 50% for clip1 and clip2
sound2.setVolume(50); // Volume becomes ~25% for clip2, since the soundtransforms apply together
```
It's okay to defer this latter behavior to a later PR, but to the former global behavior is commonly used for muting audio.

**Comment by jeffallen** [comment]
Hi, I tried out this PR with FlyGuy and it did not work for me with the desktop backend. What I see is that the correct volumes arrive in avm1/globals/sound.rs according to the events happening in the movie, but then they never make it into the desktop backend's audio implementation, where all of the SoundInstances have volume == 1.0.

**Comment by relrelb** [comment]
@Herschel Thanks for the information. I think that a solution for both behaviors you described would require each audio backend to maintain the sound hierarchy internally, so we might need to re-design the audio backend interface.

My suggestion is introducing a new concept called "sound scope", such that every sound instance lives in such one:
* Add a `register_sound_scope(&mut self, parent: Option<SoundScopeHandle>) -> SoundScopeHandle` audio backend method, which corresponds to a `MovieClip` creation (each `MovieClip` would hold its own `SoundScopeHandle`).
* Similarly add a `unregister_sound_scope(&mut self, sound_scope: SoundScopeHandle)` method.
* Update `set_volume` to operate on either a `SoundInstanceHandle` or a `SoundScopeHandle`.
* Make `start_sound` accept a `scope` parameter like so: `start_sound(&mut self, scope: SoundScopeHandle, sound: SoundHandle, settings: &swf::SoundInfo)`, then take it into account in an implementation-specific way:
    * Desktop - Currently the active sound instances are all stored flattened in an `Arc<Mutex<Arena<SoundInstance>>>`. We need to somehow maintain them in a tree-ish data structure, then sum them up recursively in `mix_audio`.
    * Web - We need to associate each "sound scope" with its own `GainNode`, such they're connected according to their hierarchy. Each new `AudioNode` is added to its appropriate location in the graph per its scope.

**Comment by Herschel** [comment]
I'm wondering if we can handle the sound transforms on the `core` side, and the audio backends only provide methods to set the transform per-sound-instance, something like:

* Add SoundTransform property to DisplayObject.
  * (this maps to `Sound.getTransform` in AS2 [`Sprite.soundTransform`](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Sprite.html#soundTransform) in AS3)
  * This also handles the case of two Sound objects targeting the same clip; volume changes should be reflected in both:
    * `var sound1 = new Sound(); var sound2 = new Sound(); sound1.setVolume(0); trace(sound2.setVolume());`
* Whenever a volume is changed, modify the transforms recursively as appropriate.
  * A display object needs a way to query which sounds it is actively playing. When the volume of a clip needs to be changed, it can iterate through this list and update the volume.
  * We need this list anyway to implement `Sound.stop`.
* In AS3, display objects can be re-parented; for example, playing a sound on one MC, then removing it and adding it to another parent with a different volume. This may be more difficult to handle if the sound transform hierarchy is stored on the audio backend's side.

This keeps the audio backend itself simple, and puts the common logic inside the player.

In any case, maybe a first step is for the player to maintain a list of active sound instances, because we need it to implement all of `stop`, `setVolume`, `onSoundComplete`, etc...
* Add `struct SoundInstance` that has a `SoundHandle`, `Option<DisplayObject>`, and `Option<avm1::SoundObject>`.
* `Player` and `UpdateContext` can have a list of `SoundInstance`
* Each tick, Player iterates through that list and cleans up any completed sounds.
  * Fire `onSoundComplete` if non-null SoundObject.
* On `Sound.stop`, stop and remove any instance where the display object is an ancestor.
* On `Sound.setVolume`, iterate through and update the backend for any sound where the display object is an ancestor.
A max of ~32 sounds can be played (cc #1388) at any one time, so iterating through a list like this should be fine.

**Comment by Diatonator** [comment]
Is there any good progress on this PR? Some flashes blast the listener with sounds because they are played at max volume, implementing the volume stuff at least will save some people's ears I guarantee!

**Comment by relrelb** [comment]
Superseded by #2825.

**Pull request closed without merging**
