### PR TITLE
ci: Release and test with Rust 1.78 instead of stable

### PR DESCRIPTION
**Pull request by torokati44**
At least until a release with https://github.com/gfx-rs/wgpu/pull/5831 is out.

Fixes https://github.com/ruffle-rs/ruffle/issues/16715

### CODE REVIEW

**Review by danielhjacobs — APPROVED** [review]

**Review by kjarosh — APPROVED** [review]

**Comment by torokati44** [comment]
Then we have to make sure to build the nightlies with this too.

**Comment by torokati44** [comment]
I opted to switch all desktop releases to 1.78 because it's a smaller/simpler change, and doesn't really make a difference otherwise.

**Comment by kjarosh** [comment]
Shouldn't we switch all tests to 1.78 too for consistency? Otherwise we will release using a different version than the one used for testing.

**Comment by torokati44** [comment]
Fair point. That's also fine by me. Feel free to amend-commit-force-push. Any counter-opinions?

**Pull request merged**
