### PR TITLE
avm1: Don't ignore mouse_pick on static text (fix #9274)

### LINKED ISSUE #9274: [Regression] Drag and drop not working
### Describe the bug

Issue with https://dnalc.cshl.edu/view/16999-Genetic-Traits.html

Ruffle behavior:

[Screencast from 01-23-2023 09:44:41 AM.webm](https://user-images.githubusercontent.com/29206584/214069134-0bd983db-83bc-4758-ace0-530460970ed5.webm)

### Expected behavior

Flash behavior:

[Screencast from 01-23-2023 09:44:04 AM.webm](https://user-images.githubusercontent.com/29206584/214069201-7f096ff9-6b2b-4fd3-a2a9-ac5d362711cf.webm)

### Affected platform

Self-hosted version

### Operating system

Linux Fedora 36

### Browser

Mozilla Firefox 107

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by danielhjacobs**

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
There are other changes in #8744 in `movie_clip.rs`, should those also be changed to AVM2 only?

**Comment by danielhjacobs** [comment]
Not sure, wasn't needed for this to work, so I wanted to keep the changes minimal.

**Comment by danielhjacobs** [comment]
If I should, the right changes would be these.

In mouse_pick change from:
```rs
if self.visible() {
```
To:
```rs
if self.visible() && self.mouse_enabled() || context.is_action_script_3() {
```
And in hit_test_shape change from:
```rs
} else if child.depth() >= clip_depth
```
To:
```rs
} else if child.depth() > clip_depth || (child.depth() == clip_depth && context.is_action_script_3())
```

**Comment by danielhjacobs** [comment]
Second commit added as according to CUB3D: "Everything in that pr was only intended to change avm2, so unless we have an outstanding avm1 issue that they fix I would gate them to avm2 only"

**Comment by Dinnerbone** [comment]
Can we add mouse pick tests for avm1 and avm2?

**Comment by danielhjacobs** [comment]
I have not really messed with adding tests before and I'm not going to be able to do much more work on this PR until Thursday. If someone wants to push to the branch to add tests before then I don't have an issue with that as I allow edits by maintainers.

**Pull request merged**
