### PR TITLE
avm2: Skip nested 'goto' frame for SWF 9

### PR DESCRIPTION
**Pull request by Aaron1011**
This fixes 'who_killed_travolta'

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]

**Comment by jarca0123** [comment]
This also fixes this game: https://www.superhry.cz/games/1692/

**Comment by Aaron1011** [comment]
After some additional testing, this seems to be incorrect - we run the constructors for child objects at an odd time.

**Comment by adrian17** [comment]
> After some additional testing, this seems to be incorrect - we run the constructors for child objects at an odd time.

For the record, Aaron's later comment from discord

> It's "less wrong" now
> it's still not correct, but I think we're going to need to do some invasive framscript refactoring to get it right for swf 9

**Review by adrian17 — APPROVED** [review]

**Comment by n0samu** [comment]
For posterity, here is the download link for Who Killed Travolta: https://files.scene.org/view/parties/2006/assembly06/browser_demo/who_killed_travolta_by_evo_flash_bombsquad.zip

**Pull request merged**
