### PR TITLE
core: Include Cyrillic and Greek glyphs in the default font

### LINKED ISSUE #7811: Cyrillic characters don't render at all
### Describe the bug

I tried different swfs, the problem seems to be unrelated to any particular one. Here's one that "works" except the text rendering: [злоген.swf.zip](https://github.com/ruffle-rs/ruffle/files/9449499/swf.zip)

This happens both in the online demo and in the native app.
2022-08-30 07 10 22 ruffle rs Ruffle Web Demo
Снимок экрана 2022-08-30 в 07 12 42

Here's one more swf (though AS3 one) that also has this problem: [Graffiti.swf.zip](https://github.com/ruffle-rs/ruffle/files/9449539/Graffiti.swf.zip)

### Expected behavior

Adobe Flash Player renders all characters correctly:
Снимок экрана 2022-08-30 в 07 11 09

### Affected platform

Online demo

### Operating system

macOS 12.5.1

### Browser

Vivaldi 5.4.2753.40 (Stable channel) (arm64) aka Chrome 104.0.5112.105

### Additional information

_No response_

### LINKED ISSUE #15575: Cyrillic letters are not rendered in ActionScript 2
### Describe the bug

Cyrillic letters are not rendered in ActionScript 2 but they do in ActionScript 3 but the AS3 conversion makes some glitches in the flash

View in the application:
Знімок екрана 2024-03-14 о 19 02 35

View in the demo:
Знімок екрана 2024-03-14 о 19 02 48

View of the AS3 version in the demo(causes some artifacts):
Знімок екрана 2024-03-14 о 19 03 06

### Expected behavior

They should render

### Content Location

The .swf: [https://file.garden/ZU-xUYjV4SO9KYcO/00137.swf](https://file.garden/ZU-xUYjV4SO9KYcO/00137.swf)

The .swf that was converted to AS3: [https://file.garden/ZU-xUYjV4SO9KYcO/00137AS3.swf](https://file.garden/ZU-xUYjV4SO9KYcO/00137AS3.swf)

### Affected platform

Online demo

### Operating system

macOS Catalina

### Browser

Mozilla Firefox

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by evilpie**
Including these new Unicode blocks (Based on https://unicodeplus.com/block) increases the default font size by about 50% (+ 24kb).

Screenshot 2024-12-01 at 11-09-07 Ruffle Player

Fixes #15575, fixes #7811

### CODE REVIEW

**Review by torokati44 — APPROVED** [review]
Just curious, would adding `--best` to `gzip` decrease the size considerably?

**Comment by evilpie** [comment]
> Just curious, would adding `--best` to `gzip` decrease the size considerably?

Seems like it would save about 1kb.

**Comment by torokati44** [comment]
I'd say that's not nothing, and since it's basically free, I think it's worth it. Don't know if it should be in this PR or a separate one (or a single commit even to not "bloat" the repo with multiple zips), but it probably doesn't matter much. Up to you!

**Comment by evilpie** [comment]
I timed the decompression time and it's basically unobservable with approximately 2ms with and without best. So I will use it for this PR.

**Pull request merged**
