### PR TITLE
Added Opt-Groups for Web Demo

### PR DESCRIPTION
**Pull request by pocketonion**
This commit adds HTML Opt-Groups separating Games and Animations on the web demo sample dropdown menu. There are also a few tiny styling changes. Mainly the addition of a transition duration to the logo image, as well as changing "max-device-width" to "max-width" on a media query so that the "mobile" view is shown if you scale down the window on desktop browsers.

### CODE REVIEW

**Comment by Justin-CB** [comment]
Can you run `npx eslint . --fix` in the `web/` directory? Ruffle has a JavaScript style checker now, & that command will fix the style issues(or non-issues) that this commit has.

**Comment by Dinnerbone** [comment]
You can also do `npm run format` in the `web` directory. Might be worth adding as a pre-commit hook 🤔

**Comment by Justin-CB** [comment]
@Dinnerbone I think it would be worth doing so we don't have formatting noise in our commits or have formatting commits all the time(I realize that I have a formatting commit on #576 , but I started that before prettier was part of the repository).

**Comment by pocketonion** [comment]
So I ran the format and I have some weird results in the HTML. (I think they are weird anyway)

For example look at how the opening and closing brackets for this section are formatted:

```html
<div id="sample-swfs-container">
    <span id="sample-swfs-label">Sample SWF:</span>
    <select id="sample-swfs">
        <option value="none">None</option>
        <optgroup id="anim-optgroup" label="Animations">
        </optgroup>
        <optgroup id="games-optgroup" label="Games"> </optgroup>
    </select>
    <span id="author-container"
        >Author: <a href="#" target="_blank" id="author"></a
    ></span>
</div>
```
The JS looks like it formatted fine, but am I wrong for thinking this looks a little off?

**Comment by pocketonion** [comment]
Oops. Nevermind I think something was wrong in which order I did it. I think I'm good now.

**Comment by Herschel** [comment]
Looks good, thanks!

**Pull request merged**
