### PR TITLE
web: As appropriate use embed height mentioned in Mozilla bug 810082 c65

### PR DESCRIPTION
**Pull request by danielhjacobs**
See https://bugzilla.mozilla.org/show_bug.cgi?id=810082#c65, the test file, and https://github.com/ruffle-rs/ruffle/pull/13030#issuecomment-1716314418. Supersedes #13030.

### CODE REVIEW

**Review by Dinnerbone — APPROVED** [review]
Nice work!

**Comment by Benman2785** [comment]
this is bugged! (or my html that worked before is wrong)

i now have bugs in firefox and edge and chrome

i am now FORCED to specify height in px and cant use 100%

just check: https://hoffmeister.li/flash-games/
image

**Comment by Benman2785** [comment]
https://hoffmeister.li/flash-games/index_test.html shows old behaviour

**Comment by Benman2785** [comment]
can you fix your code to make it work again?

**Comment by Benman2785** [comment]
https://hoffmeister.li/flash-games/The_last_Stand_2_2023-10-04.html
this logic is flawed even if not in iFrame...

**Comment by danielhjacobs** [comment]
You're right, I found the real issue, and it's something I had actually noticed before. This logic only applies if the Flash embed/object is on a page or in an iframe with `<!DOCTYPE html>`. The sizing would be accurate to Flash if you added that to the game HTML page.

**Comment by Benman2785** [comment]
thats not the problem:
https://hoffmeister.li/flash-games/The_last_Stand_2_2023-10-04.html
error persists

**Comment by danielhjacobs** [comment]
That's not what I meant. I meant this bug exists in Ruffle because this matches Flash's behavior when using `<!DOCTYPE html>`.

**Comment by Benman2785** [comment]
working ;)

**Pull request merged**
