### PR TITLE
avm2: Initialize `Object` instance vtable before other classes

### PR DESCRIPTION
**Pull request by Aaron1011**
This ensures that properties defined on the `Object` class (like `hasOwnProperty`) get correctly copied into the vtable for 'special' subclasses like `Class`.

### CODE REVIEW

**Comment by Lord-McSweeney** [comment]
Progresses #8228 (now needs `flash.geom.Transform.matrix3D`).
Progresses #7866 (now needs TLF text).
Progresses #8889 (now needs `flash.geom.Transform.matrix3D`).
Progresses #8952 (now needs `flash.geom.Transform.matrix3D`).
Progresses #9956.
Progresses #10009.
Progresses #10443.

**Comment by mara004** [comment]
Is this already sufficient to fix #10443, or just a start?

**Comment by n0samu** [comment]
Just a start I guess - the issue isn't fixed by this.

**Review by adrian17 — APPROVED** [review]
Extreme spaghetti at this point 😅 
But looks just fine 👍

**Pull request merged**
