### PR TITLE
preleminary work on avm1 XMLSocket

### PR DESCRIPTION
**Pull request by hussein-aitlahcen**
This PR introduce basic avm1 XMLSocket operations; new, connect, onConnect, onData, close, send
The implementation is supporting Desktop only for now as I don't know how to handle it in web (perhaps websockets as @EmperorBale mentioned [here](https://github.com/ruffle-rs/ruffle/discussions/5134) ?).

Disclaimer; I am not familiar with the codebase nor I am familier with how Flash Player is working under the hood. I pretty much hacked ruffle based on this documentation http://demo.ligams.free.fr/AS2LR/XMLSocket.html to check whether or not we could run Dofus Retro with ruffle.
It ended up 'working' (requiring a bit more work, not part of  this PR, as there was some issues with SWF imports).

Related to #905 #288

### CODE REVIEW

**Comment by adrian17** [comment]
Side question: do we know any specific games which we suspect will start working with this PR?

**Comment by hussein-aitlahcen** [comment]
@adrian17 Yes, I tried with [the mmo dofus retro](https://www.dofus.com/en/dofus-retro)

**Comment by spikything** [comment]
> Side question: do we know any specific games which we suspect will start working with this PR?

Dinky Bomb https://www.spikything.com/dinkybomb/

**Comment by KuromeSan** [comment]
Horse Isle client may start working with this..

**Comment by Dinnerbone** [comment]
This was added in #12489.

Thank you so much for your work on it regardless!

**Pull request closed without merging**
