### PR TITLE
avm1: Allow string paths in hitTest (fix #1449, #1559)

### LINKED ISSUE #1449: Steppenwolf 6-3 softlocks in multiple places
https://www.y8.com/games/steppenwolf_chapter_6_episode_3

1- At the very beginning of this episode, you cannot check your inventory by pressing the "I" key. If you do so in Flash, then nothing happens; in Ruffle, the game softlocks.

Steps to reproduce: Start a new "Regular game" and press "I".

Removing this part of code prevents the issue from happening (but it also prevents the inventory from being displayed completely on legit situations):
```
tellTarget("_root")
{
	gotoAndStop(/Variables:EtatVide);
}
play();
```

2 (FIXED)- Still at the beginning of the episode, you have to shoot the guard. For some reason, he's immortal in Ruffle.

Steps to reproduce: Start a new "Regular game", look at the meal tray (space), take the soda can, use the soda can (I) on the door, quickly take the gun and shoot the guard.

The following messages are logged in the console:

> Errors: SetTarget failed: _root.MurBalle.MurMechant1 not found
> Target not found: Target="_root.MurBalle.MurMechant1" Base="_level0.Mechant1"

### PR DESCRIPTION
**Pull request by Herschel**
Allow string paths for the hitTest parameter, e.g. `clip1.hitTest("/clip2/clip3");`

### CODE REVIEW

**Comment by Toad06** [comment]
Thanks for this PR.

For some reason, it breaks the collisions in [Batman Gotham](https://www.y8.com/games/gotham_dark_night) (works in current nightly build). I'm trying to check what's wrong with this game.

**Comment by Toad06** [comment]
[Bubble Gum Run](https://www.y8.com/games/bubble_gum_run) also has an issue: when you collect an item, it endlessly increments your score.

I've made some testings and I'm not completely sure but I think the issue is that `hitTest(undefined)` now returns `true` (seems to return `false` on current nightly builds).

**Comment by Herschel** [comment]
That makes sense, `undefined` gets stringified to `""` on earlier SWF versions, and this would be a path to the same movieclip, which would always collide with itself. Will have to specifically check for undefined, thx!

**Comment by Herschel** [comment]
Okay, I added a parameter to `resolve_target_display_object` to control the empty string behavior. (There are some places where "" should return the original clip, but other cases like hitTest where "" should be considered invalid).

**Pull request merged**
