### PR TITLE
extension: Check tools using TypeScript

### PR DESCRIPTION
**Pull request by relrelb**
This would have caught #10351.

### CODE REVIEW

**Comment by Herschel** [comment]
LGTM, although I'm dumb when it comes to this area and don't know all of what this entails!

**Comment by Herschel** [comment]
@danielhjacobs Do you have any thoughts here? Looks good to me but want to check with people that work a lot with the web build.

**Comment by danielhjacobs** [comment]
Yeah, from my perspective this can only be a good thing. From my understanding,  it just checks for issues on some files that weren't previously being checked, which is always a good idea.

**Comment by Herschel** [comment]
👍 Feel free to rebase and merge @relrelb

**Pull request merged**
