### PR TITLE
core:Fix Wrong frame rate for swf loaded via GetUrl2 issue #3020

### PR DESCRIPTION
**Pull request by haraldbre**
Fixes wrong frame rate when loading a file via GetUrl2
#3020

### CODE REVIEW

**Review by Herschel — CHANGES_REQUESTED** [review]
Looks like this should only occur when the load movie overwrites the root movie by loading into `_root` or level 0. Example that shouldn't change framerate:

[as2loader.zip](https://github.com/ruffle-rs/ruffle/files/6175216/as2loader.zip)

**Comment by haraldbre** [comment]
In  example #3020, GetUrl2 is used with name "mymc". The ruffle loader assigns the file to a clip with depth 1.
In  example #3663, GetUrl is used with name "_level0". The ruffle loader assigns the file to a clip with depth 0.
In  example as2loader, GetUrl2 is used with name "mc". The ruffle loader assigns the file to a clip created via createEmptyMovieClip prior to calling GetUrl2. That clip has depth 16385 = AVM_DEPTH_BIAS + 1.
So checking whether the depth of the clip < AVM_DEPTH_BIAS solves #3020 and #3663 for ruffle_desktop without conflicting with example as2loader.
 #3020 is also resolved for ruffle_extension, but #3663 not.
A by note: When searching for a fix, I first only set the player frame_rate and not the audio frame_rate. Then #3020 played just fine with ruffle_desktop. However with ruffle_extension, video and audio only stayed in synch until the first interruption (via play/pause button). When continuing, video and audio where no longer synched.
How can the ruffle extension be traced?

**Comment by Herschel** [comment]
I looked into #3020 a bit more, and unfortunately it's more complicated. The framerate in the player itself does not change, but instead the animation is kept in sync due to the audio. The audio in the loaded SWF (3zd4_001.swf) is using the "Stream" setting, which forces the timeline to stay in sync with the sound. If a "stream" sound is not playing, then the file plays as normal.

We don't sync the timeline when playing stream sounds at all currently (#10), instead relying on Ruffle's natural frame loop to keep the animation in sync. When we implement syncing, we'll have to make sure we sync with the movie that the sound is playing from, not the root movie.

The player's framerate doesn't change in the above case -- you can verify this by tracing `stage.frameRate` in AS3. The only ways to change the actual framerate of the movie is:
 * Replace the root movie by loading into `_level0` or `_root`
 * Change `Stage.frameRate` in AS3.
MC depth does not have an effect.

**Comment by Herschel** [comment]
Fixed the framerate behavior when a movie is loaded into _root in #3956. This does not fix the audio issue in #3020, which requires some deeper improvements to how we sync audio. I've opened #3958 to track this issue. Thank you!

**Pull request closed without merging**
