### PR TITLE
Move wstr code in a separate crate

### PR DESCRIPTION
**Pull request by moulins**
I initially started this in hopes of improving the compilation time, but unfortunately it gave no appreciable gains.

However, it's still good for separation of concerns, so here' the PR :)

(I put myself as the author of the new crate, given that I wrote most of the code)

### CODE REVIEW

**Review by kmeisthax — APPROVED** [review]
Seems like a worthwhile effort. I especially appreciate the move to use `core` instead of `std` where possible.

I'll give time for others comment here as well but I have no problems with this PR.

**Comment by moulins** [comment]
About `std` -> `core`, I could even make the crate `#![no_std]` (more as a lint than anything else), what do you think?

**Comment by kmeisthax** [comment]
Probably a good idea.

**Review by relrelb — APPROVED** [review]

**Comment by relrelb** [comment]
Looks good in general, thank you!
But let me have a small suggestion: Maybe we should move the `wstr` directory under `core` (next to `macros`), since AFAICT there really shouldn't be more users of `wstr` besides `core`.

**Comment by moulins** [comment]
I think other crates could use `wstr` in the future; for example, when doing the UTF16 rewrite I remember wanting a `SwfStr::into_wstr` method, which would require using `wstr` from `swf`.

**Review by Herschel — APPROVED** [review]

**Comment by torokati44** [comment]
Doesn't this undo #6528 currently?

**Comment by Herschel** [comment]
Thank you!

Eventually I'd like to move a lot of the lower-level types (Color, BoundingBox, Fixed, etc.) to a `ruffle_types` crate, so that these can be used by `swf`, `core`, and the backends and streamline some of the dependency. I wonder if `wstr` could perhaps live in there as well.

**Review by Herschel — APPROVED** [review]

**Pull request merged**
