### PR TITLE
avm1: Migrate serialization + deserialization of shared objects to the Flash Player format

### PR DESCRIPTION
**Pull request by CUB3D**
Currently we use JSON to save the contents of `SharedObject`, whereas Flash Player uses an extension of AMF.
This solves this by updating the current saving logic to use this format, as well as changing the `StorageBackend` to store bytes instead of base64 encoded strings, which allows for the import of existing Flash Player data.
Furthermore, this corrects the handling of `Date` and `XML` classes which should be recreated when loaded.
~Currently this pr removes support for JSON shared objects, however this could be re-added to allow for the migration of existing data.~ (Json support re-added for reading)

### CODE REVIEW

**Comment by Herschel** [comment]
Thanks for this!

Personally I don't have an issue with invalidating shared objects since we are still pre-release; but let me check with some site owners to see how they might feel.

**Comment by adrian17** [comment]
IMO It doesn't cost much to support the old format, at least for reading.

**Comment by adrian17** [comment]
Side note: do we want to put forked `rust-flash-lso` under Ruffle?

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
