### PR TITLE
web: On browsers which support it, specify the type of audio Ruffle uses

### PR DESCRIPTION
**Pull request by danielhjacobs**
I've not tested this, but it may fix https://github.com/ruffle-rs/ruffle-rs.github.io/issues/177.

### CODE REVIEW

**Comment by danielhjacobs** [comment]
Done, but I won't feel right merging this until someone with iOS 17+ tests it.

**Comment by danielhjacobs** [comment]
Can someone with iOS 16.4+ test https://danielhjacobs.github.io/ruffle-unmute-ios/

**Comment by danielhjacobs** [comment]
Tested and confirmed fixed by @CUB3D on Discord.

**Review by CUB3D — APPROVED** [review]
Tested and confirmed working on iOS 16.6.1

**Comment by torokati44** [comment]
Also by a friend of mine on an iPhone with iOS 18.

**Pull request merged**
