### PR TITLE
AVM1 browser interactions

### PR DESCRIPTION
**Pull request by kmeisthax**
This is a draft PR for interactions between ActionScript and the browser - namely GetURL, in it's various forms. ~~It relies on @Dinnerbone's PR #52 in order to work - please do not consider merging this PR in unless that PR has already been merged. It is technically independent of the WebExtension PR but isn't very useful without it. (I've been testing on a temporary merged branch of this PR and #53.)~~

## Progress & scope

The following are implemented:

- [x] Navigation to new webpages via legacy `ActionGetURL`/`ActionGetURL2` opcodes or `getURL` function
- [x] `Math.random` ~~and `Math.floor`~~ (Not technically necessary, but I needed it in here for Homestar to work)
- [x] Navigation to arbitrary target windows/frames
- [x] Navigation in Desktop mode (currently uses `NullNavigatorBackend`)
- [x] Form submission through `getURL` via AVM1 locals
- ~~Parsing of returned form data as new AVM1 locals~~

### Future work
GetURL functionality which implies the loading or execution of remote SWF content into a sprite, legacy `_layer` target, or movie clip is currently considered out of scope for this PR. Such functionality issues warnings in the console if used. (Rationale: We don't have test cases for this yet, I don't know how Flash Player handles some of these cases, and our MovieClip representation doesn't support remote SWFs yet)

Functionality of `getURL` or it's AVM1 opcode equivalents that allow Flash to retrieve and process data are also out of scope because Rust's async ecosystem isn't ready yet. When that is ready, a hypothetical future PR would need to enforce the following sandboxing rules that Flash did:

 * Only local content in a local page is allowed to open `javascript:` URLs
 * Filesystem content window names are obfuscated to `_flashXXXXXXXX` (where `X` is a random hexdigit)

## Implementation details

We create a new backend type called `NavigatorBackend` which represents communication between the SWF player and a browser. This allows ActionScript to control the browser it's hosted in. It currently only has one method, which causes a navigation to a new URL. Future methods for this backend are planned for future PRs.

### CODE REVIEW

**Comment by kmeisthax** [comment]
Never thought I'd build and submit a form from Rust but here we are

**Comment by kmeisthax** [comment]
I'm axing the "Parsing of returned form data as new AVM1 locals" part of the PR. Rust's async ecosystem is too unstable to justify holding back the rest of this over.

The problem is that Rust's async ecosystem is about to transition from the `futures` crate to `std::future`. It's not justifiable to write async code in the old ecosystem when it's obsolete. However, the `std::future` ecosystem is *really* unusable without `async fn`, which won't be stable until two `rustc` releases from now. I tried writing some combinators to provide a `.then()` equivalent with Rust futures, but that wasn't feasible due to conflicts between borrow checking and memory pinning.

I've moved all `Future` related code into another branch, `avm-fetchmethods`, so that I can get the part of this PR that I can actually write buttoned up and ready to merge. I *could* continue developing fetch behavior on nightly Rust but it won't be mergeable for a few months, so it wouldn't make sense unless I also worked on things like SWF streaming alongside it.

**Comment by kmeisthax** [comment]
I'm taking this out of draft status as there's no further functionality I can add to this PR before rustc 1.39. I tried to fix the formatting errors CircleCI complains about but it changed a bunch of unrelated files too, so perhaps that should be a separate operation after this is merged in.

**Comment by Herschel** [comment]
Thanks for the well-documented code! I have a few nits but I'm going to go ahead and merge this now.

**Pull request merged**
