### PR TITLE
chore: Bump png from 0.16.8 to 0.17.0

### PR DESCRIPTION
**Pull request by relrelb**
I'm not sure about the `data.resize(info.buffer_size(), 0);` line. It appears in the [docs](https://docs.rs/png/0.17.0/png/) like the right thing to do.

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]
Feels reasonable, though for us it probably doesn't make a difference given Flash probably never intended to support apngs :)

**Comment by relrelb** [comment]
> Feels reasonable, though for us it probably doesn't make a difference given Flash probably never intended to support apngs :)

I'm not sure this is relevant only for APNGs. It feels to me like `reader.output_buffer_size()` is the total available buffer size whereas `info.buffer_size()` is the actual size consumed by the PNG decoder, so it might be relevant for PNGs that contain trailing "garbage" data. But I didn't really verified that.

**Comment by adrian17** [comment]
That was my understanding from reading the rationale:

https://github.com/image-rs/image-png/commit/c6318472080a5e94e16887795866100f8697159e

But I may be wrong here

**Comment by relrelb** [comment]
> That was my understanding from reading the rationale:
> 
> [image-rs/image-png@c631847](https://github.com/image-rs/image-png/commit/c6318472080a5e94e16887795866100f8697159e)
> 
> But I may be wrong here

Sounds reasonable, rebased and removed the `data.resize(info.buffer_size(), 0);`.

**Pull request merged**
