### PR TITLE
Added AVM2 op "Swap"

### PR DESCRIPTION
**Pull request by bbb651**
Implemented `Swap` according to [this list](https://www.free-decompiler.com/flash/docs/as3_pcode_instructions.en.html).
This is my first time doing a pull request and working on public repos, so there's a big chance I did something wrong.

### CODE REVIEW

**Comment by Herschel** [comment]
Hello, and welcome!

I believe this should work on any operands, not only i32, so the `coerce_to_i32` should be removed.

**Comment by bbb651** [comment]
I'll try to fix it, I heavily referenced other methods as I'm not yet familiar with the codebase, according to [this](https://www.free-decompiler.com/flash/docs/as3_pcode_instructions.en.html) it should work for any value not just integers.

**Comment by kmeisthax** [comment]
Thanks. This looks great, and I'm honestly surprised I missed it.

Do we know of any way to generate this opcode using Adobe Animate or Flash CS? We could add it to the test suite if so. However, given that I haven't noticed this opcode being missing, it might just not be in use in modern AVM2. Still nice to have though.

**Review by kmeisthax — APPROVED** [review]

**Comment by Herschel** [comment]
Thank you!

**Comment by bbb651** [comment]
> 
> 
> Thanks. This looks great, and I'm honestly surprised I missed it.
> 
> Do we know of any way to generate this opcode using Adobe Animate or Flash CS? We could add it to the test suite if so. However, given that I haven't noticed this opcode being missing, it might just not be in use in modern AVM2. Still nice to have though.

There are several other ops (about 15) that appear in `swf::avm2::types::Op` but not in the match in `core::avm2::activation` (I temporarily removed the `_ => self.unknown_op(op),` line and rust-analyzer shows what ops are missing), I think I'll try to implement them and make another pull request.

**Pull request merged**
