### PR TITLE
avm2: Implement DisplayObjectContainer.getObjectsUnderPoint

### PR DESCRIPTION
**Pull request by Aaron1011**
I still need to write tests for this

### CODE REVIEW

**Comment by n0samu** [comment]
Unfortunately this does not fix #10751.

**Comment by n0samu** [comment]
This fixes #11640!

**Review by adrian17 — APPROVED** [review]
Can we get this in, maybe with a `// TODO` that this might be a naive not-perfect implementation?

(though, even a simplest test would be nice to have here)

**Comment by techboyg5** [comment]
Hello?

**Pull request merged**
