### PR TITLE
Add support for capturing images during tests

### PR DESCRIPTION
**Pull request by Aaron1011**
This PR extends `regression_test.rs` with the ability to capture an image of the final frame of a test (based on the code in `exporter`). This will allow for automated 'rendering tests' which compare the rendered output of a frame to a reference image on disk.

The largest change in this PR is the creation of a new `tests` package. All of the existing SWF test files are moved from `core` to this package. This allows the test code to depend on `ruffle_render_wgpu`, which is needed to render an image.

### CODE REVIEW

**Comment by Aaron1011** [comment]
It looks like Windows was able to run the test out-of-the-box - I suspect that it's automatically falling back to [WARP](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp) since there's no graphics driver available.

From my local testing, neither [SwiftShader](https://github.com/google/swiftshader) nor Mesa'a lavapipe are complete enough to support Ruffle - they both cause errors about unsupported APIs and unimplemented shader operations.

Therefore, I think the best option is to *only* enable image-based testing on Windows. According to [the WARP documentation](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp#how-to-use-warp), it's possible to force the use of WARP via the Direct3D API. Unfortunately, it looks like turning this on from Ruffle may be blocked on https://github.com/gfx-rs/wgpu/issues/1003

**Comment by torokati44** [comment]
Just out of curiosity, what version of lavapipe have you tried, and what issues have you encountered?
My experience has been quite the opposite with it. Granted, it prints some non-conformity warnings, and missing extensions (that don't sound necessary for Ruffle, such as `SAMPLER_ANISOTROPY`), but I was surprised how well it worked overall, both in terms of performance, and glitch-free-ness.

**Comment by Aaron1011** [comment]
@torokati44: I was testing locally, not on Github actions. Interestingly, I'm able to use lavapipe when using `ruffle_desktop` or `exporter` - it's only when I try my regression test code (with the same SWF) that I get an error. It looks like I may have misconfigured something.

**Comment by Aaron1011** [comment]
It turns out that I had specified `wgpu::BackendBit::all()` - on my platform, this was causing the OpenGL backend to get chosen over the Vulkan backend (for some reason, only when I specified `VK_ICD_FILENAMES`). This backend is incomplete, which is what lead to the crash.

**Comment by Aaron1011** [comment]
After adding a mesa PPA, we're now able to run an image test on Ubuntu CI

**Comment by Herschel** [comment]
This is great, thanks! One thing worth considering but not important for this PR is that we'd like to be able to do this with different rendering backends, if we add a `raqote` or `piet` backend at some point. So we may want to add the frame capture methods to `RenderBackend` eventually, and then the test harness can use different renderers as it sees fit.

**Comment by torokati44** [comment]
That same mechanism will also be needed for `BitmapData.draw()` (and `cacheAsBitmap`, and the `filters` property, and blend modes...).
In fact, it's already there in a preliminary form, at least for the `wgpu` backend in my fork - but not for the web backends.

**Comment by Aaron1011** [comment]
I think there are two options for how to fully enable this:

1. Check against both Linux and Windows reference images
2. Pick a 'reference' platform (either Windows or Linux), and only test against that.

I think the main disadvantage of testing both platforms is that it potentially creates more work for contributors, who might not have easy access to both platforms. In particular, testing against WARP (the Windows software rasterizer) requires an actual Windows instance (VM or dual-boot), since Wine does not support it. However, it should be possible for Windows users to test aginst lavapipe via WSL.

**Comment by Herschel** [comment]
Perhaps we could leverage a GitHub Action to generate the reference images for each platform? Then contributors wouldn't have to deal with it themselves. I picture this kind of workflow:

 * The rendering tests become their own GitHub Actions workflow.
 * This workflow uploads the resulting images as build artifacts.
 * When adding new rendering tests, a contributor could open a PR and have the tests run even while missing reference images; they can then grab these resulting images for any platform from the build artifacts and add them to their PR.
 * As we get fancier, perhaps a workflow could be [triggered manually](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) or via a [comment command on the PR](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment) that automatically generates any new reference images and appends them as a commit to the PR.

**Comment by Herschel** [comment]
It'd also be useful to generate reference images from the official Flash Player at some point. I could whip up a small SWF/AIR app that could run our SWFs in the official Flash Player and export images for those, similar to what [Swivel](http://github.com/herschel/Swivel) does. This could either be run manually, or on the Windows CI.

**Comment by Aaron1011** [comment]
@Herschel: If the overall structure of the crates in this PR looks good, I'll open a new PR that just moves things from `core/tests` to `tests/tests/`. That will ensure that that the PR doesn't continuously bitrot due to people adding/changing tests in `core/tests`.

**Comment by Herschel** [comment]
@Aaron1011 Yep, that's reasonable, go for it!

**Comment by Herschel** [comment]
Stumbled across this crate which may prove useful for image comparisons:
https://github.com/kornelski/dssim

**Comment by Aaron1011** [comment]
@Herschel: This is now a working prototype of CI-based image capturing. A new step in the Github Actions workflow uploads the produced images as an artifact, which can then be downloaded by users amd manually added to the repository. I had to bump `wgpu-rs` to pull in a fix for https://github.com/gfx-rs/wgpu/issues/1398.

Unresolved questions:
* What filename should use for the images? Currently, I'm using `<testname>-<OS>-<graphics_id>.png`. While this is fairly verbose (and can contain spaces), it makes the filename meaningful without needing to know additional context (e.g. the directory).
* How should we handle updating files? Currently, I append `.updated` to the filename (giving a full name of `<testname>-<OS>-<graphics_id>.png.updated`). This requires manually renaming the files when unzipping the artifact, though we could probably write a script to do this. Do we instead want to try to use the original names?
* The graphics ID for mesa on Linux contains the LLVM version that the software rasterizer was built with. I'm not sure if this is desirable - it might lead to periodic churn whenever we bump `mesa` to a version that pulls in a new LLVM. However, it will make it obvious when we've switched to a new version.

**Comment by Herschel** [comment]
@Aaron1011 Thanks for your work, I'll look it over this week.

**Comment by Herschel** [comment]
@Aaron1011 Sorry for the delay, this looks great. My thoughts on your questions:

 * .updated seems fine because I wouldn't want to overwrite the source test when running locally. Maybe eventually if we add some sort of auto-update functionality on CI, it can take care of renaming.
 * The LLVM version in mesa is a little concerning if mesa updates often, as it will break CI and we'll have to spend time renaming things fairly often. Could we pin the version of mesa we grab via apt-get to avoid this?
 * Let's make image testing conditional on a feature, since it will only spuriously fail locally. Can enable this feature by default on CI.

**Comment by Aaron1011** [comment]
@Herschel: I've made the changes you've requested. If this looks good to you, I'll squash the commits into one.

**Comment by Aaron1011** [comment]
@Herschel Are there any other changes that you'd like me to make?

**Comment by Herschel** [comment]
Sorry for the delay, this is good, thanks for your work!

We should probably move over the tests from https://github.com/ruffle-rs/visual-tests to this repo.

**Pull request merged**
