### PR TITLE
Implement arrays

### PR DESCRIPTION
**Pull request by Dinnerbone**
This implements arrays, both `new Array()` and `[]`. Uses a different approach than #151, but still a huge thanks to @kmeisthax for inspiration and putting up with me ;)

There are specialcases that I might be missing, as there's a lot of really weird things you can do in Flash with arrays if you wanted to (`{__proto__: Array.prototype}` is kinda an array but not entirely) - but I believe this will work for almost every legitimate usage of Array. I imagine that obfuscators or fancy DRM might try to use the edge cases to their advantage, but that's a problem for future us.

- Array()
- `[]` and `[1,2,3]`
- Array.concat
- Array.join
- Array.pop
- Array.push
- Array.reverse
- Array.shift
- Array.slice
- Array.splice
- Array.toString
- Array.unshift

Not covered by this PR:

- Array.CASEINSENSITIVE
- Array.DESCENDING
- Array.NUMERIC
- Array.RETURNINDEXEDARRAY
- Array.UNIQUESORT
- Array.sort
- Array.sortOn

There is further room for moving our `arguments` structure over to an array too, but I like to keep PR scopes small.

This also includes a tangibly related commit for ignoring some errors in the same way that Flash does, to make some tests pass.

### CODE REVIEW

**Comment by kmeisthax** [comment]
If I remember correctly `arguments` isn't supposed to be an Array in the ancient version of ECMAScript that AS1/2 are based off of, it's just supposed to be Array-shaped (i.e. has `length` and a number of integer-named properties).

**Comment by Dinnerbone** [comment]
`arguments.__proto__ == Array.prototype` and `arguments` has the magic array-behaviour (`arguments[10]` makes `length == 11`)

**Comment by Dinnerbone** [comment]
Updated with new approach that seems to match Flashes own implementation better (fits more corner cases & is easier to use). Also implemented `splice`.

**Comment by Herschel** [comment]
This is great, thanks to both of you!
Rebased on master, impl'd From on more things to clean up `(value.into()).into()`, and renamed `get_length` etc to `length` to be a little more Rusty.

**Pull request merged**
