### PR TITLE
avm2: Implement flash.crypto.generateRandomBytes

### PR DESCRIPTION
**Pull request by EmperorBale**
Implements the flash.crypto.generateRandomBytes function.

~~I'm not sure how to make the test for this because the output will be different each time~~

### CODE REVIEW

**Comment by jhwgh1968** [comment]
> I'm not sure how to make the test for this because the output will be different each time

Off-the-cuff suggestion: add a hidden runtime/flash parameter to enable "insecure randomness". It allows setting a seed value which is then used to prepare a non-crypto PRNG.

This would let tests generate the same pattern of random numbers every time, and verify the call works (even if perhaps the behavior is strange compared to true randomness).

**Comment by adrian17** [comment]
Yeah, but at that point you aren't really testing `generate_random_bytes`, you're testing your own pseudo-random function you made specifically for this test.

Maybe just check that it's filled to correct length and that's it? No need to test `OsRng`.

**Comment by jhwgh1968** [comment]
Handling the memory correctly is indeed the type of thing I was trying to test. Is it read from correctly, for example. I just wasn't sure if filling it with zeroes would make it difficult to write those tests.

In addition, if a test generated output that made a Flash app behave strangely, then another seed could perhaps work around it.

This might be [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) upon reflection. It was just the first thing I thought of to answer the question.

**Review by relrelb — APPROVED** [review]

**Comment by EmperorBale** [comment]
finished rebasing 👍🏻

**Pull request merged**
