### PR TITLE
Implement `Object.registerClass` correctly.

### LINKED ISSUE #2343: Object.registerClass doesn't work with symbols from child movies
Using `Object.registerClass` on a symbol exported by a child movie does nothing:
```as
var constructor = function() {
  // Doesn't fire on Ruffle, but fire on Flash.
  trace("Constructor called!");
};

// Warns on Ruffle: Tried to register_class on an unknown export childSymbol
Object.registerClass("childSymbol", constructor);

var loader = new MovieClipLoader();
loader.onLoadInit = function(target) {
  // Moving the registerClass here still doesn't work.

  // Let's assume that "child.swf" exports a "childSymbol".
  target.attachMovieClip("childSymbol", "clipname", 1);
});
loader.loadClip("child.swf", _root.createEmptyMovieClip("child", 1));
```

Probably related to #1864?

----------------

P.S.: `Object.registerClass` always return `undefined` on Ruffle, but on Flash it returns a boolean indicating whether the call succeeded. (I think the call always succeed as long as the arguments have the correct types, even if the symbol name doesn't exist)

### PR DESCRIPTION
**Pull request by moulins**
Fixes #2343 and #1864.

Changes:
 - `Object.registerClass` now returns a boolean (indicating success) instead of `undefined`, per Flash documentation.
 - Allow registering classes for symbol names that don't exist. (See [here](https://github.com/ruffle-rs/ruffle/issues/2343#issuecomment-757334238) for details).

I didn't manage to make self-contained test files for the second bullet point, so only return values are tested.

### CODE REVIEW

**Review by Herschel — CHANGES_REQUESTED** [review]
Thanks for your work! This doesn't seem to be a singular global map of IDs -> constructors, instead, it is per SWF, so the map should be inside `MovieLibrary`. Here's an example:
[as2loadtest.zip](https://github.com/ruffle-rs/ruffle/files/5793381/as2loadtest.zip)
In Flash Player, this traces "Parent Foo" and then "Child Foo" because they are different symbols in different libraries with different classes. With this PR, Ruffle traces "Child Foo" twice.

Also a possible optimization (maybe for a future PR): the library can only keep a list of unmatched `registerClass` bindings, instead of the entire list. Whenever a class is registered, if if the symbol exists, the class is stored directly in the objects `avm1_constructor` as before. If it doesn't yet exist, it is stored in the unmatched list, and this unmatched list. The unmatched list can be searched whenever a new symbol is defined, and the class can be registered at that point. This saves a lookup whenever we instantiate an exported clip.

**Comment by moulins** [comment]
> This doesn't seem to be a singular global map of IDs -> constructors, instead, it is per SWF, so the map should be inside MovieLibrary.

Hm, but the example [here](https://github.com/ruffle-rs/ruffle/issues/2343#issue-782476499) shows that you can modify the child mappings from the parent movie. Does this means the mappings should be hierachical?

--------

Regarding your suggested optimization, this would require the cached constructor to be properly invalidated when `Object.registerClass` is called twice on the same symbol ID. Do we really want this extra complexity?

**Comment by Herschel** [comment]
> Edit: Another possibility would be that `attachMovie` uses the mappings of the swf containing the bytecode currently running instead of those of the movie containing the targeted clip, but this seems wrong.

This is correct (AS2 is weird!). AS2 in general does not allow symbols to be used across SWF boundaries. When the clip loads, the child SWF becomes the "owner" of the target clip. `DisplayObject::movie()` will return the child SWF for the `target` clip, so any method calls to that clip such as `attachMovie` will use that child clip's library.

If you instead try to do `_root.attachMovie("ChildClip", ...)`, this does not work. Here's an example:

[as2loadtest2.zip](https://github.com/ruffle-rs/ruffle/files/5798337/as2loadtest2.zip)

**Comment by moulins** [comment]
> This is correct; AS2 is weird and in general does not allow symbols to be used across SWF boundaries. When the clip loads, the child SWF becomes the "owner" of the target clip. DisplayObject::movie() will return the child SWF for the target clip. So when you do target.attachMovie, the method call uses the child SWF's library.

Okay, this is clear now, but how does the example linked in the previous comment works then?

```as
// 'child.swf' exports 'childSymbol'

var constructor = function() {
  trace("Constructor called!");
};
// Here, the child isn't loaded yet, so we register the mapping in the parent's library.
Object.registerClass("childSymbol", constructor);

var loader = new MovieClipLoader();
loader.onLoadInit = function(target) {
  // Instanciate the clip on the child movie, using the child's library.
  // But the constructor registered previously in the parent's library gets called!
  // Either:
  //  - When instantiating the clip, `attachMovie` looks into the parent's library mappings
  //    if it can't find anything in the child's library;
  //  - We are instantiating a clip from the child's library, but the function gets called from the
  //    context of the parent movie, so we use still use the mappings from the parent's library.
  // Which one is the correct answer?
  target.attachMovie("childSymbol", "clipname", 1);
});

// Load the child movie.
loader.loadClip("child.swf", _root.createEmptyMovieClip("child", 1));
```

**Comment by Herschel** [comment]
Looked into it a bit more, and it seems like more differences in SWFv6 (I had been testing SWFv6 swfs because of the case sensitivity issues, sorry for the confusion.)
 * In SWFv7 and later, registered classes are global to the entire player (your original example).
 * In SWFv6, registered classes are local to the SWF (my original example).
Given the above, maybe we still store the class mapping in `MovieLibrary`. But it could be behind a `GcCell`. In SWFv7, we can copy this reference to child SWFs when they are loaded. In SWFv6, create a new one on load.

Also given the above, let's hold off on the optimization I mentioned just to keep it simple, because registering a class for "Foo" can actually affect multiple symbols if both SWFs have a symbol named "Foo".

**Comment by Herschel** [comment]
Tested some more, and it seems to test something like: `(parent.version >= 7) == (child.version >= 7)`. That is, if one SWF is v6, and the other is v7, the class registries are separate. If they are both are v6, or both are v7+, then the classes are shared.

I'm not too worried about cross-version specific behavior for now (needs more research, and the amount of mixed-version content being loaded is probably very small), but let's at least put the class registry in a `GcCell` in `MovieLibrary` so we can easily implement this in the future.

**Comment by moulins** [comment]
Mappings are now stored in a `Avm1ConstructorRegistry` struct in `Library` and `MovieLibrary`.

I implemented two global registries, one for SWF6, and one for SWF7 and later; each `MovieLibrary` selects the proper one depending on its version when created in `library_for_movie_mut`.

I've squashed everything and rebased on the current `master`, but didn't add your test cases; I'll prefer letting you do it ;).

**Comment by Herschel** [comment]
Thanks!

**Comment by adrian17** [comment]
This also improves https://github.com/ruffle-rs/ruffle/issues/2464 some more, now it's seems to be actually playable.

**Pull request merged**
