### PR TITLE
chore: Port to bitflags 2.0.0

### PR DESCRIPTION
**Pull request by torokati44**
Since Renovate won't be able to deal with this on its own, I did it for it.
I don't actually know if there is a less painful way though (through a macro option or something).

### CODE REVIEW

**Comment by torokati44** [comment]
>  I don't actually know if there is a less painful way though (through a macro option or something).

Looks like This Is The Way: https://kodraus.github.io/rust/2022/10/07/bitflags2.html#upgrading-to-2x

**Comment by torokati44** [comment]
Thank gosh for our fairly extensive test coverage! :relieved:

**Comment by torokati44** [comment]
See also: https://github.com/ruffle-rs/h263-rs/pull/47

**Review by Herschel — APPROVED** [review]
Thank you!

**Comment by Dinnerbone** [comment]
Maybe we should include h263-rs update in this PR so there isn't a period where we pull in two bitflags versions?

**Comment by torokati44** [comment]
We can do that, sure. Even though many of our other dependencies might still pull 1.x in.

Also, other than the last one, these commits don't build, so should I squash them for the sake of bisecting later?

**Comment by Dinnerbone** [comment]
Yeah that sounds smart. We can squash it when we merge the PR

**Comment by torokati44** [comment]
Added the h263-rs bump, feel free to squash on merge.

**Pull request merged**
