### PR TITLE
Update `zh-CN/messages.json`

### PR DESCRIPTION
**Pull request by steve02081504**
*Only a minor amendment to the translation

### CODE REVIEW

**Comment by n0samu** [comment]
Thanks for catching that! 👍

**Comment by Lord-McSweeney** [comment]
Since these are automatically updated from Crowdin, won't the translation be overridden by the one stored on Crowdin?

**Comment by Dinnerbone** [comment]
> Since these are automatically updated from Crowdin, won't the translation be overridden by the one stored on Crowdin?

Yes. Changes need to be done via crowdin, not here.

**Comment by steve02081504** [comment]
> > Since these are automatically updated from Crowdin, won't the translation be overridden by the one stored on Crowdin?
> 
> Yes. Changes need to be done via crowdin, not here.

Thank you all!
I voted on Crowdin for what I think is a more Sindarin translation, so I think it's OK to close this pr.☺

**Pull request closed without merging**
